force-app/main/default/objects/Case/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Waiting for Checker</fullName>
            </value>
            <value>
                <fullName>Waiting for Signer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <formula>IF(CASE(TEXT(Status), &apos;Closed&apos;, &apos;1&apos;, &apos;Cancelled&apos;, &apos;1&apos;,&apos;Disconnected&apos;, &apos;1&apos;, &apos;0&apos;)==&apos;1&apos;,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsLocked__c.field-meta.xml
<CustomField>
    <fullName>IsLocked__c</fullName>
    <formula>IF((TEXT(Approval_Status__c)==&apos;Draft&apos; || TEXT(Approval_Status__c)==&apos;Rejected&apos; || ISBLANK(TEXT(Approval_Status__c))) &amp;&amp; !IsClosed__c,FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsLocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <description>Migration.The account number or credit card number</description>
    <label>Nomor Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Amount__c.field-meta.xml
<CustomField>
    <fullName>SCC_Amount__c</fullName>
    <description>The amount from the dispute transaction</description>
    <label>Nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type_Feature__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Type Feature</label>
    <referenceTo>SCC_Call_Type_Feature__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Closure_Comments__c.field-meta.xml
<CustomField>
    <fullName>SCC_Closure_Comments__c</fullName>
    <description>Contains a brief description of the Case resolution or why the Case should be closed</description>
    <label>Keterangan Closing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Drone_Remark_Update__c.field-meta.xml
<CustomField>
    <fullName>SCC_Drone_Remark_Update__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Drone Remark Update</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Resolution_Category__c.field-meta.xml
<CustomField>
    <fullName>SCC_Resolution_Category__c</fullName>
    <label>Resolution Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Transactional</fullName>
                <label>Kirim Notifikasi</label>
            </value>
            <value>
                <fullName>Dokumen Tidak Lengkap</fullName>
            </value>
            <value>
                <fullName>Tidak Mengirimkan Notifikasi</fullName>
            </value>
            <value>
                <fullName>Transactional/Fraud with Refund</fullName>
                <isActive>false</isActive>
                <label>Transactional/Fraud with Refund</label>
            </value>
            <value>
                <fullName>Transactional/Fraud without Refund</fullName>
                <isActive>false</isActive>
                <label>Transactional/Fraud without Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Status_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Status_Transaksi__c</fullName>
    <label>Status Transaksi</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Berhasil</fullName>
            </value>
            <value>
                <fullName>Gagal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>SCC_Transaction_Date__c</fullName>
    <description>Migration.The date from dispute transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tanggal Transaksi</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Terminal_ID__c.field-meta.xml
<CustomField>
    <fullName>Terminal_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terminal ID</label>
    <referenceTo>SCC_Terminal_ID__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Kor__c/Master_Kor__c.object-meta.xml
<CustomObject>
    <label>Master Kor</label>
    <nameField>
        <label>Master Kor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Kors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Kor__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type</label>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Master Kors</relationshipLabel>
    <relationshipName>Master_Kors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCC_Call_Type_Feature__c/SCC_Call_Type_Feature__c.object-meta.xml
<CustomObject>
    <label>Case Type Feature</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Type Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Call_Type_Feature__c/fields/Fitur_ID__c.field-meta.xml
<CustomField>
    <fullName>Fitur_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fitur ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/SCC_Rekening_Koran__c.object-meta.xml
<CustomObject>
    <label>Rekening Koran</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rekening Koran</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_auxtrc__c.field-meta.xml
<CustomField>
    <fullName>SCC_auxtrc__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>auxtrc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Case__c.field-meta.xml
<CustomField>
    <fullName>SCC_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>SCC_Submit_Rekening_Koran</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Deskripsi_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Deskripsi_Transaksi__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Deskripsi Transaksi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_GLSign__c.field-meta.xml
<CustomField>
    <fullName>SCC_GLSign__c</fullName>
    <label>GLSign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_ID_Number_2__c.field-meta.xml
<CustomField>
    <fullName>SCC_ID_Number_2__c</fullName>
    <label>ID Number 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_ID_Number_3__c.field-meta.xml
<CustomField>
    <fullName>SCC_ID_Number_3__c</fullName>
    <label>ID Number 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_ID_Number__c</fullName>
    <label>ID Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Jam_Trans__c.field-meta.xml
<CustomField>
    <fullName>SCC_Jam_Trans__c</fullName>
    <label>SCC Jam Trans</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Jam_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Jam_Transaksi__c</fullName>
    <label>Jam Transaksi</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Kode_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Kode_Transaksi__c</fullName>
    <label>Kode Transaksi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Mutasi_Debet__c.field-meta.xml
<CustomField>
    <fullName>SCC_Mutasi_Debet__c</fullName>
    <label>Mutasi Debet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Mutasi_Kredit__c.field-meta.xml
<CustomField>
    <fullName>SCC_Mutasi_Kredit__c</fullName>
    <label>Mutasi Kredit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Nomor_Rekening__c.field-meta.xml
<CustomField>
    <fullName>SCC_Nomor_Rekening__c</fullName>
    <label>Nomor Rekening</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Saldo_Akhir_Mutasi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Saldo_Akhir_Mutasi__c</fullName>
    <label>Saldo Akhir Mutasi</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Saldo_Awal_Mutasi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Saldo_Awal_Mutasi__c</fullName>
    <label>Saldo Awal Mutasi</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Sequence__c.field-meta.xml
<CustomField>
    <fullName>SCC_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Serial__c.field-meta.xml
<CustomField>
    <fullName>SCC_Serial__c</fullName>
    <label>Serial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Tanggal_Effektif__c.field-meta.xml
<CustomField>
    <fullName>SCC_Tanggal_Effektif__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tanggal Effektif</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Tanggal_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Tanggal_Transaksi__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tanggal Transaksi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_tblds1__c.field-meta.xml
<CustomField>
    <fullName>SCC_tblds1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>tblds1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Rekening_Koran__c/fields/SCC_Terbilang__c.field-meta.xml
<CustomField>
    <fullName>SCC_Terbilang__c</fullName>
    <label>Terbilang</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Terminal_ID__c/SCC_Terminal_ID__c.object-meta.xml
<CustomObject>
    <label>SCC Terminal ID</label>
    <nameField>
        <label>Terminal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCC Terminal ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Terminal_ID__c/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SCC_Batch_AutoClosed_EDC.cls
public with sharing class SCC_Batch_AutoClosed_EDC implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public String query;

    public SCC_Batch_AutoClosed_EDC(String q) {
        this.query = q;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Case> scope) {
        try {

        
            List<Case> listcs = new List<Case>();
            List<SCC_Rekening_Koran__c> listrek = new List<SCC_Rekening_Koran__c>();
            List<SCC_Rekening_Koran__c> listdel = new List<SCC_Rekening_Koran__c>();
            SCC_Rekening_Koran__c rek = new SCC_Rekening_Koran__c();
            String url_current = url.getCurrentRequestUrl().tostring().replace('Url:[delegate=','').substringBeforeLast(']');
            
            Set<String> masterKorSet = new Set<String>();
            for(Master_Kor__c mk : [SELECT Name FROM Master_Kor__c WHERE Case_Type__r.name = '8412']) {
                masterKorSet.add(mk.Name);
            }
            
            for (Case s : scope) {
                if (s.SCC_Call_Type__r.external_id__c != '8412') continue;

                SCC_CaseResoultion_DataHub_Wrapper.SavingMutationRequest req = new SCC_CaseResoultion_DataHub_Wrapper.SavingMutationRequest();
                req.channel = 'CHMS';
                req.norekVarchar = s.SCC_Account_Number__c;

                Date todayz = Date.today();
                String tgl = DateTime.newInstance(todayz, Time.newInstance(0, 0, 0, 0)).format('yyyy-MM-dd');
                
                Date tgl2Date = s.SCC_Transaction_Date__c;
                String tgl2 = DateTime.newInstance(tgl2Date, Time.newInstance(0, 0, 0, 0)).format('yyyy-MM-dd');

                req.tanggalAkhirDatetime = tgl;
                req.tanggalAwalDatetime = tgl2;
                
                listdel = [select id from SCC_Rekening_Koran__c where scc_case__c=:s.id];
                
                
                SCC_CaseResoultion_DataHub_Wrapper.SavingMutationResponse res = SCC_CaseResoultion_DataHub.searchSavingStatement(req, 'EDC', s.Id);
                if (res.data != null) {
                    Integer matchedConditionCount = 0;
                    Integer matchedKor = 0;

                    for (SCC_CaseResoultion_DataHub_Wrapper.SavingMutationData smd : res.data) {
                    
                        String wordRmk = smd.trremk != null ? smd.trremk : '';

                        System.debug('work rmk : ' + wordRmk);
                        System.debug('master list kor : ' + masterKorSet );

                        // Flag untuk track apakah remark match dengan masterKor
                        Boolean matched = false;
                        for (String kor : masterKorSet) {
                            if (wordRmk.startsWith(kor)) {
                                //matchedKor++;
                                matched = true;
                                System.debug('Matched kor : ' + kor);
                                break;
                            }
                        }
                        
                        if (matched && smd.mutasiKredit == s.SCC_Amount__c) {
                            System.debug('matched condition kor : ' + matchedKor);
                            matchedConditionCount++;
                            rek = mapRekeningKoran(smd,s);
                            listrek.add(rek);
                        }
                        
                    }
                    
                    if (matchedConditionCount >= 1) {

                        String rekeningKoranTglTrans;

                        for(SCC_Rekening_Koran__c r : listrek ){

                             if(r.SCC_Tanggal_Transaksi__c != null || String.isNotBlank(r.SCC_Tanggal_Transaksi__c)){
                                String rekeningKoran = r.SCC_Tanggal_Transaksi__c.split('T')[0];
                                
                                if (String.isBlank(rekeningKoranTglTrans)) {
                                     rekeningKoranTglTrans = rekeningKoran;
                                } else {
                                    rekeningKoranTglTrans += ',' + rekeningKoran;
                                }
                            }
                            
                        }

                        s.Status = 'Closed';
                        s.SCC_Status_Transaksi__c = 'Gagal';
                        String amountz = s.SCC_Amount__c.format();
                        s.SCC_Resolution_Category__c = 'Tidak Mengirimkan Notifikasi'; 
                        s.SCC_Closure_Comments__c = Label.Closed_Rekon;
                        s.SCC_Drone_Remark_Update__c = 'Transaksi gagal dana sudah dikembalikan ke rekening nasabah pada tanggal ' + rekeningKoranTglTrans ;
                        
                        listcs.add(s);
                        matchedConditionCount = 0;
                        matchedKor = 0;
                    }
                    else {
                        matchedConditionCount = 0;
                        matchedKor = 0;
                    }
                }
            }

            if (!listcs.isEmpty()) {
                update listcs;
            }

            if(!listrek.isEmpty()) {
                insert listrek;
            }


        } catch (Exception exc) {
            InsertErrorLog(exc);
        }
    }

    public void finish(Database.BatchableContext bc) {
        // Finish method is empty as we removed the chain to other batch processes
        if (!Test.isRunningTest()) {
            String cond = '(isclosed = false OR IsClosed__c = false) and SCC_Call_Type__r.external_id__c=\'8434\' and IsLocked__c=false and SCC_Account_Number__c != null and Status = \'Escalated\' and (Approval_Status__c=\'draft\' or Approval_Status__c=\'rejected\') and CreatedDate = LAST_WEEK';
            String addfield = ', SCC_Call_Type__r.name,SCC_Call_Type__r.External_id__c,SCC_Call_Type_Feature__r.Fitur_ID__c,Terminal_ID__r.name,account.name';
            String allfield = SOQL_SOBJECT.getallfield('Case');
            String queries = SOQL_SOBJECT.SOQL(allfield, addfield, 'Case', cond, '', '', '');
            Database.executeBatch(new SCC_Batch_AutoClosed_Pulsa_Token(queries), 200);
        }
    }
   


    private SCC_Rekening_Koran__c mapRekeningKoran(SCC_CaseResoultion_DataHub_Wrapper.SavingMutationData data , Case cs){
       
        SCC_Rekening_Koran__c rekeningKoran = new SCC_Rekening_Koran__c();
        rekeningKoran.SCC_Case__c = cS.id;
        rekeningKoran.SCC_auxtrc__c = data.auxtrc;
        rekeningKoran.SCC_Deskripsi_Transaksi__c = data.deskTran;
        rekeningKoran.SCC_GLSign__c = data.glsign;
        rekeningKoran.SCC_ID_Number__c = data.idNum;
        rekeningKoran.SCC_ID_Number_2__c = data.idNum2;
        rekeningKoran.SCC_ID_Number_3__c = data.idNum3;
        rekeningKoran.SCC_Jam_Transaksi__c  = data.jamTran;
        rekeningKoran.SCC_Jam_Trans__c = SCC_CaseResolution_UI.convertjam(data.jamTran);
        rekeningKoran.SCC_Kode_Transaksi__c = data.kodeTran;
        rekeningKoran.SCC_Mutasi_Debet__c = data.mutasiDebet;
        rekeningKoran.SCC_Mutasi_Kredit__c = data.mutasiKredit;
        rekeningKoran.SCC_Nomor_Rekening__c  = data.noRek;
        rekeningKoran.SCC_Saldo_Akhir_Mutasi__c = data.saldoAkhirMutasi;
        rekeningKoran.SCC_Saldo_Awal_Mutasi__c = data.saldoAwalMutasi;
        rekeningKoran.SCC_Sequence__c = data.seq;
        rekeningKoran.SCC_Serial__c = data.serial;
        rekeningKoran.SCC_Terbilang__c = data.terbilang;
        rekeningKoran.SCC_Tanggal_Effektif__c = data.tglEfektif;
        rekeningKoran.SCC_Tanggal_Transaksi__c = data.tglTran;
        rekeningKoran.SCC_tblds1__c = data.tlbds1;
        rekeningKoran.SCC_tblds2__c = data.tlbds2;
        rekeningKoran.SCC_trremk__c = data.trremk;
        rekeningKoran.SCC_Truser__c = data.truser;

        return rekeningKoran;
        
    }

    public class RekeningKoranEdcWrapper{
        public Boolean matchedKorRemark{get;set;} 
        public Boolean matchedConditionAmount{get; set;}
        public RekeningKoranEdcWrapper(Boolean matchedKorRemark , Boolean matchedConditionAmount){
            this.matchedKorRemark = matchedKorRemark;
            this.matchedConditionAmount = matchedConditionAmount;
        }
     }


     private RekeningKoranEdcWrapper checkRekeningKoranEdc(Case cS,  SCC_CaseResoultion_DataHub_Wrapper.SavingMutationData data, Map<String, Set<String>> mapKor){

        //get call type
        String caseType = cS.SCC_Call_Type__r.external_id__c;
        String brivaNumber = cS.SCC_Nomor_Briva_Tagihan__c;
        Boolean matchedKorRemark = false;
        Boolean matchedConditionAmount = (cS.SCC_Amount__c == data.mutasiKredit);
        System.debug('matchedConditionAmount rekening koran : '+matchedConditionAmount);
        String remark = data.trremk;

        if (!matchedConditionAmount) {
            return new RekeningKoranEdcWrapper(false, false);
        }
        else {
            Set<String> masterKorSet = mapKor.get(caseType);
            if(masterKorSet != null && !masterKorSet.isEmpty() && remark != null){
                Integer countKor = 0;
                for(String korType: masterKorSet){
                    System.debug('remark kor rekening koran : '+remark.toUpperCase());
                    System.debug('remark kor korType : '+korType.toUpperCase());
                    if(remark.toUpperCase().contains(korType.toUpperCase())){
                        System.debug('Kor Sama');
                        countKor++;
                    }
                }
                if(countKor == 1){
                    matchedKorRemark = true;
                }
            }
        }
        return new RekeningKoranEdcWrapper(matchedKorRemark, matchedConditionAmount);
     }
    

    public static void insertErrorLog(Exception exc){
        ErrorLogRecord.DebugLog dl = new ErrorLogRecord.DebugLog();
        dl.message = exc?.getMessage();
        dl.trace = exc?.getStackTraceString();
        dl.typename = exc?.getTypeName();
        dl.linenumber = string.valueOf(exc?.getLineNumber()); 
        dl.errorcause = string.valueOf(exc?.getCause()); 
        dl.classname = 'SCC_Batch_AutoClosed';
        dl.iduser = UserInfo.getUserId();
        ErrorLogRecord.inserterror(JSON.serialize(dl));
    }
}