force-app/main/default/objects/Case/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Waiting for Checker</fullName>
            </value>
            <value>
                <fullName>Waiting for Signer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <formula>IF(CASE(TEXT(Status), &apos;Closed&apos;, &apos;1&apos;, &apos;Cancelled&apos;, &apos;1&apos;,&apos;Disconnected&apos;, &apos;1&apos;, &apos;0&apos;)==&apos;1&apos;,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsLocked__c.field-meta.xml
<CustomField>
    <fullName>IsLocked__c</fullName>
    <formula>IF((TEXT(Approval_Status__c)==&apos;Draft&apos; || TEXT(Approval_Status__c)==&apos;Rejected&apos; || ISBLANK(TEXT(Approval_Status__c))) &amp;&amp; !IsClosed__c,FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsLocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <description>Migration.The account number or credit card number</description>
    <label>Nomor Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type_Feature__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Type Feature</label>
    <referenceTo>SCC_Call_Type_Feature__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Terminal_ID__c.field-meta.xml
<CustomField>
    <fullName>Terminal_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terminal ID</label>
    <referenceTo>SCC_Terminal_ID__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCC_Call_Type_Feature__c/SCC_Call_Type_Feature__c.object-meta.xml
<CustomObject>
    <label>Case Type Feature</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Type Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Call_Type_Feature__c/fields/Fitur_ID__c.field-meta.xml
<CustomField>
    <fullName>Fitur_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fitur ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Terminal_ID__c/SCC_Terminal_ID__c.object-meta.xml
<CustomObject>
    <label>SCC Terminal ID</label>
    <nameField>
        <label>Terminal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCC Terminal ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Terminal_ID__c/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SCC_CaseResolution_Invoc.cls
/**
* @description       : Queue Notification to Leader Every Hour
* @last modified on  : 03/12/2024
* @last modified by  : Alvin Vigo, Lucas Kalasuvich
**/


public with sharing class SCC_CaseResolution_Invoc {
    @InvocableMethod(label='Invocable Case Resolution' description='Invocable code model can call from apex/flow' category='Invocable')    
    public static void invocablevoid(List< FlowInputValues > flowinput) {
        for(FlowInputValues fi:flowinput){
            if(fi.source=='CHM Support'){
                CHMSupport(fi);
            }
            else if(fi.source=='BRI Notification'){
                BRINotification(fi);
            }
            else if(fi.source=='Rekon'){
                Rekon(fi);
            }
        }
    }
    
    public static void chmSupport(FlowInputValues fi){
        if(fi.tipe=='Pembukuan'){
            System.enqueueJob(new SCC_CaseResolution_Pembukuan(fi.csid));
        }
        else if(fi.tipe=='User'){
            System.enqueueJob(new SCC_User1st(''));
        }
        else if(fi.tipe=='TID'){
            SCC_CaseResolution_CHMSupport.checkTerminal(fi.csid);
        }
    }

    public static void rekon(FlowInputValues fi){
        if(fi.tipe=='Flag Data Rekon'){
            //SCC_Rekon.FlagDataRekonFuture(fi.csid);
        }
        else if(fi.tipe=='Auto Closed Rekon'){
            String cond = '(isclosed = false OR IsClosed__c = false) and (SCC_Call_Type__r.external_id__c='+'\'8812'+'\' or SCC_Call_Type__r.external_id__c='+'\'8915'+'\') and IsLocked__c=false and SCC_Account_Number__c != null and Status = '+'\'Escalated'+'\' and (Approval_Status__c='+'\'draft'+'\' or Approval_Status__c='+'\'rejected'+'\')';
            String addfield = ',SCC_Call_Type__r.name,SCC_Call_Type__r.External_id__c,SCC_Call_Type_Feature__r.Fitur_ID__c,Terminal_ID__r.name,account.name';
            String allfield = SOQL_SOBJECT.getallfield('Case');
            String queries = SOQL_SOBJECT.SOQL(allfield, addfield, 'Case', cond, '', '', '');
            Database.executeBatch(new SCC_Batch_AutoClosed_RekeningKoran(queries), 1);
        }
    }
    
    public static void briNotification(FlowInputValues fi){
        if(fi.tipe=='Whatsapp Notification'){
            if(system.isBatch() || system.isFuture()){
                SCC_BRINotif.sendWANotifCase(fi.csid);
            }
            else{
                SCC_BRINotif.sendWANotifFuture(fi.csid);
            }
        }
    }

    public class FlowInputvalues{
        //PARAM
        @invocablevariable public String source;
        @invocablevariable public String tipe;
        @invocablevariable public String csid;
    }
}