force-app/main/default/objects/Case/fields/Approved_Date_Checker__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date_Checker__c</fullName>
    <label>Approved Date Checker</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Main_Branch__c.field-meta.xml
<CustomField>
    <fullName>Main_Branch__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Main Branch</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Main_Branch_Description__c.field-meta.xml
<CustomField>
    <fullName>Main_Branch_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Main Branch Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Attachment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Attachment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attachment?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Bank_BRI__c.field-meta.xml
<CustomField>
    <fullName>SCC_Bank_BRI__c</fullName>
    <label>Bank BRI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sosmed_Message_Content__c.field-meta.xml
<CustomField>
    <fullName>Sosmed_Message_Content__c</fullName>
    <label>Sosmed Message Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SCC_Batch_NotificationCase.cls
global class SCC_Batch_NotificationCase implements Database.AllowsCallouts,Database.Batchable<Case>{
    public List<Case> recordset = new List<Case>();
    
    global SCC_Batch_NotificationCase(List<Case> recordget){
        recordset = recordget;          
    }
    
	global List<Case> start(Database.BatchableContext bc) {
        return recordset;
    }

    global void execute(Database.BatchableContext bc, List<Case> scope) {
        for(Case s : scope){
            //SCC_HttpReq_NotificationCase.sendNotif(Message,Date,Orgeh,Branch,Is_Konsolidasi,Uker_Type);
            SCC_HttpReq_NotificationCase.sendNotif(s.Sosmed_Message_Content__c,String.valueOf(s.Approved_Date_Checker__c),s.Main_Branch_Description__c,s.Main_Branch__c,s.SCC_Attachment__c,s.SCC_Bank_BRI__c);
        }
    }

    global void finish(Database.BatchableContext bc) {
        // execute any post-processing operations - send emails, notify clients
    }
   
}