force-app/main/default/objects/Case/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <formula>IF(  LEFT(OwnerId, 3)= &apos;005&apos; &amp;&amp; Main_Branch__c != &apos;&apos; &amp;&amp;  Main_Branch_Description__c != &apos;&apos;, Owner:User.BranchCode__c , 

IF( Cost_Center__c != &apos;&apos;, &apos;00229&apos;, CodeBranch__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>SCC_Assigned_Date__c</fullName>
    <description>For migration only. It is the date time when case is assigned to the case owner.</description>
    <label>Tgl Assigned</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Sub_Escalation_Level__c.field-meta.xml
<CustomField>
    <fullName>SCC_Sub_Escalation_Level__c</fullName>
    <label>Sub Level Eskalasi</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Escalation Level 1</fullName>
            </value>
            <value>
                <fullName>Escalation Level 2</fullName>
            </value>
            <value>
                <fullName>Escalation Level 3</fullName>
            </value>
            <value>
                <fullName>Escalation Level 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Agent_SLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Agent_SLA__c</fullName>
    <description>This defines Agent SLA</description>
    <label>Agent SLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Customer_Segment__c</fullName>
    <description>Consists of the type of segment of the case.</description>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level1_OLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level1_OLA__c</fullName>
    <description>This is the OLA for Level 1</description>
    <label>Level 1 OLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level2_OLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level2_OLA__c</fullName>
    <description>This is for OLA Level 2</description>
    <label>Level 2 OLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level3_OLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level3_OLA__c</fullName>
    <description>This is for OLA Level 3</description>
    <label>Level 3 OLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level4_OLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level4_OLA__c</fullName>
    <description>This is for OLA Level 4</description>
    <label>Level 4 OLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Sub_Description__c.field-meta.xml
<CustomField>
    <fullName>SCC_Sub_Description__c</fullName>
    <description>This fields allows agent to add sub-description</description>
    <label>Sub Case Reference</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Category__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complaint - Non-Transaction</fullName>
            </value>
            <value>
                <fullName>Complaint - Transaction</fullName>
            </value>
            <value>
                <fullName>Customer Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud / Suspicious Transactions</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Platform &amp; Device Support</fullName>
            </value>
            <value>
                <fullName>Products / Promotion Inquiry</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Third Party Support</fullName>
            </value>
            <value>
                <fullName>Customer Feedback / Sentiment Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Description__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Description__c</fullName>
    <label>Deskripsi Case</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Level_1_Escalation_Team__c.field-meta.xml
<CustomField>
    <fullName>SSC_Level_1_Escalation_Team__c</fullName>
    <description>Escalation Team names on Case Type record as picklist</description>
    <label>Level 1 Escalation Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SSC_Escalation_Team</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Level_2_Escalation_Team__c.field-meta.xml
<CustomField>
    <fullName>SSC_Level_2_Escalation_Team__c</fullName>
    <description>Escalation Team names on Case Type record as picklist</description>
    <label>Level 2 Escalation Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SSC_Escalation_Team</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Level_3_Escalation_Team__c.field-meta.xml
<CustomField>
    <fullName>SSC_Level_3_Escalation_Team__c</fullName>
    <description>Escalation Team names on Case Type record as picklist</description>
    <label>Level 3 Escalation Teams</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SSC_Escalation_Team</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Level_4_Escalation_Team__c.field-meta.xml
<CustomField>
    <fullName>SSC_Level_4_Escalation_Team__c</fullName>
    <description>Escalation Team names on Case Type record as picklist</description>
    <label>Level 4 Escalation Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SSC_Escalation_Team</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L1__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L1__c</fullName>
    <label>Product Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Transaction Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L2__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L2__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SSC_Product_L1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bancassurance</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Deposito</fullName>
            </value>
            <value>
                <fullName>Digital Savings</fullName>
            </value>
            <value>
                <fullName>DPLK (Pension Fund)</fullName>
            </value>
            <value>
                <fullName>Electronic Money</fullName>
            </value>
            <value>
                <fullName>Giro (CA)</fullName>
            </value>
            <value>
                <fullName>Government Programme</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>Kartu Debit</fullName>
            </value>
            <value>
                <fullName>Kartu Kredit</fullName>
            </value>
            <value>
                <fullName>KPR (Mortgage)</fullName>
            </value>
            <value>
                <fullName>Kredit Investasi (Investment Loan)</fullName>
            </value>
            <value>
                <fullName>Kredit Modal Kerja (Working Capital)</fullName>
            </value>
            <value>
                <fullName>KTA (Personal Loan)</fullName>
            </value>
            <value>
                <fullName>KTA - Digital</fullName>
            </value>
            <value>
                <fullName>KUR (Business Loan - Micro)</fullName>
            </value>
            <value>
                <fullName>Mobile Banking</fullName>
            </value>
            <value>
                <fullName>Pawning</fullName>
            </value>
            <value>
                <fullName>Safe Deposit</fullName>
            </value>
            <value>
                <fullName>SBN (Bonds)</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Cabang</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Contact Center</fullName>
            </value>
            <value>
                <fullName>Tabungan</fullName>
            </value>
            <value>
                <fullName>Virtual Account</fullName>
            </value>
            <value>
                <fullName>Aplikasi Commodity Chain</fullName>
            </value>
            <value>
                <fullName>Informasi Promo, Program, Produk</fullName>
            </value>
            <value>
                <fullName>PPID</fullName>
            </value>
            <value>
                <fullName>Senyum Mobile</fullName>
            </value>
            <value>
                <fullName>Trustee &amp; Wali Amanat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SCC_CaseMilestoneServiceTest.cls
@isTest
public class SCC_CaseMilestoneServiceTest {
	@testSetup static void setup(){
        Account acc = new Account(
            Name= 'test');
        Insert acc;
        
        BusinessHours bh = [SELECT Id FROM BusinessHours LIMIT 1];
        SlaProcess esc = [SELECT Id, Name, VersionNumber FROM SlaProcess where name = 'Case Entitlement' order by VersionNumber desc limit 1];
        Entitlement entitlement = new Entitlement(
            Name = 'Agent SLA With Level 4 OLA',
            AccountId = acc.id,
            BusinessHoursId = bh.Id,
            SlaProcessId = esc.Id // Assuming there's a relationship
        );
        insert entitlement;
        
        Case cs = new Case();
        cs.Subject = 'Test';
        cs.Description = 'Test';
        cs.EntitlementId = entitlement.Id; 
        cs.OwnerId = UserInfo.getUserId();
        cs.Status = 'New';
        cs.SCC_Assigned_Date__c = DateTime.Now();
        insert cs;
        
        SSC_Call_Type__c callType = new SSC_Call_Type__c(
            Name = '1003',
            SCC_Agent_SLA__c = 60,
            SCC_Sub_Description__c = 'Initial Value',
            SSC_Case_Description__c = 'xyz',
            External_Id__c = '8812',
            SCC_Customer_Segment__c = 'UMKM',
            SSC_Product_L1__c = 'Servicing',
            SSC_Product_L2__c = 'Cash Management',
            SSC_Case_Category__c = 'Request',
            SSC_Level_1_Escalation_Team__c = 'CDD - Coll Card & Digital Lending-CERIA',
            SSC_Level_2_Escalation_Team__c = 'ORD - Fraud Management & Recovery Desk',
            SSC_Level_3_Escalation_Team__c = 'CDD - Business Partnership Team - PRN',
            SSC_Level_4_Escalation_Team__c = 'CDD - Clf-1 Credit Card Init - SSU',
            SCC_Level1_OLA__c = 5,
            SCC_Level2_OLA__c = 10,
            SCC_Level3_OLA__c = 15,
            SCC_Level4_OLA__c = 20,
            Active__c = true
        );
        insert callType;
        
        Case cs1 = new Case();
        cs1.Subject = 'Test';
        cs1.Description = 'Test';
        cs1.EntitlementId = entitlement.Id;
        cs1.OwnerId = UserInfo.getUserId();
        cs1.Status = 'New';
        cs1.SCC_Assigned_Date__c = DateTime.Now();
        cs1.SCC_Call_Type__c = callType.Id;
        insert cs1;
    }
    
    static testMethod void testProcess(){
        Case cs = [SELECT Id,Branch_Code__c,Status,SCC_Assigned_Date__c,EntitlementId,Entitlement.BusinessHoursId,SCC_Sub_Escalation_Level__c,IsClosed FROM Case WHERE SCC_Call_Type__c = NULL LIMIT 1];
        system.debug('cs:'+cs);
        Case cs1 = [SELECT Id,Branch_Code__c,Status,SCC_Assigned_Date__c,EntitlementId,Entitlement.BusinessHoursId,SCC_Sub_Escalation_Level__c,IsClosed FROM Case WHERE SCC_Call_Type__c != NULL LIMIT 1];
        system.debug('cs1:'+cs1);
        Entitlement et = [SELECT Id,BusinessHoursId FROM Entitlement LIMIT 1];
        system.debug('et:'+et);
        cs1.EntitlementId = et.Id;
        update cs1;
        system.debug('cs1:'+cs1);
        List<CaseMilestone> listcm = [SELECT Id,TimeRemainingInMins,TargetResponseInMins,ElapsedTimeInMins,
                            MilestoneType.Name,IsViolated,IsCompleted,TargetDate,TimeSinceTargetInMins,BusinessHoursId
                            FROM CaseMilestone WHERE CaseId =:cs1.Id];
        system.debug('listcm:'+listcm);
        CaseMilestone cm = new CaseMilestone();
        if(listcm.size()>0){
            cm = listcm[0];
        }
        Test.startTest();
        SCC_CaseMilestoneService.CaseMilestoneWrapper cms = new SCC_CaseMilestoneService.CaseMilestoneWrapper(false,
                                                                                     false,
                                                                                     '',
                                                                                     '',
                                                                                     false,
                                                                                     false,
                                                                                     null,
                                                                                     '0',
                                                                                     1,
                                                                                     '00:00',
                                                                                     '00:00',
                                                                                     false,
                                                                                     false,
                                                                                     1);
        SCC_CaseMilestoneService.addMilestone(cs,null,false,false,true,'',0,'',null); //CaseMilestone NULL
        SCC_CaseMilestoneService.addMilestone(cs,cm,false,false,false,'',0,'',null); //CaseMilestone 
        SCC_CaseMilestoneService.getCaseMilestonesWithCallTypeDetails(cs.Id); //Case no Call Type
        SCC_CaseMilestoneService.getCaseMilestonesWithCallTypeDetails(cs1.Id); //Case with Call Type
        Test.stopTest();
    }
}