force-app/main/default/objects/Case/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8812</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Cust_Current_Phone__c.field-meta.xml
<CustomField>
    <fullName>Cust_Current_Phone__c</fullName>
    <label>Nomor Telp yang dapat dihubungi</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <description>Migration.The account number or credit card number</description>
    <label>Nomor Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_BRINotif_reffNumber__c.field-meta.xml
<CustomField>
    <fullName>SCC_BRINotif_reffNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Result Whatsapp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type_Feature__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Type Feature</label>
    <referenceTo>SCC_Call_Type_Feature__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Cust_Phone1__c.field-meta.xml
<CustomField>
    <fullName>SCC_Cust_Phone1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Status_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Status_Transaksi__c</fullName>
    <label>Status Transaksi</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Berhasil</fullName>
            </value>
            <value>
                <fullName>Gagal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Terminal_ID__c.field-meta.xml
<CustomField>
    <fullName>Terminal_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terminal ID</label>
    <referenceTo>SCC_Terminal_ID__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCC_Call_Type_Feature__c/SCC_Call_Type_Feature__c.object-meta.xml
<CustomObject>
    <label>Case Type Feature</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Type Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Call_Type_Feature__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type</label>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Call Type Features</relationshipLabel>
    <relationshipName>Call_Type_Feature</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCC_Call_Type_Feature__c/fields/Fitur_ID__c.field-meta.xml
<CustomField>
    <fullName>Fitur_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fitur ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Endpoint_API__mdt/SCC_Endpoint_API__mdt.object-meta.xml
<CustomObject>
    <label>SCC Endpoint API</label>
    <pluralLabel>SCC Endpoint API</pluralLabel>
</CustomObject>

force-app/main/default/objects/SCC_Terminal_ID__c/SCC_Terminal_ID__c.object-meta.xml
<CustomObject>
    <label>SCC Terminal ID</label>
    <nameField>
        <label>Terminal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCC Terminal ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Terminal_ID__c/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_WA_Template__mdt/SCC_WA_Template__mdt.object-meta.xml
<CustomObject>
    <label>WA Template</label>
    <pluralLabel>WA Template</pluralLabel>
</CustomObject>

force-app/main/default/objects/SCC_WA_Template__mdt/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_WA_Template__mdt/fields/Count_Param_Body__c.field-meta.xml
<CustomField>
    <fullName>Count_Param_Body__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count Param Body</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_WA_Template__mdt/fields/Count_Param_Header__c.field-meta.xml
<CustomField>
    <fullName>Count_Param_Header__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count Param Header</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_WA_Template__mdt/fields/Notif_Pengiriman__c.field-meta.xml
<CustomField>
    <fullName>Notif_Pengiriman__c</fullName>
    <label>Notif Pengiriman</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Berhasil</fullName>
                <default>true</default>
                <label>Berhasil</label>
            </value>
            <value>
                <fullName>Gagal</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SCC_BRINotif.cls
public with sharing class SCC_BRINotif {
    public static SCC_BRINotif_Wrapper.WANotifResponse SendWANotif(SCC_BRINotif_Wrapper.WANotifRequest cdh){
        String url_current = url.getCurrentRequestUrl().tostring().replace('Url:[delegate=','').substringBeforeLast(']');
        SCC_BRINotif_Wrapper.WANotifResponse cps = new  SCC_BRINotif_Wrapper.WANotifResponse();
        map<String,SCC_BRINotif_Wrapper.WANotifPesan> m = new map<String,SCC_BRINotif_Wrapper.WANotifPesan>();
        for(SCC_BRINotif_Wrapper.WANotifPesan psn:cdh.pesanWA){
            m.put(psn.type,psn);
        }
        SCC_Endpoint_API__mdt eapi = SCC_Endpoint_API__mdt.getInstance('BRINotifWA');
        //String bodyreq = JSON.serialize(cdh,true);
        JSONGenerator gentoken = JSON.createGenerator(true);
        gentoken.writeStartObject();
        gentoken.writeStringField('rekening', cdh.rekening);
        gentoken.writeStringField('produk', cdh.produk);
        gentoken.writeStringField('phoneNumber', cdh.phoneNumber);
        gentoken.writeStringField('pesan', cdh.pesan);
        gentoken.writeFieldName('pesanWa');
        gentoken.writeStartArray();
        if(m.containsKey('header')){
            SCC_BRINotif_Wrapper.WANotifPesan h = m.get('header');
            setJsonRequest(h, gentoken);
        }
        if(m.containsKey('body')){
            SCC_BRINotif_Wrapper.WANotifPesan b = m.get('body');
            setJsonRequest(b, gentoken);
        }
        gentoken.writeEndArray();
        gentoken.writeStringField('sendTime', cdh.sendTime);
        gentoken.writeEndObject();
        String bodyreq = gentoken.getAsString();
        SCC_API.WrapperAPI wapi = SCC_API.getResponseAPI('BRINotifWA', bodyreq,'','SCC_BRINotif');
        try{
            cps = (SCC_BRINotif_Wrapper.WANotifResponse) JSON.deserialize(wapi.res.getBody(), SCC_BRINotif_Wrapper.WANotifResponse.class);
        }
        catch(exception exc){
            InsertErrorLog(exc,wapi.req,wapi.res,url_current);
        }
        return cps;
    }

    public static void setJsonRequest(SCC_BRINotif_Wrapper.WANotifPesan wa, JSONGenerator gentoken){
        gentoken.writeStartObject();
        gentoken.writeStringField('type', wa.type);
        gentoken.writeFieldName('parameters');
        gentoken.writeStartArray();
        for(SCC_BRINotif_Wrapper.WANotifParameter prm:wa.parameters){
            gentoken.writeStartObject();
            gentoken.writeStringField('type', prm.type);
            if(prm.type=='text'){
                gentoken.writeStringField('text', prm.text);
            }
            if(prm.type=='image'){
                gentoken.writeStringField('image', prm.image);
            }
            gentoken.writeEndObject();
        }
        gentoken.writeEndArray();
        gentoken.writeEndObject();
    }

    public static SCC_BRINotif_Wrapper.WANotifRequest setWANotifRequest(String csid){
        SCC_BRINotif_Wrapper.WANotifRequest warequest = new SCC_BRINotif_Wrapper.WANotifRequest();
        List<SCC_BRINotif_Wrapper.WANotifParameter> listprmhd = new List<SCC_BRINotif_Wrapper.WANotifParameter>();
        List<SCC_BRINotif_Wrapper.WANotifParameter> listprmbd = new List<SCC_BRINotif_Wrapper.WANotifParameter>();
        SCC_BRINotif_Wrapper.WANotifPesan psnhd = new SCC_BRINotif_Wrapper.WANotifPesan();
        SCC_BRINotif_Wrapper.WANotifPesan psnbd = new SCC_BRINotif_Wrapper.WANotifPesan();
        List<SCC_BRINotif_Wrapper.WANotifPesan> listpsn = new List<SCC_BRINotif_Wrapper.WANotifPesan>();
        String phn = '';
        try{
            String cond = 'id =: csid';
            String addfield = ',SCC_Call_Type__r.Name,SCC_Call_Type__r.External_id__c,SCC_Call_Type_Feature__r.Fitur_ID__c,Terminal_ID__r.name,Account.phone,Account.PersonMobilePhone ';
            String allfield = SOQL_SOBJECT.getallfield('Case');
            String queries = SOQL_SOBJECT.SOQL(allfield, addfield, 'Case', cond, '', '', '');
            Case cs = Database.query(queries);
            if(String.isNotBlank(cs?.account?.PersonMobilePhone)){
                phn = cs?.account?.PersonMobilePhone;
            }
            else if(String.isNotBlank(cs?.account?.phone)){
                phn = cs?.account?.phone;
            }
            if(String.isnotblank(cs?.Cust_Current_Phone__c)){
                phn = cs?.Cust_Current_Phone__c;
            }
            else if(String.isnotblank(cs?.SCC_Cust_Phone1__c)){
                phn = cs?.SCC_Cust_Phone1__c;
            }
            String ct = '';
            if(String.isnotblank(cs?.SCC_Call_Type__r?.Name)){
            	ct = '%'+cs?.SCC_Call_Type__r?.Name.substringbefore('-').trim()+'%';
            }
            if(String.isnotblank(cs?.SCC_Call_Type__r?.External_id__c)){
            	ct = '%'+cs?.SCC_Call_Type__r?.External_id__c+'%';
            }
            system.debug('ct : ' + ct);
            //String ct = '%'+cs.SCC_Call_Type__r.Name+'%';
            String notif = cs.SCC_Status_Transaksi__c;
            system.debug('status : ' + cs.SCC_Status_Transaksi__c);
            String cond2 = 'call_type__c  like : ct and Notif_Pengiriman__c = :notif';
            String allfield2 = SOQL_SOBJECT.getallfield('SCC_WA_Template__mdt');
            String queries2 = SOQL_SOBJECT.SOQL(allfield2, '', 'SCC_WA_Template__mdt', cond2, '', '', '1');
            SCC_WA_Template__mdt watmp = Database.query(queries2);
            system.debug('watmp  : ' + watmp);
            if(watmp.Count_Param_Header__c>0){
                for(integer i=1;i<=watmp.Count_Param_Header__c;i++){
                    String tipe = String.valueOf(watmp.get('Type_Header_'+i+'__c'));
                    String fld = String.valueOf(watmp.get('Value_Header_'+i+'__c'));
                    SCC_BRINotif_Wrapper.WANotifParameter prm = setparam(tipe, fld, cs);
                    listprmhd.add(prm);
                }
                psnhd.type = 'header';
                psnhd.parameters = listprmhd;
            }
            if(watmp.Count_Param_Body__c>0){
                for(integer j=1;j<=watmp.Count_Param_Body__c;j++){
                    String tipe = String.valueOf(watmp.get('Type_Body_'+j+'__c'));
                    String fld = String.valueOf(watmp.get('Value_Body_'+j+'__c'));
                    SCC_BRINotif_Wrapper.WANotifParameter prm = setparam(tipe, fld, cs);
                    listprmbd.add(prm);
                }
                psnbd.type = 'body';
                psnbd.parameters = listprmbd;
            }
            if(!listprmhd.isEmpty()){
                listpsn.add(psnhd);
            }
            if(!listprmbd.isEmpty()){
                listpsn.add(psnbd);
            }
            warequest.rekening = cs.SCC_Account_Number__c;
            warequest.produk = watmp.MasterLabel ;
            warequest.phoneNumber = phn;
            warequest.pesan = 'BRI-NOTIF';
            warequest.pesanWA = listpsn;
            warequest.sendtime = String.valueof(system.now());
        }
        catch(exception exc){
            InsertErrorLog(exc,new HttpRequest(),new HTTPResponse(),'');
        }
        return warequest;
    }

    public static void SendWANotifCase(String csid){
        try{
            SCC_BRINotif_Wrapper.WANotifRequest req = SCC_BRINotif.setWANotifRequest(csid);
            SCC_BRINotif_Wrapper.WANotifResponse res = SCC_BRINotif.SendWANotif(req);
            Case cs = new Case();
            cs.id = csid;
            cs.SCC_BRINotif_reffNumber__c = res?.responseMessage;
            update cs;
        }
        catch(Exception exc){
            InsertErrorLog(exc,new HttpRequest(),new HTTPResponse(),'');
        }
    }

    @future(callout=true)
    public static void SendWANotifFuture(String csid){
        SendWANotifCase(csid);
    }

    public static SCC_BRINotif_Wrapper.WANotifParameter setparam(String tipe,String fld,Case cs){
        SCC_BRINotif_Wrapper.WANotifParameter prm = new SCC_BRINotif_Wrapper.WANotifParameter();
        prm.type=tipe;
        if(tipe =='text') {
            prm.text = String.valueOf(cs.get(fld));
        }
        if(tipe =='image'){
            prm.image = String.valueOf(cs.get(fld));
        }
        return prm;
    }

    public static void InsertErrorLog(Exception exc,HttpRequest req,HTTPResponse res,String url_current){
        SCC_API.InsertErrorLog(exc,req,res,new SCC_API.WrapperError(url_current,'SCC_BRINotif'));
    }
}