force-app/main/default/objects/Case/fields/Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason__c</fullName>
    <label>Alasan High (Urgent)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pengaduan yang disampaikan dengan kemarahan dan ancaman (hard complaint)</fullName>
            </value>
            <value>
                <fullName>Pengaduan yang disampaikan oleh tokoh masyarakat setempat, pejabat daerah setempat, termasuk wartawan dan Lembaga Sosial Masyarakat (LSM)</fullName>
            </value>
            <value>
                <fullName>Pengaduan yang berulang</fullName>
            </value>
            <value>
                <fullName>Pengaduan yang melebihi SLA yang dijanjikan</fullName>
            </value>
            <value>
                <fullName>Pengaduan yang masuk media sosial dan berpotensi viral</fullName>
            </value>
            <value>
                <fullName>Pengaduan yang masuk ke media massa (cetak/elektronik)</fullName>
            </value>
            <value>
                <fullName>Pengaduan yang disampaikan kembali karena belum menyetujui hasil investigasi sanggahan transaksi sebelumnya</fullName>
            </value>
            <value>
                <fullName>Nasabah UKO Metro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Formulir_Detail__c.field-meta.xml
<CustomField>
    <fullName>Formulir_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Formulir Detail</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Formulir_Detail__c.Case_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.SCC_Call_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Formulir_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Type__c/Case_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulir_Detail__c/Formulir_Detail__c.object-meta.xml
<CustomObject>
    <label>Formulir Detail</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Formulir Detail</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulir Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulir_Detail__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type</label>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Formulir Details</relationshipLabel>
    <relationshipName>Formulir_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ctrl_picklistFormulir.cls
public without sharing class Ctrl_picklistFormulir {
	@AuraEnabled(cacheable=true)
    public static Map<String, String> getMasterPicklist(Id recordId,String idCallType) {
        Map<String, String> options = new Map<String, String>();
        /*List<Schema.DescribeSobjectResult> results = Schema.describeSObjects(new List<String>{'Case'});
        for(Schema.DescribeSobjectResult res : results) {
            for (Schema.PicklistEntry entry : res.fields.getMap().get('Case_Reason__c').getDescribe().getPicklistValues()) {
                if (entry.isActive()) {
                    options.put(entry.getValue(), entry.getLabel());
                }
            }
            
        }*/
        options.put('','Select an Option');
        List<Case> listcs = [SELECT Id,SCC_Call_Type__c FROM Case WHERE Id=:recordId AND SCC_Call_Type__c != NULL];
        if(listcs.size()>0){
            Case cs = listcs[0];
            if(idCallType == null) idCallType = cs.SCC_Call_Type__c;
            system.debug('idCallType:'+idCallType);
            List<Formulir_Detail__c> listdata = [SELECT Id,Name FROM Formulir_Detail__c WHERE Case_Type__c =:idCallType];
            for(Formulir_Detail__c data : listdata){
                options.put(data.Id,data.Name);
            }
        }
        return options;
    }
    
    @AuraEnabled
    public static formulir saveSelectedValues(Id recordId, String selectedValue) {
        system.debug('recordId:'+recordId);
        system.debug('selectedValue:'+selectedValue);
        formulir result = new formulir();
        try{
            if(selectedValue == '') selectedValue = NULL;
            Case record = new Case(Id = recordId,Formulir_Detail__c = selectedValue);
            if (Schema.sObjectType.Case.fields.Formulir_Detail__c.isUpdateable()) {
                Database.SaveResult sr = Database.update(record);
                if(sr.isSuccess()) result.message = 'Success';
                else{ string errmsg = ''; for(Database.Error err : sr.getErrors()) { errmsg += err.getMessage();} result.message = errmsg; }
            }
            Case cs = getCase(recordId);
            result.description = cs.Description;
            result.id = cs.Id;
            result.isClosed = cs.IsClosed;
        }catch(Exception ex){ result.message = ex.getMessage();}
        if(result.message != null){
            if(result.message.indexOf('FIELD_CUSTOM_VALIDATION_EXCEPTION, ') > 0) result.message = result.message.substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,');
        }
        system.debug('result:'+result);
        return result;
    }
    
    @AuraEnabled(cacheable=true)
    public static String getFieldValues(Id recordId) {      
        Case cs = [SELECT Id,Formulir_Detail__c FROM Case WHERE Id=:recordId];
        return cs.Formulir_Detail__c;
    }
    
    @AuraEnabled(cacheable=true)
    public static Case getCase(Id recordId) {      
        Case cs = [SELECT Id,isClosed,Description FROM Case WHERE Id=:recordId];
        return cs;
    }

    public class formulir{
        @AuraEnabled public id id {get;set;}
        @AuraEnabled public Boolean isClosed {get;set;}
        @AuraEnabled public String Description {get;set;}
        @AuraEnabled public String message {get;set;}
    }
}