force-app/main/default/objects/Case/fields/Cust_Current_Phone__c.field-meta.xml
<CustomField>
    <fullName>Cust_Current_Phone__c</fullName>
    <label>Nomor Telp yang dapat dihubungi</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dokumen_Nasabah_c__c.field-meta.xml
<CustomField>
    <fullName>Dokumen_Nasabah_c__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Jika terdapat &apos;List Dokumen yang Dibutuhkan&apos; tetapi Ticket ini tidak memerlukan dokumen dan ingin tereskalasi secara langsung, maka silakan centang field berikut.

Field ini pun dapat tercentang otomatis jika nasabah sudah mengirimkan dokumen melalui email dan/atau sudah dilakukan upload file manual di Ticket.</inlineHelpText>
    <label>Dokumen Nasabah</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Progress_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Progress_Ticket__c</fullName>
    <description>This field is used by Back Office Agent for stating that this Ticket is already worked before getting closed in 2 days.</description>
    <inlineHelpText>Field ini digunakan untuk Agent Back Office menandai Ticket yang sudah dikerjakan sebelum di-Close dalam 2 hari.</inlineHelpText>
    <label>Progress Ticket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Belum Dikerjakan</fullName>
            </value>
            <value>
                <fullName>Sedang Dikerjakan</fullName>
            </value>
            <value>
                <fullName>Sudah Dikerjakan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Returned_Case__c.field-meta.xml
<CustomField>
    <fullName>Returned_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Field Indicates that case is been returned to its Initial case owner</description>
    <label>Returned Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <description>Migration.The account number or credit card number</description>
    <label>Nomor Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Amount__c.field-meta.xml
<CustomField>
    <fullName>SCC_Amount__c</fullName>
    <description>The amount from the dispute transaction</description>
    <label>Nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Bersedia_di_survey__c.field-meta.xml
<CustomField>
    <fullName>SCC_Bersedia_di_survey__c</fullName>
    <label>Bersedia di-survey?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ya</fullName>
            </value>
            <value>
                <fullName>Tidak</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Card_Number__c</fullName>
    <label>Nomor Kartu</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Case_Category__c.field-meta.xml
<CustomField>
    <fullName>SCC_Case_Category__c</fullName>
    <description>Migration. To store the case category</description>
    <label>Kategori Case</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Complaint - Transaction</fullName>
            </value>
            <value>
                <fullName>Fraud / Suspicious Transactions</fullName>
            </value>
            <value>
                <fullName>Products / Promotion Inquiry</fullName>
            </value>
            <value>
                <fullName>Complaint - Non-Transaction</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Platform &amp; Device Support</fullName>
            </value>
            <value>
                <fullName>Third Party Support</fullName>
            </value>
            <value>
                <fullName>Customer Feedback / Sentiment Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Channel_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Channel_Transaksi__c</fullName>
    <description>This field is used to capture Channel Transaksi (Transaction Channel) information on case.</description>
    <label>Channel Transaksi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EDC BRI</fullName>
            </value>
            <value>
                <fullName>EDC Bank Lain</fullName>
            </value>
            <value>
                <fullName>ATM / CRM BRI</fullName>
            </value>
            <value>
                <fullName>ATM Bank Lain</fullName>
            </value>
            <value>
                <fullName>QRIS BRI</fullName>
            </value>
            <value>
                <fullName>QRIS Bank Lain</fullName>
            </value>
            <value>
                <fullName>BRIMO</fullName>
            </value>
            <value>
                <fullName>CERIA</fullName>
            </value>
            <value>
                <fullName>BRI Credit Card Mobile</fullName>
            </value>
            <value>
                <fullName>Branch / Kantor BRI</fullName>
            </value>
            <value>
                <fullName>IBBIZ</fullName>
            </value>
            <value>
                <fullName>QLOLA</fullName>
            </value>
            <value>
                <fullName>Agen BRILink</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Non channel</fullName>
            </value>
            <value>
                <fullName>RPA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Closure_Comments__c.field-meta.xml
<CustomField>
    <fullName>SCC_Closure_Comments__c</fullName>
    <description>Contains a brief description of the Case resolution or why the Case should be closed</description>
    <label>Keterangan Closing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Email__c.field-meta.xml
<CustomField>
    <fullName>SCC_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_List_of_Required_Documents__c.field-meta.xml
<CustomField>
    <fullName>SCC_List_of_Required_Documents__c</fullName>
    <label>Dokumen yang dibutuhkan</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Nama_Pelapor__c.field-meta.xml
<CustomField>
    <fullName>SCC_Nama_Pelapor__c</fullName>
    <label>Nama Pelapor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Notes__c.field-meta.xml
<CustomField>
    <fullName>SCC_Notes__c</fullName>
    <description>Form to fill in the complain details</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Product_L1__c.field-meta.xml
<CustomField>
    <fullName>SCC_Product_L1__c</fullName>
    <description>Migration. To store the product related to the issue</description>
    <label>Product Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Transaction Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Product_L2__c.field-meta.xml
<CustomField>
    <fullName>SCC_Product_L2__c</fullName>
    <description>Migration.To store the product related to the issue</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SCC_Product_L1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Giro (CA)</fullName>
            </value>
            <value>
                <fullName>Tabungan (SA)</fullName>
            </value>
            <value>
                <fullName>Deposito</fullName>
            </value>
            <value>
                <fullName>Briguna Digital</fullName>
            </value>
            <value>
                <fullName>KTA (Personal Loan)</fullName>
                <label>KTA (Personal Loan) / Briguna</label>
            </value>
            <value>
                <fullName>KTA - Digital</fullName>
                <label>KTA - Digital / Ceria</label>
            </value>
            <value>
                <fullName>Kartu Kredit (Credit Card)</fullName>
            </value>
            <value>
                <fullName>KPR (Mortgage)</fullName>
            </value>
            <value>
                <fullName>KUR (Business Loan - Micro)</fullName>
            </value>
            <value>
                <fullName>KUR Ritel</fullName>
            </value>
            <value>
                <fullName>Kupedes</fullName>
            </value>
            <value>
                <fullName>Kredit Modal Kerja (Working Capital)</fullName>
            </value>
            <value>
                <fullName>Kredit Investasi (Investment Loan)</fullName>
            </value>
            <value>
                <fullName>KPR, KUR, KMK, KI</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>DPLK (Pension Fund)</fullName>
            </value>
            <value>
                <fullName>SBN (Bonds)</fullName>
            </value>
            <value>
                <fullName>Mobile Banking</fullName>
            </value>
            <value>
                <fullName>Bancassurance</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>Electronic Money</fullName>
            </value>
            <value>
                <fullName>Digital Savings</fullName>
            </value>
            <value>
                <fullName>Pawning</fullName>
                <label>Pawning / Gadai</label>
            </value>
            <value>
                <fullName>Aplikasi Commodity Chain</fullName>
            </value>
            <value>
                <fullName>Government Programme</fullName>
            </value>
            <value>
                <fullName>Informasi Promo, Program, Produk</fullName>
            </value>
            <value>
                <fullName>Kartu Debit</fullName>
            </value>
            <value>
                <fullName>PPID</fullName>
            </value>
            <value>
                <fullName>Safe Deposit</fullName>
            </value>
            <value>
                <fullName>Senyum Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Resolution_Category__c.field-meta.xml
<CustomField>
    <fullName>SCC_Resolution_Category__c</fullName>
    <label>Resolution Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Transactional</fullName>
                <label>Kirim Notifikasi</label>
            </value>
            <value>
                <fullName>Dokumen Tidak Lengkap</fullName>
            </value>
            <value>
                <fullName>Tidak Mengirimkan Notifikasi</fullName>
            </value>
            <value>
                <fullName>Transactional/Fraud with Refund</fullName>
                <isActive>false</isActive>
                <label>Transactional/Fraud with Refund</label>
            </value>
            <value>
                <fullName>Transactional/Fraud without Refund</fullName>
                <isActive>false</isActive>
                <label>Transactional/Fraud without Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCC_Terminal_ID__c/SCC_Terminal_ID__c.object-meta.xml
<CustomObject>
    <label>SCC Terminal ID</label>
    <nameField>
        <label>Terminal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCC Terminal ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Terminal_ID__c/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCC_RestrictCaseClosed.cls
/**
 * @description       : Class untuk restrict field yang ada di UI ketika Closed, tambahkan di metadata [SCC_RestrictCaseClosed] untuk restrict field
 * @author            : Alvin Vigo
 * @group             : 
 * @last modified on  : 16/12/2024
 * @last modified by  : Alvin Vigo
**/

public class SCC_RestrictCaseClosed {
    @TestVisible
    private static Boolean isBypassEnabled = false;
    
    @TestVisible
    private static Boolean isTest = false;
    
    public static void restrictCaseClosed(List<Case> newCases, Map<Id, Case> oldCaseMap) {
        // bypass case migrasi
        Boolean isByPassValidationforMigration = Test.isRunningTest() 
            ? isBypassEnabled 
            : FeatureManagement.checkPermission('By_Pass_Validation_for_Migration');
        
        if (isByPassValidationforMigration) {
            return;
        }
        
        // fields yang engga bisa edit di ticket closed,, tambahkan di metadata [SCC_RestrictCaseClosed] untuk restrict
        Set<String> fieldRestricted = new Set<String>();
        
        if(isTest){
            fieldRestricted = new Set<String>{
                'accountid',
                'cust_current_phone__c',
                'description',
                'dokumen_nasabah_c__c',
                'origin',
                'progress_ticket__c',
                'returned_case__c',
                'scc_account_number__c',
                'scc_amount__c',
                'scc_bersedia_di_survey__c',
                'scc_call_type__c',
                'scc_card_number__c',
                'scc_case_category__c',
                'scc_channel_transaksi__c',
                'scc_closure_comments__c',
                'scc_email__c',
                'scc_list_of_required_documents__c',
                'scc_nama_pelapor__c',
                'scc_notes__c',
                'scc_product_l1__c',
                'scc_product_l2__c',
                'scc_resolution_category__c',
                'scc_segment__c',
                'scc_sub_escalation_level__c',
                'scc_sudah_di_survey__c',
                'scc_terminal_id__c',
                'scc_waktu_transaksi__c',
                'ssc_call_type_description__c',
                'unit_kerja_2__c'
            };
        }
        else {
            List<SCC_RestrictCaseClosed__mdt> restrictedFieldList = [
                SELECT SCC_Field__c
                FROM SCC_RestrictCaseClosed__mdt
                WHERE SCC_Jenis__c = 'Field Restricted'
            ];
            
            for (SCC_RestrictCaseClosed__mdt field : restrictedFieldList) {
                fieldRestricted.add(field.SCC_Field__c.toLowerCase());
            }
        }
        
        for (Case newCase : newCases) {
            Case oldCase = oldCaseMap.get(newCase.Id);
            
            if (oldCase.Origin != 'MMS' && (oldCase.Status == 'Closed' || oldCase.Status == 'Disconnected' || oldCase.Status == 'Cancelled')) {
                Boolean hasUnauthorizedChanges = false;
                String unauthorizedFields = '';
                
                for (String fieldName : Schema.SObjectType.Case.fields.getMap().keySet()) {
                    // field yang engga ada di metadata akan di-skip
                    if (!fieldRestricted.contains(fieldName)) {
                        continue;
                    }
                    
                    Object newValue = newCase.get(fieldName);
                    Object oldValue = oldCase.get(fieldName);
                    
                    if (newValue != oldValue) {
                        hasUnauthorizedChanges = true;
                        unauthorizedFields += fieldName + ', ';
                    }
                }
                
                // pop up error
                if (hasUnauthorizedChanges) {
                    unauthorizedFields = unauthorizedFields.removeEnd(', ');
                    newCase.addError(System.Label.SCC_CaseCloseValidationError + 
                        ' Beberapa field yang dibatasi perubahannya: ' + unauthorizedFields);
                }
            }
        }
    }
}