force-app/main/default/objects/Case/fields/Cust_Current_Phone__c.field-meta.xml
<CustomField>
    <fullName>Cust_Current_Phone__c</fullName>
    <label>Nomor Telp yang dapat dihubungi</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <description>Migration.The account number or credit card number</description>
    <label>Nomor Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Amount__c.field-meta.xml
<CustomField>
    <fullName>SCC_Amount__c</fullName>
    <description>The amount from the dispute transaction</description>
    <label>Nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Cust_Phone1__c.field-meta.xml
<CustomField>
    <fullName>SCC_Cust_Phone1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Drone_Ticket_ID__c.field-meta.xml
<CustomField>
    <fullName>SCC_Drone_Ticket_ID__c</fullName>
    <defaultValue>&quot;-&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Drone Ticket ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Email__c.field-meta.xml
<CustomField>
    <fullName>SCC_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Terminal_ID__c.field-meta.xml
<CustomField>
    <fullName>SCC_Terminal_ID__c</fullName>
    <description>Migration. To store the terminal ID</description>
    <encryptionScheme>None</encryptionScheme>
    <label>TID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>SCC_Transaction_Date__c</fullName>
    <description>Migration.The date from dispute transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tanggal Transaksi</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SCC_Terminal_ID__c/SCC_Terminal_ID__c.object-meta.xml
<CustomObject>
    <label>SCC Terminal ID</label>
    <nameField>
        <label>Terminal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCC Terminal ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Terminal_ID__c/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCC_InvocableDrone_Test.cls
@isTest
public with sharing class SCC_InvocableDrone_Test {
    @TestSetup
    static void createCase(){
        Case cs = new Case();

            cs.SCC_Terminal_ID__c = 'Test Terminal ID';
            cs.SCC_Transaction_Date__c = Date.today();
            cs.SCC_Account_Number__c = '1234567890123456';
            cs.SCC_Cust_Phone1__c = '081299928812';
            cs.Cust_Current_Phone__c = '081234567890';
            cs.SCC_Transaction_Date__c = Date.today();
            cs.Description = 'test desc';
            cs.SCC_Email__c = 'test@test.co';
            cs.SCC_Amount__c = 100;
        insert cs;
        
        cs.SCC_Drone_Ticket_ID__c = '812999';
        update cs;
    }
    @isTest
    static void testCreateTicket() {
        String allfieldCase = SOQL_SOBJECT.getallfield('Case');
        String queries = SOQL_SOBJECT.SOQL(allfieldCase, '', 'Case', '', '', '', '');
        List<Case> cs = Database.query(queries);

        System.debug('cs[0].id'+cs[0]);
        
        Test.startTest();
        SCC_InvocableDrone.createTicketDrone(cs[0].id);
        Test.stopTest();
    }
    @isTest
    static void testUpdateTicket() {
        String allfieldCase = SOQL_SOBJECT.getallfield('Case');
        String queries = SOQL_SOBJECT.SOQL(allfieldCase, '', 'Case', '', '', '', '');
        List<Case> cs = Database.query(queries);

        Test.startTest();
        SCC_InvocableDrone.updateTicketDrone(cs[0].id);
        Test.stopTest();
    }
    @istest
    static void invocablemethod(){
        SCC_InvocableDrone.InputVariable inv = new SCC_InvocableDrone.InputVariable();
        String allfieldCase = SOQL_SOBJECT.getallfield('Case');
        String queries = SOQL_SOBJECT.SOQL(allfieldCase, '', 'Case', '', '', '', '1');
        Case cs = Database.query(queries);
		inv.param = 'Create Ticket Drone';
        inv.recordId = cs.id;
        list<SCC_InvocableDrone.InputVariable> listinv = new list<SCC_InvocableDrone.InputVariable>();
        listinv.add(inv);
        Test.startTest();
        SCC_InvocableDrone.Invocablevoid(listinv);
        Test.stopTest();
    }
}