force-app/main/default/objects/Case/fields/Date_Time_Answer__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Answer__c</fullName>
    <label>Date/ Time Answer</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/FromSosmed__c.field-meta.xml
<CustomField>
    <fullName>FromSosmed__c</fullName>
    <formula>ISPICKVAL(Origin, &quot;Instagram&quot;) || ISPICKVAL(Origin, &quot;YouTube&quot;) || ISPICKVAL(Origin, &quot;Twitter&quot;) || ISPICKVAL(Origin, &quot;Facebook&quot;) || ISPICKVAL(Origin, &quot;Google Play Store&quot;) || ISPICKVAL(Origin, &quot;Apple App Store&quot;) || ISPICKVAL(Origin, &quot;TikTok&quot;)</formula>
    <label>From Sosmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Response_Time_Minutes_v2__c.field-meta.xml
<CustomField>
    <fullName>Response_Time_Minutes_v2__c</fullName>
    <formula>(Date_Time_Answer__c -  CreatedDate)*24*60</formula>
    <label>Response Time (Minutes) v2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SproutSocialApp__Sprout_Social_Post__c/SproutSocialApp__Sprout_Social_Post__c.object-meta.xml
<CustomObject>
    <label>Sprout Social Post</label>
    <nameField>
        <label>Sprout Social Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprout Social Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SproutSocialApp__Sprout_Social_Post__c/fields/SproutSocialApp__IsOutbound__c.field-meta.xml
<CustomField>
    <fullName>SproutSocialApp__IsOutbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Outbound</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SproutSocialApp__Sprout_Social_Post__c/fields/SproutSocialApp__ParentId__c.field-meta.xml
<CustomField>
    <fullName>SproutSocialApp__ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sprout Social Posts</relationshipLabel>
    <relationshipName>Sprout_Social_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateDTABatch.cls
global class UpdateDTABatch implements Database.Batchable<SObject> {

    /*  Database.executeBatch(new UpdateDTABatch(), 1);
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id FROM Case WHERE Response_Time_Minutes_v2__c < 0 AND FromSosmed__c = TRUE AND ID = '500MR000004mD8mYAE'
        ]);
    }*/
    
    // Database.executeBatch(new UpdateDTABatch('SELECT Id FROM Case WHERE Response_Time_Minutes_v2__c < 0 AND FromSosmed__c = TRUE AND ID = \'500MR000004mDlUYAU\''), 1);
    public String Query;
    public UpdateDTABatch(String q) {
        this.query = q;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Case> scope) {
        Set<Id> caseIds = new Set<Id>();
        for (Case c : scope) {
            caseIds.add(c.Id);
        }

        List<AggregateResult> earliestPostsAgg = [
            SELECT SproutSocialApp__ParentId__c, MIN(CreatedDate) minDate
            FROM SproutSocialApp__Sprout_Social_Post__c 
            WHERE SproutSocialApp__ParentId__c IN :caseIds AND SproutSocialApp__IsOutbound__c = TRUE
            GROUP BY SproutSocialApp__ParentId__c 
        ];

        Map<Id, DateTime> caseToMinDateMap = new Map<Id, DateTime>();
        for (AggregateResult ar : earliestPostsAgg) {
            caseToMinDateMap.put((Id)ar.get('SproutSocialApp__ParentId__c'), (DateTime)ar.get('minDate'));
        }
        
        List<Case> casesToUpdate = new List<Case>();
        for (Case c : scope) {
            if (caseToMinDateMap.containsKey(c.Id)) {
                c.Date_Time_Answer__c = caseToMinDateMap.get(c.Id);
                casesToUpdate.add(c);
            }
        }

        if (!casesToUpdate.isEmpty()) {
            update casesToUpdate;
        }
        
    }

    global void finish(Database.BatchableContext bc) {
        System.debug('Batch complete.');
    }
}