force-app/main/default/objects/Case/fields/Date_Time_Answer__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Answer__c</fullName>
    <label>Date/ Time Answer</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Done_Survey__c.field-meta.xml
<CustomField>
    <fullName>Done_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Done Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invitation_Link__c.field-meta.xml
<CustomField>
    <fullName>Invitation_Link__c</fullName>
    <label>Invitation Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/fields/Notification_12__c.field-meta.xml
<CustomField>
    <fullName>Notification_12__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notification 12</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Notification_13__c.field-meta.xml
<CustomField>
    <fullName>Notification_13__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notification 13</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Notification_2__c.field-meta.xml
<CustomField>
    <fullName>Notification_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notification 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Notification_3__c.field-meta.xml
<CustomField>
    <fullName>Notification_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notification 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Attachment_Done_Date__c.field-meta.xml
<CustomField>
    <fullName>SCC_Attachment_Done_Date__c</fullName>
    <description>The date of attachment has been collected</description>
    <label>Tanggal Attachment Done</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_BRINotif_reffNumber__c.field-meta.xml
<CustomField>
    <fullName>SCC_BRINotif_reffNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Result Whatsapp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Drone_Remark__c.field-meta.xml
<CustomField>
    <fullName>SCC_Drone_Remark__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Drone Remark</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Drone_Remark_Update__c.field-meta.xml
<CustomField>
    <fullName>SCC_Drone_Remark_Update__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Drone Remark Update</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_ITSM_Closed__c.field-meta.xml
<CustomField>
    <fullName>SCC_ITSM_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCC_ITSM_Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Legacy_Ticket_ID__c.field-meta.xml
<CustomField>
    <fullName>SCC_Legacy_Ticket_ID__c</fullName>
    <description>It&apos;s used only for migration or with the internal app also</description>
    <externalId>true</externalId>
    <label>Legacy Ticket ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Remark__c.field-meta.xml
<CustomField>
    <fullName>SCC_Remark__c</fullName>
    <label>Remark</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Result_Pembukuan__c.field-meta.xml
<CustomField>
    <fullName>SCC_Result_Pembukuan__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Result Pembukuan</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Tipe_Remark__c.field-meta.xml
<CustomField>
    <fullName>SCC_Tipe_Remark__c</fullName>
    <label>Tipe Remark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCC_RestrictCaseClosedTest.cls
/**
 * @description       : Class untuk restrict field yang ada di UI ketika Closed, tambahkan di metadata [SCC_RestrictCaseClosed] untuk restrict field
 * @author            : Alvin Vigo
 * @group             : 
 * @last modified on  : 16/12/2024
 * @last modified by  : Alvin Vigo
**/

@isTest
private class SCC_RestrictCaseClosedTest {
    @testSetup
    static void setupTestData() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        List<Case> testCases = new List<Case>{
            new Case(
                Subject = 'Closed Ticket',
                Status = 'Closed',
                AccountId = testAccount.Id,
                Description = 'Ticket Closed',
                scc_legacy_ticket_id__c = 'xxx',
                scc_brinotif_reffnumber__c = '123',
                scc_remark__c = 'Remark',
                scc_drone_remark__c = 'Remark2',
                scc_drone_remark_update__c = 'Remark3',
                scc_tipe_remark__c = 'Remark',
                done_survey__c = false,
                invitation_link__c = 'http://test.com',
                notification_13__c = false,
                scc_itsm_closed__c = false,
                notification_12__c = false,
                notification_3__c = false,
                notification_2__c = false,
                scc_result_pembukuan__c = 'Done',
                date_time_answer__c = System.now(),
                priority = 'Low',
                OwnerId = UserInfo.getUserId(),
                scc_attachment_done_date__c = System.today()
            )
        };
        insert testCases;
    }
    
    @isTest
    static void testValidationMigration() {
        SCC_RestrictCaseClosed.isTest = true;
        
        Case closedCase = [SELECT Id, Status, Subject, Description FROM Case WHERE Status = 'Closed' LIMIT 1];
        
        Test.startTest();
        
        Map<Id, Case> oldCaseMap = new Map<Id, Case>{
            closedCase.Id => closedCase.clone(true, true, true, true)
        };
        
        List<Case> newCases = new List<Case>{
            closedCase.clone(true, true, true, true)
        };
        
        newCases[0].Subject = 'Unauthorized Change';
        
        try {
            SCC_RestrictCaseClosed.restrictCaseClosed(newCases, oldCaseMap);
            System.assert(false, 'Expected an error for unauthorized change');
        } catch (Exception e) {
            /*System.assert(
                e.getMessage().contains('Beberapa field yang dibatasi perubahannya'), 
                'Unexpected error message: ' + e.getMessage()
            );*/
        }
        
        Test.stopTest();
    }
    
    @isTest
    static void testRestrictCaseClosed() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        Case testCase = new Case(
            Subject = 'Test Case',
            Status = 'Closed',
            AccountId = testAccount.Id
        );
        insert testCase;
        
        Test.startTest();
        
        // 1. test bypass
        SCC_RestrictCaseClosed.isBypassEnabled = true;
        Map<Id, Case> oldCaseMap = new Map<Id, Case>{
            testCase.Id => testCase.clone(true, true, true, true)
        };
        
        Case bypassCase = testCase.clone(true, true, true, true);
        bypassCase.Subject = 'Modified Subject';
        
        try {
            SCC_RestrictCaseClosed.restrictCaseClosed(new List<Case>{bypassCase}, oldCaseMap);
            System.assert(true, 'Bypass should work');
        } catch (Exception e) {
            System.assert(false, 'Bypass failed: ' + e.getMessage());
        }
        
        // 2. test field changed
        SCC_RestrictCaseClosed.isBypassEnabled = false;
        SCC_RestrictCaseClosed.isTest = true;
        
        Case changeCase = testCase.clone(true, true, true, true);
        changeCase.Subject = 'Unauthorized Change';
        
        try {
            SCC_RestrictCaseClosed.restrictCaseClosed(new List<Case>{changeCase}, oldCaseMap);
            System.assert(true, 'Expected an error for unauthorized change');
        } catch (Exception e) {
            System.assert(
                e.getMessage().contains('Beberapa field yang dibatasi perubahannya'),
                'Unexpected error message: ' + e.getMessage()
            );
        }
        
        Test.stopTest();
    }
}