force-app/main/default/objects/Case/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <formula>IF(CASE(TEXT(Status), &apos;Closed&apos;, &apos;1&apos;, &apos;Cancelled&apos;, &apos;1&apos;,&apos;Disconnected&apos;, &apos;1&apos;, &apos;0&apos;)==&apos;1&apos;,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Terminal_ID__c.field-meta.xml
<CustomField>
    <fullName>SCC_Terminal_ID__c</fullName>
    <description>Migration. To store the terminal ID</description>
    <encryptionScheme>None</encryptionScheme>
    <label>TID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>SCC_Transaction_Date__c</fullName>
    <description>Migration.The date from dispute transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tanggal Transaksi</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Terminal_ID__c.field-meta.xml
<CustomField>
    <fullName>Terminal_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terminal ID</label>
    <referenceTo>SCC_Terminal_ID__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCC_Terminal_ID__c/SCC_Terminal_ID__c.object-meta.xml
<CustomObject>
    <label>SCC Terminal ID</label>
    <nameField>
        <label>Terminal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCC Terminal ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/Send_to_Drone__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Drone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Drone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SCC_Channel.cls
global class SCC_Channel implements Queueable, Database.AllowsCallouts{
	public String csid {get;set;}
    public String logika {get;set;}
    global SCC_Channel(String csid,String logika){
        this.csid = csid;
        this.logika = logika;
    }
    
    global void execute(QueueableContext context) {
        String cond = 'id=:csid';
        String allfield = SOQL_SOBJECT.getallfield('Case');
        String queries = SOQL_SOBJECT.SOQL(allfield, ',scc_call_type__r.Send_to_Drone__c', 'Case', cond, '', '', '1');
        Case cs = Database.query(queries);
        if(logika=='Escalation'){
            if(String.isNotBlank(cs.SCC_Terminal_ID__c) && cs.SCC_Terminal_ID__c!=label.tid && cs.SCC_Transaction_Date__c!=null){
                CustomLookupController.RecordsData rd = CustomLookupController.GetDataDetail(String.valueof(cs.SCC_Transaction_Date__c), cs.SCC_Terminal_ID__c);
                cs.terminal_id__c = rd?.value; 
            }
        	if(!cs.isclosed__c){
            	update cs;
        	}
            if(cs.scc_call_type__r.Send_to_Drone__c && !Test.isRunningTest()){
                System.enqueueJob(new SCC_Channel(cs.id,'Send To Drone'));
            }
        }
        if(logika=='Send To Drone'){
            SCC_InvocableDrone.sendCreateToDroneFuture(cs.id);
        }
    }
}