force-app/main/default/objects/Case/fields/Pengisian_Form_APPK__c.field-meta.xml
<CustomField>
    <fullName>Pengisian_Form_APPK__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for checking appk form</description>
    <label>Pengisian Form APPK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ScheduleHoliday_APPK.cls
global without sharing class ScheduleHoliday_APPK implements Schedulable{
    global void execute(SchedulableContext ctx) {
        String schedulename = 'Schedule Holiday APPK';
        Date nextrun = system.today().addDays(1);
        String cond = 'isclosed = false and (SCC_Call_Type__c !=null OR Pengisian_Form_APPK__c = true)';
        String allfield = SOQL_SOBJECT.getallfield('Case');
        String queries = SOQL_SOBJECT.SOQL(allfield, '', 'Case', cond, 'createddate', 'Desc', '');
        Database.executeBatch(new BatchHoliday_APPK(queries), 10);
        List<CronTrigger> ctlists = [SELECT Id, CronJobDetail.name, CronJobDetail.jobtype, NextFireTime, PreviousFireTime, State, StartTime, EndTime, 
                                             CronExpression, TimeZoneSidKey, OwnerId, LastModifiedById, CreatedById, CreatedDate, TimesTriggered 
                                             FROM CronTrigger 
                                             where CronJobDetail.name =: schedulename];
        if(CTlists.size()>0){
            for(CronTrigger apxjob:CTlists){
                System.abortJob(apxJob.Id);
            }
        }
        Datetime nexttime = system.now().addhours(integer.valueOf(label.add_hours));
        ScheduleHoliday_APPK sch = new ScheduleHoliday_APPK();
        System.schedule(schedulename, '0 0 1 '+nextrun.day()+' '+nextrun.month()+' ? '+nextrun.year(), sch);
    }
}