force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Product_L1__c.field-meta.xml
<CustomField>
    <fullName>SCC_Product_L1__c</fullName>
    <description>Migration. To store the product related to the issue</description>
    <label>Product Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Transaction Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Product_L2__c.field-meta.xml
<CustomField>
    <fullName>SCC_Product_L2__c</fullName>
    <description>Migration.To store the product related to the issue</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SCC_Product_L1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Giro (CA)</fullName>
            </value>
            <value>
                <fullName>Tabungan (SA)</fullName>
            </value>
            <value>
                <fullName>Deposito</fullName>
            </value>
            <value>
                <fullName>Briguna Digital</fullName>
            </value>
            <value>
                <fullName>KTA (Personal Loan)</fullName>
                <label>KTA (Personal Loan) / Briguna</label>
            </value>
            <value>
                <fullName>KTA - Digital</fullName>
                <label>KTA - Digital / Ceria</label>
            </value>
            <value>
                <fullName>Kartu Kredit (Credit Card)</fullName>
            </value>
            <value>
                <fullName>KPR (Mortgage)</fullName>
            </value>
            <value>
                <fullName>KUR (Business Loan - Micro)</fullName>
            </value>
            <value>
                <fullName>KUR Ritel</fullName>
            </value>
            <value>
                <fullName>Kupedes</fullName>
            </value>
            <value>
                <fullName>Kredit Modal Kerja (Working Capital)</fullName>
            </value>
            <value>
                <fullName>Kredit Investasi (Investment Loan)</fullName>
            </value>
            <value>
                <fullName>KPR, KUR, KMK, KI</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>DPLK (Pension Fund)</fullName>
            </value>
            <value>
                <fullName>SBN (Bonds)</fullName>
            </value>
            <value>
                <fullName>Mobile Banking</fullName>
            </value>
            <value>
                <fullName>Bancassurance</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>Electronic Money</fullName>
            </value>
            <value>
                <fullName>Digital Savings</fullName>
            </value>
            <value>
                <fullName>Pawning</fullName>
                <label>Pawning / Gadai</label>
            </value>
            <value>
                <fullName>Aplikasi Commodity Chain</fullName>
            </value>
            <value>
                <fullName>Government Programme</fullName>
            </value>
            <value>
                <fullName>Informasi Promo, Program, Produk</fullName>
            </value>
            <value>
                <fullName>Kartu Debit</fullName>
            </value>
            <value>
                <fullName>PPID</fullName>
            </value>
            <value>
                <fullName>Safe Deposit</fullName>
            </value>
            <value>
                <fullName>Senyum Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Resolution_Category__c.field-meta.xml
<CustomField>
    <fullName>SCC_Resolution_Category__c</fullName>
    <label>Resolution Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Transactional</fullName>
                <label>Kirim Notifikasi</label>
            </value>
            <value>
                <fullName>Dokumen Tidak Lengkap</fullName>
            </value>
            <value>
                <fullName>Tidak Mengirimkan Notifikasi</fullName>
            </value>
            <value>
                <fullName>Transactional/Fraud with Refund</fullName>
                <isActive>false</isActive>
                <label>Transactional/Fraud with Refund</label>
            </value>
            <value>
                <fullName>Transactional/Fraud without Refund</fullName>
                <isActive>false</isActive>
                <label>Transactional/Fraud without Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Segment__c</fullName>
    <description>Migration. To store the customer segment</description>
    <label>Segmen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Customer_Segment__c</fullName>
    <description>Consists of the type of segment of the case.</description>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level1_Escalation_team__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level1_Escalation_team__c</fullName>
    <description>This field indicates the escalation team for level 1</description>
    <label>Level 1 Escalation Team</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Segment__c</fullName>
    <description>Consists of the type of segment of the case.</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
            <value>
                <fullName>Individu Umum, Individu Priority &amp; Private</fullName>
                <isActive>false</isActive>
                <label>Individu Umum, Individu Priority &amp; Private</label>
            </value>
            <value>
                <fullName>Individu Umum, UMKM</fullName>
                <isActive>false</isActive>
                <label>Individu Umum, UMKM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Category__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complaint - Non-Transaction</fullName>
            </value>
            <value>
                <fullName>Complaint - Transaction</fullName>
            </value>
            <value>
                <fullName>Customer Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud / Suspicious Transactions</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Platform &amp; Device Support</fullName>
            </value>
            <value>
                <fullName>Products / Promotion Inquiry</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Third Party Support</fullName>
            </value>
            <value>
                <fullName>Customer Feedback / Sentiment Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Description__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Description__c</fullName>
    <label>Deskripsi Case</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L1__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L1__c</fullName>
    <label>Product Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Transaction Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L2__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L2__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SSC_Product_L1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bancassurance</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Deposito</fullName>
            </value>
            <value>
                <fullName>Digital Savings</fullName>
            </value>
            <value>
                <fullName>DPLK (Pension Fund)</fullName>
            </value>
            <value>
                <fullName>Electronic Money</fullName>
            </value>
            <value>
                <fullName>Giro (CA)</fullName>
            </value>
            <value>
                <fullName>Government Programme</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>Kartu Debit</fullName>
            </value>
            <value>
                <fullName>Kartu Kredit</fullName>
            </value>
            <value>
                <fullName>KPR (Mortgage)</fullName>
            </value>
            <value>
                <fullName>Kredit Investasi (Investment Loan)</fullName>
            </value>
            <value>
                <fullName>Kredit Modal Kerja (Working Capital)</fullName>
            </value>
            <value>
                <fullName>KTA (Personal Loan)</fullName>
            </value>
            <value>
                <fullName>KTA - Digital</fullName>
            </value>
            <value>
                <fullName>KUR (Business Loan - Micro)</fullName>
            </value>
            <value>
                <fullName>Mobile Banking</fullName>
            </value>
            <value>
                <fullName>Pawning</fullName>
            </value>
            <value>
                <fullName>Safe Deposit</fullName>
            </value>
            <value>
                <fullName>SBN (Bonds)</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Cabang</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Contact Center</fullName>
            </value>
            <value>
                <fullName>Tabungan</fullName>
            </value>
            <value>
                <fullName>Virtual Account</fullName>
            </value>
            <value>
                <fullName>Aplikasi Commodity Chain</fullName>
            </value>
            <value>
                <fullName>Informasi Promo, Program, Produk</fullName>
            </value>
            <value>
                <fullName>PPID</fullName>
            </value>
            <value>
                <fullName>Senyum Mobile</fullName>
            </value>
            <value>
                <fullName>Trustee &amp; Wali Amanat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SCC_Migration_Test.cls
@IsTest
public class SCC_Migration_Test {
    /*@TestSetup
    static void setupTestData() {
        // Create necessary test data
        // Create SSC_Call_Type__c records
        List<SSC_Call_Type__c> callTypes = new List<SSC_Call_Type__c>();
            SSC_Call_Type__c callType = new SSC_Call_Type__c(
                Name = '8812',
                SCC_Customer_Segment__c = 'Individu Umum ',  // Field yang diwajibkan oleh validasi
                SSC_Case_Category__c = 'Complaint - Transaction ',    // Field yang diwajibkan oleh validasi
                SSC_Case_Description__c = 'Complaint - Transaction ',       // Field yang diwajibkan oleh validasi
				SSC_Product_L1__c = 'Transaction Banking ',       // Field yang diwajibkan oleh validasi
				SSC_Product_L2__c = 'Transaction Solution ',       // Field yang diwajibkan oleh validasi
                SCC_Level1_Escalation_team__c = 'Team ',
                Active__c = true
            );
            callTypes.add(callType);
        
        insert callTypes;

        // Create Queue records
        List<Group> queueGroups = new List<Group>();
        for (Integer i = 1; i <= 4; i++) {
            Group queue = new Group(
                Name = 'Team ' + i,
                Type = 'Queue'
            );
            queueGroups.add(queue);
        }
        insert queueGroups;

        // Create Case records
        List<Case> cases = new List<Case>();
            Case caseRecord = new Case(
                RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Case Migration').getRecordTypeId(),
                Description = 'Test Description',
                SCC_Call_Type__c = callTypes[0].Id,
                SCC_Segment__c = 'Individu Umum ',  // Field yang diwajibkan oleh validasi
                SCC_Resolution_Category__c = 'Transactional/Fraud without Refund ', // Field yang diwajibkan oleh validasi
                SCC_Product_L1__c = 'Savings ',           // Field yang diwajibkan oleh validasi
                SCC_Product_L2__c = 'Tabungan (SA) ',           // Field yang diwajibkan oleh validasi
                SCC_Case_Category__c = 'Complaint - Transaction ',    // Field yang diwajibkan oleh validasi
                SSC_Call_Type_Description__c = 'test '      // Field yang diwajibkan oleh validasi
            );
            cases.add(caseRecord);
        insert cases;
        system.debug(callTypes[0].Name);
    }*/
    
    @IsTest 
    static void testBatchMigration() {
        User u = [SELECT Id FROM User Where isActive = true AND profile.name = 'System Administrator' LIMIT 1];
       	System.runAs(u) {
            Test.startTest();
            String query = 'SELECT Id, SCC_Call_Type__c, RecordTypeId FROM Case';
            SCC_Migration job = new SCC_Migration(query);
            Database.executeBatch(job, 2);
            Test.stopTest();
            
            List<Case> cases = [SELECT Id, OwnerId FROM Case];

            // Verify the results
            /*for (Case c : cases) {
                System.assertNotEquals(null, c.OwnerId, 'OwnerId should be updated');
            }*/
        }
    }
}