force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Email__c.field-meta.xml
<CustomField>
    <fullName>SCC_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_List_of_Required_Documents__c.field-meta.xml
<CustomField>
    <fullName>SCC_List_of_Required_Documents__c</fullName>
    <label>Dokumen yang dibutuhkan</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Sent_Email_Perpanjangan_SLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Sent_Email_Perpanjangan_SLA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent Email Perpanjangan SLA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Customer_Segment__c</fullName>
    <description>Consists of the type of segment of the case.</description>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level1_OLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level1_OLA__c</fullName>
    <description>This is the OLA for Level 1</description>
    <label>Level 1 OLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level2_OLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level2_OLA__c</fullName>
    <description>This is for OLA Level 2</description>
    <label>Level 2 OLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_List_of_Required_Documents__c.field-meta.xml
<CustomField>
    <fullName>SCC_List_of_Required_Documents__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>List Dokumen yang dibutuhkan</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Sub_Description__c.field-meta.xml
<CustomField>
    <fullName>SCC_Sub_Description__c</fullName>
    <description>This fields allows agent to add sub-description</description>
    <label>Sub Case Reference</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Category__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complaint - Non-Transaction</fullName>
            </value>
            <value>
                <fullName>Complaint - Transaction</fullName>
            </value>
            <value>
                <fullName>Customer Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud / Suspicious Transactions</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Platform &amp; Device Support</fullName>
            </value>
            <value>
                <fullName>Products / Promotion Inquiry</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Third Party Support</fullName>
            </value>
            <value>
                <fullName>Customer Feedback / Sentiment Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Description__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Description__c</fullName>
    <label>Deskripsi Case</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L1__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L1__c</fullName>
    <label>Product Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Transaction Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L2__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L2__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SSC_Product_L1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bancassurance</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Deposito</fullName>
            </value>
            <value>
                <fullName>Digital Savings</fullName>
            </value>
            <value>
                <fullName>DPLK (Pension Fund)</fullName>
            </value>
            <value>
                <fullName>Electronic Money</fullName>
            </value>
            <value>
                <fullName>Giro (CA)</fullName>
            </value>
            <value>
                <fullName>Government Programme</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>Kartu Debit</fullName>
            </value>
            <value>
                <fullName>Kartu Kredit</fullName>
            </value>
            <value>
                <fullName>KPR (Mortgage)</fullName>
            </value>
            <value>
                <fullName>Kredit Investasi (Investment Loan)</fullName>
            </value>
            <value>
                <fullName>Kredit Modal Kerja (Working Capital)</fullName>
            </value>
            <value>
                <fullName>KTA (Personal Loan)</fullName>
            </value>
            <value>
                <fullName>KTA - Digital</fullName>
            </value>
            <value>
                <fullName>KUR (Business Loan - Micro)</fullName>
            </value>
            <value>
                <fullName>Mobile Banking</fullName>
            </value>
            <value>
                <fullName>Pawning</fullName>
            </value>
            <value>
                <fullName>Safe Deposit</fullName>
            </value>
            <value>
                <fullName>SBN (Bonds)</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Cabang</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Contact Center</fullName>
            </value>
            <value>
                <fullName>Tabungan</fullName>
            </value>
            <value>
                <fullName>Virtual Account</fullName>
            </value>
            <value>
                <fullName>Aplikasi Commodity Chain</fullName>
            </value>
            <value>
                <fullName>Informasi Promo, Program, Produk</fullName>
            </value>
            <value>
                <fullName>PPID</fullName>
            </value>
            <value>
                <fullName>Senyum Mobile</fullName>
            </value>
            <value>
                <fullName>Trustee &amp; Wali Amanat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SCC_SendEmailRemainderH9BatchTest.cls
/**
 * @description       : 
 * @author            : Ahmad Yazid Munif
 * @group             : 
 * @last modified on  : 03-13-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private class SCC_SendEmailRemainderH9BatchTest {
    private static final String BUSINESS_HOURS_NAME = System.Label.Business_Hour;
    private static final String EMAIL_TEMPLATE_DEVELOPER_NAME = System.Label.Email_Template_H9; 
    private static final String ORG_WIDE_EMAIL_DISPLAY_NAME = System.Label.Email_Wide_Organization;
    private static final String ADMIN_EMAIL = System.Label.Admin_Email_Notification; 
    @TestSetup
    static void makeData(){
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE Name =:BUSINESS_HOURS_NAME LIMIT 1];
        // Create Call Type
        SSC_Call_Type__c callTypeRecord = new SSC_Call_Type__c(
            Name = 'Test Call Type',
            SCC_Customer_Segment__c = 'Individu Umum',
            SSC_Product_L1__c = 'Investment',
            SSC_Product_L2__c = 'DPLK',
            SSC_Case_Category__c = 'Complaint - Transaction',
            SSC_Case_Description__c = 'Nasabah Komplain Terkait Dana Pensiun Lembaga Keuangan (Dplk)',
            SCC_Sub_Description__c = 'Option1;Option2;Option3',
            Active__c = true,
            SCC_Level1_OLA__c = 6,
            SCC_Level2_OLA__c = 2
        );
        insert callTypeRecord;

        // Create an Account
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        // Create ContentVersion for file attachment
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDoc.pdf';
        cv.VersionData = Blob.valueOf('Test file content');
        cv.IsMajorVersion = true;
        insert cv;
        
        // Get ContentDocumentId
        ContentVersion cvInserted = [
            SELECT Id, ContentDocumentId 
            FROM ContentVersion 
            WHERE Id = :cv.Id
        ];
        
        // Create ContentDocumentLink to Call Type
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = callTypeRecord.Id;
        cdl.ContentDocumentId = cvInserted.ContentDocumentId;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;

        // Create test Cases
        Case caseRecord1 = new Case();
        caseRecord1.Subject = 'Test Case';
        caseRecord1.CreatedDate = System.now().addDays(-20);
        caseRecord1.SCC_Email__c = 'test@example.com';
        caseRecord1.Status = 'Waiting Document';
        caseRecord1.SCC_List_of_Required_Documents__c = 'Document kk';
        caseRecord1.SCC_Call_Type__c = callTypeRecord.Id;
        insert caseRecord1;

        Case caseRecord2 = new Case();
        caseRecord2.Subject = 'Test Case 2';
        caseRecord2.CreatedDate = System.now().addDays(-20);
        caseRecord2.SCC_Email__c = 'test2@example.com';
        caseRecord2.Status = 'Waiting Document';
        caseRecord2.SCC_List_of_Required_Documents__c = 'Document kk';
        caseRecord2.SCC_Call_Type__c = callTypeRecord.Id;
        insert caseRecord2;
    }
    @isTest
    static void testBatchSendEmailRemainder() {
        // Step 1: Create test data
        // Create a Business Hours record (assuming it exists in the org)
        // BusinessHours bh = [SELECT Id FROM BusinessHours WHERE Name = 'Branch User' LIMIT 1];

        // // Create Call Type
        // SSC_Call_Type__c callTypeRecord = new SSC_Call_Type__c(
        //     Name = 'Test Call Type',
        //     SCC_Customer_Segment__c = 'Individu Umum',
        //     SSC_Product_L1__c = 'Investment',
        //     SSC_Product_L2__c = 'DPLK',
        //     SSC_Case_Category__c = 'Complaint - Transaction',
        //     SSC_Case_Description__c = 'Nasabah Komplain Terkait Dana Pensiun Lembaga Keuangan (Dplk)',
        //     SCC_Sub_Description__c = 'Option1;Option2;Option3',
        //     Active__c = true
        // );
        // insert callTypeRecord;

        // // Create an Account
        // Account testAccount = new Account(Name = 'Test Account');
        // insert testAccount;

        // // Create test Cases
        // Case caseRecord1 = new Case();
        // caseRecord1.CreatedDate = System.now().addDays(-20);
        // caseRecord1.SCC_Email__c = 'test@example.com';
        // caseRecord1.Status = 'Waiting Document';
        // caseRecord1.SCC_List_of_Required_Documents__c = 'Document kk';
        // caseRecord1.SCC_Call_Type__c = callTypeRecord.Id;
        // insert caseRecord1;

        // Step 2: Execute the batch
        Test.startTest();
        SCC_SendEmailRemainderH9Batch batch = new SCC_SendEmailRemainderH9Batch();
        Database.executeBatch(batch);
        Test.stopTest();

        // Step 3: Verify the results
        // Check the debug logs for the total emails sent
        // Note: You can check the debug logs in the Salesforce Developer Console to see the output of the debug statements.
        
        // Since we cannot directly assert the email sending in tests, we can check the debug logs
        // Alternatively, you can use a mock for the Messaging.sendEmail method if needed.

        // Step 4: Verify that the emails were sent
        // This part is tricky because Salesforce does not allow us to verify sent emails directly in tests.
        // However, we can check the number of emails sent by checking the debug logs or using a mock.

        // You can also check if the admin notification email was sent by mocking the Messaging.sendEmail method.
    }
    @isTest
    static void testExecuteMethod() {
        Test.startTest();
        SCC_SendEmailNotificationOverSLA batchJob = new SCC_SendEmailNotificationOverSLA();
        List<Case> caseList = [SELECT Id, SCC_Email__c, SCC_Sent_Email_Perpanjangan_SLA__c, Subject, CaseNumber, Account.Name FROM Case WHERE Subject = 'Test Case 2'];
        System.assert(caseList.size() > 0, 'There should be at least one case to process.');

        batchJob.execute(null, caseList);
        Test.stopTest();

        for (Case c : [SELECT SCC_Sent_Email_Perpanjangan_SLA__c, CaseNumber FROM Case WHERE SCC_Sent_Email_Perpanjangan_SLA__c = true]) {
            System.assertEquals(true, c.SCC_Sent_Email_Perpanjangan_SLA__c, 'The email sent flag should be true for case: ' + c.CaseNumber);
        }
    }

    @isTest
    static void testRunBatch() {
        Test.startTest();
        SCC_SendEmailRemainderH9Batch.runBatch();
        Test.stopTest();
    }
}