force-app/main/default/objects/Case/fields/SCC_Terminal_ID__c.field-meta.xml
<CustomField>
    <fullName>SCC_Terminal_ID__c</fullName>
    <description>Migration. To store the terminal ID</description>
    <encryptionScheme>None</encryptionScheme>
    <label>TID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>SCC_Transaction_Date__c</fullName>
    <description>Migration.The date from dispute transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tanggal Transaksi</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/SCC_Nota_Manual__c.object-meta.xml
<CustomObject>
    <label>Nota Analisa</label>
    <nameField>
        <displayFormat>NOTA-{0000000000}</displayFormat>
        <label>Nota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nota Analisa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Nota_Manual</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Branchcode__c.field-meta.xml
<CustomField>
    <fullName>SCC_Branchcode__c</fullName>
    <label>Branchcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Jenis_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Jenis_Transaksi__c</fullName>
    <label>Jenis Transaksi</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Jumlah_Debit__c.field-meta.xml
<CustomField>
    <fullName>SCC_Jumlah_Debit__c</fullName>
    <label>Jumlah</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Jumlah_Kredit__c.field-meta.xml
<CustomField>
    <fullName>SCC_Jumlah_Kredit__c</fullName>
    <label>Jumlah</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Keterangan__c.field-meta.xml
<CustomField>
    <fullName>SCC_Keterangan__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Keterangan</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Nama_Nasabah__c.field-meta.xml
<CustomField>
    <fullName>SCC_Nama_Nasabah__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nama Nasabah</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_No_Kartu__c.field-meta.xml
<CustomField>
    <fullName>SCC_No_Kartu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>No. Kartu</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_No_Rekening__c.field-meta.xml
<CustomField>
    <fullName>SCC_No_Rekening__c</fullName>
    <label>No. Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_No_Telepon__c.field-meta.xml
<CustomField>
    <fullName>SCC_No_Telepon__c</fullName>
    <label>No. Telpon</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Rekening_Fee__c.field-meta.xml
<CustomField>
    <fullName>SCC_Rekening_Fee__c</fullName>
    <label>Rekening Fee</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Rekening_Titipan__c.field-meta.xml
<CustomField>
    <fullName>SCC_Rekening_Titipan__c</fullName>
    <label>Rekening Titipan</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Terminal_ID__c.field-meta.xml
<CustomField>
    <fullName>SCC_Terminal_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SCC Terminal ID</label>
    <referenceTo>SCC_Terminal_ID__c</referenceTo>
    <relationshipName>Nota_Manual</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Total__c.field-meta.xml
<CustomField>
    <fullName>SCC_Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SCC_Terminal_ID__c/SCC_Terminal_ID__c.object-meta.xml
<CustomObject>
    <label>SCC Terminal ID</label>
    <nameField>
        <label>Terminal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCC Terminal ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SCC_NotaController_Test.cls
@isTest
public class SCC_NotaController_Test {
    @testSetup
    static void setupTestData() {
        Case testCase = new Case(
            SCC_Terminal_ID__c = 'TID12345',
            SCC_Transaction_Date__c = Date.today(),
            Description = 'Test case description'
        );
        insert testCase;

        SCC_Nota_Manual__c testNota = new SCC_Nota_Manual__c(
            Case__c = testCase.Id,
            SCC_Nama_Nasabah__c = 'Test Nasabah',
            SCC_Branchcode__c = '123',
            SCC_No_Rekening__c = '4567890',
            SCC_No_Kartu__c = '9876543210',
            SCC_Keterangan__c = 'Test Keterangan',
            SCC_Rekening_Titipan__c = 'RekTitipan123',
            SCC_Rekening_Fee__c = 'RekFee123',
            SCC_Jumlah_Kredit__c = 1000,
            SCC_Jumlah_Debit__c = 500,
            SCC_Total__c = 1500,
            SCC_No_Telepon__c = '08123456789',
            SCC_Jenis_Transaksi__c = '1111'
        );
        insert testNota;
    }

    @isTest
    static void testSCC_NotaController() {
        Case testCase = [SELECT Id, CreatedDate FROM Case LIMIT 1];
        Test.setCurrentPageReference(new PageReference('/apex/SCC_NotaPage?id=' + testCase.Id));

        ApexPages.StandardController sc = new ApexPages.StandardController(testCase);

        SCC_NotaController controller = new SCC_NotaController(sc);

        System.assertNotEquals(null, controller.caseId);
        System.assertEquals('123', controller.BRANCH_CODE);
        System.assertEquals('Test Nasabah', controller.NAMA_NASABAH);
        System.assertEquals('08123456789', '08123456789');
        System.assertEquals('1111', controller.JENISTRX);
        System.assertEquals('4567890', controller.NOREK);
        System.assertEquals('9876543210', controller.NOMOR_KARTU);
        System.assertEquals('TID12345', controller.TID);
        System.assertEquals('Test case description', controller.KETERANGAN1);
        System.assertEquals('RekTitipan123', controller.REKTITIPAN);
        System.assertEquals('RekFee123', controller.REKFEE);
        System.assertEquals(1000, controller.AMOUNTKREDIT);
        System.assertEquals(500, controller.AMOUNTDEBIT);
        System.assertEquals(1500, controller.TOTAL);
        System.assertEquals(testCase.CreatedDate.format('dd-MM-yyyy'), controller.CreatedDate);
    }
}