force-app/main/default/objects/Case/fields/SCC_Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>SCC_Assigned_Date__c</fullName>
    <description>For migration only. It is the date time when case is assigned to the case owner.</description>
    <label>Tgl Assigned</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Case_Category__c.field-meta.xml
<CustomField>
    <fullName>SCC_Case_Category__c</fullName>
    <description>Migration. To store the case category</description>
    <label>Kategori Case</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Complaint - Transaction</fullName>
            </value>
            <value>
                <fullName>Fraud / Suspicious Transactions</fullName>
            </value>
            <value>
                <fullName>Products / Promotion Inquiry</fullName>
            </value>
            <value>
                <fullName>Complaint - Non-Transaction</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Platform &amp; Device Support</fullName>
            </value>
            <value>
                <fullName>Third Party Support</fullName>
            </value>
            <value>
                <fullName>Customer Feedback / Sentiment Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Case_Type_assigned_time__c.field-meta.xml
<CustomField>
    <fullName>SCC_Case_Type_assigned_time__c</fullName>
    <description>The purpose of this field is to get date and time when case type is assigned to case</description>
    <label>Case Type assigned time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Next_Escalation_Level__c.field-meta.xml
<CustomField>
    <fullName>SCC_Next_Escalation_Level__c</fullName>
    <defaultValue>&quot;SCC_Level1_Escalation_team__c&quot;</defaultValue>
    <description>Technical Field to identify next Escalation team from the related Call Type</description>
    <label>Next Escalation Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SCC_Level1_Escalation_team__c</fullName>
                <default>true</default>
                <label>SCC_Level1_Escalation_team__c</label>
            </value>
            <value>
                <fullName>SCC_Level2_Escalation_team__c</fullName>
            </value>
            <value>
                <fullName>SCC_Level3_Escalation_team__c</fullName>
            </value>
            <value>
                <fullName>SCC_Level4_Escalation_team__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Product_L1__c.field-meta.xml
<CustomField>
    <fullName>SCC_Product_L1__c</fullName>
    <description>Migration. To store the product related to the issue</description>
    <label>Product Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Transaction Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Product_L2__c.field-meta.xml
<CustomField>
    <fullName>SCC_Product_L2__c</fullName>
    <description>Migration.To store the product related to the issue</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SCC_Product_L1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Giro (CA)</fullName>
            </value>
            <value>
                <fullName>Tabungan (SA)</fullName>
            </value>
            <value>
                <fullName>Deposito</fullName>
            </value>
            <value>
                <fullName>Briguna Digital</fullName>
            </value>
            <value>
                <fullName>KTA (Personal Loan)</fullName>
                <label>KTA (Personal Loan) / Briguna</label>
            </value>
            <value>
                <fullName>KTA - Digital</fullName>
                <label>KTA - Digital / Ceria</label>
            </value>
            <value>
                <fullName>Kartu Kredit (Credit Card)</fullName>
            </value>
            <value>
                <fullName>KPR (Mortgage)</fullName>
            </value>
            <value>
                <fullName>KUR (Business Loan - Micro)</fullName>
            </value>
            <value>
                <fullName>KUR Ritel</fullName>
            </value>
            <value>
                <fullName>Kupedes</fullName>
            </value>
            <value>
                <fullName>Kredit Modal Kerja (Working Capital)</fullName>
            </value>
            <value>
                <fullName>Kredit Investasi (Investment Loan)</fullName>
            </value>
            <value>
                <fullName>KPR, KUR, KMK, KI</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>DPLK (Pension Fund)</fullName>
            </value>
            <value>
                <fullName>SBN (Bonds)</fullName>
            </value>
            <value>
                <fullName>Mobile Banking</fullName>
            </value>
            <value>
                <fullName>Bancassurance</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>Electronic Money</fullName>
            </value>
            <value>
                <fullName>Digital Savings</fullName>
            </value>
            <value>
                <fullName>Pawning</fullName>
                <label>Pawning / Gadai</label>
            </value>
            <value>
                <fullName>Aplikasi Commodity Chain</fullName>
            </value>
            <value>
                <fullName>Government Programme</fullName>
            </value>
            <value>
                <fullName>Informasi Promo, Program, Produk</fullName>
            </value>
            <value>
                <fullName>Kartu Debit</fullName>
            </value>
            <value>
                <fullName>PPID</fullName>
            </value>
            <value>
                <fullName>Safe Deposit</fullName>
            </value>
            <value>
                <fullName>Senyum Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Segment__c</fullName>
    <description>Migration. To store the customer segment</description>
    <label>Segmen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Agent_SLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Agent_SLA__c</fullName>
    <description>This defines Agent SLA</description>
    <label>Agent SLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Customer_Segment__c</fullName>
    <description>Consists of the type of segment of the case.</description>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level1_Escalation_team__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level1_Escalation_team__c</fullName>
    <description>This field indicates the escalation team for level 1</description>
    <label>Level 1 Escalation Team</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level1_OLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level1_OLA__c</fullName>
    <description>This is the OLA for Level 1</description>
    <label>Level 1 OLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Segment__c</fullName>
    <description>Consists of the type of segment of the case.</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
            <value>
                <fullName>Individu Umum, Individu Priority &amp; Private</fullName>
                <isActive>false</isActive>
                <label>Individu Umum, Individu Priority &amp; Private</label>
            </value>
            <value>
                <fullName>Individu Umum, UMKM</fullName>
                <isActive>false</isActive>
                <label>Individu Umum, UMKM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Description__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Description__c</fullName>
    <label>Deskripsi Case</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L1__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L1__c</fullName>
    <label>Product Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Transaction Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTotalSLAMilestoneTimeCalculatorTest.cls
/** @description
 * Test class to verify the functionality of the CaseTotalSLAMilestoneTimeCalculator class.
 */
@isTest
private class CaseTotalSLAMilestoneTimeCalculatorTest {
    
    /** @description
     * Test method to verify the calculateMilestoneTriggerTime() function.
     */
    @isTest
    static void testCalculateMilestoneTriggerTime() {
        // Test data setup
        Case testCase = new Case(
            Priority = 'High',
             SCC_Assigned_Date__c = Date.today().addDays(-1), // Assigned date 1 day ago
            SCC_Case_Type_assigned_time__c = Datetime.now().addMinutes(-30),
                         SCC_Next_Escalation_Level__c = 'SCC_Level1_Escalation_team__c', // Replace with your specific SCC_Next_Escalation_Level__c
            SCC_Case_Category__c = 'Request',
            SCC_Product_L1__c ='Loans',
            SCC_Product_L2__c='KTA - Digital',
            SCC_Segment__c = 'Individu Umum',
            Description='xyz'// Case type assigned time 30 minutes ago
            // Add any other required fields for the Case record
        );
        insert testCase;

        SSC_Call_Type__c callType = new SSC_Call_Type__c(
              Name = 'Test Call Type',
            SCC_Agent_SLA__c = 1, // Adjusted to a valid value
           // SCC_Level1_OLA__c = 1,
            SSC_Case_Description__c	 = 'xyz',
            External_Id__c = '8812',
            SCC_Customer_Segment__c = 'UMKM',
            SSC_Product_L1__c = 'Servicing',
            SSC_Product_L2__c = 'Cash Management',
            SSC_Case_Category__c = 'Request'// 2 minutes as SCC_Agent_SLA__c
            // Add any other required fields for the SSC Call Type record
        );
        insert callType;

        // Test the calculateMilestoneTriggerTime method
        Test.startTest();
        CaseTotalSLAMilestoneTimeCalculator calculator = new CaseTotalSLAMilestoneTimeCalculator();
        Integer result = calculator.calculateMilestoneTriggerTime(testCase.Id, callType.Id);
        Test.stopTest();

        // Verify the result
        Integer expectedTimeValue = 1; // Convert hours to days
        System.assertEquals(expectedTimeValue, result, 'Milestone trigger time calculation is incorrect');
    }
}