force-app/main/default/objects/Case/fields/SCC_Email__c.field-meta.xml
<CustomField>
    <fullName>SCC_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case_Waiting_Document__c/Case_Waiting_Document__c.object-meta.xml
<CustomObject>
    <label>Case Waiting Document</label>
    <nameField>
        <displayFormat>CWS{YYYYMMDD}{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Waiting Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Waiting_Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Waiting Documents</relationshipLabel>
    <relationshipName>Case_Waiting_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Waiting_Document__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>EndDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Waiting_Document__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>StartDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestCaseWaitingDocument.cls
@istest
public class TestCaseWaitingDocument {
    /**
     * @description createGetCase
     */
    @IsTest
    static void testCaseWaitingDocument(){
        Account acc = new Account();
        acc.Name='Test account';
        insert acc;
        
        Case sce = new Case();
        sce.Subject='test Case';
        sce.Origin='Phone';
        sce.SCC_Email__c='TestEmail@gmail.com';
        sce.Status='New';
        sce.Priority='Low';
        sce.AccountId=acc.Id;
        insert sce;
        
        Case_Waiting_Document__c CWS=new Case_Waiting_Document__c();
        CWS.startdate__c=system.today();
        CWS.startdatetime__c=system.now();
        CWS.case__c =sce.id;
        insert CWS;
        CWS.enddate__c=system.today().adddays(1);
        CWS.enddatetime__c=system.now().adddays(1);
        update CWS;
        }
        
 }