force-app/main/default/objects/Case/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <description>Migration.The account number or credit card number</description>
    <label>Nomor Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Amount__c.field-meta.xml
<CustomField>
    <fullName>SCC_Amount__c</fullName>
    <description>The amount from the dispute transaction</description>
    <label>Nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Closure_Comments__c.field-meta.xml
<CustomField>
    <fullName>SCC_Closure_Comments__c</fullName>
    <description>Contains a brief description of the Case resolution or why the Case should be closed</description>
    <label>Keterangan Closing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Resolution_Category__c.field-meta.xml
<CustomField>
    <fullName>SCC_Resolution_Category__c</fullName>
    <label>Resolution Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Transactional</fullName>
                <label>Kirim Notifikasi</label>
            </value>
            <value>
                <fullName>Dokumen Tidak Lengkap</fullName>
            </value>
            <value>
                <fullName>Tidak Mengirimkan Notifikasi</fullName>
            </value>
            <value>
                <fullName>Transactional/Fraud with Refund</fullName>
                <isActive>false</isActive>
                <label>Transactional/Fraud with Refund</label>
            </value>
            <value>
                <fullName>Transactional/Fraud without Refund</fullName>
                <isActive>false</isActive>
                <label>Transactional/Fraud without Refund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>SCC_Transaction_Date__c</fullName>
    <description>Migration.The date from dispute transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tanggal Transaksi</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Terminal_ID__c.field-meta.xml
<CustomField>
    <fullName>Terminal_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terminal ID</label>
    <referenceTo>SCC_Terminal_ID__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCC_Terminal_ID__c/SCC_Terminal_ID__c.object-meta.xml
<CustomObject>
    <label>SCC Terminal ID</label>
    <nameField>
        <label>Terminal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCC Terminal ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Terminal_ID__c/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SCC_Batch_AutoClosed.cls
public with sharing class SCC_Batch_AutoClosed implements  Database.Batchable<sObject>, Database.AllowsCallouts{
    public String Query;
    public SCC_Batch_AutoClosed(String q){
        this.query = q;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
     }
  
    public void execute(Database.BatchableContext bc, List<Case> scope){
        try{
            List<Case> listcs = new List<Case>();
            for(Case s : scope){
                SCC_RekonWrapper.RequestRekon req = new SCC_RekonWrapper.RequestRekon();
                req.AccountNumber = s.SCC_Account_Number__c;
                req.Amount = String.valueOf(s.SCC_Amount__c);
                req.Page = 1;
                req.TerminalID =s.terminal_id__r.name;
                req.TransactionDate = String.valueOf(s.SCC_Transaction_Date__c);
                if(String.isNotBlank(s.SCC_Call_Type__c)){
                    String ctnum = s.SCC_Call_Type__r.Name.substringbefore('-').trim();
                    if(String.isNotBlank(s?.SCC_Call_Type__r?.External_Id__c)){
                        ctnum = s.SCC_Call_Type__r.External_Id__c;
                    }
                    SCC_RekonWrapper.ResponseRekon res = SCC_Rekon.SearchRekon(req, ctnum);
                    if(res?.RESPONSE_DATA?.result!=null){
                        for(SCC_RekonWrapper.ResponseRekonResult rrr: res?.RESPONSE_DATA?.result){
                            if(rrr?.StatusPenyelesaian=='Transaction Successful'){
                                s.Status = 'Closed';
                                s.SCC_Resolution_Category__c ='Tidak Mengirimkan Notifikasi';
                                s.SCC_Closure_Comments__c = label.Closed_Rekon;
                                listcs.add(s);
                            }
                        }
                    }    
                }
            }
            //update scope;
            if(!listcs.isempty()){
                update listcs;
            }
        }
        catch(Exception exc){
            InsertErrorLog(exc);
        }
    }
  
    public void finish(Database.BatchableContext bc){
     
    }

    public static void InsertErrorLog(Exception exc){
        ErrorLogRecord.DebugLog dl = new ErrorLogRecord.DebugLog();
        dl.message = exc?.getMessage();
        dl.trace = exc?.getStackTraceString();
        dl.typename = exc?.getTypeName();
        dl.linenumber = string.valueOf(exc?.getLineNumber()); 
        dl.errorcause = string.valueOf(exc?.getCause()); 
        dl.classname = 'SCC_Batch_AutoClosed';
        dl.iduser = UserInfo.getUserId();
        ErrorLogRecord.inserterror(JSON.serialize(dl));
    }
}