force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Total_SLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Total_SLA__c</fullName>
    <description>This is the sum of Agent SLA and OLAs of all level</description>
    <formula>SCC_Level1_OLA__c + SCC_Level2_OLA__c + SCC_Level3_OLA__c + SCC_Level4_OLA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total SLA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseTotalSLAMilestoneTimeCalculator.cls
global without sharing class CaseTotalSLAMilestoneTimeCalculator implements Support.MilestoneTriggerTimeCalculator {
    global  Integer calculateMilestoneTriggerTime(String caseId, String milestoneTypeId) {
        Integer timeValue = 1;
        Integer iHour = Integer.ValueOf(Label.HourInBusinessHour);
        //if(!FeatureManagement.checkPermission('By_Pass_Validation_for_Migration')){
        Case c = [SELECT Priority, SCC_Call_Type__c, CreatedDate FROM Case WHERE Id = :caseId WITH SECURITY_ENFORCED];
        List<SSC_Call_Type__c> calls = [SELECT Id, SCC_Total_SLA__c FROM SSC_Call_Type__c WHERE Id = :c.SCC_Call_Type__c WITH SECURITY_ENFORCED];
        if (!calls.isEmpty()) timeValue = Integer.valueOf(calls[0].SCC_Total_SLA__c * 60 * iHour);
        if(timeValue <= 0) timeValue = 1;
        //}
        return timeValue;
    }   
}