force-app/main/default/objects/Bristar_Summary__c/Bristar_Summary__c.object-meta.xml
<CustomObject>
    <label>Bristar Summary</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Bristar Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bristar Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bristar_Summary__c/fields/area__c.field-meta.xml
<CustomField>
    <fullName>area__c</fullName>
    <label>area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/branch__c.field-meta.xml
<CustomField>
    <fullName>branch__c</fullName>
    <label>branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/branchDesc__c.field-meta.xml
<CustomField>
    <fullName>branchDesc__c</fullName>
    <label>branchDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/closedTicket__c.field-meta.xml
<CustomField>
    <fullName>closedTicket__c</fullName>
    <label>closedTicket</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/costCenter__c.field-meta.xml
<CustomField>
    <fullName>costCenter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>costCenter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/costCenterDesc__c.field-meta.xml
<CustomField>
    <fullName>costCenterDesc__c</fullName>
    <label>costCenterDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/mainBranch__c.field-meta.xml
<CustomField>
    <fullName>mainBranch__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>mainBranch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/mainBranchDesc__c.field-meta.xml
<CustomField>
    <fullName>mainBranchDesc__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>mainBranchDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/onSla__c.field-meta.xml
<CustomField>
    <fullName>onSla__c</fullName>
    <label>onSla</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/onSlaClosed__c.field-meta.xml
<CustomField>
    <fullName>onSlaClosed__c</fullName>
    <label>onSlaClosed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/onSlaOpen__c.field-meta.xml
<CustomField>
    <fullName>onSlaOpen__c</fullName>
    <label>onSlaOpen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/openTicket__c.field-meta.xml
<CustomField>
    <fullName>openTicket__c</fullName>
    <label>openTicket</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/overSla__c.field-meta.xml
<CustomField>
    <fullName>overSla__c</fullName>
    <label>overSla</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/overSlaClosed__c.field-meta.xml
<CustomField>
    <fullName>overSlaClosed__c</fullName>
    <label>overSlaClosed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/overSlaOpen__c.field-meta.xml
<CustomField>
    <fullName>overSlaOpen__c</fullName>
    <label>overSlaOpen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/region__c.field-meta.xml
<CustomField>
    <fullName>region__c</fullName>
    <label>region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/regionDesc__c.field-meta.xml
<CustomField>
    <fullName>regionDesc__c</fullName>
    <label>regionDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>CreatedBy.Title</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <formula>IF(  LEFT(OwnerId, 3)= &apos;005&apos; &amp;&amp; Main_Branch__c != &apos;&apos; &amp;&amp;  Main_Branch_Description__c != &apos;&apos;, Owner:User.BranchCode__c , 

IF( Cost_Center__c != &apos;&apos;, &apos;00229&apos;, CodeBranch__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Branch_Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Unit_Name__c</fullName>
    <label>Branch Unit Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cost_Center_Description__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cost Center Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>DATEVALUE(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <formula>IF(CASE(TEXT(Status), &apos;Closed&apos;, &apos;1&apos;, &apos;Cancelled&apos;, &apos;1&apos;,&apos;Disconnected&apos;, &apos;1&apos;, &apos;0&apos;)==&apos;1&apos;,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Main_Branch__c.field-meta.xml
<CustomField>
    <fullName>Main_Branch__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Main Branch</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Main_Branch_Description__c.field-meta.xml
<CustomField>
    <fullName>Main_Branch_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Main Branch Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <formula>LEFT(Region__c, FIND(&quot; &quot;, Region__c &amp; &quot; &quot;) - 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region_Description__c.field-meta.xml
<CustomField>
    <fullName>Region_Description__c</fullName>
    <formula>IF(
    NOT(ISBLANK(Region_Name__c)), 
    Region_Name__c,
    IF(
        NOT(ISBLANK(Region__c)),
        Region__c,
        &quot;&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Within_Target_SLA__c.field-meta.xml
<CustomField>
    <fullName>Within_Target_SLA__c</fullName>
    <formula>IF( Net_SLA_Saat_Ini__c &lt;= SCC_Call_Type__r.SCC_Total_SLA__c,&apos;Sesuai SLA&apos;, &apos;Melebihi SLA&apos;)</formula>
    <label>Status Pencapaian SLA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCC_BristarSummary.cls
public class SCC_BristarSummary implements Database.Batchable<SObject>, Database.Stateful {
    private Date processDate2;
    private Date processDate1;
    private String lmDate;
    private String batchRunIdentifier;
    private Integer excute;
    private String conditions;
    private Set<Date> uniqueDates = new Set<Date>();
    private static final Integer CHUNK_SIZE = 10000;
    
    // Stateful map to track cumulative summary across batch chunks
    private Map<String, Bristar_Summary__c> cumulativeSummaryMap = new Map<String, Bristar_Summary__c>();
    
    // Constructor to allow date to be passed in
    public SCC_BristarSummary(Date processDate1, Date processDate2, Integer excute) {
        this.processDate2 = (processDate2 == null) ? Date.today().addDays(-1) : processDate2;
        this.processDate1 = (processDate1 == null) ? Date.today().addDays(-1) : processDate1;
        System.debug('processDate1 :'+processDate1);
        // Generate a unique batch run identifier for this entire scheduler execution
        this.batchRunIdentifier = String.valueOf(System.now().getTime());
        if(excute == null){
            List<AggregateResult> results = [SELECT Date__c FROM case WHERE LastModifiedDate = YESTERDAY AND ((Area__c = 'KP00' AND Cost_Center__c != null) OR (Area__c != 'KP00' AND Region__c != null AND Main_Branch__c != null AND Branch_Code__c != null)) AND Status IN ('New','Waiting Document','Working','Escalated','Returned','Closed') GROUP BY Date__c];

            // Populate the sets with unique values from the query results
            for (AggregateResult record : results) {
                this.uniqueDates.add((Date)record.get('Date__c'));
            }
            System.debug('uniqueDates :'+uniqueDates);
            // Construct the conditions string with dynamic IN clauses
            this.conditions = 
            ' AND Date__c IN :uniqueDates';

        }else{
            this.conditions = ' AND Date__c <= :processDate2 AND Date__c >= :processDate1';
        }
    }

    // Batch start method - define the query to retrieve cases
    public Database.QueryLocator start(Database.BatchableContext BC) {
        
        String query = 'SELECT ' +
            'Id, Area__c, Date__c, IsClosed__c, Cost_Center__c, ' +
            'Status, Region_Code__c, Region_Description__c, Main_Branch__c, ' +
            'Main_Branch_Description__c, Branch_Code__c, ' +
            'Within_Target_SLA__c, Branch_Unit_Name__c, Cost_Center_Description__c ' +
            'FROM Case ' +
            'WHERE Status IN (\'New\', \'Waiting Document\', \'Working\', \'Escalated\', \'Returned\',\'Closed\') ' +
            ''+conditions+'';
        return Database.getQueryLocator(query);
    }
    
    // Batch execute method - process cases in batches
    public void execute(Database.BatchableContext BC, List<Case> scope) {
        // Prepare map to aggregate summary data for this batch chunk
        Map<String, Bristar_Summary__c> batchSummaryMap = new Map<String, Bristar_Summary__c>();
        
        // Process each case in the current batch
        for (Case cs : scope) {
            // Generate unique external ID
            String externalID = generateExternalIDBristar(cs);
            
            // Initialize or get existing summary record for this batch chunk
            Bristar_Summary__c batchSummary = batchSummaryMap.get(externalID);
            if (batchSummary == null) {
                batchSummary = new Bristar_Summary__c(
                    External_ID__c = externalID,
                    Date__c = cs.Date__c,
                    area__c = cs.Area__c,
                    branch__c = cs.Branch_Code__c,
                    mainBranch__c = cs.Main_Branch__c,
                    region__c = cs.Region_Code__c,
                    costCenter__c = cs.Cost_Center__c,
                    branchDesc__c = cs.Branch_Unit_Name__c,
                    mainBranchDesc__c = cs.Main_Branch_Description__c,
                    regionDesc__c = cs.Region_Description__c,
                    costCenterDesc__c = cs.Cost_Center_Description__c,
                    closedTicket__c = 0,
                    openTicket__c = 0,
                    onSla__c = 0,
                    overSla__c = 0,
                    onSlaOpen__c = 0,
                    onSlaClosed__c = 0,
                    overSlaOpen__c = 0,
                    overSlaClosed__c = 0
                );
            }
            
            // Increment ticket counters
            if (cs.IsClosed__c) {
                batchSummary.closedTicket__c++;
            } else {
                batchSummary.openTicket__c++;
            }
            
            // SLA Tracking
            if (cs.Within_Target_SLA__c == 'Sesuai SLA') {
                batchSummary.onSla__c++;
                if (cs.IsClosed__c) {
                    batchSummary.onSlaClosed__c++;
                } else {
                    batchSummary.onSlaOpen__c++;
                }
            } else if (cs.Within_Target_SLA__c == 'Melebihi SLA') {
                batchSummary.overSla__c++;
                if (cs.IsClosed__c) {
                    batchSummary.overSlaClosed__c++;
                } else {
                    batchSummary.overSlaOpen__c++;
                }
            }
            
            // Update batch summary map
            batchSummaryMap.put(externalID, batchSummary);
        }
        
        // Merge batch summary with cumulative summary
        mergeSummaryMaps(batchSummaryMap);
    }
    
    // Helper method to merge batch summary with cumulative summary
    private void mergeSummaryMaps(Map<String, Bristar_Summary__c> batchSummaryMap) {
        for (String externalId : batchSummaryMap.keySet()) {
            Bristar_Summary__c batchSummary = batchSummaryMap.get(externalId);
            
            // Get or create cumulative summary for this external ID
            Bristar_Summary__c cumulativeSummary = cumulativeSummaryMap.get(externalId);
            if (cumulativeSummary == null) {
                cumulativeSummary = batchSummary.clone(false, true, false, false);
            } else {
                // Aggregate counters
                cumulativeSummary.closedTicket__c += batchSummary.closedTicket__c;
                cumulativeSummary.openTicket__c += batchSummary.openTicket__c;
                cumulativeSummary.onSla__c += batchSummary.onSla__c;
                cumulativeSummary.overSla__c += batchSummary.overSla__c;
                cumulativeSummary.onSlaOpen__c += batchSummary.onSlaOpen__c;
                cumulativeSummary.onSlaClosed__c += batchSummary.onSlaClosed__c;
                cumulativeSummary.overSlaOpen__c += batchSummary.overSlaOpen__c;
                cumulativeSummary.overSlaClosed__c += batchSummary.overSlaClosed__c;
            }
            
            // Update cumulative summary map
            cumulativeSummaryMap.put(externalId, cumulativeSummary);
        }
    }
    
    private void performUpsertChunk(List<Bristar_Summary__c> summaryList) {
        if (summaryList.isEmpty()) return;
        
        Database.UpsertResult[] results = Database.upsert(summaryList, Bristar_Summary__c.External_ID__c, false);
        
        // Error handling
        List<String> errorMessages = new List<String>();
        for (Database.UpsertResult result : results) {
            if (!result.isSuccess()) {
                for (Database.Error error : result.getErrors()) {
                    errorMessages.add('Upsert Error: ' + error.getStatusCode() + ' - ' + error.getMessage());
                }
            }
        }
        
        // Log errors if any
        if (!errorMessages.isEmpty()) {
            for (String errorMsg : errorMessages) {
                System.debug(errorMsg);
            }
        }
        
        System.debug('Upsert Chunk Processed: ' + summaryList.size() + ' records');
    }
    
    // Modify the Queueable class to remove static from performUpsertChunk
    public class SummaryUpsertQueue implements Queueable {
        private List<Bristar_Summary__c> recordsToUpsert;
        private Integer startIndex;
        private SCC_BristarSummary parentBatchClass; // Add reference to parent class
    
        // Modify constructors to accept parent class reference
        public SummaryUpsertQueue(List<Bristar_Summary__c> records, SCC_BristarSummary parentClass) {
            this.recordsToUpsert = records;
            this.startIndex = 0;
            this.parentBatchClass = parentClass;
        }
    
        // Constructor for subsequent chunks
        public SummaryUpsertQueue(List<Bristar_Summary__c> records, Integer startIndex, SCC_BristarSummary parentClass) {
            this.recordsToUpsert = records;
            this.startIndex = startIndex;
            this.parentBatchClass = parentClass;
        }
    
        public void execute(QueueableContext context) {
            // Calculate the end index for this chunk
            Integer endIndex = Math.min(startIndex + 10000, recordsToUpsert.size());
            
            // Create a new list to hold the current chunk
            List<Bristar_Summary__c> currentChunk = new List<Bristar_Summary__c>();
            
            // Manually copy the chunk of records
            for (Integer i = startIndex; i < endIndex; i++) {
                currentChunk.add(recordsToUpsert[i]);
            }
            
            // Perform upsert on the current chunk using parent class method
            parentBatchClass.performUpsertChunk(currentChunk);
            
            // If there are more records, enqueue the next chunk
            if (endIndex < recordsToUpsert.size()) {
                System.enqueueJob(new SummaryUpsertQueue(recordsToUpsert, endIndex, parentBatchClass));
            }
        }
    }
    
    // Modify finish method to pass 'this'
    public void finish(Database.BatchableContext BC) {
        if (!cumulativeSummaryMap.isEmpty()) {
            List<Bristar_Summary__c> summaryList = cumulativeSummaryMap.values();
            
            // If the list is large, use a queueable job to process in chunks
            if (summaryList.size() > 10000) {
                System.enqueueJob(new SummaryUpsertQueue(summaryList, this));
            } else {
                // Perform direct upsert for smaller lists
                performUpsertChunk(summaryList);
            }
        }
        
        System.debug('Bristar Summary Batch Process Completed');
    }
    
    // Helper method to generate external ID
    public static String generateExternalIDBristar(Case cs) {
        String area = cs.Area__c != null ? cs.Area__c : '-';
        String costCenter = cs.Cost_Center__c != null ? cs.Cost_Center__c : '-';
        String region = cs.Region_Code__c != null ? cs.Region_Code__c : '-';
        String mainBranch = cs.Main_Branch__c != null ? cs.Main_Branch__c : '-';
        String branch = cs.Branch_Code__c != null ? cs.Branch_Code__c : '-';
        String dtcs = cs.Date__c != null ? String.valueOf(cs.Date__c) : '-';
        
        return area + '-' + costCenter + '-' + region + '-' + mainBranch + '-' + branch + '-' + dtcs;
    }
}