force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Endpoint_Long__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Long__c</fullName>
    <label>Endpoint Long</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Error_Datetime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Search Parameter</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <label>Request Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_IP__c.field-meta.xml
<CustomField>
    <fullName>Request_IP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request IP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_IP_Long__c.field-meta.xml
<CustomField>
    <fullName>Request_IP_Long__c</fullName>
    <label>Request IP Long</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Related customer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Header__c.field-meta.xml
<CustomField>
    <fullName>Response_Header__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/User_Run__c.field-meta.xml
<CustomField>
    <fullName>User_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Run</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SCC_ErrorLogUtility.cls
/**
 * @description Utility class to capture Integration Logs
 */
public without sharing class SCC_ErrorLogUtility {
    /**
     * @description Method to insert an error log using the wrapper class
     * @param errorLogWrapper SCC_ErrorLogWrapper class instance
     */
    public static void insertErrorLog(SCC_ErrorLogWrapper errorLogWrapper) {
        if (errorLogWrapper == null) {
            throw new IllegalArgumentException('ErrorLogWrapper cannot be null');
        }
        
        // Create a new Error Log SObject
        Error_Log__c errorLog = new Error_Log__c();
        errorLog.put('API_Type__c', errorLogWrapper.apiType);
        errorLog.put('Class_Name__c', errorLogWrapper.className);
        errorLog.put('Endpoint__c', errorLogWrapper.endPoint);
        errorLog.put('Endpoint_Long__c', errorLogWrapper.endPointLong);
        errorLog.put('Error_Cause__c', errorLogWrapper.errorCause);
        errorLog.put('Error_Messages__c', errorLogWrapper.errorMessages);
        errorLog.put('Line_Number__c', errorLogWrapper.lineNumber);
        errorLog.put('Request_Header__c', errorLogWrapper.requestHeader);
        errorLog.put('Request_IP__c', errorLogWrapper.requestIP);
        errorLog.put('Request_IP_Long__c', errorLogWrapper.requestIPLong);
        errorLog.put('Request_Body__c', errorLogWrapper.requestBody);
        errorLog.put('Response_Header__c', errorLogWrapper.responseHeader);
        errorLog.put('Response_Status__c', errorLogWrapper.responseStatus);
        errorLog.put('Response_Status_Code__c', errorLogWrapper.responseStatusCode);
        errorLog.put('Response_Body__c', errorLogWrapper.responseBody);
        errorLog.put('Stack_Trace__c', errorLogWrapper.stackTrace);
        errorLog.put('Error_Datetime__c', errorLogWrapper.errorDatetime);
        errorLog.put('Type_Name__c', errorLogWrapper.typeName);
        errorLog.put('User_Run__c', errorLogWrapper.userRun);
        
        try {
            if(Schema.sObjectType.Error_Log__c.isCreateable()){
                insert errorLog;
            }
        } catch (DmlException e) {
            throw e;
        }
    }
}