force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API Cams</fullName>
            </value>
            <value>
                <fullName>BRI Notif</fullName>
            </value>
            <value>
                <fullName>CHM</fullName>
            </value>
            <value>
                <fullName>CHM Support</fullName>
            </value>
            <value>
                <fullName>Data Hub</fullName>
            </value>
            <value>
                <fullName>Drone</fullName>
            </value>
            <value>
                <fullName>EDM</fullName>
            </value>
            <value>
                <fullName>EJOL</fullName>
            </value>
            <value>
                <fullName>ITSM</fullName>
            </value>
            <value>
                <fullName>Rekon</fullName>
            </value>
            <value>
                <fullName>Wise</fullName>
            </value>
            <value>
                <fullName>BRIMO</fullName>
            </value>
            <value>
                <fullName>BRISTARS</fullName>
            </value>
            <value>
                <fullName>BRIVA</fullName>
            </value>
            <value>
                <fullName>BRIZZI</fullName>
            </value>
            <value>
                <fullName>CASA</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MPN</fullName>
            </value>
            <value>
                <fullName>AVAYA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Endpoint_Long__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Long__c</fullName>
    <label>Endpoint Long</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Menu__c.field-meta.xml
<CustomField>
    <fullName>Menu__c</fullName>
    <label>Menu</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Case - Resolution Center</fullName>
            </value>
            <value>
                <fullName>Case - BRICare</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/RelatedId__c.field-meta.xml
<CustomField>
    <fullName>RelatedId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RelatedId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Search Parameter</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <label>Request Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_IP__c.field-meta.xml
<CustomField>
    <fullName>Request_IP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request IP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_IP_Long__c.field-meta.xml
<CustomField>
    <fullName>Request_IP_Long__c</fullName>
    <label>Request IP Long</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Related customer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Header__c.field-meta.xml
<CustomField>
    <fullName>Response_Header__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CHM</fullName>
            </value>
            <value>
                <fullName>BRImo</fullName>
            </value>
            <value>
                <fullName>BRILink</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>Ceria</fullName>
            </value>
            <value>
                <fullName>RPA</fullName>
            </value>
            <value>
                <fullName>ITSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/User_Run__c.field-meta.xml
<CustomField>
    <fullName>User_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Run</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/Error_Logs__e.object-meta.xml
<CustomObject>
    <label>Error Logs</label>
    <pluralLabel>Error Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Logs__e/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Class_Flow_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Flow_Name__c</fullName>
    <label>Class / Flow Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Endpoint_Long__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Long__c</fullName>
    <label>Endpoint Long</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Menu__c.field-meta.xml
<CustomField>
    <fullName>Menu__c</fullName>
    <label>Menu</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/RelatedId__c.field-meta.xml
<CustomField>
    <fullName>RelatedId__c</fullName>
    <label>RelatedId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <label>Request Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Request_IP__c.field-meta.xml
<CustomField>
    <fullName>Request_IP__c</fullName>
    <label>Request IP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Request_IP_Long__c.field-meta.xml
<CustomField>
    <fullName>Request_IP_Long__c</fullName>
    <label>Request IP Long</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Response_Header__c.field-meta.xml
<CustomField>
    <fullName>Response_Header__c</fullName>
    <label>Response Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Response_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Status_Code__c</fullName>
    <label>Response Status Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/User_Run__c.field-meta.xml
<CustomField>
    <fullName>User_Run__c</fullName>
    <label>User Run</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogRecord.cls
/**
 * @description Class for capture error Log
 */
public without sharing class ErrorLogRecord {
    /**
     * @description Function for capture error from trigger
     * 
     */
    public static void errorexception(
        DebugLog dl,
        Savepoint sp,
        Exception exc){
        if(!test.isRunningTest()) {
            dl.cs.addError(exc.getMessage());
        }
        Database.rollback(sp);
        DebugLog dls = new DebugLog();
        dls.message = exc.getMessage();
        dls.trace = exc.getStackTraceString();
        dls.typename = exc.getTypeName();
        dls.linenumber = string.valueOf(exc.getLineNumber());
        dls.errorcause = string.valueOf(exc.getCause());
        dls.classname = dl.classname;
        ErrorLogRecord.seteventerror(JSON.serialize(dls));
    }
    /**
     * @description Function for capture error from trigger
     * 
     */
    public static void seteventerror( String jsonLogError){
        ErrorLogRecord.DebugLog dls = (ErrorLogRecord.DebugLog) JSON.deserialize(jsonLogError,ErrorLogRecord.DebugLog.class);
        String bodyreq = dls.body;
        if(bodyreq?.length()>130000) {
            bodyreq = bodyreq.substring(0, 130000);
        }
        String bodyres = dls.responseBody;
        if(bodyres?.length()>130000) {
            bodyres = bodyres.substring(0, 130000);
        }
        String ipreq = dls.iprequest;
        if(ipreq?.length()>255) {
            ipreq = ipreq.substring(0,255);
        }
        String endp = dls.urlEndpoint;
        if(endp?.length()>255) {
            endp = endp.substring(0,255);
        }
        Error_Logs__e erl = new Error_Logs__e(
                            Class_Flow_Name__c=dls.classname,
                            user_run__c=dls.iduser,
                            Error_Cause__c=dls.errorcause,
                            Error_Messages__c=dls.message,
                            Line_Number__c=dls.linenumber,
                            Stack_Trace__c=dls.trace,
                            Type_Name__c=dls.typename,
                            request_header__c=dls.header,
                            request_body__c=bodyreq,
                            request_ip__c=ipreq,
                            Request_IP_Long__c=dls.iprequest,
                            endpoint__c=endp,
                            Endpoint_Long__c=dls.urlEndpoint,
                            Response_Header__c=dls.responseHeader,
                            Response_Status__c=dls.responseStatus,
                            Response_Status_Code__c=dls.statusCode,
                            Response_Body__c=bodyres,
                            API_Type__c=dls.typeApi,
                            Menu__c	 = dls.menu,
                            RelatedId__c = dls.recid,
                            Object_Name__c = dls.objnm,
                            Source__c = dls.sorc,
                            Destination__c = dls.dest);
        EventBus.publish(erl);
    }
    /**
     * @description Function for capture error from class non integration
     * 
     */
    public static void inserterror(String jsonLogError){
        ErrorLogRecord.seteventerror(jsonLogError);
    }
    /**
     * @description Function for capture error from integration
     * 
     */
    public static void inserterrorAPI(String jsonLogError){
        ErrorLogRecord.seteventerror(jsonLogError);
        /*
        if (Schema.sObjectType.Error_Log__c.isCreateable()) {
            insert el;
        }
            */
    }

    public class DebugLog {
        public String iduser {get;set;}
        public String message {get;set;} 
        public String trace {get;set;} 
        public String typename {get;set;} 
        public String linenumber {get;set;} 
        public String errorcause {get;set;} 
        public String classname {get;set;}
        public String header {get;set;} 
        public String body {get;set;} 
        public String iprequest {get;set;}
        public String responseStatus {get;set;}
        public Integer statusCode {get;set;}
        public String responseHeader {get;set;}
        public String responseBody {get;set;}
        public string urlEndpoint {get;set;}
        public string typeApi {get;set;}
        public string menu {get;set;}
        public string recid {get;set;}
        public string objnm {get;set;}
        public string sorc {get;set;}
        public string dest {get;set;}
        public SOBJECT cs {get;set;}
    }
}