force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Anomali__c.field-meta.xml
<CustomField>
    <fullName>Anomali__c</fullName>
    <label>Anomali</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Access Datahub Not Create Case</fullName>
            </value>
            <value>
                <fullName>Access Outside Business Hours</fullName>
            </value>
            <value>
                <fullName>Extremely Frequency Access Datahub</fullName>
            </value>
            <value>
                <fullName>Access Data Outside BRI IP</fullName>
                <isActive>false</isActive>
                <label>Access Data Outside BRI IP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API Cams</fullName>
            </value>
            <value>
                <fullName>BRI Notif</fullName>
            </value>
            <value>
                <fullName>CHM</fullName>
            </value>
            <value>
                <fullName>CHM Support</fullName>
            </value>
            <value>
                <fullName>Data Hub</fullName>
            </value>
            <value>
                <fullName>Drone</fullName>
            </value>
            <value>
                <fullName>EDM</fullName>
            </value>
            <value>
                <fullName>EJOL</fullName>
            </value>
            <value>
                <fullName>ITSM</fullName>
            </value>
            <value>
                <fullName>Rekon</fullName>
            </value>
            <value>
                <fullName>Wise</fullName>
            </value>
            <value>
                <fullName>BRIMO</fullName>
            </value>
            <value>
                <fullName>BRISTARS</fullName>
            </value>
            <value>
                <fullName>BRIVA</fullName>
            </value>
            <value>
                <fullName>BRIZZI</fullName>
            </value>
            <value>
                <fullName>CASA</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MPN</fullName>
            </value>
            <value>
                <fullName>AVAYA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Error_Datetime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Menu__c.field-meta.xml
<CustomField>
    <fullName>Menu__c</fullName>
    <label>Menu</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Case - Resolution Center</fullName>
            </value>
            <value>
                <fullName>Case - BRICare</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/User_Run__c.field-meta.xml
<CustomField>
    <fullName>User_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Run</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SCC_Batch_ActionMonitoringLog.cls
global class SCC_Batch_ActionMonitoringLog implements Database.AllowsCallouts,Database.Batchable<sObject>{
    private String strdt;
    private String menu;
    private String destination;
    private List<String> listuserid = new List<String>();
    private String anomali;
    
    global SCC_Batch_ActionMonitoringLog(String strdt,String menu,String destination,List<String> listuserid,String anomali){
        this.strdt = strdt;
        this.menu = menu;
        this.destination = destination;
        this.listuserid = listuserid;
        this.anomali = anomali;
    }
    
	global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id,Anomali__c,User_Run__c FROM Error_Log__c ';
            query += 'WHERE Error_Datetime__c = ' + strdt + ' ';
            query += 'AND Response_Status_Code__c = 200 ';
            query += 'AND Menu__c !=: menu ';
            query += 'AND Destination__c =: destination ';
            query += 'AND User_Run__c IN:listuserid ';
            query += 'ORDER BY User_Run__c ASC, Error_Datetime__c ASC LIMIT 50000 ';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<sObject> scope) {
        List<Error_Log__c> listelnew = new List<Error_Log__c>();
        for(sObject sobj : scope){
            Error_Log__c el = (Error_Log__c)sobj;
            if(el.Anomali__c == '' || el.Anomali__c == null){
                el.Anomali__c = anomali;
                listelnew.add(el);
            }else if(!el.Anomali__c.contains(anomali)){
                el.Anomali__c = el.Anomali__c + ';' + anomali;
                listelnew.add(el);
            }
        }
        if(listelnew.size()>0) update listelnew;
    }

    global void finish(Database.BatchableContext bc) {
        // execute any post-processing operations - send emails, notify clients
    }
   
}