force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/RelatedId__c.field-meta.xml
<CustomField>
    <fullName>RelatedId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RelatedId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Search Parameter</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <label>Request Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_IP__c.field-meta.xml
<CustomField>
    <fullName>Request_IP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request IP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Related customer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Header__c.field-meta.xml
<CustomField>
    <fullName>Response_Header__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/String_To_Sign__c.field-meta.xml
<CustomField>
    <fullName>String_To_Sign__c</fullName>
    <label>String To Sign</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/User_Run__c.field-meta.xml
<CustomField>
    <fullName>User_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Run</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/Error_Logs__e.object-meta.xml
<CustomObject>
    <label>Error Logs</label>
    <pluralLabel>Error Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Logs__e/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <label>API Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Class_Flow_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Flow_Name__c</fullName>
    <label>Class / Flow Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Error_Messages__c.field-meta.xml
<CustomField>
    <fullName>Error_Messages__c</fullName>
    <label>Error Messages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/RelatedId__c.field-meta.xml
<CustomField>
    <fullName>RelatedId__c</fullName>
    <label>RelatedId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <label>Request Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Request_IP__c.field-meta.xml
<CustomField>
    <fullName>Request_IP__c</fullName>
    <label>Request IP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Response_Header__c.field-meta.xml
<CustomField>
    <fullName>Response_Header__c</fullName>
    <label>Response Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/Response_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Status_Code__c</fullName>
    <label>Response Status Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/String_To_Sign__c.field-meta.xml
<CustomField>
    <fullName>String_To_Sign__c</fullName>
    <label>String To Sign</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__e/fields/User_Run__c.field-meta.xml
<CustomField>
    <fullName>User_Run__c</fullName>
    <label>User Run</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventErrorLogHandler.cls
/**
 * @description EventErrorLogHandler
 */
public without sharing class EventErrorLogHandler {
    /**
     * @description handleAfterInsert
     * @param newEvents
     */
    public static void handleAfterInsert(List<Error_Logs__e> newEvents) {
        List<Error_Log__c> logsToInsert = new List<Error_Log__c>();
        
        for (Error_Logs__e dls : newEvents) {
            Error_Log__c el = new Error_Log__c(
                Class_Name__c          = dls.Class_Flow_Name__c,
                User_run__c            = dls.User_run__c,
                API_Type__c            = dls.API_Type__c,
                RelatedId__c           = dls.RelatedId__c,
                Object_Name__c         = dls.Object_Name__c,
                Error_Cause__c         = dls.Error_Cause__c,
                Error_Messages__c      = dls.Error_Messages__c,
                Line_Number__c         = dls.Line_Number__c,
                Stack_Trace__c         = dls.Stack_Trace__c,
                Type_Name__c           = dls.Type_Name__c,
                Request_header__c      = dls.Request_header__c,
                Request_body__c        = dls.Request_body__c,
                Request_IP__c          = dls.Request_IP__c,
                Endpoint__c            = dls.Endpoint__c,
                Response_Header__c     = dls.Response_Header__c,
                Response_Status__c     = dls.Response_Status__c,
                Response_Status_Code__c= dls.Response_Status_Code__c,
                Response_Body__c       = dls.Response_Body__c,
                String_To_Sign__c      = dls.String_To_Sign__c
            );
            logsToInsert.add(el);
        }
        
        if (!logsToInsert.isEmpty() && Schema.sObjectType.Error_Log__c.isCreateable()) {
            Database.insert(logsToInsert, false);
        }
    }
}