force-app/main/default/objects/BRIMO__c/BRIMO__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BRIMO</label>
</CustomObject>

force-app/main/default/objects/BRIMO__c/fields/request_refnum__c.field-meta.xml
<CustomField>
    <fullName>request_refnum__c</fullName>
    <defaultValue>0</defaultValue>
    <label>request refnum</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <description>Migration.The account number or credit card number</description>
    <label>Nomor Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Amount__c.field-meta.xml
<CustomField>
    <fullName>SCC_Amount__c</fullName>
    <description>The amount from the dispute transaction</description>
    <label>Nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/scc_Billing_Number__c.field-meta.xml
<CustomField>
    <fullName>scc_Billing_Number__c</fullName>
    <label>Billing Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type_Feature__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type_Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Type Feature</label>
    <referenceTo>SCC_Call_Type_Feature__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>SCC_Transaction_Date__c</fullName>
    <description>Migration.The date from dispute transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tanggal Transaksi</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SCC_Call_Type_Feature__c/SCC_Call_Type_Feature__c.object-meta.xml
<CustomObject>
    <label>Case Type Feature</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Type Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SCC_Batch_AutoClosed_RTGS_Test.cls
/**
 * @description       : 
 * @author            : Suherbing Septian
 * @group             : 
 * @last modified on  : 15/09/2025
 * @last modified by  : Suherbing Septian
**/

@isTest
private class SCC_Batch_AutoClosed_RTGS_Test {
    @TestSetup
    static void makeData(){
        SSC_Call_Type__c callType = Object_Test.setCallType('8222');
        insert callType;
        SCC_Call_Type_Feature__c callTypeFeature = Object_Test.setFitur(callType.Id);
        insert callTypeFeature;
        Case testCase = Object_Test.setCase(callType.Id);
        testCase.SCC_Call_Type_Feature__c = callTypeFeature.Id;
        testCase.SCC_Amount__c = 130000000;
        testCase.SCC_Transaction_Date__c = Date.today();
        testCase.SCC_Account_Number__c = '326301020301234';
        testCase.scc_Billing_Number__c = '3263010203012';
        insert testCase;

        // Buat custom setting BRIMO__c
        BRIMO__c brimoSetting = new BRIMO__c(
            Name = 'extId RTGS',
            request_refnum__c = 1000
        );
        insert brimoSetting;
    }
    @isTest
    static void testBatchSucess() {
        
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new SCC_CaseResolution_FindRTGSMock.FindRTGS());
        String cond = 'isclosed = false';
        String addfield = '';
        String allfield = SOQL_SOBJECT.getallfield('Case');
        String queries = SOQL_SOBJECT.SOQL(allfield, addfield, 'Case', cond, '', '', '');
        Database.executeBatch(new SCC_Batch_AutoClosed_RTGS(queries), 1);
        test.stopTest();
    }

    @isTest
    static void testInsertError() {
        // TO DO: implement unit test
        test.startTest();
        Account acc = new Account();
        try{
            insert acc;
        }
        catch(exception exc){
            SCC_Batch_AutoClosed_RTGS.InsertErrorLog(exc);
        }
        test.stopTest();
    }
}