force-app/main/default/objects/Incident/fields/Hold_Justification__c.field-meta.xml
<CustomField>
    <fullName>Hold_Justification__c</fullName>
    <inlineHelpText>alasan status unhold pada iRis</inlineHelpText>
    <label>Hold Justification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incident/fields/Remark_History__c.field-meta.xml
<CustomField>
    <fullName>Remark_History__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remark History</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incident/fields/Root_Cause2__c.field-meta.xml
<CustomField>
    <fullName>Root_Cause2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Root Cause</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Incident/fields/Un_Hold_Justification__c.field-meta.xml
<CustomField>
    <fullName>Un_Hold_Justification__c</fullName>
    <inlineHelpText>Alasan unhold</inlineHelpText>
    <label>Un-Hold Justification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SCC_IncidentHistory_UI.cls
public with sharing class SCC_IncidentHistory_UI {
    
    @AuraEnabled
    public static Incident getIncidentDetail(String idIncident){
        // String cond = 'id=:idIncident';
        // String allfield = SOQL_SOBJECT.getallfield('Incident');
        // String queries = SOQL_SOBJECT.SOQL(allfield, '', 'Incident', cond, '', '', '');
        // Incident inc = Database.query(queries);
        // return inc;

        if (String.isBlank(idIncident)) {
            throw new AuraHandledException('Incident ID cannot be null or empty');
        }
        
        try {
            Incident inc = [SELECT Id,IncidentNumber, Hold_Justification__c, Un_Hold_Justification__c, Root_Cause2__c, Remark_History__c
            FROM Incident 
            WHERE Id = :idIncident 
            LIMIT 1];

            return inc;
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving Incident: ' + e.getMessage());
        }
    }

}