force-app/main/default/objects/Anomali_Category__c/Anomali_Category__c.object-meta.xml
<CustomObject>
    <label>Anomali Category</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Anomali Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomali Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Anomali_Category__c/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Anomali_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Anomali_Category__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Profile</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Anomali_Category__c/recordTypes/Access_Not_Create_Case.recordType-meta.xml
<RecordType>
    <fullName>Access_Not_Create_Case</fullName>
    <active>true</active>
    <label>Access Not Create Case</label>
</RecordType>

force-app/main/default/objects/Anomali_Category__c/recordTypes/extremely_frequency.recordType-meta.xml
<RecordType>
    <fullName>extremely_frequency</fullName>
    <active>true</active>
    <label>extremely frequency</label>
</RecordType>

force-app/main/default/objects/Anomali_Category__c/recordTypes/Outside_Business_Hours.recordType-meta.xml
<RecordType>
    <fullName>Outside_Business_Hours</fullName>
    <active>true</active>
    <label>Outside Business Hours</label>
</RecordType>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API Cams</fullName>
            </value>
            <value>
                <fullName>BRI Notif</fullName>
            </value>
            <value>
                <fullName>CHM</fullName>
            </value>
            <value>
                <fullName>CHM Support</fullName>
            </value>
            <value>
                <fullName>Data Hub</fullName>
            </value>
            <value>
                <fullName>Drone</fullName>
            </value>
            <value>
                <fullName>EDM</fullName>
            </value>
            <value>
                <fullName>EJOL</fullName>
            </value>
            <value>
                <fullName>ITSM</fullName>
            </value>
            <value>
                <fullName>Rekon</fullName>
            </value>
            <value>
                <fullName>Wise</fullName>
            </value>
            <value>
                <fullName>BRIMO</fullName>
            </value>
            <value>
                <fullName>BRISTARS</fullName>
            </value>
            <value>
                <fullName>BRIVA</fullName>
            </value>
            <value>
                <fullName>BRIZZI</fullName>
            </value>
            <value>
                <fullName>CASA</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MPN</fullName>
            </value>
            <value>
                <fullName>AVAYA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Error_Datetime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Menu__c.field-meta.xml
<CustomField>
    <fullName>Menu__c</fullName>
    <label>Menu</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Case - Resolution Center</fullName>
            </value>
            <value>
                <fullName>Case - BRICare</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Monitoring_Summary__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monitoring Summary</label>
    <referenceTo>Monitoring_Summary__c</referenceTo>
    <relationshipLabel>Request and Error Logs</relationshipLabel>
    <relationshipName>Request_and_Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/RelatedId__c.field-meta.xml
<CustomField>
    <fullName>RelatedId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RelatedId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/User_Run__c.field-meta.xml
<CustomField>
    <fullName>User_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Run</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monitoring_Summary__c/Monitoring_Summary__c.object-meta.xml
<CustomObject>
    <label>Monitoring Summary</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Monitoring Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitoring Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring_Summary__c/fields/Anomali_Category__c.field-meta.xml
<CustomField>
    <fullName>Anomali_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Anomali Category</label>
    <referenceTo>Anomali_Category__c</referenceTo>
    <relationshipLabel>Monitoring Summary</relationshipLabel>
    <relationshipName>Monitoring_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SCC_MonitoringTest.cls
@isTest
public class SCC_MonitoringTest {
	@testSetup static void setup(){
        Id IdExtremely = Schema.SObjectType.Anomali_Category__c.getRecordTypeInfosByDeveloperName().get('extremely_frequency').getRecordTypeId();
        Id IdBusiness = Schema.SObjectType.Anomali_Category__c.getRecordTypeInfosByDeveloperName().get('Outside_Business_Hours').getRecordTypeId();
        Id IdNotCreate = Schema.SObjectType.Anomali_Category__c.getRecordTypeInfosByDeveloperName().get('Access_Not_Create_Case').getRecordTypeId();
        List<BusinessHours> bhs=[SELECT id FROM BusinessHours WHERE IsDefault=true];
        
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Anomali_Category__c ac = new Anomali_Category__c();
        ac.Active__c = true;
        ac.Profile__c = 'System Administrator';
        ac.RecordTypeId = IdExtremely;
        ac.Frequency__c = 0;
        insert ac;
        
        Anomali_Category__c ac1 = new Anomali_Category__c();
        ac1.Active__c = true;
        ac1.Business_Hours__c = bhs[0].Id;
        ac1.Profile__c = 'System Administrator';
        ac1.RecordTypeId = IdBusiness;
        insert ac1;
        
        Anomali_Category__c ac2 = new Anomali_Category__c();
        ac2.Name = 'Access Datahub Not Create Case';
        ac2.Active__c = true;
        ac2.RecordTypeId = IdNotCreate;
        insert ac2;
        
        Error_Log__c el = new Error_Log__c();
        el.Menu__c = 'Account';
        el.Response_Status_Code__c = 200;
        el.Error_Datetime__c = DateTime.Now().addDays(-1);
        el.User_Run__c = UserInfo.getUserId();
        el.RelatedId__c = acc.Id;
        el.Destination__c = 'Data Hub';
        insert el;
    }
    
    static testMethod void testProcess(){
        system.schedule('Monitoring Summary', '0 0 0 * * ?', new SCC_Sch_Monitoring());
        system.schedule('Monitoring Summary 1', '0 0 0 * * ?', new SCC_Sch_Monitoring1());
        system.schedule('Monitoring Summary 2', '0 0 0 * * ?', new SCC_Sch_Monitoring2());
        SCC_Monitoring.execute(null,null,'Extremely');
        SCC_Monitoring.execute(null,null,'Business_Hours');
        SCC_Monitoring.execute(null,null,'Not_Create_Case');
        List<Monitoring_Summary__c> recordset = new List<Monitoring_Summary__c>();
        database.executebatch(new SCC_Batch_ActionMonitoring(recordset,'update'),200);
    }
}