force-app/main/default/objects/Anomali_Category__c/Anomali_Category__c.object-meta.xml
<CustomObject>
    <label>Anomali Category</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Anomali Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomali Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Unit__c/Branch_Unit__c.object-meta.xml
<CustomObject>
    <label>Branch Unit 2</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Units</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring_Summary__c/Monitoring_Summary__c.object-meta.xml
<CustomObject>
    <label>Monitoring Summary</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Monitoring Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitoring Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring_Summary__c/fields/Anomali_Category__c.field-meta.xml
<CustomField>
    <fullName>Anomali_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Anomali Category</label>
    <referenceTo>Anomali_Category__c</referenceTo>
    <relationshipLabel>Monitoring Summary</relationshipLabel>
    <relationshipName>Monitoring_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monitoring_Summary__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>User__r.SCC_Area__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monitoring_Summary__c/fields/Branch_Unit__c.field-meta.xml
<CustomField>
    <fullName>Branch_Unit__c</fullName>
    <formula>Branch_Unit_2__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monitoring_Summary__c/fields/Divisi__c.field-meta.xml
<CustomField>
    <fullName>Divisi__c</fullName>
    <formula>User__r.SCC_Cost_Center_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Divisi</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monitoring_Summary__c/fields/Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Sub_Area__c</fullName>
    <formula>User__r.SCC_Sub_Area_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monitoring_Summary__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monitoring_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCC_Custom_API_Response_Code__mdt/SCC_Custom_API_Response_Code__mdt.object-meta.xml
<CustomObject>
    <label>SCC_Custom_API_Response_Code</label>
    <pluralLabel>SCC_Custom_API_Response_Code</pluralLabel>
</CustomObject>

force-app/main/default/objects/SCC_Custom_API_Response_Code__mdt/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <label>Response Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SCC_Legacy_API_Mapping_Query__mdt/SCC_Legacy_API_Mapping_Query__mdt.object-meta.xml
<CustomObject>
    <label>SCC_Legacy_API_Mapping_Query</label>
    <pluralLabel>SCC_Legacy_API_Mapping_Query</pluralLabel>
</CustomObject>

force-app/main/default/objects/User/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Branch_Unit__c.field-meta.xml
<CustomField>
    <fullName>Branch_Unit__c</fullName>
    <label>Branch Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>73</fullName>
        <label>Area Barat</label>
    </customValue>
    <customValue>
        <fullName>72</fullName>
        <label>Area Jakarta</label>
    </customValue>
    <customValue>
        <fullName>71</fullName>
        <label>Area Tengah</label>
    </customValue>
    <customValue>
        <fullName>74</fullName>
        <label>Area Timur</label>
    </customValue>
    <customValue>
        <fullName>-1</fullName>
        <label>Area Khusus</label>
    </customValue>
    <masterLabel>Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MonitoringSummary_API_Ctrl.cls
public with sharing class MonitoringSummary_API_Ctrl {

// Handle API get by Date

    Public Static String GetByDate(MonitoringSummary_API_Wrapper.GetByDateRequestModel jreq){
        //Map<String, SCC_Legacy_API_Mapping_Query__mdt> mapmfc = SCC_Legacy_API_Mapping_Query__mdt.getAll();
        Map<String, SCC_Custom_API_Response_Code__mdt> maprc = SCC_Custom_API_Response_Code__mdt.getAll();
        SCC_Custom_API_Response_Code__mdt rc = new SCC_Custom_API_Response_Code__mdt();
        //String cond = jreq.Qualification;
        Date StartDate = Date.valueOf(jreq.StartDate);
        Date EndDate = Date.valueOf(jreq.EndDate);
        String cond = 'Date__c <= :EndDate and Date__c >= :StartDate';
        String addfield = ',Anomali_Category__r.RecordType.Name,Anomali_Category__r.Name,User__r.Name';
        String allfield = SOQL_SOBJECT.getallfield('Monitoring_Summary__c');
        String queries = SOQL_SOBJECT.SOQL(allfield, addfield, 'Monitoring_Summary__c', cond, 'Date__c', 'ASC', '');
        List<Monitoring_Summary__c> listms = Database.query(queries);
        MonitoringSummary_API_Wrapper.GetByDateResponseModel jres = new MonitoringSummary_API_Wrapper.GetByDateResponseModel();
        List<MonitoringSummary_API_Wrapper.GetByDateDetailModel> MonitoringSummary = new List<MonitoringSummary_API_Wrapper.GetByDateDetailModel>();
        if(!listms.isEmpty()){
            System.debug('listms tidak kosong');
            for(Monitoring_Summary__c ms:listms){
                //Datetime dt = ms.Date__c;
                MonitoringSummary_API_Wrapper.GetByDateDetailModel msdt = new MonitoringSummary_API_Wrapper.GetByDateDetailModel();
                msdt.Tanggal = String.valueOf(ms.Date__c);
                msdt.AnomalyCategory_RecordType = ms.Anomali_Category__r.RecordType.Name;
                msdt.Area = ms.Area__c;
                msdt.Branch_Unit = ms.Branch_Unit__c;
                msdt.Divisi = ms.Divisi__c;
                msdt.AnomalyCategory_Name = ms.Anomali_Category__r.Name;
                msdt.MonitoringSummary_Name = ms.Name;
                msdt.User_Name = ms.User__r.Name;
                msdt.Total = String.valueOf(ms.Total__c);
                MonitoringSummary.add(msdt);
            }
            rc = maprc?.get('Success');
        }
        else{
            System.debug('listms kosong');
            rc = maprc?.get('Data_Not_Found');
        }
        System.debug('MonitoringSummary: '+MonitoringSummary);
        jres.MonitoringSummary = MonitoringSummary;
        jres.responseCode = rc?.Response_Code__c;
        jres.responseMessage = rc?.Description__c;
        String return_json = MonitoringSummary_API_Ctrl.returnAPIGetByDate(jres);
        return return_json;
    }

    Public Static String returnAPIGetByDate(MonitoringSummary_API_Wrapper.GetByDateResponseModel jres){
        String return_json = '';
        return_json = (String) JSON.serialize(jres,false);
        return_json = return_json.normalizeSpace().trim(); 
        return return_json;
    }

// Handle API get by Divisi - Kantor Pusat

    Public Static String GetByAreaDivisi(MonitoringSummary_API_Wrapper.GetByAreaRequestModel jreq){
        //Map<String, SCC_Legacy_API_Mapping_Query__mdt> mapmfc = SCC_Legacy_API_Mapping_Query__mdt.getAll();
        Map<String, SCC_Custom_API_Response_Code__mdt> maprc = SCC_Custom_API_Response_Code__mdt.getAll();
        SCC_Custom_API_Response_Code__mdt rc = new SCC_Custom_API_Response_Code__mdt();
        //String cond = jreq.Qualification;
        String Area = jreq.Area;
        String GroupBy = jreq.GroupBy;
        MonitoringSummary_API_Wrapper.GetByAreaDivisiResponseModel jres = new MonitoringSummary_API_Wrapper.GetByAreaDivisiResponseModel();
        List<MonitoringSummary_API_Wrapper.GetByAreaDivisiDetailModel> MonitoringSummary = new List<MonitoringSummary_API_Wrapper.GetByAreaDivisiDetailModel>();
        if(GroupBy == 'Divisi' && Area == 'Kantor Pusat'){
            String cond = 'Area__c = :Area and Divisi__c != null';
            String addfield = ',Anomali_Category__r.RecordType.Name,Anomali_Category__r.Name,User__r.Name';
            String allfield = SOQL_SOBJECT.getallfield('Monitoring_Summary__c');
            String queries = SOQL_SOBJECT.SOQL(allfield, addfield, 'Monitoring_Summary__c', cond, 'Date__c', 'ASC', '');
            List<Monitoring_Summary__c> listms = Database.query(queries);
            if(!listms.isEmpty()){
                for(Monitoring_Summary__c ms:listms){
                    //Datetime dt = ms.Date__c;
                    MonitoringSummary_API_Wrapper.GetByAreaDivisiDetailModel msdt = new MonitoringSummary_API_Wrapper.GetByAreaDivisiDetailModel();
                    msdt.Tanggal = String.valueOf(ms.Date__c);
                    msdt.AnomalyCategory_RecordType = ms.Anomali_Category__r.RecordType.Name;
                    msdt.Area = ms.Area__c;
                    msdt.Divisi = ms.Divisi__c;
                    msdt.AnomalyCategory_Name = ms.Anomali_Category__r.Name;
                    msdt.MonitoringSummary_Name = ms.Name;
                    msdt.User_Name = ms.User__r.Name;
                    msdt.Total = String.valueOf(ms.Total__c);
                    MonitoringSummary.add(msdt);
                }
                rc = maprc?.get('Success');
            }
            else{
                rc = maprc?.get('Data_Not_Found');
            }
        }else {
            rc = maprc?.get('Mandatory');
        }
        jres.MonitoringSummary = MonitoringSummary;
        jres.responseCode = rc?.Response_Code__c;
        jres.responseMessage = rc?.Description__c;
        String return_json = MonitoringSummary_API_Ctrl.returnAPIGetByAreaDivisi(jres);
        return return_json;
    }

    Public Static String returnAPIGetByAreaDivisi(MonitoringSummary_API_Wrapper.GetByAreaDivisiResponseModel jres){
        String return_json = '';
        return_json = (String) JSON.serialize(jres,false);
        return_json = return_json.normalizeSpace().trim(); 
        return return_json;
    }
    
// Handle API get by Branch - Cabang

    Public Static String GetByAreaBranch(MonitoringSummary_API_Wrapper.GetByAreaRequestModel jreq){
        //Map<String, SCC_Legacy_API_Mapping_Query__mdt> mapmfc = SCC_Legacy_API_Mapping_Query__mdt.getAll();
        Map<String, SCC_Custom_API_Response_Code__mdt> maprc = SCC_Custom_API_Response_Code__mdt.getAll();
        SCC_Custom_API_Response_Code__mdt rc = new SCC_Custom_API_Response_Code__mdt();
        //String cond = jreq.Qualification;
        String Area = jreq.Area;
        String GroupBy = jreq.GroupBy;
        MonitoringSummary_API_Wrapper.GetByAreaBranchResponseModel jres = new MonitoringSummary_API_Wrapper.GetByAreaBranchResponseModel();
        List<MonitoringSummary_API_Wrapper.GetByAreaBranchDetailModel> MonitoringSummary = new List<MonitoringSummary_API_Wrapper.GetByAreaBranchDetailModel>();
        if(GroupBy == 'Branch' && Area == 'Cabang'){
            String cond = 'Area__c != \'Kantor Pusat\' and Branch_Unit__c != null';
            String addfield = ',Anomali_Category__r.RecordType.Name,Anomali_Category__r.Name,User__r.Name';
            String allfield = SOQL_SOBJECT.getallfield('Monitoring_Summary__c');
            String queries = SOQL_SOBJECT.SOQL(allfield, addfield, 'Monitoring_Summary__c', cond, 'Date__c', 'ASC', '');
            List<Monitoring_Summary__c> listms = Database.query(queries);
            if(!listms.isEmpty()){
                for(Monitoring_Summary__c ms:listms){
                    //Datetime dt = ms.Date__c;
                    MonitoringSummary_API_Wrapper.GetByAreaBranchDetailModel msdt = new MonitoringSummary_API_Wrapper.GetByAreaBranchDetailModel();
                    msdt.Tanggal = String.valueOf(ms.Date__c);
                    msdt.AnomalyCategory_RecordType = ms.Anomali_Category__r.RecordType.Name;
                    msdt.Area = ms.Area__c;
                    msdt.Sub_Area = ms.Sub_Area__c;
                    msdt.Branch_Unit = ms.Branch_Unit__c;
                    msdt.AnomalyCategory_Name = ms.Anomali_Category__r.Name;
                    msdt.MonitoringSummary_Name = ms.Name;
                    msdt.User_Name = ms.User__r.Name;
                    msdt.Total = String.valueOf(ms.Total__c);
                    MonitoringSummary.add(msdt);
                }
                rc = maprc?.get('Success');
            }
            else{
                rc = maprc?.get('Data_Not_Found');
            }
        }else {
            rc = maprc?.get('Mandatory');
        }
        jres.MonitoringSummary = MonitoringSummary;
        jres.responseCode = rc?.Response_Code__c;
        jres.responseMessage = rc?.Description__c;
        String return_json = MonitoringSummary_API_Ctrl.returnAPIGetByAreaBranch(jres);
        return return_json;
    }

    Public Static String returnAPIGetByAreaBranch(MonitoringSummary_API_Wrapper.GetByAreaBranchResponseModel jres){
        String return_json = '';
        return_json = (String) JSON.serialize(jres,false);
        return_json = return_json.normalizeSpace().trim(); 
        return return_json;
    }
}