force-app/main/default/objects/Asset/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premises Address / Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>amount asset</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Amount_Insured__c.field-meta.xml
<CustomField>
    <fullName>Amount_Insured__c</fullName>
    <description>amount dari risk</description>
    <label>Amount Insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City/Regency</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Assets (City)</relationshipLabel>
    <relationshipName>Assets2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <formula>Text(Opportunity__r.COB__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/jenis_perlengkapan__c.field-meta.xml
<CustomField>
    <fullName>jenis_perlengkapan__c</fullName>
    <label>jenis perlengkapan</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/License_Plate_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Plate_Number__c</fullName>
    <label>License Plate Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Occupation_Code__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Risk Type</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Occupation_Description__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Description__c</fullName>
    <formula>Occupation_Code__r.Description__c</formula>
    <label>Occupation Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Rate_All_Coverages__c.field-meta.xml
<CustomField>
    <fullName>Rate_All_Coverages__c</fullName>
    <label>Rate All Coverages</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Total_Premi_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Premi_Amount__c</fullName>
    <label>Total Premi Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Road Bike</fullName>
            </value>
            <value>
                <fullName>Cruiser / City Bike</fullName>
            </value>
            <value>
                <fullName>Hybrid Bike</fullName>
            </value>
            <value>
                <fullName>BMX</fullName>
            </value>
            <value>
                <fullName>Fixie</fullName>
            </value>
            <value>
                <fullName>Folding Bike</fullName>
            </value>
            <value>
                <fullName>Electric Bike</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Utilization__c.field-meta.xml
<CustomField>
    <fullName>Utilization__c</fullName>
    <inlineHelpText>Referensi dari data Industry</inlineHelpText>
    <label>Utilization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
                <label>Private (Pribadi/ Dinas Perusahaan)</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Commercial (Disewakan/Dikaryakan)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/vehicle_model_desc__c.field-meta.xml
<CustomField>
    <fullName>vehicle_model_desc__c</fullName>
    <label>vehicle model desc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Sedan</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Jeep</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Minibus</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Box</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Pick Up</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Station Wagon</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Double Cabin</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Bus</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Truck</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Heavy Equipment</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Sepeda Motor</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Truck - Tangki</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Year_of_Manufacture__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Manufacture__c</fullName>
    <label>Year of Manufacture</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Code</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Assets (Zip Code)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <label>Risk</label>
</RecordType>

force-app/main/default/objects/InsurancePolicyCoverage/fields/amount_insured__c.field-meta.xml
<CustomField>
    <fullName>amount_insured__c</fullName>
    <label>amount insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Locations (Kabupaten)</relationshipLabel>
    <relationshipName>Locations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Locations (Country)</relationshipLabel>
    <relationshipName>Locations5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Zip Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Locations (Zip Code)</relationshipLabel>
    <relationshipName>Locations4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/Master_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c/fields/ADDRESS__c.field-meta.xml
<CustomField>
    <fullName>ADDRESS__c</fullName>
    <label>ADDRESS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Occupation_Code__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Code__c</fullName>
    <label>Occupation Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Occupy_Id__c.field-meta.xml
<CustomField>
    <fullName>Occupy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Occupy Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/TYPE__c.field-meta.xml
<CustomField>
    <fullName>TYPE__c</fullName>
    <label>TYPE</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/ZIP_CODE__c.field-meta.xml
<CustomField>
    <fullName>ZIP_CODE__c</fullName>
    <label>ZIP CODE</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <label>COB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Occupation_Code__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Code__c</fullName>
    <label>Occupation Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Administration_Cost__c.field-meta.xml
<CustomField>
    <fullName>Administration_Cost__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Administration Cost</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Quotes (Administration Cost)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <formula>TEXT(Risk_Name__r.Class__c)</formula>
    <label>Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stamp Duty</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Utilization__c.field-meta.xml
<CustomField>
    <fullName>Utilization__c</fullName>
    <formula>TEXT(Risk_Name__r.Utilization__c)</formula>
    <label>Utilization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <formula>Risk_Name__r.Zip_Code__c</formula>
    <label>Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Aswata_QuotationSlip_Controller.cls
/**
 * @description       : For Generate PDF Quotation Slip
 * @author            : Ahmad Yazid Munif
 * @last modified on  : 11-23-2025
 * @last modified by  : Ahmad Yazid Munif
**/
public without sharing class Aswata_QuotationSlip_Controller {
    /** @description multiRisk */
    public Boolean multiRisk { get; private set; }
    /** @description quoteRecord */
    public Quote quoteRecord { get; private set; }
    /** @description shouldRedirect */
    // public Boolean shouldRedirect { get; private set; }
    /** @description quotationDetails Multi*/
    public List<Aswata_QuotationSlip_Wrapper.QuotationWrapper301> quotationDetails { get; set; }
    /** @description quotationDetail Single */
    public Aswata_QuotationSlip_Wrapper.QuotationWrapper301 quotationDetailSingle {get;set;}
    /** @description totalPertanggungan */
    // public Decimal totalPertanggungan { get; private set; }
    /** @description risk */
    // public Asset risk { get; private set; }
    /**
     * @description function constructor
     */
    public Aswata_QuotationSlip_Controller() {
        Id quoteId = ApexPages.currentPage().getParameters().get('id');
        if (quoteId != null) {
            this.quoteRecord = [
                SELECT OpportunityId, Administration_Cost__c, Stamp_Duty__c, Opportunity.COB__c
                FROM Quote
                WHERE Id = :quoteId
                WITH SECURITY_ENFORCED LIMIT 1
            ];
        }
        generateQuotation301();
    }
    /**
     * @description function for generate PDF Quote COB 301
     */
    public void generateQuotation301(){
        quotationDetails = new List<Aswata_QuotationSlip_Wrapper.QuotationWrapper301>();
        quotationDetailSingle = new Aswata_QuotationSlip_Wrapper.QuotationWrapper301();
        String opptyId = this.quoteRecord.OpportunityId;
        // opptyId = '006MS000007owG7YAI';
        if (opptyId == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Quote tidak memiliki Opportunity.'));
            return;
        }
        Aswata_QuotationSlip_Wrapper.TrxOpptyWrapper getOpportunity = Aswata_QuotationSlip_DataHandler.getOpportunityQuote(opptyId);
        quotationDetailSingle.opportunityData = getOpportunity.opp;
        quotationDetailSingle.monthsDiff = getOpportunity.monthsDifference;
        quotationDetailSingle.qqName = getOpportunity.qqName;
        quotationDetailSingle.trxDataList = getOpportunity.trxDataList;
        quotationDetailSingle.insuredName = getOpportunity.insuredName;
        quotationDetailSingle.insuredAddress = getOpportunity.insuredAddress;
        List<Asset> assetOppty = Aswata_QuotationSlip_DataHandler.queryRiskOppty(opptyId);
        // List<Asset> assetOppty = [
        //     SELECT Id, Name, Address__c, Amount__c,
        //     Occupation_Code__r.Occupy_Id__c,
        //     Address__r.Name,
        //     Address__r.City__r.Name,
        //     Address__r.Country__r.Name,
        //     Address__r.Zip_Code__r.name,
        //     Total_Premi_Amount__c, Class__c, Occupation_Description__c,Type__c, Amount_Insured__c,
        //     Rate_All_Coverages__c,
        //     Opportunity__c, License_Plate_Number__c,
        //     vehicle_model_desc__c, Year_of_Manufacture__c,
        //     Color__c,  Engine_No__c, Chasis_No__c, Vehicle_Type__c,
        //     jenis_perlengkapan__c, Utilization__c
        //     FROM Asset
        //     WHERE Id = '02iMS000000Q7nVYAS'
        // ];
        // System.debug('### AWT quotation Risk Single'+assetOppty);
        if (assetOppty.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Quote tidak memiliki Opportunity.'));
            return;
        }
        if(assetOppty.size()>1){
            handleMultiRiskQuote(assetOppty);
        }else{
            handleSingleRiskQuote(assetOppty);
        }
    }
    /**
     * @description function for get picklist label and value
     * @return Map<String,String>
     */
    public static Map<String, String> getPicklistLabel(){
        Map<String, String> valueToLabelMap = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = Asset.Vehicle_Type__c.getDescribe();
        for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
            valueToLabelMap.put(entry.getValue(), entry.getLabel());
        }
        return valueToLabelMap;
    }
    /**
     * @description function for generate PDF Quote Multi Risk
     * @param assetOppty
     */
    public void handleMultiRiskQuote(List<Asset> assetOppty){
        // Map<String, String> valueToLabelMap = getPicklistLabel();
        this.multiRisk = true;
        quotationDetails.add(new Aswata_QuotationSlip_Wrapper.QuotationWrapper301());
    }
    /**
     * @description function for generate PDF Quote Multi Risk
     * @param assetOppty
     */
    public void handleSingleRiskQuote(List<Asset> assetOppty){
        Map<String, String> valueToLabelMap = getPicklistLabel();
        this.multiRisk = false;
        Asset risk = assetOppty[0];
        quotationDetailSingle.risk = risk;
        //
        List<Aswata_QuotationSlip_Wrapper.DetailAsset> listDetailAsset =Aswata_QuotationSlip_DataHandler.getListDetailAsset(assetOppty);
        quotationDetailSingle.platNomorPolisi = risk.License_Plate_Number__c;
        quotationDetailSingle.merkTypeKendaraan = risk.vehicle_model_desc__c+' / '+risk.Year_of_Manufacture__c+' / '+risk.Color__c;
        quotationDetailSingle.noMesinRangkaKendaraan = risk.Engine_No__c+' / '+risk.Chasis_No__c;
        quotationDetailSingle.jenisKendaraan = valueToLabelMap.get(risk.Vehicle_Type__c);
        if(risk.Utilization__c == 'P'){
            quotationDetailSingle.tipePenggunaan = 'Pribadi';
        }else{
            quotationDetailSingle.tipePenggunaan = 'Dinas';
        }
        quotationDetailSingle.detailAsset = listDetailAsset;
        // Perlengkapan Tambahan
        List<Aswata_QuotationSlip_Wrapper.PerlengkapanTambahan> listTambahan = new List<Aswata_QuotationSlip_Wrapper.PerlengkapanTambahan>();
        if(risk.jenis_perlengkapan__c!=null){
            List<Object> rawList = (List<Object>) JSON.deserializeUntyped(risk.jenis_perlengkapan__c);
            if (!rawList.isEmpty()) {
                for (Object rawItem : rawList) {
                    Map<String, Object> itemMap = (Map<String, Object>) rawItem;
                    Aswata_QuotationSlip_Wrapper.PerlengkapanTambahan wrapper = new Aswata_QuotationSlip_Wrapper.PerlengkapanTambahan();
                    wrapper.merk = (String) itemMap.get('merk');
                    wrapper.value = (Integer) itemMap.get('value');
                    wrapper.curId = (String) itemMap.get('cur_id');
                    listTambahan.add(wrapper);
                }
            }
        }
        quotationDetailSingle.perlengkapan = listTambahan;
        // Kondisi Pertanggungan
        quotationDetailSingle.uraianPertanggungan = risk.Name;
        Decimal amountPertanggungTemp = 0;
        if(risk.Amount__c!=null){
            amountPertanggungTemp = risk.Amount__c;
        }
        quotationDetailSingle.amountPertanggungan = amountPertanggungTemp;
        quotationDetailSingle.amountInsured = risk.Amount_Insured__c;
        // --- Query InsurancePolicyCoverage ---
        Aswata_QuotationSlip_Wrapper.QuotationWrapper calcTotalPremi = Aswata_QuotationSlip_DataHandler.getTotalPremi(risk,quoteRecord,assetOppty);
        quotationDetailSingle.policyCoverage = calcTotalPremi.policyCoverage;
        quotationDetailSingle.totalAllRate = calcTotalPremi.totalAllRate;
        quotationDetailSingle.premiNonStockCalculated = calcTotalPremi.premiNonStockCalculated;
        quotationDetailSingle.stampDuty = calcTotalPremi.stampDuty;
        quotationDetailSingle.adminCost = calcTotalPremi.adminCost;
        quotationDetailSingle.totalPremi = calcTotalPremi.totalPremi;
        quotationDetailSingle.nominalTerbilang = calcTotalPremi.nominalTerbilang;
    }
}