force-app/main/default/objects/Asset/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>amount asset</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Amount_IDR__c.field-meta.xml
<CustomField>
    <fullName>Amount_IDR__c</fullName>
    <label>Amount IDR(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Amount_Insured__c.field-meta.xml
<CustomField>
    <fullName>Amount_Insured__c</fullName>
    <description>amount dari risk</description>
    <label>Amount Insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master_Data__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Asset Category</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Risks (Category)</relationshipLabel>
    <relationshipName>Risks3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Category_ID__c</fullName>
    <label>Category ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <formula>Text(Opportunity__r.COB__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Currency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master_Data__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Exchange Rate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Risks (Currency)</relationshipLabel>
    <relationshipName>Risks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Declare_Value__c.field-meta.xml
<CustomField>
    <fullName>Declare_Value__c</fullName>
    <label>Declare Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Indemnity_Type__c.field-meta.xml
<CustomField>
    <fullName>Indemnity_Type__c</fullName>
    <label>Indemnity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sum Insured</fullName>
            </value>
            <value>
                <fullName>New Reinstatement Value</fullName>
            </value>
            <value>
                <fullName>Replacement Value</fullName>
            </value>
            <value>
                <fullName>Sub-Limit</fullName>
            </value>
            <value>
                <fullName>First Loss</fullName>
            </value>
            <value>
                <fullName>Lost Limit</fullName>
            </value>
            <value>
                <fullName>Loss Limit - any one claim</fullName>
            </value>
            <value>
                <fullName>Loss Limit - aggregate any one claim</fullName>
            </value>
            <value>
                <fullName>Loss Limit - aggregate during period</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Insurance_Policy__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Policy</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Interest_Insured_Detail_Description__c.field-meta.xml
<CustomField>
    <fullName>Interest_Insured_Detail_Description__c</fullName>
    <label>Interest Insured Detail Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/risk_detail_id__c.field-meta.xml
<CustomField>
    <fullName>risk_detail_id__c</fullName>
    <label>risk detail id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master_Data__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Asset Section</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Risks (Section)</relationshipLabel>
    <relationshipName>Risks2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Section_ID__c.field-meta.xml
<CustomField>
    <fullName>Section_ID__c</fullName>
    <label>Section ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <label>Risk</label>
</RecordType>

force-app/main/default/objects/InsurancePolicyCoverage/fields/amount_insured__c.field-meta.xml
<CustomField>
    <fullName>amount_insured__c</fullName>
    <label>amount insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency buat COB301 dari data Asset</description>
    <label>Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Indemnity_Type__c.field-meta.xml
<CustomField>
    <fullName>Indemnity_Type__c</fullName>
    <label>Indemnity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
                <label>Sum Insured</label>
            </value>
            <value>
                <fullName>LL</fullName>
                <label>Loss Limit</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>First Loss</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible Currency Section 4</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Insurance Policy Coverages (Deductible Currency Section 4)</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/Master_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c/fields/Asset_Section__c.field-meta.xml
<CustomField>
    <fullName>Asset_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Section</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Master Data (Asset Section)</relationshipLabel>
    <relationshipName>Master_Data6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/BSN__c.field-meta.xml
<CustomField>
    <fullName>BSN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BSN</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Master Data</relationshipLabel>
    <relationshipName>Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/BSN_ID__c.field-meta.xml
<CustomField>
    <fullName>BSN_ID__c</fullName>
    <label>BSN ID</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Lookup_Object__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Object__c</fullName>
    <label>Lookup Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Section_Title__c.field-meta.xml
<CustomField>
    <fullName>Section_Title__c</fullName>
    <label>Section Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/showData__c.field-meta.xml
<CustomField>
    <fullName>showData__c</fullName>
    <label>showData</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Asset_Section__c.field-meta.xml
<CustomField>
    <fullName>Asset_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Section</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Products (Asset Section)</relationshipLabel>
    <relationshipName>Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Aswata_Add_New_DetailAsset_Controller.cls
/**
 * @description       : Controller for LWC Detail Asset
 * @author            : Ahmad Yazid Munif
 * @last modified on  : 12-18-2025
 * @last modified by  : Ahmad Yazid Munif
**/
public with sharing class Aswata_Add_New_DetailAsset_Controller {
    private static final String MASTER_DATA_OBJECT_API = 'Master_Data__c';
    private static final String DETAIL_ASSET_NAME = 'Detail Asset';
    private static final String RECORD_TYPE_NAME = 'Asset';
    /**
     * @description function for save data asset
     * @param formData contains data from LWC
     * @return String Id asset
     */
    @AuraEnabled
    public static String saveDetailAsset(Map<String, Object> formData) {
        if (formData == null || formData.isEmpty()) {
            throw new AuraHandledException('No data provided to save.');
        }
        String recordId = (formData.containsKey('Id')) ? (String)formData.get('Id') : null;
        Boolean isUpdate = (recordId != null && recordId != '');
        // Get Record Type (if needed for new record) and Asset
        Asset record = initializeAssetRecord(formData, isUpdate);
        // Map fields from formData
        record = mapFormDataToAsset(formData, record);
        // InsertorUpdate Asset
        return performDML(record, isUpdate);
    }
    /**
     * @description to get AssetRecord is Existing/New
     * @param formData = data Map
     * @param isUpdate = boolean
     * @return Asset object
     */
    private static Asset initializeAssetRecord(Map<String, Object> formData, Boolean isUpdate) {
        if (isUpdate) {
            return [SELECT Id,Opportunity__c FROM Asset WHERE Id = :(String)formData.get('Id') WITH SECURITY_ENFORCED LIMIT 1];
        } else {
            RecordType rt = [
                SELECT Id
                FROM RecordType
                WHERE SobjectType = :RECORD_TYPE_NAME
                AND Name = :RECORD_TYPE_NAME
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            Asset newRecord = new Asset();
            newRecord.put('RecordTypeId', rt.Id);
            return newRecord;
        }
    }
    /**
     * @description to generate record Asset
     * @param formData = data Map
     * @param record = Asset record will be update
     * @return Asset object
     */
    private static Asset mapFormDataToAsset(Map<String, Object> formData, Asset record) {
        // Asset updateData = record;
        Set<String> numericFields = new Set<String>{
            'Exchange_Rate__c', 'Amount__c', 'Amount_IDR__c', 'Declare_Value__c', 'Amount_Insured__c'
        };

        for (String fieldApi : formData.keySet()) {
            if (fieldApi == 'Id') {
                continue;
            }
            Object value = formData.get(fieldApi);
            if (value == null && fieldApi != 'Declare_Value__c') {
                continue;
            }
            try {
                if (numericFields.contains(fieldApi) && value instanceof String) {
                    // Handle numeric conversion for String values
                    record.put(fieldApi, Decimal.valueOf((String)value));
                } else {
                    record.put(fieldApi, value);
                }
            } catch (Exception e) {
                throw new AuraHandledException('Failed to set field: ' + fieldApi + ': ' + e.getMessage()); // NCSS: 11
            }
        }
        return record;
    }
    /**
     * @description to perform DML Insert or Update data Asset
     * @param record = Asset record will be update
     * @param isUpdate = boolean
     * @return String Id Asset
     */
    private static String performDML(Asset record, Boolean isUpdate) {
        // if (!Schema.sObjectType.Asset.isAccessible()
        //     && !Schema.sObjectType.Asset.isUpdateable()
        //     && !Schema.sObjectType.Asset.isCreateable()){
        //     throw new SecurityException('Insufficient permissions to access or modify Asset record.');
        // }
        if (!checkPermission()) {
            throw new SecurityException('Insufficient permissions to access or modify Asset record.');
        }
        try {
            if (isUpdate) {
                Database.update(record, AccessLevel.USER_MODE);
            } else {
                Decimal newRiskNumber = 1;
                if(record.Opportunity__c != null){
                    // System.debug('record.Opportunity__c'+record.Opportunity__c);
                    String policyId = Aswata_GlobalFunction.createInsurancePolicy(record.Opportunity__c);
                    List<Asset> latestAssetList = [
                        SELECT risk_detail_id__c
                        FROM Asset WHERE Opportunity__c = :record.Opportunity__c
                        AND risk_detail_id__c != null
                        WITH SECURITY_ENFORCED
                        ORDER BY risk_detail_id__c DESC LIMIT 1
                    ];
                    if (!latestAssetList.isEmpty()) {
                        Asset latestAsset = latestAssetList[0];
                        newRiskNumber = latestAsset.risk_detail_id__c + 1;
                    }
                    record.insurance_policy__c = policyId;
                }
                record.risk_detail_id__c = newRiskNumber;
                Database.insert(record, AccessLevel.USER_MODE);
            }
            return record.Id;
        } catch (Exception e) {
            // System.debug('An unexpected error occurred during save: ' + e.getMessage());
            throw new AuraHandledException('An unexpected error occurred during save: ' + e.getMessage());
        }
    }
    /**
     * @description get section based on title and COB
     * @param titleValue = Title Section
     * @param cobValue = COB
     * @return List<String> return list section
     */
    @AuraEnabled(cacheable=true)
    public static List<String> getSections(String titleValue,String cobValue) {
        RecordType rtSection = [
            SELECT Id FROM RecordType
            WHERE SobjectType = 'Master_Data__c' AND Name = 'Asset Section'
            WITH SECURITY_ENFORCED LIMIT 1
        ];
        Set<String> results = new Set<String>();
        List<Master_Data__c> configs = [
            SELECT
            Name, Section__c, BSN__c,
            Asset_Section__c, Asset_Section__r.Section__c, Section_Title__c, RecordType.Name
            FROM Master_Data__c
            WHERE BSN__r.ProductCode = :cobValue AND Name  = :titleValue
            AND RecordTypeId = :rtSection.Id
            WITH SECURITY_ENFORCED
        ];
        for (Master_Data__c master : configs) {
            if (master.Section__c != null) {
                results.add(String.valueOf(master.Section__c));
            }
        }
        List<String> uniqueNamesList = new List<String>(results);
        return uniqueNamesList;
    }
    /**
     * @description get ActiveField for Dynamic Custom UI
     * @param cobValue
     * @return List<DynamicFieldConfig> return object
     */
    @AuraEnabled(cacheable=true)
    public static List<DynamicFieldConfig> getActiveFields(String cobValue) {
        // RecordType SB : 012MS000000DSMfYAO
        RecordType recordType = [SELECT Id, Name FROM RecordType where SobjectType = :MASTER_DATA_OBJECT_API and Name = :DETAIL_ASSET_NAME WITH SECURITY_ENFORCED LIMIT 1];
        List<DynamicFieldConfig> results = new List<DynamicFieldConfig>();
        List<Master_Data__c> configs = [
            SELECT Name,Section__c,BSN_ID__c , Label__c, Data_Type__c, Lookup_Object__c, Filter__c,
                   Status__c, Object__c, Order__c, showData__c
            FROM Master_Data__c
            WHERE Status__c = 'Active'AND RecordTypeId = :recordType.Id
            AND BSN_ID__c = :cobValue
            WITH SECURITY_ENFORCED
            ORDER BY Order__c ASC
        ];
        for (Master_Data__c cfg : configs) {
            DynamicFieldConfig dcf = new DynamicFieldConfig();
            dcf.apiName = cfg.Name;
            dcf.section = cfg.Section__c;
            dcf.label = cfg.Label__c;
            dcf.dataType = cfg.Data_Type__c;
            dcf.lookupObject = cfg.Lookup_Object__c;
            dcf.filter = cfg.Filter__c;
            dcf.showData = cfg.showData__c;
            results.add(dcf);
        }
        return results;
    }
    /**
     * @description Class for dynamicFieldConfig
     */
    public class DynamicFieldConfig {
        /**
         * @description ApiName
         */
        @AuraEnabled public String apiName {get;set;}
        /**
         * @description Section
         */
        @AuraEnabled public Decimal section {get;set;}
        /**
         * @description Label
         */
        @AuraEnabled public String label {get;set;}
        /**
         * @description dataType
         */
        @AuraEnabled public String dataType {get;set;}
        /**
         * @description lookupObject
         */
        @AuraEnabled public String lookupObject {get;set;}
        /**
         * @description filter
         */
        @AuraEnabled public String filter {get;set;}
        /**
         * @description showData
         */
        @AuraEnabled public String showData {get;set;}
    }

    /**
     * @description function for get detail asset
     * @param detailAssetId id of asset
     * @return Map<String, Object>
     */
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getDetailAssetData(String detailAssetId) {
        if (detailAssetId == null) {
            return new Map<String, Object>();
        }
        Asset detailAsset = [
            SELECT Id,
                Name,
                Currency__c,
                Exchange_Rate__c,
                Amount__c,
                Amount_IDR__c,
                Category_ID__c,
                Section_ID__c,
                Interest_Insured_Detail_Description__c,
                Declare_Value__c,
                Indemnity_Type__c,
                Amount_Insured__c,
                ParentId,
                Parent.COB__c,
                Category__c,
                Section__c,
                Section__r.Name,
                Section__r.Section__c,
                Section__r.Section_Title__c
            FROM Asset
            WHERE Id = :detailAssetId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        // Convert the Asset record into a map for easy use in LWC
        Map<String, Object> result = new Map<String, Object>();
        result.put('Id', detailAsset.Id);
        result.put('Name', detailAsset.Name);
        result.put('Currency__c', detailAsset.Currency__c);
        result.put('Exchange_Rate__c', detailAsset.Exchange_Rate__c);
        result.put('Amount__c', detailAsset.Amount__c);
        result.put('Amount_IDR__c', detailAsset.Amount_IDR__c);
        result.put('Category_ID__c', detailAsset.Category_ID__c);
        result.put('Section_ID__c', detailAsset.Section_ID__c);
        result.put('Interest_Insured_Detail_Description__c', detailAsset.Interest_Insured_Detail_Description__c);
        result.put('Declare_Value__c', detailAsset.Declare_Value__c);
        result.put('Indemnity_Type__c', detailAsset.Indemnity_Type__c);
        result.put('Amount_Insured__c', detailAsset.Amount_Insured__c);
        result.put('Parent_Asset__c', detailAsset.ParentId);
        result.put('COB__c', detailAsset.Parent.COB__c);
        result.put('Category__c', detailAsset.Category__c);
        result.put('Section__c', detailAsset.Section__c);
        result.put('Section_Name__c', detailAsset.Section__r.Name);
        return result;
    }

    /**
     * @description Get all detail assets for a specific Risk
     * @param riskId Id of the parent Risk record
     * @return List<Asset> List of detail assets under this Risk
     */
    @AuraEnabled(cacheable=false)
    public static List<Asset> getDetailAssetsByRisk(Id riskId) {
        try {
            if (riskId == null) {
                return new List<Asset>();
            }

            List<Asset> assets = [
                SELECT 
                    Id, 
                    Name, 
                    Interest_Insured_Detail_Description__c,
                    Section__c,
                    Section__r.Name,
                    Category__c,
                    Category__r.Name,
                    Amount_IDR__c,
                    Amount__c,
                    Currency__c,
                    Exchange_Rate__c,
                    Indemnity_Type__c,
                    Declare_Value__c,
                    Amount_Insured__c,
                    CreatedDate
                FROM Asset 
                WHERE ParentId = :riskId
                AND RecordType.Name = 'Asset'
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC
            ];
            
            System.debug('✅ Found ' + assets.size() + ' assets for Risk: ' + riskId);
            return assets;
            
        } catch (Exception e) {
            System.debug('❌ Error loading assets: ' + e.getMessage());
            throw new AuraHandledException('Error loading assets: ' + e.getMessage());
        }
    }

    /**
     * @description function for checkPermission Access
     * @return boolean accessible
     */
    public static Boolean checkPermission(){
        Boolean access = true;
        if (!Schema.sObjectType.RecordType.isAccessible() &&
            !Schema.sObjectType.Asset.isAccessible() &&
            !Schema.sObjectType.Master_Data__c.isAccessible() &&
            !Schema.sObjectType.InsurancePolicyCoverage.isCreateable() &&
            !Schema.sObjectType.Asset.isUpdateable()
        ){
            access = false;
        }
        return access;
    }
}