force-app/main/default/objects/Asset/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>amount asset</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Amount_Insured__c.field-meta.xml
<CustomField>
    <fullName>Amount_Insured__c</fullName>
    <description>amount dari risk</description>
    <label>Amount Insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Busreq_ID__c.field-meta.xml
<CustomField>
    <fullName>Busreq_ID__c</fullName>
    <formula>Opportunity__r.Busreq_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Busreq ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <formula>Text(Opportunity__r.COB__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/jenis_perlengkapan__c.field-meta.xml
<CustomField>
    <fullName>jenis_perlengkapan__c</fullName>
    <label>jenis perlengkapan</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Risk_ID__c.field-meta.xml
<CustomField>
    <fullName>Risk_ID__c</fullName>
    <label>Risk ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Total_Premi_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Premi_Amount__c</fullName>
    <label>Total Premi Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <label>Risk</label>
</RecordType>

force-app/main/default/objects/InsurancePolicy/fields/BUSREQ_ID__c.field-meta.xml
<CustomField>
    <fullName>BUSREQ_ID__c</fullName>
    <externalId>true</externalId>
    <label>BUSREQ_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <label>COB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/amount_insured__c.field-meta.xml
<CustomField>
    <fullName>amount_insured__c</fullName>
    <label>amount insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Final_Approved_Rate__c.field-meta.xml
<CustomField>
    <fullName>Final_Approved_Rate__c</fullName>
    <label>Final Approved Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Proposed_Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Fixed_Amount__c</fullName>
    <label>Proposed Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Risk_ID__c.field-meta.xml
<CustomField>
    <fullName>Risk_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Risk</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Busreq_ID__c.field-meta.xml
<CustomField>
    <fullName>Busreq_ID__c</fullName>
    <externalId>true</externalId>
    <label>Busreq ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <label>COB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date_Periode__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Periode__c</fullName>
    <label>End Date Periode</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date_Periode__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Periode__c</fullName>
    <label>Start Date Periode</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/The_Insured_Address__c.field-meta.xml
<CustomField>
    <fullName>The_Insured_Address__c</fullName>
    <label>The Insured Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/The_Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>The_Insured_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>The Insured Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (The Insured Name)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <label>Warranty</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Administration_Cost__c.field-meta.xml
<CustomField>
    <fullName>Administration_Cost__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Administration Cost</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Quotes (Administration Cost)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stamp Duty</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/The_Insured_Address__c.field-meta.xml
<CustomField>
    <fullName>The_Insured_Address__c</fullName>
    <label>The Insured Address</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/The_Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>The_Insured_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>The Insured Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Data__c/Transaction_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Transaction Data</label>
    <nameField>
        <label>Transaction Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Data__c/fields/Administration_Cost__c.field-meta.xml
<CustomField>
    <fullName>Administration_Cost__c</fullName>
    <label>Administration Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Data__c/fields/BUSREQ_ID__c.field-meta.xml
<CustomField>
    <fullName>BUSREQ_ID__c</fullName>
    <label>BUSREQ_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Data__c/fields/Clause_Description__c.field-meta.xml
<CustomField>
    <fullName>Clause_Description__c</fullName>
    <label>Clause Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction_Data__c/fields/Clauses_Name__c.field-meta.xml
<CustomField>
    <fullName>Clauses_Name__c</fullName>
    <label>Clauses Name</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction_Data__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions Data</relationshipLabel>
    <relationshipName>Transactions_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Data__c/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Data__c/recordTypes/Clause.recordType-meta.xml
<RecordType>
    <fullName>Clause</fullName>
    <active>true</active>
    <label>Clause</label>
</RecordType>

force-app/main/default/classes/Aswata_QuotationSlip_Test.cls
/**
 * @description       : Test Class PDF Quotation
 * @author            : Ahmad Yazid Munif
 * @last modified on  : 12-02-2025
 * @last modified by  : Ahmad Yazid Munif
**/
@IsTest
private class Aswata_QuotationSlip_Test {
    @TestSetup
    static void makeData() {
        Account acc = new Account(Name = 'Jhon');
        insert acc;
        Opportunity opp201 = new Opportunity(
            Name = 'Test Opp 201',
            Busreq_ID__c = '201201',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            The_Insured_Name__c = acc.Id,
            COB__c = '201',
            The_Insured_Address__c = 'Jl. Test 123',
            Start_Date_Periode__c = Date.today(),
            End_Date_Periode__c = Date.today().addYears(1),
            Warranty__c = 'waranty'
        );
        insert opp201;
        Opportunity opp301 = new Opportunity(
            Name = 'Test Opp 301',
            Busreq_ID__c = '301001',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            The_Insured_Name__c = acc.Id,
            COB__c = '301',
            The_Insured_Address__c = 'Jl. Test 456',
            Start_Date_Periode__c = Date.today(),
            End_Date_Periode__c = Date.today().addYears(1),
            Warranty__c = 'waranty'
        );
        insert opp301;
        Opportunity opp201Multi = new Opportunity(
            Name = 'Test Opp 201 Multi',
            Busreq_ID__c = '201202',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            The_Insured_Name__c = acc.Id,
            COB__c = '201',
            The_Insured_Address__c = 'Jl. Test 123',
            Start_Date_Periode__c = Date.today(),
            End_Date_Periode__c = Date.today().addYears(1),
            Warranty__c = 'waranty'
        );
        insert opp201Multi;
        Opportunity opp301Multi = new Opportunity(
            Name = 'Test Opp 301 Multi',
            Busreq_ID__c = '301002',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            The_Insured_Name__c = acc.Id,
            COB__c = '301',
            The_Insured_Address__c = 'Jl. Test 456',
            Start_Date_Periode__c = Date.today(),
            End_Date_Periode__c = Date.today().addYears(1),
            Warranty__c = 'waranty'
        );
        insert opp301Multi;
        InsurancePolicy policy = new InsurancePolicy(
            Name = 'Test Policy',
            NameInsuredId = acc.Id
        );
        insert policy;
        List<Quote> listQuote = new List<Quote>();
        listQuote.add(new Quote(
            Name = 'Quote 201',
            OpportunityId = opp201.Id,
            Administration_Cost__c = 2000,
            Stamp_Duty__c = 5000
        ));
        listQuote.add(new Quote(
            Name = 'Quote 201 Multi',
            OpportunityId = opp201Multi.Id,
            Administration_Cost__c = 2000,
            Stamp_Duty__c = 5000
        ));
        listQuote.add(new Quote(
            Name = 'Quote 301',
            OpportunityId = opp301.Id,
            Administration_Cost__c = 2000,
            Stamp_Duty__c = 5000
        ));
        listQuote.add(new Quote(
            Name = 'Quote 301 Multi',
            OpportunityId = opp301Multi.Id,
            Administration_Cost__c = 2000,
            Stamp_Duty__c = 5000
        ));
        insert listQuote;
        RecordType rtRisk = [SELECT Id FROM RecordType WHERE SobjectType = 'Asset' AND Name = 'RIsk' LIMIT 1];
        Asset risk201 = new Asset(
            Name = 'Test Risk',
            Opportunity__c = opp201.Id,
            Total_Premi_Amount__c = 5000000,
            Amount_Insured__c = 5000000,
            RecordTypeId = rtRisk.Id
        );
        insert risk201;
        Asset risk201Multi = new Asset(
            Name = 'Test Risk Multi',
            Opportunity__c = opp201Multi.Id,
            Total_Premi_Amount__c = 5000000,
            Amount__c = 5000000,
            RecordTypeId = rtRisk.Id
        );
        insert risk201Multi;
        Asset risk201Multi2 = new Asset(
            Name = 'Test Risk Multi 2',
            Opportunity__c = opp201Multi.Id,
            Total_Premi_Amount__c = 5000000,
            Amount__c = 5000000,
            RecordTypeId = rtRisk.Id
        );
        insert risk201Multi2;
        Asset risk301 = new Asset(
            Name = 'Test Risk',
            Opportunity__c = opp301.Id,
            Total_Premi_Amount__c = 5000000,
            Amount__c = 5000000,
            jenis_perlengkapan__c = '[{"merk":"test","value":300000,"cur_id":"IDR"},{"merk":"test2","value":40000,"cur_id":"IDR"}]',
            RecordTypeId = rtRisk.Id
        );
        insert risk301;
        Asset risk301Multi = new Asset(
            Name = 'Test Risk Multi',
            Opportunity__c = opp301Multi.Id,
            Total_Premi_Amount__c = 5000000,
            Amount__c = 5000000,
            RecordTypeId = rtRisk.Id
        );
        insert risk301Multi;
        Asset risk301Multi2 = new Asset(
            Name = 'Test Risk Multi 2',
            Opportunity__c = opp301Multi.Id,
            Total_Premi_Amount__c = 5000000,
            Amount__c = 5000000,
            RecordTypeId = rtRisk.Id
        );
        insert risk301Multi2;

        List<InsurancePolicyCoverage> listCoverage = new List<InsurancePolicyCoverage>();
        listCoverage.add(new InsurancePolicyCoverage(
            InsurancePolicyId = policy.Id,
            Risk_ID__c = risk201.Id,
            CoverageName = 'Coverage 1',
            Proposed_Fixed_Amount__c = 1000000,
            Final_Approved_Rate__c = 2.0
        ));
        listCoverage.add(new InsurancePolicyCoverage(
            InsurancePolicyId = policy.Id,
            Risk_ID__c = risk201Multi.Id,
            CoverageName = 'Coverage 2',
            Proposed_Fixed_Amount__c = 1000000,
            Final_Approved_Rate__c = 2.0
        ));
        listCoverage.add(new InsurancePolicyCoverage(
            InsurancePolicyId = policy.Id,
            Risk_ID__c = risk301.Id,
            CoverageName = 'Coverage 3',
            Proposed_Fixed_Amount__c = 1000000,
            Final_Approved_Rate__c = 2.0
        ));
        listCoverage.add(new InsurancePolicyCoverage(
            InsurancePolicyId = policy.Id,
            Risk_ID__c = risk301Multi.Id,
            CoverageName = 'Coverage 2',
            Proposed_Fixed_Amount__c = 2000000,
            Final_Approved_Rate__c = 2.5
        ));
        insert listCoverage;
        List<Transaction_Data__c> listTrxData = new List<Transaction_Data__c>();
        listTrxData.add(new Transaction_Data__c(
            Opportunity__c = opp201.Id,
            Clauses_Name__c = 'Clause A',
            Clause_Description__c = 'Desc A'
        ));
        listTrxData.add(new Transaction_Data__c(
            Opportunity__c = opp301.Id,
            Clauses_Name__c = '',
            Clause_Description__c = 'Blank'
        ));
        // listTrxData.add(new Transaction_Data__c(
        //     Opportunity__c = opp.Id,
        //     Clauses_Name__c = '-',
        //     Clause_Description__c = 'Dash'
        // ));
        insert listTrxData;
    }
    @IsTest
    static void testCob201SingleRisk() {
        User adminUser = createUser();
        Quote testQuote = [SELECT Id FROM Quote WHERE Name = 'Quote 201' LIMIT 1];
        QuotationVFPController controller;
        PageReference resultPage;
        Test.startTest();
        System.runAs(adminUser) {
            PageReference pageRef = Page.quotation;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', testQuote.Id);
            controller = new QuotationVFPController();
            controller.redirectToPdf();
            Aswata_QuotationSlip_Terbilang.terbilangRupiah(5123451711L);
            Aswata_QuotationSlip_Terbilang.terbilangRupiah(null);
            Aswata_QuotationSlip_Terbilang.terbilangRupiah(0);
            Aswata_QuotationSlip_Terbilang.terbilangRupiah(1000);
            Aswata_QuotationSlip_Terbilang.terbilangRupiah(117300);
        }
        Test.stopTest();
        System.assertNotEquals(null, controller.quoteRecord, 'Quote Record seharusnya berhasil di-query di konstruktor.');
        System.assertEquals(null, resultPage, 'Seharusnya tetap dipage ini.');
    }
    @IsTest
    static void testCob201MultiRisk() {
        User adminUser = createUser();
        Quote testQuote = [SELECT Id FROM Quote WHERE Name = 'Quote 201 Multi' LIMIT 1];
        QuotationVFPController controller;
        PageReference resultPage;
        Test.startTest();
        System.runAs(adminUser) {
            PageReference pageRef = Page.quotation;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', testQuote.Id);
            controller = new QuotationVFPController();
            controller.redirectToPdf();
            Aswata_QuotationSlip_Wrapper.CoverageRate deductible = new Aswata_QuotationSlip_Wrapper.CoverageRate();
            deductible.riskId = '1';
            deductible.coverageName = 'coverageName';
            deductible.premiFixedAmount = 5000;
            deductible.deductibleAmountPct = 5;
            deductible.totalPremi = 500;
        }
        Test.stopTest();
        System.assertNotEquals(null, controller.quoteRecord, 'Quote Record seharusnya berhasil di-query di konstruktor.');
        System.assertEquals(null, resultPage, 'Seharusnya tetap dipage ini.');
    }
    @IsTest
    static void testCob301Redirect() {
        User adminUser = createUser();
        Quote testQuote = [SELECT OpportunityId, Administration_Cost__c, Stamp_Duty__c, Opportunity.COB__c FROM Quote WHERE Name = 'Quote 301' LIMIT 1];
        QuotationVFPController controller;
        PageReference resultPage;
        Test.startTest();
        System.runAs(adminUser) {
            PageReference pageRef = Page.quotation;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', testQuote.Id);
            controller = new QuotationVFPController();
            controller.redirectToPdf();
        }
        Test.stopTest();
        System.assertNotEquals(null, controller.quoteRecord, 'Quote Record seharusnya berhasil di-query di konstruktor.');
        System.assertEquals(null, resultPage, 'Seharusnya Pindah Page.');
    }
    @IsTest
    static void testCob301SingleRisk() {
        User adminUser = createUser();
        Quote testQuote = [SELECT OpportunityId, Administration_Cost__c, Stamp_Duty__c, Opportunity.COB__c FROM Quote WHERE Name = 'Quote 301' LIMIT 1];
        Aswata_QuotationSlip_Controller controller;
        PageReference resultPage;
        Test.startTest();
        System.runAs(adminUser) {
            PageReference pageRef = Page.quotation;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', testQuote.Id);
            controller = new Aswata_QuotationSlip_Controller();
        }
        Test.stopTest();
        System.assertNotEquals(null, controller.quoteRecord, 'Quote Record seharusnya berhasil di-query di konstruktor.');
        System.assertEquals(null, resultPage, 'Return PageReference.');
    }
    @IsTest
    static void testCob301MultiRisk() {
        User adminUser = createUser();
        Quote testQuote = [SELECT OpportunityId, Administration_Cost__c, Stamp_Duty__c, Opportunity.COB__c FROM Quote WHERE Name = 'Quote 301 Multi' LIMIT 1];
        Aswata_QuotationSlip_Controller controller;
        PageReference resultPage;
        Test.startTest();
        System.runAs(adminUser) {
            PageReference pageRef = Page.quotation;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', testQuote.Id);
            controller = new Aswata_QuotationSlip_Controller();
        }
        Test.stopTest();
        System.assertNotEquals(null, controller.quoteRecord, 'Quote Record seharusnya berhasil di-query di konstruktor.');
        System.assertEquals(null, resultPage, 'Return PageReference.');
    }
    /**
     * @description function for createUser
     * @return User return usercreated
     */
    public static User createUser(){
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User adminUser = new User(
            Alias = 'testad',
            Email = 'testadmin' + System.currentTimeMillis() + '@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'AdminTest',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = adminProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'test.admin.' + System.currentTimeMillis() + '@testorg.com' // Unique Username
        );
        insert adminUser;
        return adminUser;
    }
}