force-app/main/default/objects/Asset/fields/Amount_IDR_new__c.field-meta.xml
<CustomField>
    <fullName>Amount_IDR_new__c</fullName>
    <formula>Amount__c *  Exchange_Rate__c</formula>
    <label>Amount IDR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Amount_Insured__c.field-meta.xml
<CustomField>
    <fullName>Amount_Insured__c</fullName>
    <description>amount dari risk</description>
    <label>Amount Insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master_Data__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Asset Category</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Risks (Category)</relationshipLabel>
    <relationshipName>Risks3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <formula>Text(Opportunity__r.COB__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Commission_All_Coverages__c.field-meta.xml
<CustomField>
    <fullName>Commission_All_Coverages__c</fullName>
    <label>Commission All Coverages</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Coverage_Name__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Jika diisi berarti dari Coverage create master data melalui matrix</description>
    <label>Coverage Name</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Risks (Coverage Name)</relationshipLabel>
    <relationshipName>Risks5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Currency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master_Data__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Exchange Rate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Risks (Currency)</relationshipLabel>
    <relationshipName>Risks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Declare_Value__c.field-meta.xml
<CustomField>
    <fullName>Declare_Value__c</fullName>
    <label>Declare Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Deductible__c.field-meta.xml
<CustomField>
    <fullName>Deductible__c</fullName>
    <label>Deductible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Indemnity_Type__c.field-meta.xml
<CustomField>
    <fullName>Indemnity_Type__c</fullName>
    <label>Indemnity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sum Insured</fullName>
            </value>
            <value>
                <fullName>New Reinstatement Value</fullName>
            </value>
            <value>
                <fullName>Replacement Value</fullName>
            </value>
            <value>
                <fullName>Sub-Limit</fullName>
            </value>
            <value>
                <fullName>First Loss</fullName>
            </value>
            <value>
                <fullName>Lost Limit</fullName>
            </value>
            <value>
                <fullName>Loss Limit - any one claim</fullName>
            </value>
            <value>
                <fullName>Loss Limit - aggregate any one claim</fullName>
            </value>
            <value>
                <fullName>Loss Limit - aggregate during period</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Risks (Model)</relationshipLabel>
    <relationshipName>Model</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Rate_All_Coverages__c.field-meta.xml
<CustomField>
    <fullName>Rate_All_Coverages__c</fullName>
    <label>Rate All Coverages</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Risk_ID__c.field-meta.xml
<CustomField>
    <fullName>Risk_ID__c</fullName>
    <label>Risk ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <label>Risk</label>
</RecordType>

force-app/main/default/objects/InsurancePolicyCoverage/fields/amount_insured__c.field-meta.xml
<CustomField>
    <fullName>amount_insured__c</fullName>
    <label>amount insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Claim_Loss_Amount__c.field-meta.xml
<CustomField>
    <fullName>Claim_Loss_Amount__c</fullName>
    <label>Claim Loss Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Claim_Options__c.field-meta.xml
<CustomField>
    <fullName>Claim_Options__c</fullName>
    <label>Claim Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
                <label>SI:SUM INSURED</label>
            </value>
            <value>
                <fullName>LL</fullName>
                <label>LL:LOSS LIMIT</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>FL: FIRST LOSS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Claim_UR_Id__c.field-meta.xml
<CustomField>
    <fullName>Claim_UR_Id__c</fullName>
    <label>Claim UR Id</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Commision__c.field-meta.xml
<CustomField>
    <fullName>Commision__c</fullName>
    <label>Comission</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/cov_tahun_id__c.field-meta.xml
<CustomField>
    <fullName>cov_tahun_id__c</fullName>
    <label>cov tahun id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Coverage_Id__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Id__c</fullName>
    <label>Coverage Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Coverage_Name__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage Name</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Insurance Policy Coverages (Coverage Name)</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency buat COB301 dari data Asset</description>
    <label>Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible__c.field-meta.xml
<CustomField>
    <fullName>Deductible__c</fullName>
    <label>Deductible Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Total Sum Insured</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Claim Paid</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Claim Amount</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Recoverable Claim</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>Claim Dibayar</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>Harga Pertanggungan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Type__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Type__c</fullName>
    <label>Deductible Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Indemnity_Type__c.field-meta.xml
<CustomField>
    <fullName>Indemnity_Type__c</fullName>
    <label>Indemnity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
                <label>Sum Insured</label>
            </value>
            <value>
                <fullName>LL</fullName>
                <label>Loss Limit</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>First Loss</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible Currency Section 4</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Insurance Policy Coverages (Deductible Currency Section 4)</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Minimum_Cur_ID__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Cur_ID__c</fullName>
    <label>Minimum Cur ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Premi_Amount__c.field-meta.xml
<CustomField>
    <fullName>Premi_Amount__c</fullName>
    <label>Premi Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Propose_Rate__c.field-meta.xml
<CustomField>
    <fullName>Propose_Rate__c</fullName>
    <label>Standard Bottom rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Proposed_Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Fixed_Amount__c</fullName>
    <label>Proposed Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Risk_ID__c.field-meta.xml
<CustomField>
    <fullName>Risk_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Risk</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/Master_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c/fields/Asset_Category__c.field-meta.xml
<CustomField>
    <fullName>Asset_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Category</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Master Data (Asset Category)</relationshipLabel>
    <relationshipName>Master_Data8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Coverage_301__c.field-meta.xml
<CustomField>
    <fullName>Coverage_301__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coverage 301</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Master Data (Coverage 301)</relationshipLabel>
    <relationshipName>Master_Data9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/COVERAGE_REF_ID__c.field-meta.xml
<CustomField>
    <fullName>COVERAGE_REF_ID__c</fullName>
    <externalId>true</externalId>
    <label>COVERAGE REF ID</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Master_Data__c/recordTypes/Coverage.recordType-meta.xml
<RecordType>
    <fullName>Coverage</fullName>
    <active>true</active>
    <label>Coverage</label>
</RecordType>

force-app/main/default/globalValueSets/Currency_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>IDR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Currency Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Aswata_Coverage_Data_301.cls
/**
 * @description       : Class for create new Coverage 301
 * @author            : Ahmad Yazid Munif
 * @last modified on  : 12-11-2025
 * @last modified by  : Ahmad Yazid Munif
**/
public without sharing class Aswata_Coverage_Data_301 {
    /**
     * @description function for generate InsurancePolicyCoverage for 301
     */
    public static String singleComposite {get; set;}
    /**
     * @description function for generate InsurancePolicyCoverage for 301
     * @param listCoverage list of InsurancePolicyCoverage
     * @param risk
     * @param idParentCoverage
     * @return InsurancePolicyCoverage
     */
    public static List<InsurancePolicyCoverage> coverageByAssetCategory(List<InsurancePolicyCoverage> listCoverage,Asset risk,List<String> idParentCoverage){
        // Decimal counter = 1;
        if((String)risk.COB__c != '301'){
            return listCoverage;
        }
        singleComposite = 'false';
        List<String> listCategoryId = new List<String>();
        List<Asset> getByParentId = getAssetByParentId(risk);
        List<InsurancePolicyCoverage> newListCoverage = listCoverage;
        if(getByParentId.isEmpty()){
            return newListCoverage;
        }
        for(Asset item: getByParentId){
            listCategoryId.add(item.Category__c);
        }
        Map<String, InsurancePolicyCoverage> coverageMap = generateCoverageMap(listCoverage);
        List<String> listCovId = generateListCoverageId(idParentCoverage,listCoverage);
        // System.debug('### AWT coverageMap : '+coverageMap);
        // System.debug('### AWT listCategoryId : '+listCategoryId);
        // System.debug('### AWT listCovId : '+listCovId);
        Map<String, Master_Data__c> mdCoverage301 = generateMasterDataCoverage(listCategoryId,listCovId);
        if(mdCoverage301 == null){
            return listCoverage;
        }
        // System.debug('### AWT mdCoverage301 : '+mdCoverage301);
        for(Asset assetItem : getByParentId){
            if(assetItem.Category__c == null){
                continue;
            }
            Master_Data__c matchingMasterData = mdCoverage301.get(assetItem.Category__c);
            if (matchingMasterData != null) {
                InsurancePolicyCoverage referenceCov = getReferenceCoverage(matchingMasterData, listCoverage, coverageMap);
                // System.debug('### AWT referenceCov : '+referenceCov);
                InsurancePolicyCoverage newCov = assignmentValue301(referenceCov.clone(false, true, false, false),matchingMasterData,assetItem);
                newCov.cov_tahun_id__c = listCoverage[0].cov_tahun_id__c;
                newListCoverage.add(newCov);
            }
        }
        return newListCoverage;
    }
    /**
     * @description function for mapping from asset to coverage
     * @param risk
     * @return List<Asset>
     */
    public static List<Asset> getAssetByParentId(Asset risk){
        List<Asset> getByParentId = [
            SELECT Id,Amount_Insured__c,Category__c,ParentId,Amount_IDR_new__c, Currency__r.Name,
            Indemnity_Type__c, Declare_Value__c
            FROM Asset
            WHERE ParentId = :risk.Id
            WITH SECURITY_ENFORCED
        ];
        return getByParentId;
    }
    /**
     * @description function for mapping from asset to coverage
     * @param newCov
     * @param matchingMasterData
     * @param assetItem
     * @return InsurancePolicyCoverage
     */
    public static InsurancePolicyCoverage assignmentValue301(InsurancePolicyCoverage newCov,Master_Data__c matchingMasterData,Asset assetItem){
        newCov.CoverageName = matchingMasterData.Name;
        newCov.Coverage_Name__c = matchingMasterData.Id;
        newCov.Coverage_Id__c = matchingMasterData.COVERAGE_REF_ID__c;
        newCov.amount_insured__c = assetItem.Amount_IDR_new__c;
        newCov.Currency__c = assetItem.Currency__r.Name;
        newCov.Claim_Options__c = getShortCode('indemnity',assetItem.Indemnity_Type__c);
        newCov.Claim_Loss_Amount__c = getSafeDecimal(assetItem.Declare_Value__c);
        newCov.Claim_UR_Id__c = getShortCode('currency',assetItem.Currency__r.Name);
        return newCov;
    }
    /**
     * @description function for mapping from asset to coverage
     * @param type
     * @param picklistValue
     * @return String
     */
    public static String getShortCode(String type,String picklistValue){
        if(type == 'indemnity'){
            if (String.isBlank(picklistValue)) {
                return null;
            }
            String normalizedValue = picklistValue.toUpperCase().trim();
            if (normalizedValue.contains('FIRST LOSS')) {
                return 'FL';
            }else if (normalizedValue.contains('LOSS LIMIT')) {
                return 'LL';
            }else if (normalizedValue.contains('SUM INSURED')) {
                return 'SI';
            }
        }else{
            List<String> picklistCurrency = new List<String>();
            Schema.DescribeFieldResult ddtibleField = InsurancePolicyCoverage.Claim_UR_Id__c.getDescribe();
            for (Schema.PicklistEntry f : ddtibleField.getPicklistValues()) {
                picklistCurrency.add(f.getValue());
            }
            if(picklistCurrency.contains(picklistValue)){
                return picklistValue;
            }else{
                return 'IDR';
            }
        }
        return null;
    }
    /**
     * @description function for mapping from asset to coverage
     * @param dataValue
     * @return Decimal
     */
    public static Decimal getSafeDecimal(Decimal dataValue){
        if(dataValue == null){
            return 0;
        }
        return dataValue;
    }
    /**
     * @description function for get reference coverage Asset
     * @param matchingMasterData
     * @param listCoverage
     * @param coverageMap
     * @return InsurancePolicyCoverage
     */
    private static InsurancePolicyCoverage getReferenceCoverage(
        Master_Data__c matchingMasterData,
        List<InsurancePolicyCoverage> listCoverage,
        Map<String, InsurancePolicyCoverage> coverageMap)
    {
        if (singleComposite == 'true') {
            return listCoverage[0];
        } else {
            // System.debug('### AWT matchingMasterData.Coverage_301__c : '+matchingMasterData.Coverage_301__c);
            return coverageMap.get(matchingMasterData.Coverage_301__c);
        }
    }
    /**
     * @description function for get masterData Coverage 301
     * @param listCategoryId
     * @param listCovId
     * @return Map<String, Master_Data__c>
     */
    public static Map<String, Master_Data__c> generateMasterDataCoverage(List<String> listCategoryId,List<String> listCovId){
        Map<String, Master_Data__c> mdCoverage301 = new Map<String, Master_Data__c>();
        List<Master_Data__c> masterDataCov301 = [
            SELECT Id,Name,COVERAGE_REF_ID__c,Coverage_301__c,Asset_Category__c
            FROM Master_Data__c
            WHERE Asset_Category__c IN :listCategoryId AND Coverage_301__c IN :listCovId
            WITH SECURITY_ENFORCED
        ];
        if (masterDataCov301.isEmpty()){
            return null;
        }
        for(Master_Data__c item : masterDataCov301){
            mdCoverage301.put(item.Asset_Category__c, item);
        }
        return mdCoverage301;
    }
    /**
     * @description function for generate ListCoverageId
     * @param idParentCoverage
     * @param listCoverage
     * @return List<String>
     */
    public static List<String> generateListCoverageId(List<String> idParentCoverage,List<InsurancePolicyCoverage> listCoverage){
        List<String> listCovId = new List<String>();
        if(!idParentCoverage.isEmpty()){
            listCovId.addAll(idParentCoverage);
            singleComposite = 'true';
        }else{
            for(InsurancePolicyCoverage item: listCoverage){
                listCovId.add(item.Coverage_Name__c);
            }
        }
        return listCovId;
    }
    /**
     * @description function for generate ListCoverageId
     * @param listCoverage
     * @return Map<String, InsurancePolicyCoverage>
     */
    public static Map<String, InsurancePolicyCoverage> generateCoverageMap(List<InsurancePolicyCoverage> listCoverage){
        Map<String, InsurancePolicyCoverage> coverageMap = new Map<String, InsurancePolicyCoverage>();
        for (InsurancePolicyCoverage cov : listCoverage) {
            if (cov.Coverage_Name__c != null) {
                coverageMap.put(cov.Coverage_Name__c, cov);
            }
        }
        return coverageMap;
    }
    /**
     * @description function for generate ListCoverageId
     * @param coverageList
     * @param risk
     * @return Asset
     */
    public static Asset calculateAllRate(List<InsurancePolicyCoverage> coverageList,Asset risk){
        Asset updateRisk = risk;
        Decimal sumOfRate = 0;
        Decimal sumOfCommision = 0;
        Integer countCov = 0;
        for (InsurancePolicyCoverage coverage : coverageList) {
            Decimal currentRate = coverage.Proposed_Fixed_Amount__c;
            Decimal currentCommision = coverage.Commision__c;
            if (currentRate != null) {
                sumOfRate += currentRate;
            }
            if(currentCommision != null){
                sumOfCommision += currentCommision;
            }
            countCov++;
        }
        if (countCov > 0) {
            Decimal averageRate = sumOfRate / countCov;
            Decimal averageCommision = sumOfCommision / countCov;
            // System.debug('### AWT coverageList'+coverageList.size());
            // System.debug('### AWT sumOfRate'+sumOfRate+' - '+countCov);
            // System.debug('### AWT averageRate'+averageRate+' - '+averageCommision);
            // System.debug('### AWT updateRisk'+updateRisk.Model__c);
            updateRisk.Rate_All_Coverages__c  = averageRate;
            updateRisk.Commission_All_Coverages__c = averageCommision;
            return updateRisk;
        }
        return risk;
    }
}
// newCov.InsurancePolicyId = item.InsurancePolicyId;
// newCov.Opportunity__c = item.Opportunity__c;
// newCov.Risk_ID__c = item.Risk_ID__c;
// newCov.Propose_Rate__c = item.Propose_Rate__c;
// newCov.Coverage_Name__c = item.ProposeCoverage_Name__c_Rate__c;
// newCov.Proposed_Fixed_Amount__c = item.Proposed_Fixed_Amount__c;
// newCov.Premi_Amount__c = item.Premi_Amount__c;
// newCov.Deductible_Type__c = item.Deductible_Type__c;
// newCov.Deductible__c = item.Deductible__c;
// newCov.DeductibleAmount = item.DeductibleAmount;
// newCov.Minimum_Cur_ID__c = item.Minimum_Cur_ID__c;
// newCov.Deductible_PCT__c = item.Deductible_PCT__c;
// newCov.Description = item.Description;
// newCov.Description__c = item.Description__c;
// newCov.Minimum_Amount__c = item.Minimum_Amount__c;
// newCov.Total_Rebate__c = item.Total_Rebate__c;
// newCov.Discount__c = item.Discount__c;
// newCov.Commision__c = item.Commision__c;
// newCov.Banks_Fee_Comission__c = item.Banks_Fee_Comission__c;
// newCov.Risk_Closing_Survey_Fee_BSP__c = item.Risk_Closing_Survey_Fee_BSP__c;
// newCov.Profit_Sharing__c = item.Profit_Sharing__c;
// newCov.Leasing_Fee__c = item.Leasing_Fee__c;
// newCov.Overdng_Comission__c = item.Overdng_Comission__c;
// newCov.Agent_Comission__c = item.Agent_Comission__c;
// newCov.Broker_Comission__c = item.Broker_Comission__c;
// newCov.Finance_Commision_PCT__c = item.Finance_Commision_PCT__c;