force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Risk_ID__c.field-meta.xml
<CustomField>
    <fullName>Risk_ID__c</fullName>
    <label>Risk ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Agent_Comission__c.field-meta.xml
<CustomField>
    <fullName>Agent_Comission__c</fullName>
    <label>Agent Comission</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Banks_Fee_Comission__c.field-meta.xml
<CustomField>
    <fullName>Banks_Fee_Comission__c</fullName>
    <label>Banks Fee Comission</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Broker_Comission__c.field-meta.xml
<CustomField>
    <fullName>Broker_Comission__c</fullName>
    <label>Broker Comission</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Commision__c.field-meta.xml
<CustomField>
    <fullName>Commision__c</fullName>
    <label>Comission</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Finance_Commision_PCT__c.field-meta.xml
<CustomField>
    <fullName>Finance_Commision_PCT__c</fullName>
    <label>Finance Commision</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Leasing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Leasing_Fee__c</fullName>
    <label>Leasing&apos;s Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Overdng_Comission__c.field-meta.xml
<CustomField>
    <fullName>Overdng_Comission__c</fullName>
    <label>Overiding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Premi_Amount__c.field-meta.xml
<CustomField>
    <fullName>Premi_Amount__c</fullName>
    <label>Premi Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Risk_Closing_Survey_Fee_BSP__c.field-meta.xml
<CustomField>
    <fullName>Risk_Closing_Survey_Fee_BSP__c</fullName>
    <label>Risk/Closing Survey Fee / BSP</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Risk_ID__c.field-meta.xml
<CustomField>
    <fullName>Risk_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Risk</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Total_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebate__c</fullName>
    <label>Total Rebate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agent_Commission__c.field-meta.xml
<CustomField>
    <fullName>Agent_Commission__c</fullName>
    <description>Derived from Coverage</description>
    <label>Agent Commission</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Banks_Fee_Commission__c.field-meta.xml
<CustomField>
    <fullName>Banks_Fee_Commission__c</fullName>
    <description>Derived from Coverage</description>
    <label>Bank&apos;s Fee Commission</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Broker_Commission__c.field-meta.xml
<CustomField>
    <fullName>Broker_Commission__c</fullName>
    <description>Derived from Coverage</description>
    <label>Broker Commission</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commision__c.field-meta.xml
<CustomField>
    <fullName>Commision__c</fullName>
    <label>Commision</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Derived from Coverage</description>
    <label>Discount</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finance_Commission_PCT__c.field-meta.xml
<CustomField>
    <fullName>Finance_Commission_PCT__c</fullName>
    <description>Derived from Coverage</description>
    <label>Finance Commission PCT</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Leasings_Fee__c.field-meta.xml
<CustomField>
    <fullName>Leasings_Fee__c</fullName>
    <description>Derived from Coverage</description>
    <label>Leasing&apos;s Fee</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Overriding_Commission__c.field-meta.xml
<CustomField>
    <fullName>Overriding_Commission__c</fullName>
    <description>Derived from Coverage</description>
    <label>Overriding Commission</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Risk_Closing_Survey_Fee_BSP__c.field-meta.xml
<CustomField>
    <fullName>Risk_Closing_Survey_Fee_BSP__c</fullName>
    <description>Derived from Coverage</description>
    <label>Risk/Closing Survey Fee / BSP</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebate__c</fullName>
    <description>Derived from Coverage</description>
    <label>Total Rebate</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Aswata_Async_PremiCalculation.cls
/**
 * @description       : Async Premi Calculation
 * @author            : Fikri Hailal
 * @last modified on  : 11-25-2025
 * @last modified by  : Ahmad Yazid Munif
**/
public with sharing class Aswata_Async_PremiCalculation {
    /**
     * @description function future for calculation total premi
     * @param opportunityId
     */
    @future
    public static void aswataPremiCalculation(String opportunityId) {
        aswataPremiCalculation2(opportunityId);
    }
    /**
     * @description function for calculation total premi
     * @param opportunityId
     */
    public static void aswataPremiCalculation2(String opportunityId) {
        if(String.isNotBlank(opportunityId)){
            List<InsurancePolicyCoverage> lstAllCoverage = [
                SELECT id, Premi_Amount__c, Risk_ID__c,Discount__c
                    ,Commision__c,Agent_Comission__c,Banks_Fee_Comission__c
                    ,Leasing_Fee__c,Overdng_Comission__c,Risk_Closing_Survey_Fee_BSP__c
                    ,Broker_Comission__c,Total_Rebate__c,Finance_Commision_PCT__c
                    from InsurancePolicyCoverage
                WHERE Opportunity__c =: opportunityId and Premi_Amount__c != null
                WITH Security_Enforced
            ];

            List<OpportunityLineItem> lstOLI = [
                SELECT id, UnitPrice from OpportunityLineItem
                WHERE OpportunityId =: opportunityId
                WITH Security_Enforced LIMIT 1
            ];
            if (!lstAllCoverage.isEmpty()) {
                performUpdate(opportunityId,lstAllCoverage,lstOLI);
            }
        }
    }
    /**
     * @description function update total premi
     * @param opportunityId
     * @param lstAllCoverage
     * @param lstOLI
     */
    public static void performUpdate(
        String opportunityId,
        List<InsurancePolicyCoverage> lstAllCoverage,
        List<OpportunityLineItem> lstOLI
    ) {
        if (
            !Schema.sObjectType.Opportunity.isUpdateable() &&
            !Schema.sObjectType.OpportunityLineItem.isUpdateable()
        ){
            throw new SecurityException(
                'Insufficient permissions to access Asset or InsurancePolicyCoverage'
            );
        }
        CoverageDetailWrapper result = generateDetailCoverage(lstAllCoverage);
        CoverageDetailWrapper secondResult = generateDetailCoverage2(lstAllCoverage);
        Decimal totalPremi = result.totalPremi;
        Decimal totalDiscount = result.totalDiscount;
        Decimal totalCommision = result.totalCommision;
        Decimal totalAgentComm = result.totalAgentComm;
        Decimal totalBankFee = result.totalBankFee;
        Decimal totalLeasingFee = secondResult.totalLeasingFee;
        Decimal totalOverdng = secondResult.totalOverdng;
        Decimal totalRiskClosing = secondResult.totalRiskClosing;
        Decimal totalBrokerComm = secondResult.totalBrokerComm;
        Decimal totalRebate = secondResult.totalRebate;
        Decimal totalFinanceComm = secondResult.totalFinanceComm;
        // === Compute Averages ===
        Integer recordCount = lstAllCoverage.size();
        Decimal avgDiscount = totalDiscount / recordCount;
        Decimal avgCommision = totalCommision / recordCount;
        Decimal avgAgentComm = totalAgentComm / recordCount;
        Decimal avgBankFee = totalBankFee / recordCount;
        Decimal avgLeasingFee = totalLeasingFee / recordCount;
        Decimal avgOverdng = totalOverdng / recordCount;
        Decimal avgRiskClosing = totalRiskClosing / recordCount;
        Decimal avgBrokerComm = totalBrokerComm / recordCount;
        Decimal avgRebate = totalRebate / recordCount;
        Decimal avgFinanceComm = totalFinanceComm / recordCount;
        List<OpportunityLineItem> lstAddOli = new List<OpportunityLineItem>();
        for(OpportunityLineItem oli : lstOLI){
            oli.UnitPrice = totalPremi;
            lstAddOli.add(oli);
        }
        Database.update(lstAddOli, false);

        Opportunity opp = new Opportunity(
            Id = opportunityId,
            Amount = totalPremi,
            Discount__c = avgDiscount,
            Commision__c = avgCommision,
            Agent_Commission__c = avgAgentComm,
            Banks_Fee_Commission__c = avgBankFee,
            Leasings_Fee__c = avgLeasingFee,
            Overriding_Commission__c = avgOverdng,
            Risk_Closing_Survey_Fee_BSP__c = avgRiskClosing,
            Broker_Commission__c = avgBrokerComm,
            Total_Rebate__c = avgRebate,
            Finance_Commission_pct__c = avgFinanceComm
        );
        Database.update(opp, false);
    }
    /**
     * @description function for checkPermission Access
     * @param lstAllCoverage
     * @return CoverageDetailWrapper
     */
    public static CoverageDetailWrapper generateDetailCoverage(List<InsurancePolicyCoverage> lstAllCoverage){
        CoverageDetailWrapper result = new CoverageDetailWrapper();
        Decimal totalPremi = 0;
        Decimal totalDiscount = 0;
        Decimal totalCommision = 0;
        Decimal totalAgentComm = 0;
        Decimal totalBankFee = 0;
        for (InsurancePolicyCoverage cov : lstAllCoverage) {
            totalPremi += cov.Premi_Amount__c;
            totalDiscount += cov.Discount__c == null ? 0 : cov.Discount__c;
            totalCommision += cov.Commision__c == null ? 0 : cov.Commision__c;
            totalAgentComm += cov.Agent_Comission__c == null ? 0 : cov.Agent_Comission__c;
            totalBankFee += cov.Banks_Fee_Comission__c == null ? 0 : cov.Banks_Fee_Comission__c;
        }
        result.totalPremi = totalPremi;
        result.totalDiscount = totalDiscount;
        result.totalCommision = totalCommision;
        result.totalAgentComm = totalAgentComm;
        result.totalBankFee = totalBankFee;
        return result;
    }
    /**
     * @description function for checkPermission Access
     * @param lstAllCoverage
     * @return CoverageDetailWrapper
     */
    public static CoverageDetailWrapper generateDetailCoverage2(List<InsurancePolicyCoverage> lstAllCoverage){
        CoverageDetailWrapper result = new CoverageDetailWrapper();
        Decimal totalLeasingFee = 0;
        Decimal totalOverdng = 0;
        Decimal totalRiskClosing = 0;
        Decimal totalBrokerComm = 0;
        Decimal totalRebate = 0;
        Decimal totalFinanceComm = 0;

        for (InsurancePolicyCoverage cov : lstAllCoverage) {
            totalLeasingFee += cov.Leasing_Fee__c == null ? 0 : cov.Leasing_Fee__c;
            totalOverdng += cov.Overdng_Comission__c == null ? 0 : cov.Overdng_Comission__c;
            totalRiskClosing += cov.Risk_Closing_Survey_Fee_BSP__c == null ? 0 : cov.Risk_Closing_Survey_Fee_BSP__c;
            totalBrokerComm += cov.Broker_Comission__c == null ? 0 : cov.Broker_Comission__c;
            totalRebate += cov.Total_Rebate__c == null ? 0 : cov.Total_Rebate__c;
            totalFinanceComm += cov.Finance_Commision_PCT__c == null ? 0 : cov.Finance_Commision_PCT__c;
        }
        result.totalLeasingFee = totalLeasingFee;
        result.totalOverdng = totalOverdng;
        result.totalRiskClosing = totalRiskClosing;
        result.totalBrokerComm = totalBrokerComm;
        result.totalRebate = totalRebate;
        result.totalFinanceComm = totalFinanceComm;
        return result;
    }
    /**
     * @description Class wrapper
     */
    public class CoverageDetailWrapper {
        public Decimal totalPremi;
        public Decimal totalDiscount;
        public Decimal totalCommision;
        public Decimal totalAgentComm;
        public Decimal totalBankFee;
        public Decimal totalLeasingFee;
        public Decimal totalOverdng;
        public Decimal totalRiskClosing;
        public Decimal totalBrokerComm;
        public Decimal totalRebate;
        public Decimal totalFinanceComm;
    }
}