force-app/main/default/objects/Account/fields/Account_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Segment__c</fullName>
    <label>Account Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Business_Segmentation__c</fullName>
    <label>Business Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>false</fullName>
                <isActive>false</isActive>
                <label>false</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/Master_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c/fields/Account_Pipeline_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Pipeline_Status__c</fullName>
    <label>Account Pipeline Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Account_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Pipeline_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Account_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Segment__c</fullName>
    <label>Account Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Business_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Business_Segmentation__c</fullName>
    <label>Business Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Segmentation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Round_Robin_Counter_Account__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Counter_Account__c</fullName>
    <label>Round Robin Counter Account</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Round_Robin_Counter_Branch__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Counter_Branch__c</fullName>
    <label>Round Robin Counter Branch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Pipeline_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Channel</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Business/Enterprise</fullName>
        <isActive>false</isActive>
        <label>Business/Enterprise</label>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
        <isActive>false</isActive>
        <label>Individual</label>
    </customValue>
    <masterLabel>Account Pipeline Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Account_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>I</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Business / Enterprise</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Business / Enterprise Group</label>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
        <isActive>false</isActive>
        <label>Business</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
        <isActive>false</isActive>
        <label>Government</label>
    </customValue>
    <customValue>
        <fullName>Business - Group</fullName>
        <isActive>false</isActive>
        <label>Business - Group</label>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
        <isActive>false</isActive>
        <label>Enterprise</label>
    </customValue>
    <customValue>
        <fullName>Private</fullName>
        <isActive>false</isActive>
        <label>Private</label>
    </customValue>
    <masterLabel>Account Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Bank</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Broker</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Agent</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Finance/ Leasing</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Group</label>
    </customValue>
    <customValue>
        <fullName>Salvage Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>INSURANCE</fullName>
        <label>Insurance</label>
    </customValue>
    <customValue>
        <fullName>REINSURANCE</fullName>
        <label>Reinsurance</label>
    </customValue>
    <customValue>
        <fullName>BROKER</fullName>
        <label>Reinsurance Broker</label>
    </customValue>
    <customValue>
        <fullName>Independent Surveyor</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Surveyor</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Adjuster</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Investigator</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Claim Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Repairer Shop</fullName>
    </customValue>
    <customValue>
        <fullName>Part Supplier</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Insurer</fullName>
        <isActive>false</isActive>
        <label>Co-Insurer</label>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Business_Segmentation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <masterLabel>Business Segmentation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Aswata_Reset_RoundRobinCounter_Test.cls
@IsTest (seeAllData=false)
public with sharing class Aswata_Reset_RoundRobinCounter_Test {
    @IsTest
    static void testexecuteResetCounters() {

        Master_Data__c roundRobin = Aswata_TestDataFactory.createMasterData('R Robin 1', 'Round Robin Member');
        roundRobin.Account_Type__c = '0';
        roundRobin.Account_Segment__c = 'I';
        roundRobin.Account_Pipeline_Status__c = 'Direct';
        roundRobin.Business_Segmentation__c = 'Corporate';
        roundRobin.Round_Robin_Counter_Branch__c = 5;
        roundRobin.Round_Robin_Counter_Account__c = 10;
        update roundRobin;

        Test.startTest();
        Aswata_Reset_RoundRobinCounter job = new Aswata_Reset_RoundRobinCounter();
        String jobId = System.schedule('Test Reset Job', '0 0 0 * * ?', job);
        Test.stopTest();

        // 3️⃣ Verify that counters have been reset to 0
        List<Master_Data__c> results = [
            SELECT Round_Robin_Counter_Branch__c, Round_Robin_Counter_Account__c 
            FROM Master_Data__c
            WHERE Id IN :new List<Id>{ roundRobin.Id}
        ];

        System.assertEquals(0, results[0].Round_Robin_Counter_Branch__c, 'Branch counter should be reset to 0');
        System.assertEquals(0, results[0].Round_Robin_Counter_Account__c, 'Account counter should be reset to 0');
    }
}