force-app/main/default/objects/Account/fields/Account_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Segment__c</fullName>
    <label>Account Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Sub_Segment__c</fullName>
    <description>Khusus Bank
Private = Bank Swasta
Government = Bank Pemerintah</description>
    <label>Account Sub-Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Sub_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Business_Segmentation__c</fullName>
    <label>Business Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>false</fullName>
                <isActive>false</isActive>
                <label>false</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>IF(NOT(ISBLANK(TEXT(Account_Channel__c))),TEXT(Account_Channel__c), CASE(TEXT(Account_Segment__c),&apos;E&apos;,&apos;0&apos;, &apos;I&apos;,&apos;0&apos;,&apos;5&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <description>Is the Customer’s Email.
When there is already a value in SF DB for this field, the value will be replaced with the one from SF DB.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Province</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Accounts (Province)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Convert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <description>Account Insurance</description>
    <label>Insurance</label>
-->
    <!---->
    <!---->
</RecordType>

force-app/main/default/objects/Asset/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <formula>Text(Opportunity__r.COB__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Assets (Province)</relationshipLabel>
    <relationshipName>Assets3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <label>Risk</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BO</fullName>
                <label>Beneficial Owner / Pihak Pengendali Akhir</label>
            </value>
            <value>
                <fullName>CP</fullName>
                <label>Contact Person</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <label>COB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Pipeline_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Pipeline_Status__c</fullName>
    <label>Account Pipeline Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Pipeline_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Segment__c</fullName>
    <label>Account Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Sub_Segment__c</fullName>
    <label>Account Sub-Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Sub_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Business_Segmentation__c</fullName>
    <label>Business Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Segmentation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.RecordTypeId</field>
            <operation>equals</operation>
            <value>Province</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Leads and Referrals</relationshipLabel>
    <relationshipName>Leads_and_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Province</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/recordTypes/Address.recordType-meta.xml
<RecordType>
    <fullName>Address</fullName>
    <active>true</active>
    <label>Address</label>
</RecordType>

force-app/main/default/objects/Location/recordTypes/City.recordType-meta.xml
<RecordType>
    <fullName>City</fullName>
    <active>true</active>
    <label>City</label>
</RecordType>

force-app/main/default/objects/Location/recordTypes/Province.recordType-meta.xml
<RecordType>
    <fullName>Province</fullName>
    <active>true</active>
    <label>Province</label>
    <!---->
</RecordType>

force-app/main/default/objects/Location/recordTypes/Village.recordType-meta.xml
<RecordType>
    <fullName>Village</fullName>
    <active>false</active>
    <label>Village</label>
</RecordType>

force-app/main/default/objects/Master_Data__c/Master_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c/fields/Account_Pipeline_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Pipeline_Status__c</fullName>
    <label>Account Pipeline Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Account_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Pipeline_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Account_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Segment__c</fullName>
    <label>Account Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Account_Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Sub_Segment__c</fullName>
    <description>untuk logic omniscript</description>
    <label>Account Sub Segment Omniscript</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Account_Type_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Account_Sub_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Business_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Business_Segmentation__c</fullName>
    <label>Business Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Segmentation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/recordTypes/Coverage.recordType-meta.xml
<RecordType>
    <fullName>Coverage</fullName>
    <active>true</active>
    <label>Coverage</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Business_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Business_Segmentation__c</fullName>
    <label>Business Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Leasing</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <label>COB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <formula>Risk_Name__r.Province__c</formula>
    <label>Province</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Data__c/Transaction_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Transaction Data</label>
    <nameField>
        <label>Transaction Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Data__c/fields/Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clausa</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Transactions Data</relationshipLabel>
    <relationshipName>Transactions_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Data__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions Data</relationshipLabel>
    <relationshipName>Transactions_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Pipeline_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Channel</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Business/Enterprise</fullName>
        <isActive>false</isActive>
        <label>Business/Enterprise</label>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
        <isActive>false</isActive>
        <label>Individual</label>
    </customValue>
    <masterLabel>Account Pipeline Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Account_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>I</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Business / Enterprise</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Business / Enterprise Group</label>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
        <isActive>false</isActive>
        <label>Business</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
        <isActive>false</isActive>
        <label>Government</label>
    </customValue>
    <customValue>
        <fullName>Business - Group</fullName>
        <isActive>false</isActive>
        <label>Business - Group</label>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
        <isActive>false</isActive>
        <label>Enterprise</label>
    </customValue>
    <customValue>
        <fullName>Private</fullName>
        <isActive>false</isActive>
        <label>Private</label>
    </customValue>
    <masterLabel>Account Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Account_Sub_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Private</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Government</label>
    </customValue>
    <description>Khusus Bank
Private = Bank Swasta
Government = Bank Pemerintah</description>
    <masterLabel>Account Sub-Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Bank</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Broker</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Agent</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Finance/ Leasing</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Group</label>
    </customValue>
    <customValue>
        <fullName>Salvage Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>INSURANCE</fullName>
        <label>Insurance</label>
    </customValue>
    <customValue>
        <fullName>REINSURANCE</fullName>
        <label>Reinsurance</label>
    </customValue>
    <customValue>
        <fullName>BROKER</fullName>
        <label>Reinsurance Broker</label>
    </customValue>
    <customValue>
        <fullName>Independent Surveyor</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Surveyor</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Adjuster</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Investigator</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Claim Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Repairer Shop</fullName>
    </customValue>
    <customValue>
        <fullName>Part Supplier</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Insurer</fullName>
        <isActive>false</isActive>
        <label>Co-Insurer</label>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Business_Segmentation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <masterLabel>Business Segmentation</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Aswata_TestDataFactory.cls
/**
 * -------------------------------------------------------------------------------
 * Class Name   : Aswata_TestDataFactory
 * Description  : Centralized factory class for creating test data such as
 *                Account, Contact, and Opportunity records.
 * Author       : Fikri
 * -------------------------------------------------------------------------------
 */
@IsTest
public class Aswata_TestDataFactory {


   // 🔹 Create a Lead record
    public static Lead createLead(String firstName, String lastName, String company) {
        Lead lead = new Lead(
            FirstName = firstName,
            LastName = lastName,
            Company = company,
            Email = firstName.toLowerCase() + '.' + lastName.toLowerCase() + '@test.com',
            Phone = '08123456789',
            Status = 'New',
            Account_Segment__c = 'I',
            Account_Type__c = '	0',
            Account_Sub_Segment__c = 'Y',
            Account_Pipeline_Status__c = 'Direct',
            //Channel__c = 'Broker',
            Business_Segmentation__c = 'Retail'
        );
        insert lead;
        return lead;
    }

    public static Lead createLeadCustom(String firstName, String lastName, String company) {
        Lead lead = new Lead(
            FirstName = firstName,
            LastName = lastName,
            Company = company,
            Email = firstName.toLowerCase() + '.' + lastName.toLowerCase() + '@test.com',
            Phone = '08123456789',
            Status = 'New',
            Account_Segment__c = 'I',
            Account_Type__c = '	0',
            Account_Sub_Segment__c = 'Y',
            Account_Pipeline_Status__c = 'Direct',
            //Channel__c = 'Broker',
            Business_Segmentation__c = 'Retail'
        );
        return lead;
    }

    // Create a standard Account
    public static Account createAccount(String name) {
        Account acc = new Account(
            Name = name,
            Phone = '0211234567',
            Email__c = 'account@test.com'
        );
        insert acc;
        return acc;
    }

    // Create a Contact linked to an Account
    public static Contact createContact(Account acc, String firstName, String lastName) {
        Contact con = new Contact(
            FirstName = firstName,
            LastName = lastName,
            Email = firstName.toLowerCase() + '.' + lastName.toLowerCase() + '@test.com',
            Phone = '08123456789',
            AccountId = acc.Id,
            Status__c = 'CP'
        );
        insert con;
        return con;
    }

    // Create an Opportunity linked to an Account
    public static Opportunity createOpportunity(Account acc, String name) {
        Opportunity opp = new Opportunity(
            Name = name,
            AccountId = acc.Id,
            StageName = 'Prospecting',
            CloseDate = System.today().addDays(30),
            Amount = 50000
        );
        insert opp;
        return opp;
    }

    public static Quote createQuote(Opportunity opp, String name) {
        Quote quo = new Quote(
            Name = name,
            //AccountId = acc.Id,
            OpportunityId = opp.id
        );
        insert quo;
        return quo;
    }

    public static Asset createRisk(Opportunity oppty, String name) {
    
        RecordType rt = [
            SELECT Id 
            FROM RecordType 
            WHERE SObjectType = 'Asset' 
            AND Name = 'Risk' 
            LIMIT 1
        ];

        // Create Asset record
        Asset risk = new Asset(
            Name = name,
            Opportunity__c = oppty.Id,
            COB__c = '201',
            RecordTypeId = rt.Id
        );
        insert risk;
        return risk;
    }

    public static Asset createAsset(Opportunity oppty,Asset risk, String name) {
    
        RecordType rt = [
            SELECT Id 
            FROM RecordType 
            WHERE SObjectType = 'Asset' 
            AND Name = 'Asset' 
            LIMIT 1
        ];

        // Create Asset record
        Asset ast = new Asset(
            Name = name,
            Opportunity__c = oppty.Id,
            ParentId = risk.Id,
            COB__c = '201',
            RecordTypeId = rt.Id
        );
        insert ast;
        return ast;
    }


    // Combined convenience method
    public static Map<String, SObject> createStandardDataSet() {
        Map<String, SObject> data = new Map<String, SObject>();
        Account acc = createAccount('Test Account');
        Contact con = createContact(acc, 'John', 'Doe');
        Opportunity opp = createOpportunity(acc, 'Test Opportunity');
        
        data.put('Account', acc);
        data.put('Contact', con);
        data.put('Opportunity', opp);

        return data;
    }

    // 🔹 Create Master_Data__c record (generic for Coverage, City, Province, etc.)
    public static Master_Data__c createMasterData(String name, String recordTypeName) {
        RecordType rt = [
            SELECT Id FROM RecordType
            WHERE SObjectType = 'Master_Data__c' AND Name = :recordTypeName
            LIMIT 1
        ];

        Master_Data__c md = new Master_Data__c(
            Name = name,
            RecordTypeId = rt.Id
        );
        insert md;
        return md;
    }

    // 🔹 Create Exchange Rate record
    public static Master_Data__c createExchangeRate(String name, Decimal rate) {
        RecordType rt = [
            SELECT Id FROM RecordType
            WHERE SObjectType = 'Master_Data__c' AND Name = 'Exchange Rate'
            LIMIT 1
        ];

        Master_Data__c ex = new Master_Data__c(
            Name = name,
            Exchange_Rate__c = rate,
            RecordTypeId = rt.Id
        );
        insert ex;
        return ex;
    }

    // 🔹 Create linked Province → City → Address hierarchy
    public static Map<String, Schema.Location> createLocationHierarchy() {
        RecordType rtProvince = [
            SELECT Id FROM RecordType WHERE SObjectType = 'Location' AND Name = 'Province' LIMIT 1
        ];
        RecordType rtCity = [
            SELECT Id FROM RecordType WHERE SObjectType = 'Location' AND Name = 'City' LIMIT 1
        ];
        RecordType rtVillage = [
            SELECT Id FROM RecordType WHERE SObjectType = 'Location' AND Name = 'Village' LIMIT 1
        ];
        RecordType rtZipCode = [
            SELECT Id FROM RecordType WHERE SObjectType = 'Location' AND Name = 'Zip Code' LIMIT 1
        ];

        RecordType rtAddress = [
            SELECT Id FROM RecordType WHERE SObjectType = 'Location' AND Name = 'Address' LIMIT 1
        ];

        Schema.Location province = new Schema.Location(Name = 'Jakarta', RecordTypeId = rtProvince.Id, LocationType = 'Province');
        insert province;

        Schema.Location city = new Schema.Location(Name = 'Jakarta Selatan', RecordTypeId = rtCity.Id, Province__c = province.Id, LocationType = 'City');
        insert city;
        
        Schema.Location village = new Schema.Location(Name = 'Setiabudi', RecordTypeId = rtVillage.Id, Province__c = province.Id, City__c = city.Id, LocationType = 'Village');
        insert village;

        Schema.Location zipCode = new Schema.Location(Name = '1171', RecordTypeId = rtZipCode.Id, City__c = city.Id, Province__c = province.Id, Village__c = village.Id, LocationType = 'Zip Code');
        insert zipCode;

        Schema.Location address = new Schema.Location(Name = 'Jl. Sudirman No. 10', Address_Name__c = 'Jl. Sudirman No. 10' , RecordTypeId = rtAddress.Id, City__c = city.Id, Province__c = province.Id, Village__c = village.Id, Zip_Code__c = zipCode.Id);
        insert address;

        return new Map<String, Schema.Location>{
            'Province' => province,
            'City' => city,
            'Village' => village,
            'Zip Code' => zipCode,
            'Address' => address
        };
    }

    public static Schema.Location createZipCode() {
        RecordType rtZipCode = [
            SELECT Id FROM RecordType WHERE SObjectType = 'Location' AND Name = 'Zip Code' LIMIT 1
        ];


        Schema.Location zipCode = new Schema.Location(Name = '1171', RecordTypeId = rtZipCode.Id, LocationType = 'Zip Code');
        return  zipCode;

    }

    public static Schema.Location createAddress() {
        RecordType rtAddress = [
            SELECT Id FROM RecordType WHERE SObjectType = 'Location' AND Name = 'Address' LIMIT 1
        ];


        Schema.Location address = new Schema.Location(Name = 'Jl. Sudirman No. 10', RecordTypeId = rtAddress.Id);
        return address;

    }

    // 🔹 Overloaded version (reusable)
    public static InsurancePolicy createInsurancePolicy(Account acc, Opportunity opp) {
        InsurancePolicy policy = new InsurancePolicy(
            Name = 'Test Insurance Policy',
            NameInsuredId = acc.Id,
            SourceOpportunityId = opp.Id
        );
        insert policy;

        return policy;
    }

    
    public static Transaction_Data__c createTransactionData(String recordTypeName, String recordName) {
        RecordType rt = [
            SELECT Id FROM RecordType
            WHERE SObjectType = 'Transaction_Data__c' AND Name =: recordTypeName
            LIMIT 1
        ];
        
        Transaction_Data__c transactionData = new Transaction_Data__c(
            Name = recordName,
            RecordTypeId = rt.Id
        );
        insert transactionData;

        return transactionData;
    }
}