force-app/main/default/objects/Account/fields/Account_Channel__c.field-meta.xml
<CustomField>
    <fullName>Account_Channel__c</fullName>
    <label>Account Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Segment__c</fullName>
    <label>Account Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Sub_Segment__c</fullName>
    <description>Khusus Bank
Private = Bank Swasta
Government = Bank Pemerintah</description>
    <label>Account Sub-Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Sub_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <externalId>true</externalId>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IsSchedule__c.field-meta.xml
<CustomField>
    <fullName>IsSchedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSchedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Schedule</label>
</CustomObject>

force-app/main/default/globalValueSets/Account_Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Broker</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Bank</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Agent</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Finance/ Leasing</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Group</label>
    </customValue>
    <customValue>
        <fullName>Leasing</fullName>
        <isActive>false</isActive>
        <label>Leasing</label>
    </customValue>
    <customValue>
        <fullName>Direct</fullName>
        <isActive>false</isActive>
        <label>Direct</label>
    </customValue>
    <masterLabel>Account Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Account_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>I</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Business / Enterprise</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Business / Enterprise Group</label>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
        <isActive>false</isActive>
        <label>Business</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
        <isActive>false</isActive>
        <label>Government</label>
    </customValue>
    <customValue>
        <fullName>Business - Group</fullName>
        <isActive>false</isActive>
        <label>Business - Group</label>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
        <isActive>false</isActive>
        <label>Enterprise</label>
    </customValue>
    <customValue>
        <fullName>Private</fullName>
        <isActive>false</isActive>
        <label>Private</label>
    </customValue>
    <masterLabel>Account Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Account_Sub_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Private</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Government</label>
    </customValue>
    <description>Khusus Bank
Private = Bank Swasta
Government = Bank Pemerintah</description>
    <masterLabel>Account Sub-Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ScheduleSFAWT17_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 * @description ScheduleSFAWT17_Test
 */
@isTest
private class ScheduleSFAWT17_Test {
    @testSetup
    static void setupData() {
        // TO DO: implement unit test setup
        Id rtId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Business').getRecordTypeId();
        // Arrange
        Account acc = new Account(Name='Test Account',RecordtypeId = rtId,Client_id__c = 'CLIENT123',Type='0',Account_Segment__c='E',Account_Sub_Segment__c='Y',Account_Channel__c='0',isschedule__c=true);
        insert acc;

        Schedule__c mysc = new Schedule__c();
        mysc.name = 'Account';
        mysc.Schedule_Time__c = '0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20;21;22;23';
        insert mysc;
    }
    
    @isTest
    static void myUnitTest() {
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        System.runAs(currentUser) {
            // TO DO: implement unit test
            ScheduleSFAWT17 sch = new ScheduleSFAWT17();
            sch.execute(null);
            system.assertEquals(UserInfo.getUserId(), currentUser.Id);
        }
    }
}