force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Accounts (City)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Convert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <description>Account Insurance</description>
    <label>Insurance</label>
-->
    <!---->
    <!---->
</RecordType>

force-app/main/default/objects/Asset/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premises Address / Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City/Regency</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Assets (City)</relationshipLabel>
    <relationshipName>Assets2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <formula>Text(Opportunity__r.COB__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Coordinate__c.field-meta.xml
<CustomField>
    <fullName>Coordinate__c</fullName>
    <label>Coordinate</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Eq_Zone__c.field-meta.xml
<CustomField>
    <fullName>Eq_Zone__c</fullName>
    <label>Earthquake Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/N_K_R__c.field-meta.xml
<CustomField>
    <fullName>N_K_R__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>N.K.R</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Risks (N.K.R)</relationshipLabel>
    <relationshipName>NKR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Occupation_Code__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Risk Type</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Risk_Description__c.field-meta.xml
<CustomField>
    <fullName>Risk_Description__c</fullName>
    <description>For COB 951 Risk Profile Section</description>
    <label>Risk Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/risk_situation__c.field-meta.xml
<CustomField>
    <fullName>risk_situation__c</fullName>
    <label>risk situation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master_Data__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Asset Section</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Risks (Section)</relationshipLabel>
    <relationshipName>Risks2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Road Bike</fullName>
            </value>
            <value>
                <fullName>Cruiser / City Bike</fullName>
            </value>
            <value>
                <fullName>Hybrid Bike</fullName>
            </value>
            <value>
                <fullName>BMX</fullName>
            </value>
            <value>
                <fullName>Fixie</fullName>
            </value>
            <value>
                <fullName>Folding Bike</fullName>
            </value>
            <value>
                <fullName>Electric Bike</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Code</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Assets (Zip Code)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <label>Risk</label>
</RecordType>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Master_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deductible Currency Section 4</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Insurance Policy Coverages (Deductible Currency Section 4)</relationshipLabel>
    <relationshipName>Insurance_Policy_Coverages4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Locations (Kabupaten)</relationshipLabel>
    <relationshipName>Locations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Earthquake_Zone__c.field-meta.xml
<CustomField>
    <fullName>Earthquake_Zone__c</fullName>
    <label>Earthquake Zone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Zip Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Locations (Zip Code)</relationshipLabel>
    <relationshipName>Locations4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/Master_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c/fields/ADDRESS__c.field-meta.xml
<CustomField>
    <fullName>ADDRESS__c</fullName>
    <label>ADDRESS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/BSN_ID__c.field-meta.xml
<CustomField>
    <fullName>BSN_ID__c</fullName>
    <label>BSN ID</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/EQ_ZONE__c.field-meta.xml
<CustomField>
    <fullName>EQ_ZONE__c</fullName>
    <label>EQ ZONE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Lookup_Object__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Object__c</fullName>
    <label>Lookup Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Occupation_Code__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Code__c</fullName>
    <label>Occupation Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Class_of_Business</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Risk_Description__c.field-meta.xml
<CustomField>
    <fullName>Risk_Description__c</fullName>
    <label>Risk Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Risk_Situation__c.field-meta.xml
<CustomField>
    <fullName>Risk_Situation__c</fullName>
    <label>Risk Situation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/showData__c.field-meta.xml
<CustomField>
    <fullName>showData__c</fullName>
    <label>showData</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/TYPE__c.field-meta.xml
<CustomField>
    <fullName>TYPE__c</fullName>
    <label>TYPE</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Wording__c.field-meta.xml
<CustomField>
    <fullName>Wording__c</fullName>
    <label>Wording</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/ZIP_CODE__c.field-meta.xml
<CustomField>
    <fullName>ZIP_CODE__c</fullName>
    <label>ZIP CODE</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/recordTypes/Coverage.recordType-meta.xml
<RecordType>
    <fullName>Coverage</fullName>
    <active>true</active>
    <label>Coverage</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Occupation_Code__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Occupation Code</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Products (Occupation Code)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Product Line)</relationshipLabel>
    <relationshipName>Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product Segment</fullName>
            </value>
            <value>
                <fullName>Product Class</fullName>
            </value>
            <value>
                <fullName>Product Line</fullName>
            </value>
            <value>
                <fullName>Product Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/globalValueSets/Class_of_Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marine Cargo</fullName>
    </customValue>
    <customValue>
        <fullName>201</fullName>
        <label>Fire</label>
    </customValue>
    <customValue>
        <fullName>Earthquake</fullName>
    </customValue>
    <customValue>
        <fullName>Terrorism And Sabotage</fullName>
    </customValue>
    <customValue>
        <fullName>301</fullName>
        <label>Motor Vehicle</label>
    </customValue>
    <customValue>
        <fullName>Heavy Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Aswata Motor</fullName>
    </customValue>
    <customValue>
        <fullName>Glass Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Burglary/Theft</fullName>
    </customValue>
    <customValue>
        <fullName>Hole In One</fullName>
    </customValue>
    <customValue>
        <fullName>Fidelity</fullName>
    </customValue>
    <customValue>
        <fullName>Moveable</fullName>
    </customValue>
    <customValue>
        <fullName>Billboard</fullName>
    </customValue>
    <customValue>
        <fullName>Growing Timber</fullName>
    </customValue>
    <customValue>
        <fullName>Oil Palm Plantation</fullName>
    </customValue>
    <customValue>
        <fullName>Rubber Plantation</fullName>
    </customValue>
    <customValue>
        <fullName>Sattelite</fullName>
    </customValue>
    <customValue>
        <fullName>Bike</fullName>
    </customValue>
    <customValue>
        <fullName>Liability - Public</fullName>
    </customValue>
    <customValue>
        <fullName>Liability - Product</fullName>
    </customValue>
    <customValue>
        <fullName>Liability - Comprehensive General</fullName>
    </customValue>
    <customValue>
        <fullName>Marine Hull</fullName>
    </customValue>
    <customValue>
        <fullName>Builder&apos;s Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation Hull</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation Loss of License</fullName>
    </customValue>
    <customValue>
        <fullName>Contractors All Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Erection All Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Machinery Breakdown</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Equipment Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Contractor&apos;s Plant &amp; Machinery</fullName>
    </customValue>
    <description>COB</description>
    <masterLabel>Class of Business</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClsNewRequest_Test.cls
@IsTest(SeeAllData=false)
public class ClsNewRequest_Test {
	@TestSetup
    static void setTestData(){
        Product2 pd = new Product2(); 
        pd.Name = 'Test';
        pd.ProductCode = '123';
        insert pd;
        
        Product2 pd2 = new Product2();
        pd2.Name = '2';
        pd2.ProductCode = '2';
        pd2.Product_Line__c = pd.Id;
        pd2.IsActive = true; 
        pd2.Type__c = 'Product Type';
        insert pd2;
        
        PriceBook2 pb = new PriceBook2();
        pb.name = 'test';
        pb.IsActive = TRUE;
        insert pb;
        
        Id standardPricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPriceEntry = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = pd.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert standardPriceEntry;
        
        PricebookEntry customPriceEntry = new PricebookEntry(
            Pricebook2Id = pb.Id,
            Product2Id = pd.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert customPriceEntry;
        
        String strRTIndividual = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Insurance').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'ACC12345';
        acc.RecordTypeId = strRTIndividual;
        insert acc;
        
        Account acc2 = new Account();
        acc2.Name = 'QQ';
        acc2.RecordTypeId = strRTIndividual;
        insert acc2;
        
        String RT1 = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Field COB').getRecordTypeId();
        Master_Data__c md = new Master_Data__c();
        md.RecordTypeId = RT1;
        md.BSN_ID__c = '201';
        md.Status__c = 'Active';
        md.Name = '1';
        md.Description__c = 'test';
        md.Wording__c = 'A,B,C';
        insert md;
        
        Master_Data__c md3 = new Master_Data__c();
        md3.RecordTypeId = RT1;
        md3.BSN_ID__c = '201';
        md3.Status__c = 'Active';
        md3.Name = 'Address__c';
        md3.Lookup_Object__c = 'Location';
        md3.showData__c = '[{"param1" : "Eq_Zone__c", "param2": "Earthquake_Zone__c"}]';
        insert md3;
        
        String RT2 = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Master Policy Wording').getRecordTypeId();
        Master_Data__c md2 = new Master_Data__c();
        md2.RecordTypeId = RT2;
        md2.Name = '2';
        md2.Product_Type_Id__c = pd.ProductCode;
        insert md2;
        
        String RT3 = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Exchange Rate').getRecordTypeId();
        Master_Data__c md4 = new Master_Data__c();
        md4.RecordTypeId = RT3;
        md4.Name = 'USD';
        md4.Exchange_Rate__c = 15000;
        insert md4;
        
        String RT4 = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Double Prospect').getRecordTypeId();
        Master_Data__c md5 = new Master_Data__c();
        md5.RecordTypeId = RT4;
        md5.Name = 'Test';
        md5.Risk_Description__c = 'Name';
        md5.Risk_Situation__c = 'Address__c,City__c,Zip_Code__c,N_K_R__c';
        md5.BSN_ID__c = '201';
        insert md5;
        
        String RT5 = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Asset Section').getRecordTypeId();
        Master_Data__c md6 = new Master_Data__c();
        md6.RecordTypeId = RT5;
        md6.Name = 'Test';
        md6.BSN_Id__c = '201';
        md6.Section__c = 1;
        insert md6;
        
        String RT6 = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Detail Asset').getRecordTypeId();
        Master_Data__c md7 = new Master_Data__c();
        md7.RecordTypeId = RT6;
        md7.Name = 'Test';
        md7.BSN_Id__c = '201';
        md7.Section__c = 1;
        md7.Status__c = 'Active';
        insert md7;
        
        ContentVersion contentVersion = new ContentVersion(
            Title          = 'a picture',
            PathOnClient   = 'Pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),            
            IsMajorVersion = true);
        insert contentVersion;
        
        Schema.Location l = new Schema.Location();
        l.name = 'Hawai';
        insert l;
    }
    
    @IsTest
    static void setTestMethod(){
       	Schema.Location l = [SELECT Id FROM Location LIMIT 1];
        Master_Data__c md = [SELECT Id FROM Master_Data__c WHERE Name = '1' LIMIT 1];
        Account acc = [SELECT Id FROM Account WHERE Name = 'ACC12345' LIMIT 1];
        Account acc2 = [SELECT Id FROM Account WHERE Name = 'QQ' LIMIT 1];
        Account acc1 = ClsNewRequest.getAccountDetail(acc.Id);
        List<Account> listacc = ClsNewRequest.searchQQAccounts('ACC');
        String cob = '201';
        String description = 'test';
        List<ClsNewRequest.data> listdata = ClsNewRequest.getMasterData(cob,description,'1');
        system.assertEquals(listdata.size(),1);
        ContentDocument cd = [SELECT Id FROM ContentDocument LIMIT 1];
        Product2 pd = [SELECT Id,ProductCode FROM Product2 LIMIT 1];
        string filter = pd.ProductCode;
        string producttype = pd.Id;
        ClsNewRequest.getPolicyWording(filter,producttype);
        ClsNewRequest.getProductType('123');
        ClsNewRequest.getPicklist('Product2','Type__c');
        ClsNewRequest.getObject('Address__c',cob,l.Id);
        ClsNewRequest.getWording(md.Id);
        ClsNewRequest.getRate('USD');
        Map<String, String> mapAssetSection = ClsNewRequest.getAssetSection(cob);
        List<String> keysAssetSection = new List<String>(mapAssetSection.keySet());
        ClsNewRequest.getAssetCategory(cob,null);
        ClsNewRequest.getMasterDataSection(cob,'1');
        ClsNewRequest.getCurrency();
        ClsNewRequest.getContract(acc.Id);
        ClsNewRequest.getAssetSectionMOU(null,'mou');
        ClsNewRequest.getAssetCategoryMOU(null,null,'mou');
        List<String> assetsection = new List<String>();
        assetsection.add('Material Damage');
        ClsNewRequest.getCoverage(null,assetsection,null,null,'mou');
        ClsNewRequest.getCoverageDetail(null,null,assetsection,'mou');
        Map<String,Object> mapObj = new Map<String,Object>();
        mapObj.put('section',1);
        InsurancePolicyCoverage ipc = new InsurancePolicyCoverage();
        ClsNewRequest.createCoverage(mapObj,ipc);
        mapObj.put('section',2);
        ClsNewRequest.createCoverage(mapObj,ipc);
        mapObj.put('section',3);
        ClsNewRequest.createCoverage(mapObj,ipc);
        mapObj.put('section',4);
        ClsNewRequest.createCoverage(mapObj,ipc);
        
        Master_Data__c mdSection = [SELECT Id FROM Master_Data__c WHERE Name = 'Test' AND RecordType.Name = 'Asset Section' LIMIT 1];
        ClsNewRequest.getMasterDataDetailAsset('1',mdSection.Id);
        List<String> listSectionids = new List<String>();
        listSectionids.add(mdSection.Id);
        ClsNewRequest.getSectionDetail(listSectionids);

        List<String> listdata1 = new List<String>();
        listdata1.add('Name'); 
        Asset ass = new Asset();
        ass.Name = 'Test';
        ClsNewRequest.setData(listdata1, ass);        
        
        String situation1 = '{';
        situation1 += '"COB__c":"'+cob+'"';
        situation1 += ',"Eq_Zone__c":"Test"';
        situation1 += ',"Coordinate__c":{"latitude":"10","longitude":"20"}';
        situation1 += '}';
        
        String summary1 = '{';
        summary1 += '"Occupation_Code__c":"'+md.Id+'"';
        summary1 += '}';
        
        String data = '{';
        data += '"opportunitytype":"NB"';
        data += ',"accountId":"'+acc.Id+'"';
        data += ',"insuredId":"'+acc.Id+'"';
        data += ',"qqmember":[{"Id":"'+acc2.Id+'"}]';
        data += ',"risk":"multiple"';
        data += ',"cob":"201"';
        data += ',"riskName":"Test"';
        data += ',"policywording":"Test"';
        data += ',"insuranceperiod":"1"';
        data += ',"startdateperiod":"2025-01-01"';
        data += ',"enddateperiod":"2026-01-01"';
        data += ',"yearperiod":"1"';
        data += ',"schematype":"Sum Insured Adjustment"';
        data += ',"transactionRows":[{"year":1,"percentage":"100","type":"1"}]';
        data += ',"description":"Test"';
        data += ',"annualperiod":"1"';
        data += ',"shortperiod":""';
        data += ',"percentageperiod":"1"';
        data += ',"rateperiod":1';
        data += ',"type":"Standard"';
        data += ',"contracttype":"1"';
        data += ',"risksituation1":' + JSON.serialize(situation1);
        data += ',"risk1":' + JSON.serialize(situation1);
        data += ',"producttype":"'+pd.Id+'"';
        data += ',"assetsection":"'+keysAssetSection.get(0)+'"';
        data += ',"asset1":[{"assetSectionId":"'+keysAssetSection.get(0)+'","coverage":[{"proposedFixedAmount":10000,"agentComission":"0","brokerComission":"0","maxPerson":"0"}]}]';
        data += ',"sumInsured":"1"';
        data += ',"premium":"1"';
        data += ',"summary1":' + JSON.serialize(summary1);
        data += ',"numberOfRisk":"1"';
        data += ',"closedDate":"2026-01-01"';
        data += ',"filequote1":[{"documentId":"'+cd.Id+'","name":"Test"}]';
        data += ',"fileclosing1":[{"documentId":"'+cd.Id+'","name":"Test"}]';
        data += ',"filesurvey1":[{"documentId":"'+cd.Id+'","name":"Test"}]';
        data += ',"riskName2":"Test"';
        data += ',"cob2":"201"';
        data += ',"policywording2":"Test"';
        data += ',"insuranceperiod2":"1"';
        data += ',"startdateperiod2":"2025-01-01"';
        data += ',"enddateperiod2":"2026-01-01"';
        data += ',"schematype2":"Sum Insured Adjustment"';
        data += ',"transactionRows2":[{"year":1,"percentage":"100","type":"1"}]';
        data += ',"description2":"Test"';
        data += ',"yearperiod2":"1"';
        data += ',"annualperiod2":"1"';
        data += ',"shortperiod2":""';
        data += ',"percentageperiod2":"1"';
        data += ',"rateperiod2":1';
        data += ',"type2":"Standard"';
        data += ',"contracttype2":"1"'; 
        data += ',"risksituation2":' + JSON.serialize(situation1);
        data += ',"producttype2":"'+pd.Id+'"';
        data += ',"assetsection2":"'+keysAssetSection.get(0)+'"';
        data += ',"sumInsured2":"1"';
        data += ',"premium2":"1"';
        data += ',"summary2":' + JSON.serialize(summary1);
        data += ',"numberOfRisk2":"1"';
        data += ',"closedDate2":"2026-01-01"';
        data += ',"filequote2":[{"documentId":"'+cd.Id+'","name":"Test"}]';
        data += ',"fileclosing2":[{"documentId":"'+cd.Id+'","name":"Test"}]';
        data += ',"filesurvey2":[{"documentId":"'+cd.Id+'","name":"Test"}]';
        data += '}';
        ClsNewRequest.getValidateDouble(data);
        string result = ClsNewRequest.saveData(data);
        system.debug('result:'+result);
        system.assertNotEquals(result,null);
        String data2 = data.replaceAll('Standard','MOU');
        string result2 = ClsNewRequest.saveData(data2);
        String data3 = data.replaceAll('Standard','Realisasi');
        string result3 = ClsNewRequest.saveData(data3);
        ClsNewRequest.deleteFile(cd.Id);
        ClsNewRequest.getOpportunity(result); 
        ClsNewRequest.getSectionAmount(result,'Material Damage',null);
    }
    
    @IsTest
    static void setTestMethod2(){
        ContentDocument cd = [SELECT Id FROM ContentDocument LIMIT 1];
        List<String> listData = new List<String>();
        listData.add(cd.Id);
        ClsNewRequest.deleteFiles(JSON.serialize(listData));
    }
}