force-app/main/default/objects/Account/fields/SCC_Address__c.field-meta.xml
<CustomField>
    <fullName>SCC_Address__c</fullName>
    <description>This address will hold Value is concatenated from all of the API Fields, concatenated by alamatId1,alamatId2,alamatId3,alamatId4</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCC_Tipe_Nasabah__c.field-meta.xml
<CustomField>
    <fullName>SCC_Tipe_Nasabah__c</fullName>
    <description>Is the Customer Type (Indvidual/ Non-Individual).</description>
    <label>Tipe Nasabah</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individu</fullName>
            </value>
            <value>
                <fullName>Non-Individu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTrigger_Test.cls
@isTest
public class AccountTrigger_Test {
    @isTest
    static void testFormatPhoneAccount() {
        Account acc = new Account(
            Name = 'Test Account', 
            SCC_Address__c = 'Nama Jalan',
            SCC_Tipe_Nasabah__c='Individu', 
            Phone = '6281299928812');
        insert acc;
        
        Account acc2 = [SELECT Id, Phone FROM Account WHERE SCC_Address__c = 'Nama Jalan'];
        System.assertEquals(acc2.Phone, '081299928812', 'Number is in the correct format');
        
        acc2.Phone = '6281299628812';
        update acc2;
        
        Account acc3 = [SELECT Id, Phone FROM Account WHERE SCC_Address__c = 'Nama Jalan'];
        System.assertEquals(acc3.Phone, '081299628812', 'Number is in the correct format');
        
        Account acc4 = new Account(Name = 'Test Account 2', SCC_Address__c = 'Nama Jalan 2', SCC_Tipe_Nasabah__c='Individu');
        insert acc4;
        
        Account acc5 = [SELECT Id, Phone FROM Account WHERE SCC_Address__c = 'Nama Jalan 2'];
        System.assertEquals(acc5.Phone, null, 'Number should be null');
    }
}