force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Convert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <description>Account Insurance</description>
    <label>Insurance</label>
-->
    <!---->
    <!---->
</RecordType>

force-app/main/default/objects/Master_Data__c/Master_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c/fields/AUTHORITY_TYPE__c.field-meta.xml
<CustomField>
    <fullName>AUTHORITY_TYPE__c</fullName>
    <label>AUTHORITY TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UW</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>Policy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/LIMIT_AMOUNT__c.field-meta.xml
<CustomField>
    <fullName>LIMIT_AMOUNT__c</fullName>
    <label>LIMIT AMOUNT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/USER_ID__c.field-meta.xml
<CustomField>
    <fullName>USER_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>USER ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>Sum_Insured__c</fullName>
    <label>Sum Insured</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/USER_ID__c.field-meta.xml
<CustomField>
    <fullName>USER_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Policy Distribution = Operation Support</description>
    <label>USER ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ID__c.field-meta.xml
<CustomField>
    <fullName>USER_ID__c</fullName>
    <externalId>true</externalId>
    <label>USER ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ClsUserLimit_Test.cls
@IsTest(SeeAllData=false)
public class ClsUserLimit_Test {
	@TestSetup
    static void setTestData(){
        String strRTIndividual = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Insurance').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'ACC12345';
        acc.RecordTypeId = strRTIndividual;
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.AccountId = acc.Id;
        opp.StageName = 'Proposal';
        opp.CloseDate = Date.Today();
        opp.Sum_Insured__c = 100000;
        insert opp;
        
        Quote qu = new Quote();
        qu.OpportunityId = opp.Id;
        qu.Name = 'Test';
        insert qu;
        
        String strRTMd = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Approval Limit').getRecordTypeId();
        Master_Data__c md = new Master_Data__c();
        md.RecordTypeId = strRTMd;
        md.AUTHORITY_TYPE__c = 'UW';
        md.LIMIT_AMOUNT__c = 1000000;
        md.Status__c = 'Approved';
        md.USER_ID__c = UserInfo.GetUserId();
        insert md;
    }
    
    @IsTest
    static void setTestMethod(){
        User u = [SELECT Id FROM User WHERE Id=:UserInfo.getUserId()];
        System.runAs(u){
            Test.startTest();
            Quote qu = [SELECT Id FROM Quote LIMIT 1];
            List<ID> ids = new List<ID>();
            ids.Add(qu.Id);
            List<string> listdata = ClsUserLimit.getUserIds(ids);
            system.assertEquals(listdata.size(),1);
            Test.stopTest();
        }
    }
}