force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Convert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <description>Account Insurance</description>
    <label>Insurance</label>
-->
    <!---->
    <!---->
</RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BO</fullName>
                <label>Beneficial Owner / Pihak Pengendali Akhir</label>
            </value>
            <value>
                <fullName>CP</fullName>
                <label>Contact Person</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/Master_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c/fields/AUTHORITY_TYPE__c.field-meta.xml
<CustomField>
    <fullName>AUTHORITY_TYPE__c</fullName>
    <label>AUTHORITY TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UW</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>Policy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/BSN_ID__c.field-meta.xml
<CustomField>
    <fullName>BSN_ID__c</fullName>
    <label>BSN ID</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/LIMIT_AMOUNT__c.field-meta.xml
<CustomField>
    <fullName>LIMIT_AMOUNT__c</fullName>
    <label>LIMIT AMOUNT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/showData__c.field-meta.xml
<CustomField>
    <fullName>showData__c</fullName>
    <label>showData</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/USER_ID__c.field-meta.xml
<CustomField>
    <fullName>USER_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>USER ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/fields/USER_PIC__c.field-meta.xml
<CustomField>
    <fullName>USER_PIC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>USER PIC</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Master Data</relationshipLabel>
    <relationshipName>Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bsn_ID__c.field-meta.xml
<CustomField>
    <fullName>Bsn_ID__c</fullName>
    <label>Bsn ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/COB__c.field-meta.xml
<CustomField>
    <fullName>COB__c</fullName>
    <label>COB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>Sum_Insured__c</fullName>
    <label>Sum Insured</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>Total_Sum_Insured__c</fullName>
    <label>Total Sum Insured</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/USER_ID__c.field-meta.xml
<CustomField>
    <fullName>USER_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Policy Distribution = Operation Support</description>
    <label>USER ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/USER_PIC__c.field-meta.xml
<CustomField>
    <fullName>USER_PIC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Operation Support</description>
    <label>USER PIC</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (USER PIC)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>Total_Sum_Insured__c</fullName>
    <formula>Opportunity.Total_Sum_Insured__c</formula>
    <label>Total Sum Insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ID__c.field-meta.xml
<CustomField>
    <fullName>USER_ID__c</fullName>
    <externalId>true</externalId>
    <label>USER ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ClsPolicyDistribution_Test.cls
@IsTest(SeeAllData=false)
public class ClsPolicyDistribution_Test {
    @TestSetup
    static void setTestData(){
        String strRTIndividual = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Insurance').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'ACC12345';
        acc.RecordTypeId = strRTIndividual;
        insert acc;
        
        Contact ct = new Contact();
        ct.AccountId = acc.Id;
        ct.LastName = 'Test';
        insert ct;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.AccountId = acc.Id;
        opp.StageName = 'Proposal';
        opp.CloseDate = Date.Today();
        opp.Sum_Insured__c = 100000;
        opp.Total_Sum_Insured__c = 100000;
        opp.COB__c = '201';
        insert opp;
        
        String strRTMd = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Policy Distribution').getRecordTypeId();
        Master_Data__c md = new Master_Data__c();
        md.RecordTypeId = strRTMd;
        md.AUTHORITY_TYPE__c = 'UW';
        md.LIMIT_AMOUNT__c = 100000;
        md.Status__c = 'Approved';
        md.BSN_ID__c = '201';
        md.USER_PIC__c = ct.Id;
        md.USER_ID__c = UserInfo.getUserId();
        insert md;
        
        String strRT2 = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Filter Policy Distribution').getRecordTypeId();
        Master_Data__c md2 = new Master_Data__c();
        md2.BSN_ID__c = '201';
        md2.Status__c = 'Active';
        md2.showData__c = '[{"param1":"BSN_ID__c","param2":"COB__c"}]';
        md2.RecordTypeId = strRT2;
        insert md2;
        
        Quote qu = new Quote();
        qu.OpportunityId = opp.Id;
        qu.Name = 'Test';
        insert qu;
    }
    
    @IsTest
    static void setTestMethod(){
        User u = [SELECT Id FROM User WHERE Id=:UserInfo.getUserId()];
        System.runAs(u){
            Test.startTest();
            Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
            Quote qu = [SELECT Id FROM Quote LIMIT 1];
            ClsPolicyDistribution.data data = ClsPolicyDistribution.getUserIdFilter(opp.Id);
            system.assertNotEquals(data.userid,null);
            List<ID> ids = new List<ID>();
            ids.add(qu.Id);
            ClsPolicyDistribution.getUserIds(ids);
            Test.stopTest();
        }
    }
}