force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Convert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Account_Number__c</fullName>
    <description>Migration.The account number or credit card number</description>
    <label>Nomor Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Amount__c.field-meta.xml
<CustomField>
    <fullName>SCC_Amount__c</fullName>
    <description>The amount from the dispute transaction</description>
    <label>Nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>SCC_Card_Number__c</fullName>
    <label>Nomor Kartu</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Cust_Phone1__c.field-meta.xml
<CustomField>
    <fullName>SCC_Cust_Phone1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Waktu_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Waktu_Transaksi__c</fullName>
    <label>Waktu Transaksi</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SSC_Call_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>SSC_Call_Type_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Deskripsi Case</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drone__c/Drone__c.object-meta.xml
<CustomObject>
    <label>Drone</label>
    <nameField>
        <displayFormat>D{0000000}</displayFormat>
        <label>Drone No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drone__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Drone</relationshipLabel>
    <relationshipName>Drone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drone__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Sch_SendToDroneTest.cls
@isTest
public class Sch_SendToDroneTest {
	@testSetup static void setup(){
        Account acc = new Account();
        acc.LastName = 'Test';
        insert acc;
        
        Case cs = new Case();
        cs.Subject = 'Test';
        cs.Description = 'Test';
        cs.SCC_Waktu_Transaksi__c = DateTime.Now();
        cs.AccountId = acc.Id;
        cs.SCC_Cust_Phone1__c = '123456789012';
        cs.SCC_Amount__c = 1000000;
        cs.SCC_Card_Number__c = '1234567890123456';
        cs.SCC_Account_Number__c = '1234567890123456';
        cs.SSC_Call_Type_Description__c = 'Test';
        insert cs;      
        
        Drone__c d = new Drone__c();
        d.Case__c = cs.Id;
        d.Status__c = 'Draft';
        d.Method__c = 'Insert';
        insert d;
        
        Drone__c d2 = new Drone__c();
        d2.Case__c = cs.Id;
        d2.Status__c = 'Draft';
        d2.Method__c = 'Update';
        insert d2;
    }
    
    static testMethod void testProcess(){
        Case cs = [SELECT Id FROM Case LIMIT 1];
        SCC_InvocableDrone.Invocablevoid(null);
        SCC_InvocableDrone.createTicketDrone(cs.Id);
        SCC_InvocableDrone.updateTicketDrone(cs.Id);
        
        Test.setMock(HttpCalloutMock.class, new Cls_HttpMockTest());
        Test.startTest();
        system.schedule('Send To Drone 0', '0 0 * * * ?', new Sch_SendToDrone());
        Test.stopTest();
    }
}