force-app/main/default/objects/SCC_Nota_Manual__c/SCC_Nota_Manual__c.object-meta.xml
<CustomObject>
    <label>Nota Analisa</label>
    <nameField>
        <displayFormat>NOTA-{0000000000}</displayFormat>
        <label>Nota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nota Analisa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Nota_Manual</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Branchcode__c.field-meta.xml
<CustomField>
    <fullName>SCC_Branchcode__c</fullName>
    <label>Branchcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Jenis_Transaksi__c.field-meta.xml
<CustomField>
    <fullName>SCC_Jenis_Transaksi__c</fullName>
    <label>Jenis Transaksi</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Jumlah_Debit__c.field-meta.xml
<CustomField>
    <fullName>SCC_Jumlah_Debit__c</fullName>
    <label>Jumlah</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Jumlah_Fee__c.field-meta.xml
<CustomField>
    <fullName>SCC_Jumlah_Fee__c</fullName>
    <label>Jumlah Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Jumlah_Kredit__c.field-meta.xml
<CustomField>
    <fullName>SCC_Jumlah_Kredit__c</fullName>
    <label>Jumlah</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Keterangan__c.field-meta.xml
<CustomField>
    <fullName>SCC_Keterangan__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Keterangan</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Nama_Nasabah__c.field-meta.xml
<CustomField>
    <fullName>SCC_Nama_Nasabah__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nama Nasabah</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_No_Kartu__c.field-meta.xml
<CustomField>
    <fullName>SCC_No_Kartu__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>No. Kartu</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_No_Rekening__c.field-meta.xml
<CustomField>
    <fullName>SCC_No_Rekening__c</fullName>
    <label>No. Rekening</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_No_Telepon__c.field-meta.xml
<CustomField>
    <fullName>SCC_No_Telepon__c</fullName>
    <label>No. Telpon</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Rekening_Fee__c.field-meta.xml
<CustomField>
    <fullName>SCC_Rekening_Fee__c</fullName>
    <label>Rekening Fee</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Rekening_Nasabah__c.field-meta.xml
<CustomField>
    <fullName>SCC_Rekening_Nasabah__c</fullName>
    <label>Rekening Nasabah</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Nota_Manual__c/fields/SCC_Rekening_Titipan__c.field-meta.xml
<CustomField>
    <fullName>SCC_Rekening_Titipan__c</fullName>
    <label>Rekening Titipan</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Queuetrans__c/SCC_Queuetrans__c.object-meta.xml
<CustomObject>
    <label>SCC Queuetrans</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCC Queuetrans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SCC_Queuetrans__c/fields/scc_amt_debet1__c.field-meta.xml
<CustomField>
    <fullName>scc_amt_debet1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>amt_debet1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Queuetrans__c/fields/scc_amt_kredit1__c.field-meta.xml
<CustomField>
    <fullName>scc_amt_kredit1__c</fullName>
    <label>amt_kredit1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Queuetrans__c/fields/scc_branchcode__c.field-meta.xml
<CustomField>
    <fullName>scc_branchcode__c</fullName>
    <defaultValue>&apos;CHMS&apos;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>branchcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Queuetrans__c/fields/SCC_Case__c.field-meta.xml
<CustomField>
    <fullName>SCC_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SCC Queuetrans</relationshipLabel>
    <relationshipName>SCC_Queuetrans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SCC_EditNotaController.cls
public class SCC_EditNotaController {
    @AuraEnabled
    public static SCC_Nota_Manual__c getNotaManual(Id caseId) {
        return [SELECT Id, 
                SCC_Jenis_Transaksi__c, 
                SCC_No_Rekening__c, 
                SCC_No_Telepon__c, 
                SCC_Nama_Nasabah__c, 
                SCC_No_Kartu__c, 
                SCC_Branchcode__c, 
                SCC_Keterangan__c, 
                SCC_Rekening_Titipan__c, 
                SCC_Jumlah_Debit__c, 
                SCC_Rekening_Fee__c, 
                SCC_Jumlah_Fee__c,
                SCC_Jumlah_Kredit__c,
                SCC_Rekening_Nasabah__c,
                Case__c
                FROM SCC_Nota_Manual__c WHERE Case__c = :caseId LIMIT 1];
    }

    @AuraEnabled
    public static SCC_Nota_Manual__c updateNotaManualFromForm(SCC_Nota_Manual__c notaManual) {
        try {
            Decimal jumlahDebit = notaManual.SCC_Jumlah_Debit__c;
            Decimal jumlahKredit = notaManual.SCC_Jumlah_Debit__c;
            Id caseId = notaManual.Case__c;

            System.debug('Jumlah Debit: ' + jumlahDebit);
            System.debug('Jumlah Kredit: ' + jumlahKredit);
            System.debug('Case Id: ' + caseId);
            
            update notaManual;
            System.debug('Nota Manual updated: ' + notaManual);

            List<SCC_Queuetrans__c> queuetransList = [SELECT Id, scc_amt_debet1__c, scc_amt_kredit1__c
                                                      FROM SCC_Queuetrans__c
                                                      WHERE scc_case__c = :caseId];

            System.debug('QueueTrans records found: ' + queuetransList.size());

            for (SCC_Queuetrans__c queuetrans : queuetransList) {
                System.debug('Before update QueueTrans record: ' + queuetrans);
                queuetrans.scc_amt_debet1__c = String.valueOf(jumlahDebit);
                queuetrans.scc_amt_kredit1__c = String.valueOf(jumlahDebit);
                System.debug('After update QueueTrans record: ' + queuetrans);
            }

            if (!queuetransList.isEmpty()) {
                update queuetransList;
                System.debug('QueueTrans records updated: ' + queuetransList);
            }

            return notaManual;
        } catch(Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException('Gagal memperbarui / mengupdate manual nota: ' + e.getMessage());
        }
    }
}