force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Customer_Segment__c</fullName>
    <description>Consists of the type of segment of the case.</description>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level1_Escalation_team__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level1_Escalation_team__c</fullName>
    <description>This field indicates the escalation team for level 1</description>
    <label>Level 1 Escalation Team</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level2_Escalation_team__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level2_Escalation_team__c</fullName>
    <description>This indicates the escalation team for level 2</description>
    <label>Level 2 Escalation Team</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level3_Escalation_team__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level3_Escalation_team__c</fullName>
    <description>This indicates the escalation team for level 3</description>
    <label>Level 3 Escalation Team</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level4_Escalation_team__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level4_Escalation_team__c</fullName>
    <description>This indicates the escalation team for level 4</description>
    <label>Level 4 Escalation Team</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Category__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complaint - Non-Transaction</fullName>
            </value>
            <value>
                <fullName>Complaint - Transaction</fullName>
            </value>
            <value>
                <fullName>Customer Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud / Suspicious Transactions</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Platform &amp; Device Support</fullName>
            </value>
            <value>
                <fullName>Products / Promotion Inquiry</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Third Party Support</fullName>
            </value>
            <value>
                <fullName>Customer Feedback / Sentiment Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Description__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Description__c</fullName>
    <label>Deskripsi Case</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L1__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L1__c</fullName>
    <label>Product Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Transaction Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L2__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L2__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SSC_Product_L1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bancassurance</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Deposito</fullName>
            </value>
            <value>
                <fullName>Digital Savings</fullName>
            </value>
            <value>
                <fullName>DPLK (Pension Fund)</fullName>
            </value>
            <value>
                <fullName>Electronic Money</fullName>
            </value>
            <value>
                <fullName>Giro (CA)</fullName>
            </value>
            <value>
                <fullName>Government Programme</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>Kartu Debit</fullName>
            </value>
            <value>
                <fullName>Kartu Kredit</fullName>
            </value>
            <value>
                <fullName>KPR (Mortgage)</fullName>
            </value>
            <value>
                <fullName>Kredit Investasi (Investment Loan)</fullName>
            </value>
            <value>
                <fullName>Kredit Modal Kerja (Working Capital)</fullName>
            </value>
            <value>
                <fullName>KTA (Personal Loan)</fullName>
            </value>
            <value>
                <fullName>KTA - Digital</fullName>
            </value>
            <value>
                <fullName>KUR (Business Loan - Micro)</fullName>
            </value>
            <value>
                <fullName>Mobile Banking</fullName>
            </value>
            <value>
                <fullName>Pawning</fullName>
            </value>
            <value>
                <fullName>Safe Deposit</fullName>
            </value>
            <value>
                <fullName>SBN (Bonds)</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Cabang</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Contact Center</fullName>
            </value>
            <value>
                <fullName>Tabungan</fullName>
            </value>
            <value>
                <fullName>Virtual Account</fullName>
            </value>
            <value>
                <fullName>Aplikasi Commodity Chain</fullName>
            </value>
            <value>
                <fullName>Informasi Promo, Program, Produk</fullName>
            </value>
            <value>
                <fullName>PPID</fullName>
            </value>
            <value>
                <fullName>Senyum Mobile</fullName>
            </value>
            <value>
                <fullName>Trustee &amp; Wali Amanat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SCC_QueueController_Test.cls
/**
 * @description       : Test Class for SCC_QueueController
 * @last modified on  : 03-06-2025
 * @last modified by  : Ahmad Yazid Munif
 */
@isTest
private class SCC_QueueController_Test {
    @TestSetup
    static void makeData(){
        Group groupQueue = new Group();
        groupQueue.Name = 'TestQueue';
        groupQueue.Type = 'Queue';
        insert groupQueue;

        SSC_Call_Type__c callType = new SSC_Call_Type__c(
            Name = '8412',
            External_Id__c = '8412',
            SCC_Customer_Segment__c = 'Segment 1',
            SSC_Product_L1__c = 'Savings',
            SSC_Product_L2__c = 'Digital Savings',
            SSC_Case_Category__c = 'Inquiry',
            SSC_Case_Description__c = 'Description 1',
            Active__c = true);
        insert callType;
    }
    @isTest
    static void testSearchQueueNames() {
        Test.startTest();
        List<String> result = SCC_QueueController.searchQueueNames('TestQueue');
        Test.stopTest();

        System.assertNotEquals(0, result.size(), 'Queue list kosong');
        System.assertEquals('TestQueue', result[0], 'Nama queue tidak sesuai');
    }
    @IsTest
    static void testSaveQueueToCustomObjectLevel1() {
        SSC_Call_Type__c resultTestRecord = [SELECT id FROM SSC_Call_Type__c LIMIT 1];
        String customObjectId = resultTestRecord.Id;
        Test.startTest();
        SCC_QueueController.saveQueueToCustomObject(customObjectId, 'TestQueue', 'SCC_Level1_Escalation_team__c');
        Test.stopTest();

        SSC_Call_Type__c getUpdatedRecord = [SELECT 
                                            Id, 
                                            SCC_Level1_Escalation_team__c,
                                            SCC_Level2_Escalation_team__c,
                                            SCC_Level3_Escalation_team__c,
                                            SCC_Level4_Escalation_team__c
                                            FROM SSC_Call_Type__c 
                                            WHERE Id = :customObjectId
                                            LIMIT 1
                                        ];
        System.assertEquals('TestQueue', getUpdatedRecord.SCC_Level1_Escalation_team__c, 'Queue name tidak tersimpan dengan benar');
    }
    @IsTest
    static void testSaveQueueToCustomObjectLevel2() {
        SSC_Call_Type__c resultTestRecord = [SELECT id FROM SSC_Call_Type__c LIMIT 1];
        String customObjectId = resultTestRecord.Id;
        Test.startTest();
        SCC_QueueController.saveQueueToCustomObject(customObjectId, 'TestQueue', 'SCC_Level2_Escalation_team__c');
        Test.stopTest();

        SSC_Call_Type__c getUpdatedRecord = [SELECT 
                                            Id, 
                                            SCC_Level1_Escalation_team__c,
                                            SCC_Level2_Escalation_team__c,
                                            SCC_Level3_Escalation_team__c,
                                            SCC_Level4_Escalation_team__c
                                            FROM SSC_Call_Type__c 
                                            WHERE Id = :customObjectId
                                            LIMIT 1
                                        ];
        System.assertEquals('TestQueue', getUpdatedRecord.SCC_Level2_Escalation_team__c, 'Queue name tidak tersimpan dengan benar');
    }
    @IsTest
    static void testSaveQueueToCustomObjectLevel3() {
        SSC_Call_Type__c resultTestRecord = [SELECT id FROM SSC_Call_Type__c LIMIT 1];
        String customObjectId = resultTestRecord.Id;
        Test.startTest();
        SCC_QueueController.saveQueueToCustomObject(customObjectId, 'TestQueue', 'SCC_Level3_Escalation_team__c');
        Test.stopTest();

        SSC_Call_Type__c getUpdatedRecord = [SELECT 
                                            Id, 
                                            SCC_Level1_Escalation_team__c,
                                            SCC_Level2_Escalation_team__c,
                                            SCC_Level3_Escalation_team__c,
                                            SCC_Level4_Escalation_team__c
                                            FROM SSC_Call_Type__c 
                                            WHERE Id = :customObjectId
                                            LIMIT 1
                                        ];
        System.assertEquals('TestQueue', getUpdatedRecord.SCC_Level3_Escalation_team__c, 'Queue name tidak tersimpan dengan benar');
    }
    @IsTest
    static void testSaveQueueToCustomObjectLevel4() {
        SSC_Call_Type__c resultTestRecord = [SELECT id FROM SSC_Call_Type__c LIMIT 1];
        String customObjectId = resultTestRecord.Id;
        Test.startTest();
        SCC_QueueController.saveQueueToCustomObject(customObjectId, 'TestQueue', 'SCC_Level4_Escalation_team__c');
        Test.stopTest();

        SSC_Call_Type__c getUpdatedRecord = [SELECT 
                                            Id, 
                                            SCC_Level1_Escalation_team__c,
                                            SCC_Level2_Escalation_team__c,
                                            SCC_Level3_Escalation_team__c,
                                            SCC_Level4_Escalation_team__c
                                            FROM SSC_Call_Type__c 
                                            WHERE Id = :customObjectId
                                            LIMIT 1
                                        ];
        System.assertEquals('TestQueue', getUpdatedRecord.SCC_Level4_Escalation_team__c, 'Queue name tidak tersimpan dengan benar');
    }
}