force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>SCC_Customer_Segment__c</fullName>
    <description>Consists of the type of segment of the case.</description>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individu Umum</fullName>
            </value>
            <value>
                <fullName>Individu Priority &amp; Private</fullName>
            </value>
            <value>
                <fullName>UMKM</fullName>
            </value>
            <value>
                <fullName>Korporasi</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Level1_OLA__c.field-meta.xml
<CustomField>
    <fullName>SCC_Level1_OLA__c</fullName>
    <description>This is the OLA for Level 1</description>
    <label>Level 1 OLA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SCC_Sub_Description__c.field-meta.xml
<CustomField>
    <fullName>SCC_Sub_Description__c</fullName>
    <description>This fields allows agent to add sub-description</description>
    <label>Sub Case Reference</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Category__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complaint - Non-Transaction</fullName>
            </value>
            <value>
                <fullName>Complaint - Transaction</fullName>
            </value>
            <value>
                <fullName>Customer Feedback</fullName>
            </value>
            <value>
                <fullName>Fraud / Suspicious Transactions</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Platform &amp; Device Support</fullName>
            </value>
            <value>
                <fullName>Products / Promotion Inquiry</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Third Party Support</fullName>
            </value>
            <value>
                <fullName>Customer Feedback / Sentiment Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Description__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Description__c</fullName>
    <label>Deskripsi Case</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L1__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L1__c</fullName>
    <label>Product Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Transaction Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Product_L2__c.field-meta.xml
<CustomField>
    <fullName>SSC_Product_L2__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SSC_Product_L1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bancassurance</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Deposito</fullName>
            </value>
            <value>
                <fullName>Digital Savings</fullName>
            </value>
            <value>
                <fullName>DPLK (Pension Fund)</fullName>
            </value>
            <value>
                <fullName>Electronic Money</fullName>
            </value>
            <value>
                <fullName>Giro (CA)</fullName>
            </value>
            <value>
                <fullName>Government Programme</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>Kartu Debit</fullName>
            </value>
            <value>
                <fullName>Kartu Kredit</fullName>
            </value>
            <value>
                <fullName>KPR (Mortgage)</fullName>
            </value>
            <value>
                <fullName>Kredit Investasi (Investment Loan)</fullName>
            </value>
            <value>
                <fullName>Kredit Modal Kerja (Working Capital)</fullName>
            </value>
            <value>
                <fullName>KTA (Personal Loan)</fullName>
            </value>
            <value>
                <fullName>KTA - Digital</fullName>
            </value>
            <value>
                <fullName>KUR (Business Loan - Micro)</fullName>
            </value>
            <value>
                <fullName>Mobile Banking</fullName>
            </value>
            <value>
                <fullName>Pawning</fullName>
            </value>
            <value>
                <fullName>Safe Deposit</fullName>
            </value>
            <value>
                <fullName>SBN (Bonds)</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Cabang</fullName>
            </value>
            <value>
                <fullName>Servicing - Layanan Contact Center</fullName>
            </value>
            <value>
                <fullName>Tabungan</fullName>
            </value>
            <value>
                <fullName>Virtual Account</fullName>
            </value>
            <value>
                <fullName>Aplikasi Commodity Chain</fullName>
            </value>
            <value>
                <fullName>Informasi Promo, Program, Produk</fullName>
            </value>
            <value>
                <fullName>PPID</fullName>
            </value>
            <value>
                <fullName>Senyum Mobile</fullName>
            </value>
            <value>
                <fullName>Trustee &amp; Wali Amanat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sub_Case_Reference__c/Sub_Case_Reference__c.object-meta.xml
<CustomObject>
    <label>Sub Case Reference</label>
    <nameField>
        <label>Sub Case Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Case References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Case_Reference__c/fields/Sub_Case_Code__c.field-meta.xml
<CustomField>
    <fullName>Sub_Case_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sub Case Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteSubCaseMasterDataTest.cls
@isTest
public with sharing class DeleteSubCaseMasterDataTest {
    @isTest
    public static void testdelete()
    {
        SSC_Call_Type__c callTypeRecord = new SSC_Call_Type__c(
            Name = 'Test Call Type',
            SCC_Sub_Description__c = 'SCR1',
             SCC_Level1_OLA__c = 1,
            SSC_Case_Description__c	 = 'xyz',
            External_Id__c = '8812',
            SCC_Customer_Segment__c = 'UMKM',
            SSC_Product_L1__c = 'Servicing',
            SSC_Product_L2__c = 'Cash Management',
            SSC_Case_Category__c = 'Request'//
        );
        insert callTypeRecord;

        SSC_Call_Type__c callTypeRecord2 = new SSC_Call_Type__c(
            Name = 'Test Call Type 2',
            SCC_Sub_Description__c = 'SCR1;SCR2',
             SCC_Level1_OLA__c = 1,
            SSC_Case_Description__c	 = 'xyz',
            External_Id__c = '88126',
            SCC_Customer_Segment__c = 'UMKM',
            SSC_Product_L1__c = 'Servicing',
            SSC_Product_L2__c = 'Cash Management',
            SSC_Case_Category__c = 'Request'//
        );
        insert callTypeRecord2;
    Sub_Case_Reference__c SCR=new Sub_Case_Reference__c();
    SCR.name='Nama';
    SCR.sub_case_code__c='SCR1';
    insert SCR;
    delete SCR;
    }
}