force-app/main/default/objects/Drone__c/Drone__c.object-meta.xml
<CustomObject>
    <label>Drone</label>
    <nameField>
        <displayFormat>D{0000000}</displayFormat>
        <label>Drone No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drone__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Drone</relationshipLabel>
    <relationshipName>Drone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drone__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Cls_Batch_SendToDrone.cls
global class Cls_Batch_SendToDrone implements Database.AllowsCallouts,Database.Batchable<Drone__c>{
	public List<Drone__c> recordset = new List<Drone__c>();
    
    global Cls_Batch_SendToDrone(List<Drone__c> recordget){
        recordset = recordget;          
    }
    
    global List<Drone__c> start(Database.BatchableContext BC){
        return recordset;
    }
    
    global void execute(Database.BatchableContext BC, List<Drone__c> scope){
        List<Drone__c> listdata = new List<Drone__c>();
        for(Drone__c d : scope){
            if(d.Case__c != null){
                if(d.Method__c == 'Insert') SCC_InvocableDrone.sendCreateToDrone(d.Case__c);
                else if(d.Method__c == 'Update') SCC_InvocableDrone.sendUpdateToDrone(d.Case__c);
                d.Status__c = 'Send';
                listdata.add(d);
            }
        }      
        if(listdata.size()>0) update listdata;
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}