force-app/main/default/objects/Cuti_Karyawan__c/Cuti_Karyawan__c.object-meta.xml
<CustomObject>
    <description>digunakan untuk menyimpan data cuti tahunan yang diupload oleh admin</description>
    <label>Master Cuti Karyawan</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Cuti Karyawan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuti_Karyawan__c/fields/Cuti_Poin_Karyawan__c.field-meta.xml
<CustomField>
    <fullName>Cuti_Poin_Karyawan__c</fullName>
    <label>Cuti &amp; Poin Karyawan</label>
    <referenceTo>Cuti_Poin_Karyawan__c</referenceTo>
    <relationshipLabel>Master Cuti Karyawan</relationshipLabel>
    <relationshipName>Cuti_Karyawan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuti_Karyawan__c/fields/Nama_Karyawan__c.field-meta.xml
<CustomField>
    <fullName>Nama_Karyawan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nama Karyawan</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuti_Karyawan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuti_Karyawan__c/fields/Quota_Cuti__c.field-meta.xml
<CustomField>
    <fullName>Quota_Cuti__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quota Cuti</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cuti_Karyawan__c/fields/Sisa_Cuti__c.field-meta.xml
<CustomField>
    <fullName>Sisa_Cuti__c</fullName>
    <formula>(Quota_Cuti__c) - Cuti_Terpakai__c +  Hutang_Cuti__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sisa Cuti</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cuti_Karyawan__c/fields/Tahun__c.field-meta.xml
<CustomField>
    <fullName>Tahun__c</fullName>
    <defaultValue>YEAR( TODAY() )</defaultValue>
    <label>Tahun Num</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cuti_Karyawan__c/fields/Tahun_Cuti__c.field-meta.xml
<CustomField>
    <fullName>Tahun_Cuti__c</fullName>
    <label>Kondisi Cuti</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tahun Ini</fullName>
            </value>
            <value>
                <fullName>Tahun Depan</fullName>
            </value>
            <value>
                <fullName>Tahun Lalu</fullName>
                <default>true</default>
                <label>Tahun Lalu</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuti_Karyawan__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuti_Poin_Karyawan__c/Cuti_Poin_Karyawan__c.object-meta.xml
<CustomObject>
    <label>Master Cuti &amp; Poin Karyawan</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Cuti &amp; Poin Karyawan</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuti_Poin_Karyawan__c/fields/Nama_Karyawan__c.field-meta.xml
<CustomField>
    <fullName>Nama_Karyawan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nama Karyawan</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuti_Poin_Karyawan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuti_Poin_Karyawan__c/fields/Poin__c.field-meta.xml
<CustomField>
    <fullName>Poin__c</fullName>
    <inlineHelpText>Poin yang dimiliki oleh agent  (poin dapat bertambah jika mendapatkan achivment)</inlineHelpText>
    <label>Poin</label>
    <summarizedField>Poin_Karyawan__c.Poin__c</summarizedField>
    <summaryForeignKey>Poin_Karyawan__c.Cuti_Poin_Karyawan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cuti_Poin_Karyawan__c/fields/Poin_Terpakai__c.field-meta.xml
<CustomField>
    <fullName>Poin_Terpakai__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Poin yang telah digunakan oleh agent</inlineHelpText>
    <label>Poin Terpakai</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cuti_Poin_Karyawan__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Jadwal_Karyawan__c/Jadwal_Karyawan__c.object-meta.xml
<CustomObject>
    <label>Master Jadwal Karyawan</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Jadwal Karyawan</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Jadwal_Karyawan__c/fields/Nama_Karyawan__c.field-meta.xml
<CustomField>
    <fullName>Nama_Karyawan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nama Karyawan</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Jadwal_Karyawan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Jadwal_Karyawan__c/fields/Opsi_Jadwal__c.field-meta.xml
<CustomField>
    <fullName>Opsi_Jadwal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opsi Jadwal</label>
    <referenceTo>Opsi_Jadwal__c</referenceTo>
    <relationshipName>Jadwal_Karyawan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Jadwal_Karyawan__c/fields/Tanggal__c.field-meta.xml
<CustomField>
    <fullName>Tanggal__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tanggal</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Jadwal_Karyawan__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <description>Login ID + Tanggal</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opsi_Jadwal__c/Opsi_Jadwal__c.object-meta.xml
<CustomObject>
    <description>menyimpan informasi jadwal shift agent</description>
    <label>Master Shift Karyawan</label>
    <nameField>
        <label>Jadwal Shift</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Shift Karyawan</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opsi_Jadwal__c/fields/Kode__c.field-meta.xml
<CustomField>
    <fullName>Kode__c</fullName>
    <externalId>true</externalId>
    <label>Kode</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Poin_Karyawan__c/Poin_Karyawan__c.object-meta.xml
<CustomObject>
    <description>menyimpan data penambahan poin yang diupload oleh admin</description>
    <label>Master Poin Penilaian Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Poin Penilaian Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Poin_Karyawan__c/fields/Cuti_Poin_Karyawan__c.field-meta.xml
<CustomField>
    <fullName>Cuti_Poin_Karyawan__c</fullName>
    <label>Cuti &amp; Poin Karyawan</label>
    <referenceTo>Cuti_Poin_Karyawan__c</referenceTo>
    <relationshipName>Poin_Karyawan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Poin_Karyawan__c/fields/Nama_Karyawan__c.field-meta.xml
<CustomField>
    <fullName>Nama_Karyawan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nama Karyawan</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Poin_Karyawan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Poin_Karyawan__c/fields/Poin__c.field-meta.xml
<CustomField>
    <fullName>Poin__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Poin Achivment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Poin_Shift__c/Poin_Shift__c.object-meta.xml
<CustomObject>
    <description>menyimpan informasi pengurangan poin jika request shift / request off</description>
    <label>Master Type Request</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Type Request</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Poin_Shift__c/fields/Poin__c.field-meta.xml
<CustomField>
    <fullName>Poin__c</fullName>
    <label>Poin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Poin_Shift__c/fields/Type_Pengajuan__c.field-meta.xml
<CustomField>
    <fullName>Type_Pengajuan__c</fullName>
    <label>Type Pengajuan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Shift</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Leave__c/Request_Leave__c.object-meta.xml
<CustomObject>
    <description>digunakan jika agent ingin melakukan cuti dan request off</description>
    <label>Request Cuti &amp; Off</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Cuti &amp; Off</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Leave__c/fields/Cuti_Poin_Karyawan__c.field-meta.xml
<CustomField>
    <fullName>Cuti_Poin_Karyawan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuti &amp; Poin Karyawan</label>
    <referenceTo>Cuti_Poin_Karyawan__c</referenceTo>
    <relationshipLabel>Request Cuti</relationshipLabel>
    <relationshipName>Request_Cuti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Leave__c/fields/Date_From__c.field-meta.xml
<CustomField>
    <fullName>Date_From__c</fullName>
    <label>Date From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Request_Leave__c/fields/Date_To__c.field-meta.xml
<CustomField>
    <fullName>Date_To__c</fullName>
    <label>Date To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Request_Leave__c/fields/Nama_Karyawan__c.field-meta.xml
<CustomField>
    <fullName>Nama_Karyawan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nama Karyawan</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Request_Leave</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Leave__c/fields/Type_Request__c.field-meta.xml
<CustomField>
    <fullName>Type_Request__c</fullName>
    <label>Type Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Cuti</fullName>
                <default>true</default>
                <label>Request Cuti</label>
            </value>
            <value>
                <fullName>Request Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Agent_Type__c.field-meta.xml
<CustomField>
    <fullName>Agent_Type__c</fullName>
    <label>Agent Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agent_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Level__c.field-meta.xml
<CustomField>
    <fullName>User_Level__c</fullName>
    <label>User Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Type__c/User_Type__c.object-meta.xml
<CustomObject>
    <label>User Type</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Type__c/fields/Agent_Type__c.field-meta.xml
<CustomField>
    <fullName>Agent_Type__c</fullName>
    <label>Agent Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agent_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Type__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Type1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Type__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Type</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Type__c/fields/User_Level__c.field-meta.xml
<CustomField>
    <fullName>User_Level__c</fullName>
    <label>User Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Agent_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MRS</fullName>
        <label>Micro &amp; Retail Banking</label>
    </customValue>
    <customValue>
        <fullName>CDS</fullName>
        <label>Credit Card &amp; Digital Lending</label>
    </customValue>
    <customValue>
        <fullName>BMS</fullName>
        <label>BRILink &amp; Merchant</label>
    </customValue>
    <customValue>
        <fullName>VBS</fullName>
        <label>Video Banking</label>
    </customValue>
    <customValue>
        <fullName>WBS</fullName>
        <label>Wholesale Banking</label>
    </customValue>
    <customValue>
        <fullName>PBS</fullName>
        <label>Priority Banking</label>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
        <label>Social Media</label>
    </customValue>
    <customValue>
        <fullName>RPS</fullName>
    </customValue>
    <customValue>
        <fullName>URS</fullName>
    </customValue>
    <customValue>
        <fullName>DA</fullName>
        <label>Data Analyst</label>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
        <label>Desk Control</label>
    </customValue>
    <masterLabel>Agent Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Type_Shift.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Request Shift</fullName>
    </customValue>
    <customValue>
        <fullName>Tukar Off</fullName>
    </customValue>
    <customValue>
        <fullName>Request Off</fullName>
    </customValue>
    <masterLabel>Type Shift</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/User_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Agent Leader</fullName>
    </customValue>
    <customValue>
        <fullName>SPV</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Manager</fullName>
    </customValue>
    <masterLabel>User Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SCC_RequestCuti_Manager_Test.cls
@isTest
public class SCC_RequestCuti_Manager_Test {
    @TestSetup
    static void setupdata(){
        // Step 1: Create test data for the related objects.

        // Create users and assign permission set in a separate context
        User u1, u2, u3;
        
        System.runAs(new User(Id = UserInfo.getUserId())) {
            // Get the Permission Set first
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'WFM_Agent'];
            
            String uniqueUsername = 'testuser' + System.currentTimeMillis() + '@example.com';

            // Create mock Users
            u1 = new User(
                Alias = 'Test1',
                Email = 'test1@example.com',
                ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
                Username = uniqueUsername  + 1,
                LastName = 'User1',
                FirstName = 'Test',
                TimeZoneSidKey = 'America/New_York',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                User_Level__c = 'Agent',
                Agent_Type__c = 'MRS'
            );
            insert u1;
            
            // Assign Permission Set only to u1
            PermissionSetAssignment psAssignment = new PermissionSetAssignment(
                AssigneeId = u1.Id,
                PermissionSetId = ps.Id
            );
            insert psAssignment;
            
            u2 = new User(
                Alias = 'Test2',
                Email = 'test3@example.com',
                ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
                Username = uniqueUsername + 2,
                LastName = 'User2',
                FirstName = 'Test',
                TimeZoneSidKey = 'America/New_York',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                User_Level__c = 'Agent Leader',
                Agent_Type__c = 'MRS'
            );
            insert u2;
            
            u3 = new User(
                Alias = 'Test3',
                Email = 'test1@example.com',
                ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
                Username = uniqueUsername + 3,
                LastName = 'User3',
                FirstName = 'Test',
                TimeZoneSidKey = 'America/New_York',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                User_Level__c = 'SPV',
                Agent_Type__c = 'MRS'
            );
            insert u3;
            
            User u4 = new User(
                Id = UserInfo.getUserId(),
                User_Level__c = 'Assistant Manager',
                Agent_Type__c = 'MRS'
            );
            update u4;
        }
        List<Opsi_Jadwal__c> listopsi = new List<Opsi_Jadwal__c>();
        for(integer i=1; i<=22;i++){
            Opsi_Jadwal__c oj = new Opsi_Jadwal__c(Kode__c = 'S'+i, Name = 'S'+i);
            listopsi.add(oj);
        }
        Opsi_Jadwal__c libur = new Opsi_Jadwal__c(Kode__c = 'LIBUR', Name = 'LIBUR');
        Opsi_Jadwal__c off = new Opsi_Jadwal__c(Kode__c = 'OFF', Name = 'OFF');
        listopsi.add(libur);
        listopsi.add(off);
        insert listopsi;

        // Create Poin_Shift__c record
        Poin_Shift__c ps = new Poin_Shift__c(
            Type_Pengajuan__c = 'Request Off',
            Poin__c = 0
        );
        insert ps;
    }

    @isTest
    public static void testCutiApproved() {      
        // Step 1: Create test data for the related objects.

        // Create users and assign permission set in a separate context
        Map<String,User> mapus = new Map<String,User>();
        User u1, u2, u3, u4;
        for(User us:[select id,User_Level__c,Agent_Type__c from User where Agent_Type__c='MRS' and User_Level__c!=null]){
            mapus.put(us.User_Level__c,us);
        }
        u1 = mapus.get('Agent');
        u2 = mapus.get('Agent Leader');
        u3 = mapus.get('SPV');
        u4 = mapus.get('Assistant Manager');
        
        //Create User Type
        User_Type__c ut1 = new User_Type__c(
            User__c = u1.Id,
            Manager__c = u2.Id,
            User_Level__c = 'Agent',
            Agent_Type__c = 'MRS'
        );
        insert ut1;
        
        User_Type__c ut2 = new User_Type__c(
            User__c = u2.Id,
            Manager__c = u3.Id,
            User_Level__c = 'Agent Leader',
            Agent_Type__c = 'MRS'
        );
        insert ut2;
        
        User_Type__c ut3 = new User_Type__c(
            User__c = u3.Id,
            Manager__c = UserInfo.getUserId(),
            User_Level__c = 'SPV',
            Agent_Type__c = 'MRS'
        );
        insert ut3;
        
        User_Type__c ut4 = new User_Type__c(
            User__c = UserInfo.getUserId(),
            User_Level__c = 'Assistant Manager',
            Agent_Type__c = 'MRS'
        );
        insert ut4;

        // Create Cuti_Poin_Karyawan__c with required fields
        Cuti_Poin_Karyawan__c cpk = new Cuti_Poin_Karyawan__c(
            Nama_Karyawan__c = u1.Id,
            Poin_Terpakai__c = 0,          
            Unique_Id__c = u1.Id
        );
        insert cpk;

        // Create Cuti_Karyawan__c without modifying Sisa_Cuti__c (since it's read-only)
        Cuti_Karyawan__c ck = new Cuti_Karyawan__c();
        ck.Nama_Karyawan__c = u1.id;
        ck.Tahun__c = system.today().year();
        ck.Quota_Cuti__c = 10;
        ck.Tahun_Cuti__c = 'Tahun Ini';
        ck.Unique_Id__c = u1.id+'-'+system.today().year();
        ck.Cuti_poin_Karyawan__c = cpk.id;
        Date dt = system.today();
        List<Jadwal_Karyawan__c> listjk = new List<Jadwal_Karyawan__c>();
        List<Opsi_Jadwal__c> listopsi = [Select id from Opsi_Jadwal__c];
        for(Integer i = 0 ;i<listopsi.size();i++){
            Jadwal_Karyawan__c jk = new Jadwal_Karyawan__c(
                Nama_Karyawan__c = u1.Id,
                Tanggal__c = Date.today().addDays(i),
                Opsi_Jadwal__c = listopsi[i].Id,  // Correctly reference the Opsi_Jadwal__c record here
                Unique_ID__c = u1.Id + '-' + Date.today().addDays(i)
            );
            listjk.add(jk);
        }
        insert listjk;

        // Create Request_Leave__c (Cuti request)
        Request_Leave__c rl = new Request_Leave__c(
            Nama_Karyawan__c = u1.Id,
            Type_Request__c = 'Request Cuti',
            Date_From__c = Date.today().addDays(2),
            Date_To__c = Date.today().addDays(3),
            Approval_Status__c = 'Draft',
            Agent_Leader__c = u2.Id,
            SPV__c = u3.id,
            Assistant_Manager__c = u4.Id
        );
        insert rl;
        
        rl.Approval_Status__c = 'Submit for Approval';
        update rl;
        rl.Approval_Status__c='Approve by Asisten Manager';
        update rl;
    }

    @isTest
    public static void testCutiRejected() {      
        Map<String,User> mapus = new Map<String,User>();
        User u1, u2, u3, u4;
        for(User us:[select id,User_Level__c,Agent_Type__c from User where Agent_Type__c='MRS' and User_Level__c!=null]){
            mapus.put(us.User_Level__c,us);
        }
        u1 = mapus.get('Agent');
        u2 = mapus.get('Agent Leader');
        u3 = mapus.get('SPV');
        u4 = mapus.get('Assistant Manager');
        //Create User Type
        User_Type__c ut1 = new User_Type__c(
            User__c = u1.Id,
            Manager__c = u2.Id,
            User_Level__c = 'Agent',
            Agent_Type__c = 'MRS'
        );
        insert ut1;
        
        User_Type__c ut2 = new User_Type__c(
            User__c = u2.Id,
            Manager__c = u3.Id,
            User_Level__c = 'Agent Leader',
            Agent_Type__c = 'MRS'
        );
        insert ut2;
        
        User_Type__c ut3 = new User_Type__c(
            User__c = u3.Id,
            Manager__c = UserInfo.getUserId(),
            User_Level__c = 'SPV',
            Agent_Type__c = 'MRS'
        );
        insert ut3;
        
        User_Type__c ut4 = new User_Type__c(
            User__c = UserInfo.getUserId(),
            User_Level__c = 'Assistant Manager',
            Agent_Type__c = 'MRS'
        );
        insert ut4;

        // Create Poin_Shift__c record
        Poin_Shift__c ps = new Poin_Shift__c(
            Type_Pengajuan__c = 'Request Off',
            Poin__c = 0
        );
        insert ps;
        
        // Create Cuti_Poin_Karyawan__c with required fields
        Cuti_Poin_Karyawan__c cpk = new Cuti_Poin_Karyawan__c(
            Nama_Karyawan__c = u1.Id,
            Poin_Terpakai__c = 0,          
            Unique_Id__c = u1.Id
        );
        insert cpk;

        Poin_Karyawan__c pk = new Poin_Karyawan__c(
            Cuti_Poin_Karyawan__c = cpk.id,
            nama_karyawan__c = u1.id,
            Poin__c = 100,
            Score__c = 100
        );

        // Create Request_Leave__c (Cuti request)
        Request_Leave__c rl = new Request_Leave__c(
            Nama_Karyawan__c = u1.Id,
            Type_Request__c = 'Request Cuti',
            Date_From__c = Date.today().addDays(2),
            Date_To__c = Date.today().addDays(3),
            Approval_Status__c = 'Draft',
            Agent_Leader__c = u2.Id,
            SPV__c = u3.id,
            Assistant_Manager__c = u4.Id
        );
        insert rl;
        
        rl.Approval_Status__c = 'Submit for Approval';
        update rl;
        rl.Approval_Status__c = 'Reject by Asisten Manager';
        update rl;
    }

    @isTest
    public static void testOffApproved() {      
        Map<String,User> mapus = new Map<String,User>();
        User u1, u2, u3, u4;
        for(User us:[select id,User_Level__c,Agent_Type__c from User where Agent_Type__c='MRS' and User_Level__c!=null]){
            mapus.put(us.User_Level__c,us);
        }
        u1 = mapus.get('Agent');
        u2 = mapus.get('Agent Leader');
        u3 = mapus.get('SPV');
        u4 = mapus.get('Assistant Manager');
        //Create User Type
        User_Type__c ut1 = new User_Type__c(
            User__c = u1.Id,
            Manager__c = u2.Id,
            User_Level__c = 'Agent',
            Agent_Type__c = 'MRS'
        );
        insert ut1;
        
        User_Type__c ut2 = new User_Type__c(
            User__c = u2.Id,
            Manager__c = u3.Id,
            User_Level__c = 'Agent Leader',
            Agent_Type__c = 'MRS'
        );
        insert ut2;
        
        User_Type__c ut3 = new User_Type__c(
            User__c = u3.Id,
            Manager__c = UserInfo.getUserId(),
            User_Level__c = 'SPV',
            Agent_Type__c = 'MRS'
        );
        insert ut3;
        
        User_Type__c ut4 = new User_Type__c(
            User__c = UserInfo.getUserId(),
            User_Level__c = 'Assistant Manager',
            Agent_Type__c = 'MRS'
        );
        insert ut4;

        // Create Cuti_Poin_Karyawan__c with required fields
        Cuti_Poin_Karyawan__c cpk = new Cuti_Poin_Karyawan__c(
            Nama_Karyawan__c = u1.Id,
            Poin_Terpakai__c = 0,          
            Unique_Id__c = u1.Id
        );
        insert cpk;

        Poin_Karyawan__c pk = new Poin_Karyawan__c(
            Cuti_Poin_Karyawan__c = cpk.id,
            nama_karyawan__c = u1.id,
            Poin__c = 100,
            Score__c = 100
        );

        // Create Request_Leave__c (Cuti request)
        Request_Leave__c rl = new Request_Leave__c(
            Nama_Karyawan__c = u1.Id,
            Type_Request__c = 'Request Off',
            Date_From__c = Date.today().addDays(2),
            Date_To__c = Date.today().addDays(3),
            Approval_Status__c = 'Draft',
            Agent_Leader__c = u2.Id,
            SPV__c = u3.id,
            Assistant_Manager__c = u4.Id
        );
        insert rl;
        
        rl.Approval_Status__c = 'Submit for Approval';
        update rl;
        rl.Approval_Status__c = 'Approve by Asisten Manager';
        update rl;
    }

    @isTest
    public static void testOffReject() {      
        Map<String,User> mapus = new Map<String,User>();
        User u1, u2, u3, u4;
        for(User us:[select id,User_Level__c,Agent_Type__c from User where Agent_Type__c='MRS' and User_Level__c!=null]){
            mapus.put(us.User_Level__c,us);
        }
        u1 = mapus.get('Agent');
        u2 = mapus.get('Agent Leader');
        u3 = mapus.get('SPV');
        u4 = mapus.get('Assistant Manager');
        //Create User Type
        User_Type__c ut1 = new User_Type__c(
            User__c = u1.Id,
            Manager__c = u2.Id,
            User_Level__c = 'Agent',
            Agent_Type__c = 'MRS'
        );
        insert ut1;
        
        User_Type__c ut2 = new User_Type__c(
            User__c = u2.Id,
            Manager__c = u3.Id,
            User_Level__c = 'Agent Leader',
            Agent_Type__c = 'MRS'
        );
        insert ut2;
        
        User_Type__c ut3 = new User_Type__c(
            User__c = u3.Id,
            Manager__c = UserInfo.getUserId(),
            User_Level__c = 'SPV',
            Agent_Type__c = 'MRS'
        );
        insert ut3;
        
        User_Type__c ut4 = new User_Type__c(
            User__c = UserInfo.getUserId(),
            User_Level__c = 'Assistant Manager',
            Agent_Type__c = 'MRS'
        );
        insert ut4;

        // Create Cuti_Poin_Karyawan__c with required fields
        Cuti_Poin_Karyawan__c cpk = new Cuti_Poin_Karyawan__c(
            Nama_Karyawan__c = u1.Id,
            Poin_Terpakai__c = 0,          
            Unique_Id__c = u1.Id
        );
        insert cpk;

        Poin_Karyawan__c pk = new Poin_Karyawan__c(
            Cuti_Poin_Karyawan__c = cpk.id,
            nama_karyawan__c = u1.id,
            Poin__c = 100,
            Score__c = 100
        );

        // Create Request_Leave__c (Cuti request)
        Request_Leave__c rl = new Request_Leave__c(
            Nama_Karyawan__c = u1.Id,
            Type_Request__c = 'Request Off',
            Date_From__c = Date.today().addDays(2),
            Date_To__c = Date.today().addDays(3),
            Approval_Status__c = 'Draft',
            Agent_Leader__c = u2.Id,
            SPV__c = u3.id,
            Assistant_Manager__c = u4.Id
        );
        insert rl;
        
        rl.Approval_Status__c = 'Submit for Approval';
        update rl;
        rl.Approval_Status__c = 'Reject by Asisten Manager';
        update rl;
    }

    @isTest
    public static void testDoubleRequestOff() {      
        Map<String,User> mapus = new Map<String,User>();
        User u1, u2, u3, u4;
        for(User us:[select id,User_Level__c,Agent_Type__c from User where Agent_Type__c='MRS' and User_Level__c!=null]){
            mapus.put(us.User_Level__c,us);
        }
        u1 = mapus.get('Agent');
        u2 = mapus.get('Agent Leader');
        u3 = mapus.get('SPV');
        u4 = mapus.get('Assistant Manager');
        //Create User Type
        User_Type__c ut1 = new User_Type__c(
            User__c = u1.Id,
            Manager__c = u2.Id,
            User_Level__c = 'Agent',
            Agent_Type__c = 'MRS'
        );
        insert ut1;
        
        User_Type__c ut2 = new User_Type__c(
            User__c = u2.Id,
            Manager__c = u3.Id,
            User_Level__c = 'Agent Leader',
            Agent_Type__c = 'MRS'
        );
        insert ut2;
        
        User_Type__c ut3 = new User_Type__c(
            User__c = u3.Id,
            Manager__c = UserInfo.getUserId(),
            User_Level__c = 'SPV',
            Agent_Type__c = 'MRS'
        );
        insert ut3;
        
        User_Type__c ut4 = new User_Type__c(
            User__c = UserInfo.getUserId(),
            User_Level__c = 'Assistant Manager',
            Agent_Type__c = 'MRS'
        );
        insert ut4;

        // Create Cuti_Poin_Karyawan__c with required fields
        Cuti_Poin_Karyawan__c cpk = new Cuti_Poin_Karyawan__c(
            Nama_Karyawan__c = u1.Id,
            Poin_Terpakai__c = 0,          
            Unique_Id__c = u1.Id
        );
        insert cpk;

        Poin_Karyawan__c pk = new Poin_Karyawan__c(
            Cuti_Poin_Karyawan__c = cpk.id,
            nama_karyawan__c = u1.id,
            Poin__c = 100,
            Score__c = 100
        );

        // Create Request_Leave__c (Cuti request)
        Request_Leave__c rl = new Request_Leave__c(
            Nama_Karyawan__c = u1.Id,
            Type_Request__c = 'Request Off',
            Date_From__c = Date.today().addDays(2),
            Date_To__c = Date.today().addDays(3),
            Approval_Status__c = 'Draft',
            Agent_Leader__c = u2.Id,
            SPV__c = u3.id,
            Assistant_Manager__c = u4.Id
        );
        insert rl;
        Request_Leave__c rl2 = new Request_Leave__c(
            Nama_Karyawan__c = u1.Id,
            Type_Request__c = 'Request Off',
            Date_From__c = Date.today().addDays(4),
            Date_To__c = Date.today().addDays(6),
            Approval_Status__c = 'Draft',
            Agent_Leader__c = u2.Id,
            SPV__c = u3.id,
            Assistant_Manager__c = u4.Id
        );
        insert rl2;
    }

    @isTest
    public static void testDoubleRequestCuti() {      
        Map<String,User> mapus = new Map<String,User>();
        User u1, u2, u3, u4;
        for(User us:[select id,User_Level__c,Agent_Type__c from User where Agent_Type__c='MRS' and User_Level__c!=null]){
            mapus.put(us.User_Level__c,us);
        }
        u1 = mapus.get('Agent');
        u2 = mapus.get('Agent Leader');
        u3 = mapus.get('SPV');
        u4 = mapus.get('Assistant Manager');
        //Create User Type
        User_Type__c ut1 = new User_Type__c(
            User__c = u1.Id,
            Manager__c = u2.Id,
            User_Level__c = 'Agent',
            Agent_Type__c = 'MRS'
        );
        insert ut1;
        
        User_Type__c ut2 = new User_Type__c(
            User__c = u2.Id,
            Manager__c = u3.Id,
            User_Level__c = 'Agent Leader',
            Agent_Type__c = 'MRS'
        );
        insert ut2;
        
        User_Type__c ut3 = new User_Type__c(
            User__c = u3.Id,
            Manager__c = UserInfo.getUserId(),
            User_Level__c = 'SPV',
            Agent_Type__c = 'MRS'
        );
        insert ut3;
        
        User_Type__c ut4 = new User_Type__c(
            User__c = UserInfo.getUserId(),
            User_Level__c = 'Assistant Manager',
            Agent_Type__c = 'MRS'
        );
        insert ut4;

        // Create Request_Leave__c (Cuti request)
        Request_Leave__c rl = new Request_Leave__c(
            Nama_Karyawan__c = u1.Id,
            Type_Request__c = 'Request Cuti',
            Date_From__c = Date.today().addDays(2),
            Date_To__c = Date.today().addDays(3),
            Approval_Status__c = 'Draft',
            Agent_Leader__c = u2.Id,
            SPV__c = u3.id,
            Assistant_Manager__c = u4.Id
        );
        insert rl;
        Request_Leave__c rl2 = new Request_Leave__c(
            Nama_Karyawan__c = u1.Id,
            Type_Request__c = 'Request Cuti',
            Date_From__c = Date.today().addDays(4),
            Date_To__c = Date.today().addDays(6),
            Approval_Status__c = 'Draft',
            Agent_Leader__c = u2.Id,
            SPV__c = u3.id,
            Assistant_Manager__c = u4.Id
        );
        insert rl2;
    }
}