force-app/main/default/objects/Lead/fields/Account_Pipeline_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Pipeline_Status__c</fullName>
    <label>Account Pipeline Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Pipeline_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Segment__c</fullName>
    <label>Account Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.RecordType.Name</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Leads and Referrals (Kabupaten)</relationshipLabel>
    <relationshipName>Leads_and_Referrals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.RecordTypeId</field>
            <operation>equals</operation>
            <value>Province</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Leads and Referrals</relationshipLabel>
    <relationshipName>Leads_and_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/User_Description__c.field-meta.xml
<CustomField>
    <fullName>User_Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.RecordTypeId</field>
            <operation>equals</operation>
            <value>Village</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Leads and Referrals (Kecamatan)</relationshipLabel>
    <relationshipName>Leads_and_Referrals2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Leads and Referrals (Zip)</relationshipLabel>
    <relationshipName>Leads_and_Referrals3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Locations (Kabupaten)</relationshipLabel>
    <relationshipName>Locations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Province</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Village</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Locations (Kecamatan)</relationshipLabel>
    <relationshipName>Locations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/recordTypes/Address.recordType-meta.xml
<RecordType>
    <fullName>Address</fullName>
    <active>true</active>
    <label>Address</label>
</RecordType>

force-app/main/default/objects/Location/recordTypes/City.recordType-meta.xml
<RecordType>
    <fullName>City</fullName>
    <active>true</active>
    <label>City</label>
</RecordType>

force-app/main/default/objects/Location/recordTypes/Province.recordType-meta.xml
<RecordType>
    <fullName>Province</fullName>
    <active>true</active>
    <label>Province</label>
    <!---->
</RecordType>

force-app/main/default/objects/Location/recordTypes/Village.recordType-meta.xml
<RecordType>
    <fullName>Village</fullName>
    <active>false</active>
    <label>Village</label>
</RecordType>

force-app/main/default/globalValueSets/Account_Pipeline_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Channel</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Business/Enterprise</fullName>
        <isActive>false</isActive>
        <label>Business/Enterprise</label>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
        <isActive>false</isActive>
        <label>Individual</label>
    </customValue>
    <masterLabel>Account Pipeline Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Account_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>I</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>Business / Enterprise</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Business / Enterprise Group</label>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
        <isActive>false</isActive>
        <label>Business</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
        <isActive>false</isActive>
        <label>Government</label>
    </customValue>
    <customValue>
        <fullName>Business - Group</fullName>
        <isActive>false</isActive>
        <label>Business - Group</label>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
        <isActive>false</isActive>
        <label>Enterprise</label>
    </customValue>
    <customValue>
        <fullName>Private</fullName>
        <isActive>false</isActive>
        <label>Private</label>
    </customValue>
    <masterLabel>Account Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>General</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Bank</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Broker</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Agent</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Finance/ Leasing</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Group</label>
    </customValue>
    <customValue>
        <fullName>Salvage Buyer</fullName>
    </customValue>
    <customValue>
        <fullName>INSURANCE</fullName>
        <label>Insurance</label>
    </customValue>
    <customValue>
        <fullName>REINSURANCE</fullName>
        <label>Reinsurance</label>
    </customValue>
    <customValue>
        <fullName>BROKER</fullName>
        <label>Reinsurance Broker</label>
    </customValue>
    <customValue>
        <fullName>Independent Surveyor</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Surveyor</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Adjuster</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Investigator</fullName>
    </customValue>
    <customValue>
        <fullName>Claim Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Claim Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Repairer Shop</fullName>
    </customValue>
    <customValue>
        <fullName>Part Supplier</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Insurer</fullName>
        <isActive>false</isActive>
        <label>Co-Insurer</label>
    </customValue>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadController.cls
/**
 * @author [Marco Lie]
 * @date [2025-11-26]
 * @description Controller class for Lead management operations including location lookup,
 * customer type options, and lead creation functionality for web-to-lead processes
 */
public with sharing class LeadController {

  /**
   * @description Wrapper class to hold location data for Aura-enabled response
   */
  @SuppressWarnings('PMD.PropertyNamingConventions')
  public class LocationWrapper {
    @AuraEnabled public String Id { get; set; }
    @AuraEnabled public String Name { get; set; }
    @AuraEnabled public String Province { get; set; }
    @AuraEnabled public String Village { get; set; }
    
    /**
     * @description Constructor for LocationWrapper class
     * @param id Location record Id
     * @param name Location name
     * @param province Province name
     * @param village Village name
     */
    public LocationWrapper(Id id, String name, String province, String village) {
      this.Id   = String.valueOf(id);
      this.Name = name;
      this.Province = province;
      this.Village  = village;
    }
  }
    
  /**
   * @description Searches for cities based on search key pattern
   * @param searchKey Search term for city name lookup
   * @return List of LocationWrapper objects containing city information
   * @throws AuraHandledException if query fails or CRUD/FLS violation occurs
   */
  @AuraEnabled(cacheable=true)
  public static List<LocationWrapper> findCities(String searchKey) {
    // Check CRUD permission for Location object
    if (!Schema.sObjectType.Location.isAccessible()) {
      throw new AuraHandledException('Insufficient access to Location object');
    }
    
    // Check FLS permission for specific fields
    if (!Schema.sObjectType.Location.fields.Id.isAccessible() ||
        !Schema.sObjectType.Location.fields.Name.isAccessible() ||
        !Schema.sObjectType.Location.fields.Province__c.isAccessible()) {
      throw new AuraHandledException('Insufficient field-level access to Location fields');
    }

    List<LocationWrapper> results = new List<LocationWrapper>();
    String pattern = '%' + String.escapeSingleQuotes(searchKey) + '%';
    try {
      List<SObject> rows = [
        SELECT Id, Name, Province__c
        FROM Location
        WHERE LocationType = 'City'
            AND RecordType.Name = 'City'
            AND Name LIKE :pattern
          ORDER BY Name
          LIMIT 10
      ];
      for (SObject row : rows) {
        results.add(new LocationWrapper(
          (Id)row.get('Id'),
          (String)row.get('Name'),
          (String)row.get('Province__c'),
            null
        ));
      }
      return results;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description Retrieves zip codes for a given city ID
   * @param cityId The ID of the city to get zip codes for
   * @return List of LocationWrapper objects containing zip code information
   * @throws AuraHandledException if query fails or CRUD/FLS violation occurs
   */
  @AuraEnabled(cacheable=true)
  public static List<LocationWrapper> getZipCodes(String cityId) {
    // Check CRUD permission for Location object
    if (!Schema.sObjectType.Location.isAccessible()) {
      throw new AuraHandledException('Insufficient access to Location object');
    }
    
    // Check FLS permission for specific fields
    if (!Schema.sObjectType.Location.fields.Id.isAccessible() ||
        !Schema.sObjectType.Location.fields.Name.isAccessible() ||
        !Schema.sObjectType.Location.fields.Village__c.isAccessible()) {
      throw new AuraHandledException('Insufficient field-level access to Location fields');
    }

    List<LocationWrapper> results = new List<LocationWrapper>();
    try {
      List<SObject> rows = [
        SELECT Id, Name, Village__c
        FROM Location
        WHERE LocationType = 'Zip Code'
          AND RecordType.Name = 'Zip Code'
          AND City__c = :cityId
        ORDER BY Name
      ];
      for (SObject row : rows) {
        results.add(new LocationWrapper(
          (Id)row.get('Id'),
          (String)row.get('Name'),
            null,
            (String)row.get('Village__c')
        ));
      }
      return results;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description Retrieves customer type options from Lead Account_Segment__c picklist
   * @return List of Maps containing label-value pairs for customer type options
   */
  @AuraEnabled(cacheable=true)
  public static List<Map<String,String>> getCustomerTypeOptions() {
    // Check if Lead object is accessible
    if (!Schema.sObjectType.Lead.isAccessible()) {
      return new List<Map<String,String>>();
    }
    
    // Check if Account_Segment__c field is accessible
    if (!Schema.sObjectType.Lead.fields.Account_Segment__c.isAccessible()) {
      return new List<Map<String,String>>();
    }

    List<Map<String,String>> options = new List<Map<String,String>>();
    for (Schema.PicklistEntry ple 
         : Lead.Account_Segment__c.getDescribe().getPicklistValues()) {
        
        if (ple.getValue() == 'G') {
            continue;
        }
        
        options.add(new Map<String, String>{
            'label' => ple.getLabel(),
            'value' => ple.getValue()
        });
    }
    return options;
  }

  /**
   * @description Creates a new Lead record with the provided information
   * @param firstName Lead's first name
   * @param lastName Lead's last name
   * @param email Lead's email address
   * @param phone Lead's phone number
   * @param company Lead's company name
   * @param provinceId Province location ID
   * @param cityId City location ID
   * @param zipCodeId Zip code location ID
   * @param villageId Village location ID
   * @param customerType Customer segment type
   * @param userDescription User-provided description
   * @return Id of the newly created Lead record
   * @throws AuraHandledException if lead creation fails or CRUD/FLS violation occurs
   */
  @AuraEnabled
  @SuppressWarnings('PMD.ExcessiveParameterList')
  public static Id createLead(
      String firstName,
      String lastName,
      String email,
      String phone,
      String company,
      String provinceId,
      String cityId,
      String zipCodeId,
      String villageId,
      String customerType,
      String userDescription
  ) {
    // Check CRUD permission for Lead object - create access
    if (!Schema.sObjectType.Lead.isCreateable()) {
      throw new AuraHandledException('Insufficient access to create Lead records');
    }
    
    // Check FLS permission for each field being created
    String[] fieldsToCheck = new String[]{
      'FirstName', 'LastName', 'Email', 'Phone', 'Company', 
      'City__c', 'Province__c', 'Zip__c', 'Village__c', 
      'Account_Type__c', 'Account_Segment__c', 'Status', 
      'LeadSource', 'Account_Pipeline_Status__c', 'User_Description__c'
    };
    
    for (String fieldName : fieldsToCheck) {
      if (!Schema.sObjectType.Lead.fields.getMap().get(fieldName).getDescribe().isCreateable()) {
        throw new AuraHandledException('Insufficient field-level access to create Lead field: ' + fieldName);
      }
    }

    try {
      Lead newLead = new Lead(
        FirstName        = firstName,
        LastName         = lastName,
        Email            = email,
        Phone            = phone,
        Company          = company,
        City__c          = cityId,
        Province__c      = provinceId,
        Zip__c           = zipCodeId,
        Village__c       = villageId,
        //Account_Type__c  = 'General',
        Account_Type__c  = '0', // General
        Account_Segment__c = customerType,
        Status           = 'New',
        LeadSource       = 'Website', // web to lead site
        Account_Pipeline_Status__c = 'Direct',
        User_Description__c = userDescription
      );
      insert newLead;
      return newLead.Id;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}

/*
 -- Draft solution if Location object simplyfied structure --

// 1. Query the database ONE time.
// The database does all the hard work and returns only 514 aggregate results.
List<AggregateResult> uniqueCityResults = [SELECT City__c
                                         FROM Master_Location__c
                                         WHERE City__c != null
                                         GROUP BY City__c];

// 2. Loop IN MEMORY.
// This is perfectly safe and fast. It doesn't use any more queries.
// It will run 514 times, which takes less than 2 milliseconds.
List<String> uniqueCities = new List<String>();
for (AggregateResult ar : uniqueCityResults) {
    uniqueCities.add((String)ar.get('City__c'));
}

 */