force-app/main/default/objects/Opportunity/fields/Confirmed_by_RI__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_by_RI__c</fullName>
    <label>Confirmed by RI (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_by_RI_Amount__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_by_RI_Amount__c</fullName>
    <formula>Amount * ( Confirmed_by_RI__c /100)</formula>
    <label>Confirmed by RI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_to_RI__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_to_RI__c</fullName>
    <label>Confirmed to RI (%)</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_to_RI_Amount__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_to_RI_Amount__c</fullName>
    <formula>Amount * ( Confirmed_to_RI__c /100)</formula>
    <label>Confirmed to RI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Offering_status__c.field-meta.xml
<CustomField>
    <fullName>Offering_status__c</fullName>
    <label>Offering status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Slip Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NB</fullName>
                <label>New Business</label>
            </value>
            <value>
                <fullName>RN</fullName>
                <label>Renewal</label>
            </value>
            <value>
                <fullName>ED</fullName>
                <label>Endorsement</label>
            </value>
            <value>
                <fullName>MO</fullName>
                <label>MoU</label>
            </value>
            <value>
                <fullName>Facultative Outward</fullName>
            </value>
            <value>
                <fullName>Facultative Inward</fullName>
            </value>
            <value>
                <fullName>Declaration</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
                <isActive>false</isActive>
                <label>Certificate</label>
            </value>
            <value>
                <fullName>Cover Note</fullName>
                <isActive>false</isActive>
                <label>Cover Note</label>
            </value>
            <value>
                <fullName>Master Policy</fullName>
                <isActive>false</isActive>
                <label>Master Policy</label>
            </value>
            <value>
                <fullName>Open Cover</fullName>
                <isActive>false</isActive>
                <label>Open Cover</label>
            </value>
            <value>
                <fullName>Open Policy</fullName>
                <isActive>false</isActive>
                <label>Open Policy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Request_Number__c.field-meta.xml
<CustomField>
    <fullName>Request_Number__c</fullName>
    <label>Request Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Share_Offered__c.field-meta.xml
<CustomField>
    <fullName>Share_Offered__c</fullName>
    <label>Share Offered (%)</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Share_Offered_Amount__c.field-meta.xml
<CustomField>
    <fullName>Share_Offered_Amount__c</fullName>
    <formula>Total_Sum_Insured__c * (Share_Offered__c/100)</formula>
    <label>Share Offered Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>Sum_Insured__c</fullName>
    <label>Sum Insured</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/The_Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>The_Insured_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>The Insured Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (The Insured Name)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Facultative.recordType-meta.xml
<RecordType>
    <fullName>Facultative</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Facultative</label>
</RecordType>

force-app/main/default/classes/opptyFluc.cls
public class opptyFluc {
// @AuraEnabled(cacheable=true)
//     public static List<Map<String, String>> getOpportunities() {
//         List<Opportunity> opps = [
//             SELECT Id, Name, The_Insured_Name__r.name,
//             Confirmed_by_RI__c,Confirmed_by_RI_Amount__c,
//             Confirmed_to_RI__c,Confirmed_to_RI_Amount__c,
//             Request_Number__c,Sum_Insured__c,
//             Share_Offered__c,Share_Offered_Amount__c,
//             Offering_status__c
//             FROM Opportunity
//             WHERE Opportunity_Type__c = 'Facultative Outward'
//         ];

//         List<Map<String, String>> result = new List<Map<String, String>>();
//         for (Opportunity opp : opps) {
//             result.add(new Map<String, String>{
//                 'label' => opp.Name,
//                 'value' => opp.Id,
//               	'requestNumber' => opp.Request_Number__c,
//                 'insuredName' => opp.The_Insured_Name__r.name,
//                 'confirmedbyRI' => String.valueOf(opp.Confirmed_by_RI__c),
//                 'byRIAmount' => String.valueOf(opp.Confirmed_by_RI_Amount__c),
//                 'confirmedtoRI' => String.valueOf(opp.Confirmed_to_RI__c),
//                 'toRIAmount' => String.valueOf(opp.Confirmed_to_RI_Amount__c),
//                 'sumInsured' => String.valueOf(opp.Sum_Insured__c),
//                 'sharedOffered' => String.valueOf(opp.Share_Offered__c),
//                 'amountOffered' => String.valueOf(opp.Share_Offered_Amount__c),
//                 'offeredStatus' => opp.Offering_status__c
                   
               
//             });
//         }

//         return result;
//     }
//      @AuraEnabled
//       public static void saveFacultativeData(Map<String, Object> data) {
//         Id opptyId = (Id) data.get('opportunityId');

//         if (opptyId == null) {
//             throw new AuraHandledException('Please select Opportunity first');
//         }

//         Opportunity oppToUpdate = new Opportunity(
//             Id = opptyId,
//             Sum_Insured__c = Decimal.valueOf((String)data.get('tsiAccum')),
//             Share_Offered__c      = Decimal.valueOf((String)data.get('sharedOffered')),
//             //Share_Offered_Amount__c = (Decimal) data.get('offeredValue'),
//             Confirmed_by_RI__c    = Decimal.valueOf((String)data.get('confirmedByRIPercent')),
//             //Confirmed_by_RI_Amount__c = (Decimal) data.get('confirmedByRIValue'),
//             Confirmed_to_RI__c    = Decimal.valueOf((String)data.get('confirmedToRIPercent'))
//             //Confirmed_to_RI_Amount__c = (Decimal) data.get('confirmedToRIValue')
//             // add more mappings as needed
//         );

//         update oppToUpdate;
//     }

}