force-app/main/default/objects/Avaya_Agent__c/Avaya_Agent__c.object-meta.xml
<CustomObject>
    <description>Report Avaya Agent</description>
    <label>Avaya Agent</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaya Agent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avaya_Agent__c/fields/Agent_Group__c.field-meta.xml
<CustomField>
    <fullName>Agent_Group__c</fullName>
    <label>Agent Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent Group 01</fullName>
            </value>
            <value>
                <fullName>Agent Group 02</fullName>
            </value>
            <value>
                <fullName>Agent Group 03</fullName>
            </value>
            <value>
                <fullName>Agent Group 04</fullName>
            </value>
            <value>
                <fullName>Agent Group 05</fullName>
            </value>
            <value>
                <fullName>Banking Jkt</fullName>
            </value>
            <value>
                <fullName>Banking Semarang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaya_Agent__c/fields/AHT__c.field-meta.xml
<CustomField>
    <fullName>AHT__c</fullName>
    <label>AHT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaya_Agent__c/fields/AUX_Isi_Form__c.field-meta.xml
<CustomField>
    <fullName>AUX_Isi_Form__c</fullName>
    <label>AUX Isi Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avaya_Agent__c/fields/AUX_Rest_Room__c.field-meta.xml
<CustomField>
    <fullName>AUX_Rest_Room__c</fullName>
    <label>AUX Rest Room</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avaya_Agent__c/fields/AUX_Sholat__c.field-meta.xml
<CustomField>
    <fullName>AUX_Sholat__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AUX Sholat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avaya_Agent__c/fields/Avail_Time__c.field-meta.xml
<CustomField>
    <fullName>Avail_Time__c</fullName>
    <label>Avail Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avaya_Agent__c/fields/Login_ID__c.field-meta.xml
<CustomField>
    <fullName>Login_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Login ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avaya_Agent__c/fields/Staffed_Time__c.field-meta.xml
<CustomField>
    <fullName>Staffed_Time__c</fullName>
    <label>Staffed Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avaya_Historical__c/Avaya_Historical__c.object-meta.xml
<CustomObject>
    <label>Avaya Historical</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaya Historical</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avaya_Historical__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>dalam detik</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaya_Historical__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Avaya_Historical__c/fields/Historical_Type__c.field-meta.xml
<CustomField>
    <fullName>Historical_Type__c</fullName>
    <label>Historical Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>auxoutofcalls</fullName>
            </value>
            <value>
                <fullName>Agents in AUX</fullName>
            </value>
            <value>
                <fullName>Split/Skill</fullName>
            </value>
            <value>
                <fullName>ABNCALLS</fullName>
            </value>
            <value>
                <fullName>ACD Calls</fullName>
            </value>
            <value>
                <fullName>Agents Staffed</fullName>
            </value>
            <value>
                <fullName>percentAbn</fullName>
            </value>
            <value>
                <fullName>INQUEUE</fullName>
            </value>
            <value>
                <fullName>auxoutCalls</fullName>
            </value>
            <value>
                <fullName>Agents Avail</fullName>
            </value>
            <value>
                <fullName>INRING</fullName>
            </value>
            <value>
                <fullName>% Within Service Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaya_Skills__c/Avaya_Skills__c.object-meta.xml
<CustomObject>
    <label>Avaya Skills</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaya Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avaya_Skills__c/fields/Abandoned_Calls__c.field-meta.xml
<CustomField>
    <fullName>Abandoned_Calls__c</fullName>
    <label>Abandoned Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaya_Skills__c/fields/Acceptable__c.field-meta.xml
<CustomField>
    <fullName>Acceptable__c</fullName>
    <label>Acceptable</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaya_Skills__c/fields/ACD_Calls__c.field-meta.xml
<CustomField>
    <fullName>ACD_Calls__c</fullName>
    <label>ACD Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaya_Skills__c/fields/Agents_Available__c.field-meta.xml
<CustomField>
    <fullName>Agents_Available__c</fullName>
    <label>Agents Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaya_Skills__c/fields/Agents_Staffed__c.field-meta.xml
<CustomField>
    <fullName>Agents_Staffed__c</fullName>
    <label>Agents Staffed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaya_Skills__c/fields/Call_Offered__c.field-meta.xml
<CustomField>
    <fullName>Call_Offered__c</fullName>
    <label>Call Offered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaya_Skills__c/fields/Seksi_Skill__c.field-meta.xml
<CustomField>
    <fullName>Seksi_Skill__c</fullName>
    <label>Seksi Skill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PSTN_Credit_Ind</fullName>
            </value>
            <value>
                <fullName>PSTN_Banking_Ind</fullName>
            </value>
            <value>
                <fullName>VOIP BANKING INA</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>VOIP CC INA</fullName>
            </value>
            <value>
                <fullName>DPLK</fullName>
            </value>
            <value>
                <fullName>EDC</fullName>
            </value>
            <value>
                <fullName>NIK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaya_Skills__c/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <label>Service Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SCC_AVAYA.cls
/**
 * @description       : 
 * @author            : Christian Vieri
 * @group             : 
 * @last modified on  : 09-16-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class SCC_AVAYA {
    public static SCC_AVAYA_Wrapper.ResponseToken getToken(SCC_AVAYA_Wrapper.RequestToken cdh,String menu,String recid){
        SCC_AVAYA_Wrapper.ResponseToken cps = new  SCC_AVAYA_Wrapper.ResponseToken();
        SCC_API.WrapperRequest wr = setWrapperRequest(JSON.serialize(cdh,true), 'AvayaToken', menu, recid);
        SCC_API.WrapperError we = setWrapperError(wr);
        SCC_API.WrapperAPI wapi = SCC_API.getResponseAPIUI(wr);
        try{
            cps = (SCC_AVAYA_Wrapper.ResponseToken) JSON.deserialize(wapi.res.getBody(), SCC_AVAYA_Wrapper.ResponseToken.class);
        }
        catch(exception exc){
            SCC_API.InsertErrorLog(exc,wapi.req,wapi.res,we); 
        }
        // if(label.Dummy_Response=='true'){
        //     cps = Object_TestAvaya.setResponseToken();
        // }
        return cps;
    }

    public static List<SCC_AVAYA_Wrapper.ResponseReportHistorical> getReportHistorical(String menu,String recid){
        List<SCC_AVAYA_Wrapper.ResponseReportHistorical> cps = new  List<SCC_AVAYA_Wrapper.ResponseReportHistorical>();
        SCC_API.WrapperRequest wr = setWrapperRequest('', 'AvayaReportHistorical', menu, recid);
        SCC_API.WrapperError we = setWrapperError(wr);
        SCC_API.WrapperAPI wapi = SCC_API.getResponseAPIUI(wr);
        try{
            cps = (List<SCC_AVAYA_Wrapper.ResponseReportHistorical>) JSON.deserialize(wapi.res.getBody(), List<SCC_AVAYA_Wrapper.ResponseReportHistorical>.class);
        }
        catch(exception exc){
            SCC_API.InsertErrorLog(exc,wapi.req,wapi.res,we); 
        }
        // if(label.Dummy_Response=='true'){
        //     cps = Object_TestAvaya.setResponseReportHistorical();
        // }
        return cps;
    }

    public static List<SCC_AVAYA_Wrapper.ResponseReportAgent> getReportAgent(String menu,String recid){
        List<SCC_AVAYA_Wrapper.ResponseReportAgent> cps = new  List<SCC_AVAYA_Wrapper.ResponseReportAgent>();
        SCC_API.WrapperRequest wr = setWrapperRequest('', 'AvayaReportAgent', menu, recid);
        SCC_API.WrapperError we = setWrapperError(wr);
        SCC_API.WrapperAPI wapi = SCC_API.getResponseAPIUI(wr);
        try{
            String rbody = wapi.res.getBody().replace('"date"', '"dates"');
            cps = (List<SCC_AVAYA_Wrapper.ResponseReportAgent>) JSON.deserialize(rbody, List<SCC_AVAYA_Wrapper.ResponseReportAgent>.class);
        }
        catch(exception exc){
            SCC_API.InsertErrorLog(exc,wapi.req,wapi.res,we); 
        }
        // if(label.Dummy_Response=='true'){
        //     cps = Object_TestAvaya.setResponseReportAgent();
        // }
        return cps;
    }

    public static List<SCC_AVAYA_Wrapper.ResponseReportSkills> getReportSkills(String menu,String recid){
        List<SCC_AVAYA_Wrapper.ResponseReportSkills> cps = new  List<SCC_AVAYA_Wrapper.ResponseReportSkills>();
        SCC_API.WrapperRequest wr = setWrapperRequest('', 'AvayaReportSkills', menu, recid);
        SCC_API.WrapperError we = setWrapperError(wr);
        SCC_API.WrapperAPI wapi = SCC_API.getResponseAPIUI(wr);
        try{
            cps = (List<SCC_AVAYA_Wrapper.ResponseReportSkills>) JSON.deserialize(wapi.res.getBody(), List<SCC_AVAYA_Wrapper.ResponseReportSkills>.class);
        }
        catch(exception exc){
            SCC_API.InsertErrorLog(exc,wapi.req,wapi.res,we); 
        }
        // if(label.Dummy_Response=='true'){
        //     cps = Object_TestAvaya.setResponseReportSkills();
        // }
        return cps;
    }
    
    @future(callout=true) 
    public static void setReportAgent(){
        Date dt = system.today();
        List<SCC_AVAYA_Wrapper.ResponseReportAgent> lres = SCC_AVAYA.getReportAgent('System', null);
        Map<String,Avaya_Agent__c> mapskl = new Map<String,Avaya_Agent__c>();
        if(!lres.isEmpty()){
            for(SCC_AVAYA_Wrapper.ResponseReportAgent resa:lres){
                if(String.isNotBlank(resa.dates)){
                    dt = Date.valueOf(resa.dates);
                }
                String ext2 ='TOTAL-'+resa.agentGroup+'-'+String.valueOf(dt);
                SCC_AVAYA_Wrapper.ReportAgent res2 = resa.totals;
                Avaya_Agent__c skl2 = new Avaya_Agent__c(Date__c=dt,Agent_Group__c=resa.agentGroup, External_ID__c=ext2, AHT__c=res2.aht, AUX_Isi_Form__c=res2.auxIsiForm, 
                                                            AUX_Rest_Room__c=res2.auxRestRoom, AUX_Sholat__c=res2.auxSholat, Avail_Time__c=res2.availTime,
                                                            Login_ID__c = '', Name__c='TOTAL', Staffed_Time__c=res2.staffedTime);
                mapskl.put(ext2,skl2);
                for(SCC_AVAYA_Wrapper.ReportAgent res:resa.agents){
                    String ext = res.loginID+'-'+res.name+'-'+String.valueOf(dt);
                    Avaya_Agent__c skl = new Avaya_Agent__c(Date__c=dt,Agent_Group__c=resa.agentGroup, External_ID__c=ext, AHT__c=res.aht, AUX_Isi_Form__c=res.auxIsiForm, 
                                                            AUX_Rest_Room__c=res.auxRestRoom, AUX_Sholat__c=res.auxSholat, Avail_Time__c=res.availTime,
                                                            Login_ID__c = String.valueOf(res.loginID), Name__c=res.name, Staffed_Time__c=res.staffedTime);
                    mapskl.put(ext,skl);
                }
            }
            if(!mapskl.isempty()){
                upsert mapskl.values() external_id__c;
            }   
        }
    }
    
    @future(callout=true) 
    public static void setReportSkill(){
        Date dt = system.today();
        List<SCC_AVAYA_Wrapper.ResponseReportSkills> lres = SCC_AVAYA.getReportSkills('System', null);
        Map<String,Avaya_Skills__c> mapskl = new Map<String,Avaya_Skills__c>();
        if(!lres.isEmpty()){
            for(SCC_AVAYA_Wrapper.ResponseReportSkills res:lres){
                String ext = res.seksiSkill+'-'+String.valueOf(dt);
                Avaya_Skills__c skl = new Avaya_Skills__c(Date__c=dt, External_ID__c=ext, Abandoned_Calls__c=res.abanCalls, Acceptable__c=res.acceptable, ACD_Calls__c=res.acdCalls, 
                                        Agents_Available__c=res.agentsAvail, Agents_Staffed__c=res.agentsStaffed, Call_Offered__c=res.callOffered, Seksi_Skill__c=res.seksiSkill, Service_Level__c=res.serviceLevel);
                mapskl.put(ext,skl);
            }
            if(!mapskl.isempty()){
                upsert mapskl.values() external_id__c;
            }   
        }
    }
    
	@future(callout=true) 
    public static void setReportHistorical(){
        Date dt = system.today();
        List<SCC_AVAYA_Wrapper.ResponseReportHistorical> lres = SCC_AVAYA.getReportHistorical('System', null);
        Map<String,Avaya_Historical__c> mapskl = new Map<String,Avaya_Historical__c>();
        if(!lres.isEmpty()){
            for(SCC_AVAYA_Wrapper.ResponseReportHistorical res:lres){
                String ext = res.headerHistorical+'-'+String.valueOf(dt);
                Avaya_Historical__c skl = new Avaya_Historical__c(Date__c=dt, External_ID__c=ext, Historical_Type__c=res.headerHistorical, Duration__c=res.valueHistorical);
                if(mapskl.containskey(ext)){
                    Avaya_Historical__c skl2 = mapskl.get(ext);
                    skl.Duration__c += skl2.Duration__c;
                }
                mapskl.put(ext,skl);
            }
            if(!mapskl.isempty()){
                upsert mapskl.values() external_id__c;
            }   
        }
    }
    
    public static SCC_API.WrapperRequest setWrapperRequest(String bd,String metanm,String menu,String recid){
        SCC_API.WrapperRequest wr = new SCC_API.WrapperRequest();
        wr.bodyreq = bd;
        wr.clsName = 'SCC_AVAYA';
        wr.menu = menu;
        wr.metaname = metanm;
        wr.recid = recid;
        wr.token = '';
        if(String.isNotBlank(recid)){
            Id idsf = id.valueOf(recid);
            wr.objnm =  idsf.getSObjectType().getDescribe().getName();
        }
        return wr;
    }

    public static SCC_API.WrapperError setWrapperError(SCC_API.WrapperRequest wr){
        String urlCurrent = url.getCurrentRequestUrl().tostring().replace('Url:[delegate=','').substringBeforeLast(']');
        SCC_API.WrapperError we = new SCC_API.WrapperError(urlCurrent,wr.clsName);
        we.menu = wr.menu;
        we.recid = wr.recid;
        we.objnm = wr.objnm;
        return we;
    }

    public static void removeAvayaReport(String reportname){
        List<CronTrigger> ctlists = [SELECT Id, CronJobDetail.name, CronJobDetail.jobtype, NextFireTime, PreviousFireTime, State, StartTime, EndTime, 
                                             CronExpression, TimeZoneSidKey, OwnerId, LastModifiedById, CreatedById, CreatedDate, TimesTriggered 
                                             FROM CronTrigger 
                                             where CronJobDetail.name =  :reportname];
        if(CTlists.size()>0){
            for(CronTrigger apxjob:CTlists){
                System.abortJob(apxJob.Id);
            }
        }
    }
}