force-app/main/default/objects/Branch_Unit__c/Branch_Unit__c.object-meta.xml
<CustomObject>
    <label>Branch Unit 2</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Units</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Unit__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Branch Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Branch_Unit__c/fields/BranchCode__c.field-meta.xml
<CustomField>
    <fullName>BranchCode__c</fullName>
    <formula>RIGHT(&apos;00000&apos;+ Branch_Code__c,5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch_Unit__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/Bristar_Summary__c.object-meta.xml
<CustomObject>
    <label>Bristar Summary</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Bristar Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bristar Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bristar_Summary__c/fields/area__c.field-meta.xml
<CustomField>
    <fullName>area__c</fullName>
    <label>area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/branch__c.field-meta.xml
<CustomField>
    <fullName>branch__c</fullName>
    <label>branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/branchDesc__c.field-meta.xml
<CustomField>
    <fullName>branchDesc__c</fullName>
    <label>branchDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/closedTicket__c.field-meta.xml
<CustomField>
    <fullName>closedTicket__c</fullName>
    <label>closedTicket</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/costCenter__c.field-meta.xml
<CustomField>
    <fullName>costCenter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>costCenter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/costCenterDesc__c.field-meta.xml
<CustomField>
    <fullName>costCenterDesc__c</fullName>
    <label>costCenterDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/mainBranch__c.field-meta.xml
<CustomField>
    <fullName>mainBranch__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>mainBranch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/mainBranchDesc__c.field-meta.xml
<CustomField>
    <fullName>mainBranchDesc__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>mainBranchDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/onSla__c.field-meta.xml
<CustomField>
    <fullName>onSla__c</fullName>
    <label>onSla</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/onSlaClosed__c.field-meta.xml
<CustomField>
    <fullName>onSlaClosed__c</fullName>
    <label>onSlaClosed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/onSlaOpen__c.field-meta.xml
<CustomField>
    <fullName>onSlaOpen__c</fullName>
    <label>onSlaOpen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/openTicket__c.field-meta.xml
<CustomField>
    <fullName>openTicket__c</fullName>
    <label>openTicket</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/overSla__c.field-meta.xml
<CustomField>
    <fullName>overSla__c</fullName>
    <label>overSla</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/overSlaClosed__c.field-meta.xml
<CustomField>
    <fullName>overSlaClosed__c</fullName>
    <label>overSlaClosed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/overSlaOpen__c.field-meta.xml
<CustomField>
    <fullName>overSlaOpen__c</fullName>
    <label>overSlaOpen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/region__c.field-meta.xml
<CustomField>
    <fullName>region__c</fullName>
    <label>region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bristar_Summary__c/fields/regionDesc__c.field-meta.xml
<CustomField>
    <fullName>regionDesc__c</fullName>
    <label>regionDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>CreatedBy.Title</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <formula>IF(  LEFT(OwnerId, 3)= &apos;005&apos; &amp;&amp; Main_Branch__c != &apos;&apos; &amp;&amp;  Main_Branch_Description__c != &apos;&apos;, Owner:User.BranchCode__c , 

IF( Cost_Center__c != &apos;&apos;, &apos;00229&apos;, CodeBranch__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cost_Center_Description__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cost Center Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>DATEVALUE(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Main_Branch__c.field-meta.xml
<CustomField>
    <fullName>Main_Branch__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Main Branch</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Orgeh__c.field-meta.xml
<CustomField>
    <fullName>Orgeh__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Orgeh</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SCC_Call_Type__c.field-meta.xml
<CustomField>
    <fullName>SCC_Call_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SSC_Call_Type__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SSC_Call_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Orgeh__c/Orgeh__c.object-meta.xml
<CustomObject>
    <label>Orgeh</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Orgeh Name (Queue)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orgeh</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orgeh__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cost Center</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Orgeh__c/fields/Cost_Center_Description__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center_Description__c</fullName>
    <label>Cost Center Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Custom_API_Response_Code__mdt/SCC_Custom_API_Response_Code__mdt.object-meta.xml
<CustomObject>
    <label>SCC_Custom_API_Response_Code</label>
    <pluralLabel>SCC_Custom_API_Response_Code</pluralLabel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/SSC_Call_Type__c.object-meta.xml
<CustomObject>
    <label>Case Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Type Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC_Call_Type__c/fields/SSC_Case_Description__c.field-meta.xml
<CustomField>
    <fullName>SSC_Case_Description__c</fullName>
    <label>Deskripsi Case</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Branch_Unit__c.field-meta.xml
<CustomField>
    <fullName>Branch_Unit__c</fullName>
    <label>Branch Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/BranchCode__c.field-meta.xml
<CustomField>
    <fullName>BranchCode__c</fullName>
    <formula>RIGHT(&apos;00000&apos; + SCC_Branch__c,5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SCC_Area__c.field-meta.xml
<CustomField>
    <fullName>SCC_Area__c</fullName>
    <label>Area</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SCC_Branch__c.field-meta.xml
<CustomField>
    <fullName>SCC_Branch__c</fullName>
    <label>Branch</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SCC_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>SCC_Cost_Center__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cost Center</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>73</fullName>
        <label>Area Barat</label>
    </customValue>
    <customValue>
        <fullName>72</fullName>
        <label>Area Jakarta</label>
    </customValue>
    <customValue>
        <fullName>71</fullName>
        <label>Area Tengah</label>
    </customValue>
    <customValue>
        <fullName>74</fullName>
        <label>Area Timur</label>
    </customValue>
    <customValue>
        <fullName>-1</fullName>
        <label>Area Khusus</label>
    </customValue>
    <masterLabel>Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewBristarSummary_API_Ctrl_Test.cls
@isTest
private class NewBristarSummary_API_Ctrl_Test {
    @TestSetup
    static void setupTestData() {
        Orgeh__c og = Object_Test.setOrgeh();
        insert og;
        // Create test data
        Orgeh__c og1 = new Orgeh__c(
            Cost_Center__c = 'PS85000',
            Cost_Center_Description__c = 'DIVISI SENTRA OPERASI'
        );
        Orgeh__c og2 = new Orgeh__c(
            Cost_Center__c = 'PS98502',
            Cost_Center_Description__c = 'DIVISI SERVICE & CONTACT CENTER'
        );
        insert new List<Orgeh__c>{og1, og2};
        Branch_Unit__c bu1 = Object_Test.setBranchUnit('113','CABANG','113','B');
        Branch_Unit__c bu2 = Object_Test.setBranchUnit('51','KANWIL','51','D');
        Branch_Unit__c bu3 = Object_Test.setBranchUnit('52','KANWIL','52','E');
        Branch_Unit__c bu4 = Object_Test.setBranchUnit('53','KANWIL','53','F');
        Branch_Unit__c bu5 = Object_Test.setBranchUnit('54','CABANG','54','G');
        Branch_Unit__c bu6 = Object_Test.setBranchUnit('55','CABANG','55','H');
        Branch_Unit__c bu7 = Object_Test.setBranchUnit('56','CABANG','56','I');
        insert new List<Branch_Unit__c>{bu1, bu2, bu3, bu4, bu5, bu6, bu7};

        Bristar_Summary__c bs1 = new Bristar_Summary__c(
            area__c = 'KP00',
            costCenter__c = 'PS98502',
            costCenterDesc__c = 'DIVISI SERVICE & CONTACT CENTER',
            openTicket__c = 2,
            closedTicket__c = 1,
            onSla__c = 3,
            overSla__c = 0,
            onSlaOpen__c = 3,
            overSlaClosed__c = 0,
            onSlaClosed__c = 0,
            overSlaOpen__c = 0,
            date__c = Datetime.now().addDays(-1).date()
        );
        Bristar_Summary__c bs2 = new Bristar_Summary__c(
            area__c = 'KP00',
            costCenter__c = 'PS98501',
            costCenterDesc__c = 'DIVISI SERVICE & CONTACT',
            openTicket__c = 4,
            closedTicket__c = 1,
            onSla__c = 3,
            overSla__c = 2,
            onSlaOpen__c = 2,
            onSlaClosed__c = 1,
            overSlaClosed__c = 0,
            date__c = Datetime.now().addDays(-1).date()
        );
        Bristar_Summary__c bs3 = new Bristar_Summary__c(
            area__c = 'KW',
            region__c = 'B',
            regionDesc__c = 'DIVISI SERVICE & CONTACT',
            mainBranch__c = '113',
            mainBranchDesc__c = '113 divisi',
            branch__c = '00113',
            branchDesc__c = '00123 divisi',
            openTicket__c = 4,
            closedTicket__c = 1,
            onSla__c = 3,
            overSla__c = 2,
            onSlaOpen__c = 2,
            onSlaClosed__c = 1,
            overSlaClosed__c = 0,
            overSlaOpen__c = 0,
            date__c = Datetime.now().addDays(-1).date()
        );
        Bristar_Summary__c bs4 = new Bristar_Summary__c(
            area__c = 'KW',
            region__c = 'B',
            regionDesc__c = 'DIVISI SERVICE & CONTACT',
            mainBranch__c = '113',
            mainBranchDesc__c = '124 divisi',
            branch__c = '00113',
            branchDesc__c = '00124 divisi',
            openTicket__c = 4,
            closedTicket__c = 1,
            onSla__c = 3,
            overSla__c = 2,
            onSlaOpen__c = 2,
            onSlaClosed__c = 1,
            overSlaClosed__c = 0,
            overSlaOpen__c = 0,
            date__c = Datetime.now().addDays(-1).date()
        );

        insert new List<Bristar_Summary__c>{bs1, bs2, bs3, bs4};

        SSC_Call_Type__c ct = Object_Test.setCaseType('8812');
        insert ct;
        Case cs = Object_Test.setCaseBristar('Escalate', ct.id);
        Case cs1 = Object_Test.setCaseBristar('New', ct.id);
        Case cs2 = Object_Test.setCaseBristar('Returned', ct.id);
        insert new List<Case>{cs, cs1, cs2};

        list<Case> lcs = [SELECT Region__c, Main_Branch__c, Branch_Code__c, Cost_Center__c FROM Case];
        System.debug('listCase :'+lcs);
    }   

    @isTest
    static void getBristarSummaryKPBlank() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestKPBlankModel();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseKP_Model resrcc = Object_Test.BristarResponseKPModel();
        NewBristarSummary_API_Ctrl.returnAPIKP(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryKPBlank2() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestKPBlank2Model();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseKP_Model resrcc = Object_Test.BristarResponseKPModel();
        NewBristarSummary_API_Ctrl.returnAPIKP(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryKPBlank3() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestKPBlank3Model();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseKP_Model resrcc = Object_Test.BristarResponseKPModel();
        NewBristarSummary_API_Ctrl.returnAPIKP(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryKPBlank4() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestKPBlank4Model();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseKP_Model resrcc = Object_Test.BristarResponseKPModel();
        NewBristarSummary_API_Ctrl.returnAPIKP(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryKPFalse() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestKPFalseModel();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseKP_Model resrcc = Object_Test.BristarResponseKPModel();
        NewBristarSummary_API_Ctrl.returnAPIKP(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryKP() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestKPModel();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseKP_Model resrcc = Object_Test.BristarResponseKPModel();
        NewBristarSummary_API_Ctrl.returnAPIKP(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryKP1() {
        list<Case> lcs = [SELECT Id, OwnerId, Region__c, Main_Branch__c, Branch_Code__c, Cost_Center__c FROM Case WHERE Status != 'Closed'];
        User us = [SELECT Id, SCC_Area__c, SCC_Branch__c, Branch_Unit__c, BranchCode__c, SCC_Cost_Center__c from user WHERE SCC_Area__c != null AND BranchCode__c != null AND SCC_Cost_Center__c != null AND IsActive = true AND SCC_Area__c = 'KP00' AND SCC_Cost_Center__c = 'PS98502' AND BranchCode__c = '00229' LIMIT 1];
        System.debug('user test :'+us);
        ID newOwnerId = us.Id; // Replace with the actual User or Queue Id

        // Loop through the list and update the owner
        for(Case c : lcs) {
            c.OwnerId = newOwnerId;
            c.Region__c = '';
        }
        // Perform the update
        try {
            update lcs;
        } catch(Exception e) {
            System.debug('Error updating cases: ' + e.getMessage());
        }
        list<Case> lcs2 = [SELECT Id, OwnerId, Region__c, Main_Branch__c, Branch_Code__c, Cost_Center__c, Area__c FROM Case WHERE Status != 'Closed'];
        System.debug('listCase :'+lcs2);
        Case cs = (Case) SOQL_SOBJECT.SingleSobject(',SCC_Call_Type__r.Name,SCC_Call_Type__r.SSC_Case_Description__c', 'Case', '', '', '', '1');
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestKP1Model();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        Map<String, SCC_Custom_API_Response_Code__mdt> maprc = SCC_Custom_API_Response_Code__mdt.getAll();
        BristarSummary_API_Ctrl.processDetailDataKP(Object_Test.getTestCaseKP(), maprc, 'KP','CC001','2024-11-01','2024-11-13',1,2,'OPEN');
        BristarSummary_API_Ctrl.processDetailDataKP(Object_Test.getTestCaseKP(), maprc, 'KP','CC001','2024-11-01','2024-11-13',1,2,'Closed');
        BristarSummary_API_Ctrl.createTicketModelKP(cs,'Closed');
        BristarSummary_API_Wrapper.GetResponseKP1_Model resrcc = Object_Test.BristarResponseKP1Model();
        NewBristarSummary_API_Ctrl.returnAPIKP1(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryRO() {
        List<Bristar_Summary__c> bs = [SELECT Id, costCenter__c, costCenterDesc__c, region__c, regionDesc__c, mainBranch__c, mainBranchDesc__c, branch__c, branchDesc__c, onSla__c, overSla__c, onSlaClosed__c, onSlaOpen__c, openTicket__c, closedTicket__c FROM Bristar_Summary__c];
        System.debug('Bristar Test Class:'+bs);
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestROModel();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseRO_Model resrcc = Object_Test.BristarResponseROModel();
        NewBristarSummary_API_Ctrl.returnAPIRO(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryROOpen() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestROModel1();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseRO_Model resrcc = Object_Test.BristarResponseROModel();
        NewBristarSummary_API_Ctrl.returnAPIRO(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryROClosed() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestROModel2();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseRO_Model resrcc = Object_Test.BristarResponseROModel();
        NewBristarSummary_API_Ctrl.returnAPIRO(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryROCancel() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestROModel3();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseRO_Model resrcc = Object_Test.BristarResponseROModel();
        NewBristarSummary_API_Ctrl.returnAPIRO(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryRO1() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestRO1Model();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseRO1_Model resrcc = Object_Test.BristarResponseRO1Model();
        NewBristarSummary_API_Ctrl.returnAPIRO1(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryRO2() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestRO2Model();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseRO2_Model resrcc = Object_Test.BristarResponseRO2Model();
        NewBristarSummary_API_Ctrl.returnAPIRO2(resrcc);
        Test.stopTest();
    }

    @isTest
    static void getBristarSummaryRO3() {
        Test.startTest();
        BristarSummary_API_Wrapper.GetRequest_Model rcc = Object_Test.BristarRequestRO3Model();
        NewBristarSummary_API_Ctrl.getBristarSummary(rcc);
        BristarSummary_API_Wrapper.GetResponseRO3_Model resrcc = Object_Test.BristarResponseRO3Model();
        NewBristarSummary_API_Ctrl.returnAPIRO3(resrcc);
        Test.stopTest();
    }
}