force-app/main/default/objects/Monitoring_Summary__c/Monitoring_Summary__c.object-meta.xml
<CustomObject>
    <label>Monitoring Summary</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Monitoring Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitoring Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monitoring_Summary__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monitoring_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/BranchCode__c.field-meta.xml
<CustomField>
    <fullName>BranchCode__c</fullName>
    <formula>RIGHT(&apos;00000&apos; + SCC_Branch__c,5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BranchCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SCC_Orgeh__c.field-meta.xml
<CustomField>
    <fullName>SCC_Orgeh__c</fullName>
    <label>Orgeh</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCC_HttpReq_MonitoringTest.cls
@isTest(seealldata=true)
public class SCC_HttpReq_MonitoringTest {
    
    static testMethod void testProcess(){
        User u = [SELECT Id FROM User WHERE BranchCode__c = '00229' AND SCC_Orgeh__c != null LIMIT 1];
        
        Monitoring_Summary__c ms = new Monitoring_Summary__c();
        ms.User__c = UserInfo.getUserId();
        ms.Date__c = Date.Today().addDays(-1);
        ms.Total__c = 1;
        insert ms;
        
        Monitoring_Summary__c ms1 = new Monitoring_Summary__c();
        ms1.User__c = u.Id;
        ms1.Date__c = Date.Today().addDays(-1);
        ms1.Total__c = 1;
        insert ms1;
        
        Monitoring_Summary__c ms2 = new Monitoring_Summary__c();
        ms2.User__c = UserInfo.getUserId();
        ms2.Date__c = Date.Today().addDays(-1);
        ms2.Total__c = 1;
        insert ms2;
        
        Test.startTest();
        
        SCC_HttpReq_Monitoring.execute(null);
        Test.stopTest();
    }
}