force-app/main/default/objects/InsurancePolicy/fields/Policy_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Policy_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Distribution</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Insurance Policies</relationshipLabel>
    <relationshipName>Insurance_Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data__c/Master_Data__c.object-meta.xml
<CustomObject>
    <!--
    -->
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c/fields/USER_PIC__c.field-meta.xml
<CustomField>
    <fullName>USER_PIC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>USER PIC</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Master Data</relationshipLabel>
    <relationshipName>Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Policy_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Policy_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Distribution</label>
    <referenceTo>Master_Data__c</referenceTo>
    <relationshipLabel>Opportunities (Policy Distribution)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/USER_PIC__c.field-meta.xml
<CustomField>
    <fullName>USER_PIC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Operation Support</description>
    <label>USER PIC</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (USER PIC)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerHandler_MasterData.cls
/**
 * Class for Trigger_MasterData
 * TC : GS
 * DATE : 10/10/25
 */

public with sharing class TriggerHandler_MasterData extends TriggerHandler{
    public override void afterUpdate(){ 
        /*List<String> listPDId = new List<String>();
        for(Master_Data__c data : (List<Master_Data__c>) Trigger.new) {
            Master_Data__c olddata = (Master_Data__c) Trigger.oldMap.get(data.id); 
            String rtpd = Schema.SObjectType.Master_Data__c.getRecordTypeInfosByName().get('Policy Distribution').getRecordTypeId(); 
            if(data.RecordTypeId == rtpd && data.USER_PIC__c != olddata.USER_PIC__c){
                listPDId.add(data.Id);
            }
        }
        //List<InsurancePolicy> listIP = [SELECT Id FROM InsurancePolicy WHERE Policy_Distribution__c IN:listPDId WITH SECURITY_ENFORCED];
        //if(listIP.size()>0){ List<Database.SaveResult> sr = Database.update(listIP);}
        List<Opportunity> listOpp = [SELECT Id FROM Opportunity WHERE Policy_Distribution__c IN:listPDId WITH SECURITY_ENFORCED];
        if(listOpp.size()>0){ List<Database.SaveResult> sr = Database.update(listOpp);}*/
    }
}