force-app/main/default/objects/SCC_Interface_Configuration__mdt/SCC_Interface_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Integration Configuration</label>
    <pluralLabel>Integration Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/SCC_Interface_Configuration__mdt/fields/Main_URL__c.field-meta.xml
<CustomField>
    <fullName>Main_URL__c</fullName>
    <label>Main URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Configuration__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <inlineHelpText>Name of named credential.</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Configuration__mdt/fields/test_exception__c.field-meta.xml
<CustomField>
    <fullName>test_exception__c</fullName>
    <label>test exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Testing Exception</fullName>
                <default>true</default>
                <label>Not Testing Exception</label>
            </value>
            <value>
                <fullName>Client-Side HTTP Error - Salesforce</fullName>
            </value>
            <value>
                <fullName>Server-Side HTTP Error - External</fullName>
            </value>
            <value>
                <fullName>Unauthorized Endpoint</fullName>
            </value>
            <value>
                <fullName>Other Exceptions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCC_Interface_Configuration__mdt/fields/test_mode__c.field-meta.xml
<CustomField>
    <fullName>test_mode__c</fullName>
    <defaultValue>false</defaultValue>
    <label>test mode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/SCC_Interface_Operation_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Integration Operation Setting</label>
    <pluralLabel>Integration Operation Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/Correlation_ID__c.field-meta.xml
<CustomField>
    <fullName>Correlation_ID__c</fullName>
    <description>Key in the API response header</description>
    <label>Correlation ID Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/http_code_field__c.field-meta.xml
<CustomField>
    <fullName>http_code_field__c</fullName>
    <label>http code field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/IDCC_ClientID__c.field-meta.xml
<CustomField>
    <fullName>IDCC_ClientID__c</fullName>
    <label>ClientID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/IDCC_Content_Type__c.field-meta.xml
<CustomField>
    <fullName>IDCC_Content_Type__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/IDCC_Password__c.field-meta.xml
<CustomField>
    <fullName>IDCC_Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/Interface_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Interface_Configuration__c</fullName>
    <label>IDS Interface Configuration</label>
    <referenceTo>SCC_Interface_Configuration__mdt</referenceTo>
    <relationshipName>SCC_Integration_Operation_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/Msg_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Msg_Mapping__c</fullName>
    <label>Object Conversion Map</label>
    <referenceTo>SCC_Object_Conversion_Map__mdt</referenceTo>
    <relationshipLabel>IDS Interface Operation Settings</relationshipLabel>
    <relationshipName>ids_Interface_Operation_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/response_message_field__c.field-meta.xml
<CustomField>
    <fullName>response_message_field__c</fullName>
    <label>response message field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/Sub_URL__c.field-meta.xml
<CustomField>
    <fullName>Sub_URL__c</fullName>
    <label>Sub URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/Test_Data__c.field-meta.xml
<CustomField>
    <fullName>Test_Data__c</fullName>
    <label>Test Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/Test_Mode__c.field-meta.xml
<CustomField>
    <fullName>Test_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Mode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>In milisecond</description>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCC_Interface_Operation_Setting__mdt/fields/Update_Method_overwrite__c.field-meta.xml
<CustomField>
    <fullName>Update_Method_overwrite__c</fullName>
    <label>Update Method (overwrite)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCC_Object_Conversion_Field_Map__mdt/SCC_Object_Conversion_Field_Map__mdt.object-meta.xml
<CustomObject>
    <label>Object Conversion Field Map</label>
    <pluralLabel>Object Conversion Field Maps</pluralLabel>
</CustomObject>

force-app/main/default/objects/SCC_Object_Conversion_Field_Map__mdt/fields/Fixed_Value__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fixed Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SCC_Object_Conversion_Field_Map__mdt/fields/Fixed_Value_Type__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Value_Type__c</fullName>
    <inlineHelpText>Date type can have Date String or differ from today.</inlineHelpText>
    <label>Fixed Value Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCC_Object_Conversion_Field_Map__mdt/fields/NullToZero__c.field-meta.xml
<CustomField>
    <fullName>NullToZero__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NullToZero</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SCC_Object_Conversion_Field_Map__mdt/fields/Object_Conversion_Map__c.field-meta.xml
<CustomField>
    <fullName>Object_Conversion_Map__c</fullName>
    <label>Object Conversion Map</label>
    <referenceTo>SCC_Object_Conversion_Map__mdt</referenceTo>
    <relationshipName>Object_Conversion_Field_Maps</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/SCC_Object_Conversion_Field_Map__mdt/fields/Same_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Same_Field_Name__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Same Field Name</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SCC_Object_Conversion_Field_Map__mdt/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCC_Object_Conversion_Field_Map__mdt/fields/Value_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Value_Conversion__c</fullName>
    <label>Value Conversion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STR.UPPER</fullName>
                <default>true</default>
                <label>STR.UPPER</label>
            </value>
            <value>
                <fullName>STR.LOWER</fullName>
            </value>
            <value>
                <fullName>DATE.GMT</fullName>
            </value>
            <value>
                <fullName>NUMBERSTR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCC_Object_Conversion_Map__mdt/SCC_Object_Conversion_Map__mdt.object-meta.xml
<CustomObject>
    <label>Object Conversion Maps</label>
    <pluralLabel>Object Conversion Maps</pluralLabel>
</CustomObject>

force-app/main/default/classes/SCC_IntegrationUtility.cls
public with sharing class SCC_IntegrationUtility {
    public class MyException extends Exception { }
    
    // main method to generate the message 
    public static String generateMessage(String mapName, Map<String, Object> source) {
        Map<String, Object> desObject = makeIntMessage(mapName, null, source);
        String tmp = JSON.serialize(desObject) ;
        //System.debug(' JSON.serialize(desObject) ==> ' +  JSON.serializePretty(desObject) );
        return JSON.serialize(desObject);
    }

    // carry out value conversion based on data type set in the Custom Metadata 
    public static object valueConversion(String convType, object input, Boolean nullToZero) {
        Object rtn = input;
        if (convType == 'STR.UPPER') {
            if (input == null) {
                return null;
            }
            rtn = (String.valueOf(input)).toUpperCase();

        } else if (convType == 'STR.LOWER') {
            if (input == null) {
                return null;
            }
            rtn = (String.valueOf(input)).toLowerCase();
        } else if (convType == 'DATE.GMT') {
            if (input == null) {
                return null;
            }
            rtn = (String.valueOfGmt(Date.valueOf(input)));

        } else if (convType == 'NUMBERSTR') {
            rtn = convStr(String.valueOf(input), true);
        }
        if (nullToZero && input == null) {
            input = 0;
        }
        return rtn;
    }
    
    // query the field mapping from Custom Metadata record 
    public static List<SCC_Object_Conversion_Field_Map__mdt> getObjectMapping(String mapName) {
        List<SCC_Object_Conversion_Map__mdt> objMap = [SELECT DeveloperName FROM SCC_Object_Conversion_Map__mdt WHERE DeveloperName = :mapName];
        if (objMap.size() == 0) {
            throw new MyException('Map(' + mapName + ') does not exist');
        }
        // get object conversion field maps 
        List<SCC_Object_Conversion_Field_Map__mdt> convMap = [SELECT Value_Conversion__c,
                                                              Destination_Field__c,
                                                              Same_Field_Name__c,
                                                              Fixed_Value__c,
                                                              Object_Conversion_Map__c,
                                                              Fixed_Value_Type__c,
                                                              Object_Conversion_Map__r.DeveloperName,
                                                              NullToZero__c,Source_Field__c
                                                              from SCC_Object_Conversion_Field_Map__mdt
                                                              WHERE Object_Conversion_Map__r.DeveloperName = :mapName
                                                              AND Inactive__c != true];
        
        return convMap;
    }
   
    // this takes a string parameter and calls the message maker method 
    public static Map<String, Object> makeIntMessage(String mapName, Map<String, Object> desObject, Map<String, Object> source) {
        List<SCC_Object_Conversion_Field_Map__mdt> convMap = getObjectMapping(mapName);
        return makeIntMessage(convMap, desObject, source);
    }
    
    // main method to make the message 
    public static Map<String, Object> makeIntMessage(List<SCC_Object_Conversion_Field_Map__mdt> convMap, Map<String, Object> desObject, Map<String, Object> source) {
        // desObject is passed as null from GenerateMessage() method 
        if (desObject == null) {
            desObject = new Map<String, Object> ();
        }

        for (SCC_Object_Conversion_Field_Map__mdt covField : convMap) {
            Boolean isSetValue = true;
            String sourceField = covField.Source_Field__c;
            if (covField.Same_Field_Name__c) {
                sourceField = covField.Destination_Field__c;
            }

            if (isSetValue) {
                Object variableValue = '';

                try {
                    if (covField.Fixed_Value__c) {
                        variableValue = sourceField;
                        if (covField.Fixed_Value_Type__c == 'Boolean') {
                            variableValue = Boolean.valueOf(sourceField);
                            putValueByPath(desObject, covField.Destination_Field__c, Boolean.valueOf(sourceField));
                        }
                        else if (covField.Fixed_Value_Type__c == 'Date') {
                            Date datevalue = Date.today();
                            if (String.isNotEmpty(sourceField)) {
                                try {
                                    integer gap = integer.valueOf(sourceField);
                                    datevalue = datevalue.addDays(gap);
                                } catch(Exception e) {
                                    datevalue = Date.parse(sourceField);
                                }
                            }
                            variableValue = datevalue;
                        }
                    } else {
                        variableValue = getVariableValue(source, sourceField);
                    }
                    if (covField.Fixed_Value_Type__c != 'Reference') {
                        variableValue = valueConversion(covField.Value_Conversion__c, variableValue, covField.NullToZero__c);

                        putValueByPath(desObject, covField.Destination_Field__c, variableValue);
                    }
                } catch(Exception e) {
                    throw(New MyException('Error during setting ' + sourceField + ' ' + variableValue + ' into ' + covField.Destination_Field__c + ' from Map(' + covField.Object_Conversion_Map__r.DeveloperName + ').  '
                                          + e.getMessage() + ' '
                                          + e.getStackTraceString()));
                }
            }
        }
        
        return desObject;
    }

    // used for dot notation to access nested objects      
    public static Object getVariableValue(Map<String, Object> variables, String variableName)
    {
        Object variableValue = null;
        if(String.isBlank(variableName)) {
            return variableValue;
        }
        if (variableName.contains('.')) {
            String objName = variableName.substringBefore('.');
            String valName = variableName.substringAfter('.');
            Object obj = variables.get(objName);
            if (obj == null) {
                return null;
            }
            if (valName.contains('.')) {
                Map<String, Object> objvariable = (Map<String, Object>) obj;
                return getVariableValue(objvariable, valName);
            } else {
                try {
                    variableValue = ((sObject) obj).get(valName);
                } catch(Exception e) {
                    variableValue = ((Map<String, Object>) obj).get(valName);
                }
            }
        } else {
            variableValue = variables.get(variableName);
        }
        return variableValue;
    }

    public static Map<String, Object> putValueByPath(Map<String, Object> variables, String path, Object value) {
        if (variables == null) {
            variables = new Map<String, Object> ();
        }
        if (path.contains('.')) {
            String objName = path.substringBefore('.');
            String valName = path.substringAfter('.');
            Object obj = variables.get(objName);
            if (obj == null) {
                obj = new Map<String, Object> ();
                variables.put(objName, obj);
            }
            if (valName.contains('.')) {
                //more child
                putValueByPath((Map<String, Object>) obj, valName, value);
                return variables;
            } else {
                ((Map<String, Object>) obj).put(valName, value);
            }
        } else {
            variables.put(path, value);
        }
        return variables;
    }
    
    public static String convStr(String val, Boolean isNum) {
        if (val == null) {
            if (isNum) {
                return '0';
            }
            else {
                return '';
            }
        }
        else {
            return val;
        }
    }
    
    public static String sendData(String childInterfaceName, Map<String,Object> interfaceData) {
        String messageReceived = '';
        // find conversion mapping from child interface
        List<SCC_Interface_Operation_Setting__mdt> findConversionMapList = [SELECT DeveloperName, Msg_Mapping__r.DeveloperName FROM SCC_Interface_Operation_Setting__mdt WHERE SCC_Interface_Operation_Setting__mdt.DeveloperName = :childInterfaceName LIMIT 1];
        if(findConversionMapList.size()>0 ){
        	String findConversionMap = findConversionMapList[0].Msg_Mapping__r.DeveloperName; 
        
        	system.debug('findConversionMap**'+findConversionMap);
         	system.debug('InterfaceData**'+interfaceData);
        	// call the GenerateMessage method to get the message
        
        	String messageGenerated = generateMessage(findConversionMap, interfaceData);
        
			system.debug( ' *** Request ==> ' + messageGenerated);
             
            messageReceived = makeCallout(childInterfaceName, MessageGenerated);
            System.debug('@@@@MessageReceived -->'+messageReceived);
       	}
        return messageReceived;
    }

    public static String makeCallout(string subApiConfig, String requestBodyMsg){
        String rawBody = '';
        SCC_Interface_Operation_Setting__mdt interfaceSetting = [SELECT Interface_Configuration__r.DeveloperName, 
                                                                Interface_Configuration__r.Main_URL__c,
                                                                Test_Mode__c, 
                                                                IDCC_ClientID__c, 
                                                                IDCC_Password__c,
                                                                IDCC_Content_Type__c, 
                                                                response_message_field__c,
                                                                Interface_Configuration__r.test_mode__c, 
                                                                Interface_Configuration__r.test_exception__c,
                                                                DeveloperName, 
                                                                http_code_field__c, 
                                                                Sub_URL__c, 
                                                                Test_Data__c, 
                                                                Update_Method_overwrite__c, 
                                                                HTTP_Method__c,
                                                                Interface_Configuration__r.Named_Credential__c, 
                                                                Correlation_ID__c,
                                                                Timeout__c
                                                                FROM SCC_Interface_Operation_Setting__mdt WHERE DeveloperName=:subApiConfig LIMIT 1];
        
        String urlEndpoint = 'callout:'+interfaceSetting.Interface_Configuration__r.Named_Credential__c + interfaceSetting.Sub_URL__c;
        system.debug('Endpoint >> ' + urlEndpoint);
        
        // check to ensure a callout can be performed using the Limits class
        if (Limits.getCallouts() >= Limits.getLimitCallouts()){
            throw new MyException('The maximum number of callouts has been reached.');
        }   
        // instantiate a new http object 
        Http h = new Http();
        // instantiate a new HTTP request and response 
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        
        // configure the request
        req.setEndpoint(urlEndpoint);
        req.setTimeout(60000);
        System.debug('Request URL >> ' + urlEndpoint);
        
        req.setMethod(interfaceSetting.HTTP_Method__c);
        System.debug('httpMethod >> ' + interfaceSetting.HTTP_Method__c);

        req.setTimeout(Integer.valueOf(interfaceSetting.Timeout__c));
        System.debug('Timeout >> ' + interfaceSetting.Timeout__c);

        req.setHeader('Content-Type', interfaceSetting.IDCC_Content_Type__c);
        
        if( interfaceSetting.HTTP_Method__c == 'POST'){
            rawBody = JSON.serialize(JSON.deserializeUntyped(requestBodyMsg));
            rawBody = String.Valueof(rawBody);
            req.setBody(rawbody);
        }
        
        system.debug('This is the raw request body: ==> ' + rawBody);
            
        // Attempt the callout - create return error on exception
        String responseBody = '';
        try {
            Integer statusCode;
            String correlationId = '';

            // start of actual http callout if testMode is off 
            if(interfaceSetting.Test_Mode__c) {
                responseBody = interfaceSetting.Test_Data__c;
                statusCode = 200;
            } else {
                res = h.send(req);
                statusCode = res.getStatusCode();
                responseBody = res.getBody();
                if (String.isNotBlank(interfaceSetting.Correlation_ID__c)) {
                    correlationId = res.getHeader(interfaceSetting.Correlation_ID__c);
                }
                System.debug('Correlation ID >> '+correlationId);
            }
            
            system.debug('statusCode: ==> ' + statusCode);
            system.debug('This is the Response Raw body: ==> ' + responseBody);
            SCC_API.InsertErrorLog(null,req,res,new SCC_API.WrapperError(urlEndpoint,'SCC_IntegrationUtility')); 
            if(statusCode >= 300) {
                // errors with HTTP status code for review 
                throw new MyException('Client-side error encountered when sending a request, with HTTP status code:' + statusCode);
            } 
        } catch (System.CalloutException e) {
            SCC_API.InsertErrorLog(e,req,res,new SCC_API.WrapperError(urlEndpoint,'SCC_IntegrationUtility')); 
            throw new MyException('System.CalloutException: ' + e.getMessage());
        } catch (Exception e) {
            // other unexpected exceptions will be caught here
            SCC_API.InsertErrorLog(e,req,res,new SCC_API.WrapperError(urlEndpoint,'SCC_IntegrationUtility')); 
            System.debug('line number: '+e.getLineNumber());
            System.debug('Exception: '+e.getMessage());
        }
        
        return responseBody;
    }
}