force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <label>Risk</label>
</RecordType>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Agent_Comission__c.field-meta.xml
<CustomField>
    <fullName>Agent_Comission__c</fullName>
    <label>Agent Comission</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Agent_Comission_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Agent_Comission_Section_2__c</fullName>
    <label>Agent Comission Section 2</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Agent_Comission_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Agent_Comission_Section_3__c</fullName>
    <label>Agent Comission Section 3</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Agent_Comission_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Agent_Comission_Section_4__c</fullName>
    <label>Agent Comission Section 4</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Banks_Fee_Comission__c.field-meta.xml
<CustomField>
    <fullName>Banks_Fee_Comission__c</fullName>
    <label>Banks Fee Comission</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Banks_Fee_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Banks_Fee_Section_2__c</fullName>
    <label>Banks Fee Section 2</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Banks_Fee_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Banks_Fee_Section_3__c</fullName>
    <label>Banks Fee Section 3</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Banks_Fee_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Banks_Fee_Section_4__c</fullName>
    <label>Banks Fee Section 4</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Broker_Comission__c.field-meta.xml
<CustomField>
    <fullName>Broker_Comission__c</fullName>
    <label>Broker Comission</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Broker_Comission_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Broker_Comission_Section_2__c</fullName>
    <label>Broker Comission Section 2</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Broker_Comission_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Broker_Comission_Section_3__c</fullName>
    <label>Broker Comission Section 3</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Broker_Comission_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Broker_Comission_Section_4__c</fullName>
    <label>Broker Comission Section 4</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Commision__c.field-meta.xml
<CustomField>
    <fullName>Commision__c</fullName>
    <label>Comission</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Amount_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount_Section_2__c</fullName>
    <label>Deductible Amount Section 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Amount_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount_Section_3__c</fullName>
    <label>Deductible Amount Section 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Amount_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Amount_Section_4__c</fullName>
    <label>Deductible Amount Section 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_PCT_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Deductible_PCT_Section_2__c</fullName>
    <label>Deductible PCT Section 2</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_PCT_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Deductible_PCT_Section_3__c</fullName>
    <label>Deductible PCT Section 3</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_PCT_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Deductible_PCT_Section_4__c</fullName>
    <label>Deductible PCT Section 4</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Section_2__c</fullName>
    <label>Deductible Flag Section 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deductible</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Section_3__c</fullName>
    <label>Deductible Flag Section 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deductible</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Section_4__c</fullName>
    <label>Deductible Flag Section 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deductible</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Type_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Type_Section_2__c</fullName>
    <label>Deductible Type Section 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Type_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Type_Section_3__c</fullName>
    <label>Deductible Type Section 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Deductible_Type_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Deductible_Type_Section_4__c</fullName>
    <label>Deductible Type Section 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Finance_Commision_PCT__c.field-meta.xml
<CustomField>
    <fullName>Finance_Commision_PCT__c</fullName>
    <label>Finance Commision</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Leasing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Leasing_Fee__c</fullName>
    <label>Leasing&apos;s Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Minimum_Amount_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Amount_Section_2__c</fullName>
    <label>Minimum Amount Section 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Minimum_Amount_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Amount_Section_3__c</fullName>
    <label>Minimum Amount Section 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Minimum_Amount_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Amount_Section_4__c</fullName>
    <label>Minimum Amount Section 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Minimum_Cur_ID_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Cur_ID_Section_2__c</fullName>
    <label>Minimum Cur ID Section 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Minimum_Cur_ID_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Cur_ID_Section_3__c</fullName>
    <label>Minimum Cur ID Section 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Minimum_Cur_ID_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Cur_ID_Section_4__c</fullName>
    <label>Minimum Cur ID Section 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Overdng_Comission__c.field-meta.xml
<CustomField>
    <fullName>Overdng_Comission__c</fullName>
    <label>Overiding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Overdng_Comission_Section_2__c.field-meta.xml
<CustomField>
    <fullName>Overdng_Comission_Section_2__c</fullName>
    <label>Overdng Comission Section 2</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Overdng_Comission_Section_3__c.field-meta.xml
<CustomField>
    <fullName>Overdng_Comission_Section_3__c</fullName>
    <label>Overdng Comission Section 3</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Overdng_Comission_Section_4__c.field-meta.xml
<CustomField>
    <fullName>Overdng_Comission_Section_4__c</fullName>
    <label>Overdng Comission Section 4</label>
    <precision>12</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Risk_Closing_Survey_Fee_BSP__c.field-meta.xml
<CustomField>
    <fullName>Risk_Closing_Survey_Fee_BSP__c</fullName>
    <label>Risk/Closing Survey Fee / BSP</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage/fields/Total_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebate__c</fullName>
    <label>Total Rebate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Deductible.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Total Sum Insured</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Claim Paid</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Claim Amount</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Recoverable Claim</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <isActive>false</isActive>
        <label>Harga Pertanggungan</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <isActive>false</isActive>
        <label>Claim Dibayar</label>
    </customValue>
    <masterLabel>Deductible</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Aswata_Coverage_SectionData_Handler.cls
/**
 * @description       : Data Handler per Section
 * @author            : Ahmad Yazid Munif
 * @last modified on  : 12-17-2025
 * @last modified by  : Ahmad Yazid Munif
**/
public with sharing class Aswata_Coverage_SectionData_Handler {
    /**
     * @description function for generate data rebate
     * @param coverage
     * @param wrapper list of Json String after deserialize
     * @param risk
     * @return InsurancePolicyCoverage
     */
    public static InsurancePolicyCoverage wrapperRebate4(InsurancePolicyCoverage coverage,Aswata_Coverage_Data_Wrapper.CoverageDetailWrapper wrapper,Asset risk){
        // coverage.Total_Rebate__c = wrapper.rebate.totalRebate;
        // coverage.Discount__c = wrapper.rebate.discountValue;
        // coverage.Commision__c = wrapper.rebate.commissionValue;
        // coverage.Banks_Fee_Comission__c = wrapper.rebate.bankFeeValue;
        // coverage.Risk_Closing_Survey_Fee_BSP__c = wrapper.rebate.bspValue;
        // coverage.Leasing_Fee__c = wrapper.rebate.leasingValue;
        // coverage.Overdng_Comission__c = wrapper.rebate.overridingValue;
        // coverage.Agent_Comission__c = wrapper.rebate.agentCommissionValue;
        // coverage.Broker_Comission__c = wrapper.rebate.brokerCommissionValue;
        // coverage.Finance_Commision_PCT__c = wrapper.rebate.financialCommissionValue;
        if(wrapper.rebates[0] != null){
            // coverage.Total_Rebate__c = wrapper.rebates[0].totalRebate;
            // coverage.Discount__c = wrapper.rebates[0].discountValue;
            // coverage.Commision__c = wrapper.rebates[0].commissionValue;
            coverage.Banks_Fee_Section_2__c = wrapper.rebates[0].bankFeeValue;
            // coverage.Risk_Closing_Survey_Fee_BSP__c = wrapper.rebates[0].bspValue;
            // coverage.Leasing_Fee__c = wrapper.rebates[0].leasingValue;
            coverage.Overdng_Comission_Section_2__c = wrapper.rebates[0].overridingValue;
            coverage.Agent_Comission_Section_2__c = wrapper.rebates[0].agentCommissionValue;
            coverage.Broker_Comission_Section_2__c = wrapper.rebates[0].brokerCommissionValue;
            // coverage.Finance_Commision_PCT__c = wrapper.rebates[0].financialCommissionValue;
        }
        if(wrapper.rebates[1] != null){
            // coverage.Total_Rebate__c = wrapper.rebates[1].totalRebate;
            // coverage.Discount__c = wrapper.rebates[1].discountValue;
            // coverage.Commision__c = wrapper.rebates[1].commissionValue;
            coverage.Banks_Fee_Section_3__c = wrapper.rebates[1].bankFeeValue;
            // coverage.Risk_Closing_Survey_Fee_BSP__c = wrapper.rebates[1].bspValue;
            // coverage.Leasing_Fee__c = wrapper.rebates[1].leasingValue;
            coverage.Overdng_Comission_Section_3__c = wrapper.rebates[1].overridingValue;
            coverage.Agent_Comission_Section_3__c = wrapper.rebates[1].agentCommissionValue;
            coverage.Broker_Comission_Section_3__c = wrapper.rebates[1].brokerCommissionValue;
            // coverage.Finance_Commision_PCT__c = wrapper.rebates[1].financialCommissionValue;
        }
        if(wrapper.rebates[2] != null){
            // coverage.Total_Rebate__c = wrapper.rebates[2].totalRebate;
            // coverage.Discount__c = wrapper.rebates[2].discountValue;
            // coverage.Commision__c = wrapper.rebates[2].commissionValue;
            coverage.Banks_Fee_Section_4__c = wrapper.rebates[2].bankFeeValue;
            // coverage.Risk_Closing_Survey_Fee_BSP__c = wrapper.rebates[2].bspValue;
            // coverage.Leasing_Fee__c = wrapper.rebates[2].leasingValue;
            coverage.Overdng_Comission_Section_4__c = wrapper.rebates[2].overridingValue;
            coverage.Agent_Comission_Section_4__c = wrapper.rebates[2].agentCommissionValue;
            coverage.Broker_Comission_Section_4__c = wrapper.rebates[2].brokerCommissionValue;
            // coverage.Finance_Commision_PCT__c = wrapper.rebates[2].financialCommissionValue;
        }
        return coverage;
    }
    /**
     * @description function for generate data deductible Section 2-4
     * @param coverage
     * @param wrapper list of Json String after deserialize
     * @param risk
     * @return InsurancePolicyCoverage
     */
    public static InsurancePolicyCoverage wrapperDeductible4(InsurancePolicyCoverage coverage,Aswata_Coverage_Data_Wrapper.CoverageDetailWrapper wrapper,Asset risk){
        // InsurancePolicyCoverage coverage = new InsurancePolicyCoverage();
        if(wrapper.deductibles[0]!=null){
            coverage.Deductible_Type_Section_2__c = wrapper.deductibles[0].deductibleSetting;
            coverage.Deductible_Section_2__c = wrapper.deductibles[0].deductibleFlag;
            coverage.Minimum_Cur_ID_Section_2__c = wrapper.deductibles[0].currencyName;
            if(wrapper.deductibles[0].deductibleSetting=='FLAT'){
                coverage.Deductible_Amount_Section_2__c = wrapper.deductibles[0].deductibleAmount;
                coverage.Deductible_PCT_Section_2__c = null;
            }else{
                coverage.Deductible_Amount_Section_2__c = null;
                coverage.Deductible_PCT_Section_2__c = wrapper.deductibles[0].deductibleAmount;
            }
            coverage.Minimum_Amount_Section_2__c = wrapper.deductibles[0].minimumAmount;
        }
        if(wrapper.deductibles[1]!=null){
            coverage.Deductible_Type_Section_3__c = wrapper.deductibles[1].deductibleSetting;
            coverage.Deductible_Section_3__c = wrapper.deductibles[1].deductibleFlag;
            coverage.Minimum_Cur_ID_Section_3__c = wrapper.deductibles[1].currencyName;
            if(wrapper.deductibles[1].deductibleSetting=='FLAT'){
                coverage.Deductible_Amount_Section_3__c = wrapper.deductibles[1].deductibleAmount;
                coverage.Deductible_PCT_Section_3__c = null;
            }else{
                coverage.Deductible_Amount_Section_3__c = null;
                coverage.Deductible_PCT_Section_3__c = wrapper.deductibles[1].deductibleAmount;
            }
            coverage.Minimum_Amount_Section_3__c = wrapper.deductibles[1].minimumAmount;
        }
        if(wrapper.deductibles[2]!=null){
            coverage.Deductible_Type_Section_4__c = wrapper.deductibles[2].deductibleSetting;
            coverage.Deductible_Section_4__c = wrapper.deductibles[2].deductibleFlag;
            coverage.Minimum_Cur_ID_Section_4__c = wrapper.deductibles[2].currencyName;
            if(wrapper.deductibles[2].deductibleSetting=='FLAT'){
                coverage.Deductible_Amount_Section_4__c = wrapper.deductibles[2].deductibleAmount;
                coverage.Deductible_PCT_Section_4__c = null;
            }else{
                coverage.Deductible_Amount_Section_4__c = null;
                coverage.Deductible_PCT_Section_4__c = wrapper.deductibles[2].deductibleAmount;
            }
            coverage.Minimum_Amount_Section_4__c = wrapper.deductibles[2].minimumAmount;
        }
        return coverage;
    }
}